### ISSUE TITLE
[Beta][Windows]: should rules for Web Watcher work for categories if they are working for visualizations?

### ISSUE THREAD

**Issue by PetbkA** [ActivityWatch/activitywatch#1018]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

- **OS name and version**: Windows 10 LTSC 2021 (version 21H2) x64 EN
- **ActivityWatch version**: 0.12.3b**16**
- **Browser**: [Ungoogled Chromium 121.0.6167.131](https://github.com/macchrome/winchrome/tree/v121.6167.131-M121.0.6167.131-r1233107-Win64) x64
- **[Web Watcher](https://chromewebstore.google.com/detail/activitywatch-web-watcher/nglaklhklhcoonedhgnpgddginnjdadi)**:  0.4.3

According to [*Rules*](https://docs.activitywatch.net/en/latest/features/categorization.html#rules) section in documentation, matching URLs from the Web Watcher isn't supported yet.

But if it isn't, why am I seeing that *Top Browser Domains* and *Top Browser URLs* visualizations are working according to rules? I.e. all visited Domains and URLs are present and are coloured according to rules that are matching only with URLs.

I wanted to file a bug about Activity circle not getting categories from URLs, then (after reading the doc) thought that this is by design, but after seeing visualizations I'm not sure...

If Activity circle is still not getting categories from URLs, I'd suggest to change note in docs 'cause now it's a bit confusing

**Comment by firefoot007** [comment]
Yes, this is confusing. They get correctly categorized in browser view but cannot find them in summary categories.

**Comment by PetbkA** [comment]
@ErikBjare , sorry for annoyance, but can you look at this?

**Comment by 42Willow** [comment]
Where is the issue tracking this?
![image](https://github.com/ActivityWatch/activitywatch/assets/70784752/58bc3760-de81-4f73-bace-18b40c172248)
https://docs.activitywatch.net/en/latest/features/categorization.html#regular-expressions-regex

**Comment by BelKed** [comment]
Here, please:
- https://github.com/ActivityWatch/activitywatch/issues/352

**Comment by 42Willow** [comment]
This issue should probably be closed as a duplicate then.

**Comment by PetbkA** [comment]
**Closed** in favor of #352
