### ISSUE TITLE
How can I store the data directly into my own database? For example, MySql

### ISSUE THREAD

**Issue by jiojiojackson** [ActivityWatch/activitywatch#1021]
- [ ✔] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [✔ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

How can I store the data directly into my own database? For example, MySql

**Comment by BelKed** [comment]
Duplicate of #1020
