### ISSUE TITLE
All my activity (apps, window titles etc) show half the correct time

### ISSUE THREAD

**Issue by Naereen** [ActivityWatch/activitywatch#1030]
Hi there,
I've been using with much pleasure AW since a few years, and I really like it. It's a good complement to my [uLogMe forked](https://github.com/Naereen/uLogMe/) app.

I recently discovered that on any web-page of the AW activity viewer, all the times displayed are showed half of what they should be. Here is an example, of a movie that was on my screen for 1h40 minutes but is displayed 50 minutes.
![Capture d’écran_2024-02-17_20-17-34](https://github.com/ActivityWatch/activitywatch/assets/11994719/fc0b5ec0-f55d-4fee-a34c-6d395c858d1b)

I don't know the source of the bug, but it's probably simple.
I'm available to help to solve it by providing more information, but I won't have time to investigate in depth and solve it by hands myself.
Cheers, @Naereen

**Comment by brayo-pip** [comment]
Which os are you running?

**Comment by Naereen** [comment]
Hi @brayo-pip,
I'm using Ubuntu (Linux).
I can provide more information if needed, of course :+1: !

**Comment by brayo-pip** [comment]
I'm currently experiencing the same bug on feora 39. I'll try to figure out the issue.

**Comment by brayo-pip** [comment]
Are you running the aw-rust-server?

**Comment by Naereen** [comment]
Hi @brayo-pip,
No I'm not using `aw-server-rust`, but only `aw-server`.

**Comment by brayo-pip** [comment]
When you export the data does it show half the total time or the correct time.

**Comment by Naereen** [comment]
How can I check that please?

**Comment by ErikBjare** [comment]
> Here is an example, of a movie that was on my screen for 1h40 minutes but is displayed 50 minutes.

Was this only for the movie you watched? If so, it's likely that there was no input during this time, thus you were AFK, thus the time wasn't included. You can toggle AFK-filtering via the "Filter" button to see if that was the case.

Here's the overarching issue for better tracking video like this: https://github.com/ActivityWatch/activitywatch/issues/261

If this happened for other activities, that'd be a curious bug. Does the timeline show both non-AFK events and window events, without gaps in one that are not in the other?

**Comment by Naereen** [comment]
Hi @ErikBjare,
Thanks for this answer. I'm not sure if this data seen with only "half the correct time bug" was because of AFK detection or not.
Apparently on YouTube videos I don't get this issue, so I guess it was indeed an error due to AFK detection.

**Comment by Naereen** [comment]
Hi again,
I think this issue can be closed.
Thanks again for the answers!
Regards.

**Comment by DivineMK** [comment]
I am curious what is the problem in the end?

**Comment by Naereen** [comment]
Hello there @DivineMK,
The issue is that for some activity, the time logged in my Activity Watch was cut in half.
Apparently it's because of the AFK (away from keyboard) automated detection technique.

**Comment by DivineMK** [comment]
Oh I see thank you for your instant response!
