### ISSUE TITLE
Delete bucket feature

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#104]
I actually want this now. It is especially when managing or moving buckets to/from a testing server. It could even be used when upgrading the database if we make the export format forwards compatible for importing.

IIRC, the reason we were previously hesitant is that it has a high risk for mistakes. We could fix this by asking for a strong confirmation dialog where the id of the bucket has to be entered to confirm (like when removing repos on GitHub). That way it has an extremely low probability of being a mistake.

But first we need https://github.com/ActivityWatch/activitywatch/issues/103 to be reliably implemented. We should definitely set up tests for importing exports (forward compatibility is critical).

**Edit:** For now I could just use the API though.

**Comment by ErikBjare** [comment]
A prerequisite for this issue: https://github.com/ActivityWatch/activitywatch/issues/73#issuecomment-325052200

**Comment by johan-bjareholt** [comment]
This is available, but only possible with testing enabled.

When should we enable this to non-testing? Should we do something before adding it to non-testing such as adding a "?force=1" which you need to specify when you are not in testing to make sure some unittest etc. doesn't delete some bucket by mistake? (or the opposite, adding "?softdelete=1" which only allows it in testing, or something completely different)

**Comment by ErikBjare** [comment]
I think we should just put up a clear confirmation dialogue in the web UI. The `&force=1` parameter feels to me like a user-layer in the API-layer, but I guess it's a reasonable precaution with minimal complexity. Definitely prefer it to `softdelete`.

**Comment by johan-bjareholt** [comment]
Initial implementation is now in aw-server and aw-webui in the dev/transform-next branches

https://github.com/ActivityWatch/aw-webui/pull/48/commits/6410170d3192c9e73bb7957ea7e7b9ce606e25ac

**Comment by johan-bjareholt** [comment]
This is merged, closing
