### ISSUE TITLE
Status of the enable/disable of aw-input module is not saved true stopping/starting the application

### ISSUE THREAD

**Issue by generic-user** [ActivityWatch/activitywatch#1047]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the open-issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 22H2 Build 19045.4170 
- **ActivityWatch version**: v0.12.3b16

## Describe the bug

The status of the enable/disable of module is not saved true stopping/starting the application when toggling watcher module from the system tray richt-click menu.
## To Reproduce

1. Enable aw-input
2. restart app
3. see it is not remembered
## Expected behavior

Should be remembered.

## Additional context

![image](https://github.com/ActivityWatch/activitywatch/assets/1516035/ed78bf61-40fb-405f-8a8e-d63a08b78873)

**Comment by BelKed** [comment]
You need to specify the modules you want to be selected on startup in the `autostart_modules` section of the `aw-qt` configuration file. Similar to this: https://docs.activitywatch.net/en/latest/migrating.html#using-aw-server-rust-by-default

**Comment by generic-user** [comment]
Aha, I thought it would be saved by default. It edited the file, works as expected now!

**Comment by j333t** [comment]
> You need to specify the modules you want to be selected on startup in the `autostart_modules` section of the `aw-qt` configuration file. Similar to this: https://docs.activitywatch.net/en/latest/migrating.html#using-aw-server-rust-by-default

Trying this for aw-watcher-input, but it's not working.
Any idea why?
