### ISSUE TITLE
Wen setting landing page from settings, and loading the webbapp from its default URL, it is not respected/loaded.

### ISSUE THREAD

**Issue by generic-user** [ActivityWatch/activitywatch#1048]
- [x] I am on the [latest BETA](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 22H2 Build 19045.4170
- **ActivityWatch version**:v0.12.3b16 

## Describe the bug

Wen setting/selecting a custom landing page from settings, and loading the webbapp from its default URL, it is not respected/loaded.

**Comment by BelKed** [comment]
There have been some reports of problems with the latest beta version (`v0.12.3b16`).
Would you mind trying the previous beta version (`v0.12.3b15`) and reporting back if the problem persists?

**Comment by BelKed** [comment]
Also, probably duplicate of https://github.com/ActivityWatch/activitywatch/issues/1033

**Comment by generic-user** [comment]
Hi an thanks for the quick reply. The issue is not a deal breaker for me, just reporting so it can be fixed in later BETA release…
Anyway, kind of busy right now, so cant promise I test a previous build, but I will do my best once I find the time for it.

**Comment by BelKed** [comment]
The issue has been fixed today in https://github.com/ActivityWatch/aw-webui/pull/573 :)

**Comment by generic-user** [comment]
Tested and it is working, superp!
