### ISSUE TITLE
Styles and colours

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/activitywatch#105]
I've noticed that when tracking my activities, the breakdown is 80% green, despite there being several different applications being used. Whats the best way to inject more colours into the bars? Are there styles that I can access?

**Comment by ErikBjare** [comment]
The colors are defined in `aw-webui/src/utils/color.js`, we've been meaning
to add more colors but haven't gotten around to it yet.

**Comment by yratof** [comment]
Great – what should I be running to compile vue into app.js – are you simply using `make`?

**Comment by ErikBjare** [comment]
Yeah, a `make build` after a `npm install` should do it.

Then you just need to copy over the new files in `dist` to the `aw_server/static` folder and you'll have an updated version.

**Comment by ErikBjare** [comment]
To do before closing:

 - [ ] Add more colors to aw-webui

**Comment by ErikBjare** [comment]
We might improve how the coloring and styling is done in a future version, but it's very low priority. Closing.
