### ISSUE TITLE
console error with uncategorized word "constructor"

### ISSUE THREAD

**Issue by john30** [ActivityWatch/activitywatch#1054]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11
- **ActivityWatch version**: v0.12.2

## Describe the bug
when using the categorization helper for uncategorized words and those contain the word 'constructor', an error with stacktrace is reported on browser console

## To Reproduce
- ensure you have an event with the word "constructor" in the list of uncategorized events
- go to the category builder (http://localhost:5600/#/settings/category-builder)
- this is it, here it breaks already, the error appears on console and the page is no longer functioning

## Expected behavior
'constructor' should not lead to this error behaviour

## Documentation
stack trace on Firefox 125.0.3 (64-Bit):
Uncaught (in promise) TypeError: c[f].events is undefined
    t CategoryBuilder.vue:123
    Babel 11
    fetchWords CategoryBuilder.vue:87
    handler CategoryBuilder.vue:74
    VueJS 12
    e QueryOptions.vue:43
    Babel 9
    mounted QueryOptions.vue:41
    VueJS 12

## Additional context
the problem is in CategoryBuilder.vue:123 which tries to access word['constructor'] as a map with an events array, but that is obviously a real constructor instead.

**Comment by john30** [comment]
seems there are duplicates or at least similar issues already (despite I was searching explicitly for it before filing the bug):
https://github.com/ActivityWatch/activitywatch/issues/965
https://github.com/ActivityWatch/activitywatch/issues/1044

**Comment by BelKed** [comment]
Could you please try the latest beta — [`v0.12.3b17`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b17)? It should be fixed there. If not, please let us know :)

**Comment by ErikBjare** [comment]
@BelKed I think this one's different actually.

I fixed it in https://github.com/ActivityWatch/aw-webui/pull/564, let me know if that looks correct to you @john30!

**Comment by john30** [comment]
this is not the correct fix for the issue.
see my review here: https://github.com/ActivityWatch/aw-webui/pull/564#pullrequestreview-2043885295
