### ISSUE TITLE
Rust not found even SKIP_SERVER_RUST is set to true when

### ISSUE THREAD

**Issue by MohammadAliAfsahi** [ActivityWatch/activitywatch#1056]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Ubuntu**
- **v0.12.3b18-1-g469cbba**

## Describe the bug
When trying to build the project from source, by running `make build` command, the following error raised:
`ERROR: Rust not found, try running with SKIP_SERVER_RUST=true`

## To Reproduce
  Steps to reproduce the behavior, for example:
    1. clone the project
    2. try building the project from source using the documentation guides
    3. set the `SKIP_SERVER_RUST` to true as an environment variable
    4. When running `make build` the mentioned error is raised

## Expected behavior
When SKIP_SERVER_RUST is set to true, even if `cargo` is not installed, it should build the source code.

## Documentation
![Screenshot from 2024-05-10 19-13-38](https://github.com/ActivityWatch/activitywatch/assets/35253602/328ce3f9-2e13-4aea-872e-93a0a16072f5)

**Comment by MohammadAliAfsahi** [comment]
Solution:

I could come up with a solution by change the 52~57 from the following:

```
	@if (which cargo); then \
		echo 'Rust found!'; \
	else \
		echo 'ERROR: Rust not found, try running with SKIP_SERVER_RUST=true'; \
		exit 1; \
	fi
```

to 

```
	@if [ "$(SKIP_SERVER_RUST)" = "false" ]; then \
		if (which cargo); then \
			echo 'Rust found!'; \
		else \
			echo 'ERROR: Rust not found, try running with SKIP_SERVER_RUST=true'; \
			exit 1; \
		fi \
	fi
``

**Comment by BelKed** [comment]
Feel free to open a PR implementing the proposed changes :)

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/activitywatch/commit/04fbfacbea41650c961f39550516a893602e658d :)
