### ISSUE TITLE
Tracking git repos / settings page

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/activitywatch#106]
Something that we'd implemented on a tracker we built was it would monitor which git repos you're in. For example, if you're in terminal and you're in a project, it would make a note of the git repo.

This would work great for developers tracking time, not so good for designers etc who'll see git repos on all their time tracking. Which leads me into thinking that a settings page or command would be fantastic – is this in the works?

**Comment by ErikBjare** [comment]
I think you could already do this by analysing the window title of your
terminal (collected by aw-watcher-window), checking if the directories
you've been in are git repos and then calculating time per repo. No new
watcher needed :)

Is that similar to what you had in mind?

**Comment by yratof** [comment]
Similar, i'm just running 20-30 titles together, they're all related to the same repo, but at the moment, I need to manually go through each title and check it's related to a project etc.

**Comment by ErikBjare** [comment]
Good, we could certainly automate it. I just want the solution to be somewhat general to avoid feature creep and make it as widely useful as possible.

One thing I have in mind is to add some kind of automated tagging system based on pattern matching. It would basically work as follows: All AFK-filtered titles/URLs would be run through a pattern (such as your project name) and we'd then get out all the events relating to your project, which could in turn be used to calculate the time spent on that project. 

Does that sound like a good solution for you?

**Comment by yratof** [comment]
Sounds like an ideal solution for the problem! It would be great to have tagging

**Comment by ErikBjare** [comment]
Alright, will close this issue and mention it in #95.
