### ISSUE TITLE
Today is 24 Hours, can it be shorter?

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/activitywatch#107]
Working hours are between 7am and 7pm – anything before / after is blank. This leaves the today chart compact.

Does D3 have the ability to be more dynamic, either defining a range or using the hours the trackers started to the tracker closes?

Here's an example of a daily chart with default 24 hours:

![image](https://user-images.githubusercontent.com/1001935/29821706-2f3ec4c0-8cc9-11e7-9056-eece4dcac25e.png)

**Comment by ErikBjare** [comment]
Yes this is definitely doable and shouldn't be too much work. I've actually
thought about it before (and we do something similar with the normal
timeline) so it's likely that it will happen in the future but I can't
promise when :)

**Comment by yratof** [comment]
Great stuff 👍
