### ISSUE TITLE
ActivityWatch shows no data

### ISSUE THREAD

**Issue by y11t0** [ActivityWatch/activitywatch#1070]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.
 - # Installed from AUR btw.
 
- **OS name and version**: Arch Linux 6.9.3
- **ActivityWatch version**: v0.13.0
- **Wayland**: Hyprland v0.40.0-1

## Describe the bug
I'm new to ActivityWatch and this problem happened in the previous version as well.I continued to use my computer while ActivityWatch was in this state, but there was no change.

## Expected behavior
It should have shown some data.Am i missing something?

![aw](https://github.com/ActivityWatch/activitywatch/assets/171605954/cc011251-df2a-4cf7-8248-8188da20e07b)

![tt](https://github.com/ActivityWatch/activitywatch/assets/171605954/14d413bd-ad4b-463b-bc35-d4f28e70c9e3)

**Comment by Ghurir** [comment]
The issue might be with wayland
#92
