### ISSUE TITLE
this.views.find is not a function

### ISSUE THREAD

**Issue by asdf141** [ActivityWatch/activitywatch#1071]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 22H2
- **ActivityWatch version**: v0.13.0

## Describe the bug
TypeError: this.views.find is not a function. See dev console (F12) and/or server logs for more info.
## To Reproduce
Go to Activity tab
## Expected behavior
Some data and graphs, like normal

## Documentation
there isn't a "logs" folder in localappdata\activitywatch

## Additional context
this happened after I reinstalled my OS. By the way, how to merge data from previous bucket/json/idontknow (apparently the hostname is changed)

**Comment by ErikBjare** [comment]
Could you try https://github.com/ActivityWatch/activitywatch/releases/tag/v0.13.1 that I released 3 minutes ago? It is possible that it fixes it :)

**Comment by asdf141** [comment]
It did :) nice update, thanks

**Comment by ErikBjare** [comment]
Awesome! Thank you for testing so quickly :)
