### ISSUE TITLE
AFK timer cannot be set to a customized value

### ISSUE THREAD

**Issue by cpeng03d** [ActivityWatch/activitywatch#1087]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- Windows 10
- **ActivityWatch version**: 
v0.13.1

## Describe the bug

Per instruction from this post
https://forum.activitywatch.net/t/disable-or-prolong-afk-watcher/483
we can set the timer in
C:\Users\username\AppData\Local\activitywatch\activitywatch\aw-watcher-afk\aw-watcher-afk.toml

I set it to 10min, but afk still triggers at 3min!
It’s not taking effect. Please advise a workaround!

## To Reproduce

goto
C:\Users\username\AppData\Local\activitywatch\activitywatch\aw-watcher-afk\aw-watcher-afk.toml
change the timeout value
and see afk still triggers at 3min

## Expected behavior

afk triggers at specified time

**Comment by ErikBjare** [comment]
Can you post the exact config?

Sometimes people don't uncomment the relevant section of the config file.

**Comment by cpeng03d** [comment]
Dane I forgot to uncomment the line!
Thank you, I will go close the ticket.
