### ISSUE TITLE
Database changes (in need of migration)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#109]
We haven't done any database migration before, but soon we will have to.

There are a few things we want to do that affects the database, I will collect them here.

 - Bucket
   - [ ] Add property `generated`, boolean indicating if it is collected data or aggregated/generated data.
     - Alternative: Add text field where value could be `"original"`,  `"generated"`, `"aggregated"` , etc.
 - Event
   - [ ] Include optional property with (offset-based) timezone information. (https://github.com/ActivityWatch/activitywatch/issues/72)
     - This information hasn't been present since we finished https://github.com/ActivityWatch/activitywatch/issues/39

Other things we must not forget when migrating:

 - [ ] Extensive tests, lost/corrupted information is catastrophic

**Comment by ErikBjare** [comment]
This issue is no longer relevant. We've done migrations since. Closing.

**Comment by johan-bjareholt** [comment]
> We've done migrations since

Not for users, only for developers in non-release code.

The peewee datastore has never even had a schema upgrade.
