### ISSUE TITLE
Malware report

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#1112]
![obraz](https://github.com/user-attachments/assets/d670b494-9722-49bc-9536-575ffc8fc5e0)

https://github.com/ActivityWatch/activitywatch/releases/download/v0.13.2/activitywatch-v0.13.2-windows-x86_64-setup.exe

**Comment by ErikBjare** [comment]
See https://github.com/ActivityWatch/activitywatch/issues/181
