### ISSUE TITLE
`Open API Browser` -> 404

### ISSUE THREAD

**Issue by deftdawg** [ActivityWatch/activitywatch#1113]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.5-xanmod1, NixOS, 24.11 (Vicuna), 24.11pre703931.4aa36568d413`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - channels(deftdawg): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

- **ActivityWatch version**: 
Version:  v0.13.2 (rust)

## Describe the bug
Opening the API option in the tray produces the following 404
![image](https://github.com/user-attachments/assets/390b6e27-0a30-45e4-b4da-10f2db98d26c)

Here's what the terminal captures:
```sh
Opening api browser
[2024-11-07 00:20:35][ERROR][rocket::server::_]: No matching routes for GET /api text/html.
[2024-11-07 00:20:35][WARN][rocket::server::_]: No 404 catcher registered. Using Rocket default.
```

## To Reproduce
Start aw-qt, click on the tray icon and select `Open API Browser` -> 404

**Comment by BelKed** [comment]
The API browser works only on Python server
