### ISSUE TITLE
Your Documentary doesn't say how to actually run it.

### ISSUE THREAD

**Issue by pschwede** [ActivityWatch/activitywatch#112]
See title.

**Comment by johan-bjareholt** [comment]
[Here's the section where you can see how you can install and run it](https://activitywatch.readthedocs.io/en/latest/getting-started.html)

As the note says on the top of that section though, the installation experience is not great currently. If you run Windows the prebuilt executables mentioned there work rather well, but if you run macOS or Linux installing from source is the most stable way to run ActivityWatch.

**Comment by ErikBjare** [comment]
I've improved the documentation for how to run it in https://github.com/ActivityWatch/activitywatch/commit/14a0f18ce53668400243b1b5962d235b0d8f9b4f

Thanks for letting us know it wasn't clear!
