### ISSUE TITLE
issue with bucket name start by aw-

### ISSUE THREAD

**Issue by e471wo** [ActivityWatch/activitywatch#1120]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **linux mint**: 
- **last one**: 

## Describe the bug
trying to do a watcher by myself, I found that if the bucket name bucket_id start by "aw-" all data are erased from the gui (not db).

## To Reproduce

1. Start and use Activitywatch as normal (and having data)
2. create a new watcher with a bucket name start by aw- (see the code below )
3. in the activity tab, you only have the watcher you created, all others deseapeard.

Here the code that does bug.
Note, to see data again,  just delete the bucket.

```
#!/usr/bin/env python3

from time import sleep
from datetime import datetime, timezone

from aw_core.models import Event
from aw_client import ActivityWatchClient

client = ActivityWatchClient("test")
bucket_id = "{}_{}".format("aw-test", client.client_hostname)
print(bucket_id)
event_type = "currentwindow"
client.create_bucket(bucket_id, event_type=event_type)
with client:
    sleeptime = 1
    for i in range(5):
        heartbeat_data = {"app": "vlc", "title":"audio stream"}
        now = datetime.now(timezone.utc)
        heartbeat_event = Event(timestamp=now, data=heartbeat_data)
        print("Sending heartbeat {}".format(i))
        client.heartbeat(bucket_id, heartbeat_event, pulsetime=sleeptime+1, queued=True, commit_interval=4.0)
        sleep(sleeptime)

```

## Expected behavior
dunno... but not that. Actually, I don't know what the issue is. why aw- is an issue.

## Documentation
after normal use
![image](https://github.com/user-attachments/assets/b59c2830-f207-4461-a04c-2ca3d3cb23b2)

after the script ran.
![image](https://github.com/user-attachments/assets/6551a95c-fdff-4ede-9f71-344374b19547)

**Comment by ErikBjare** [comment]
Right, because you now have two buckets with the `currentwindow` type for the same hostname, which is not valid.
