### ISSUE TITLE
Set up donation methods

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#115]
#### What purpose do donations serve?

 - They are proof that the project is valuable to our users
 - They help the sustainability of the project; every dollar improves the probability that the project will still exist and be actively developed years from now.
 - It helps us attract developers to the project

#### How will donations be spent?

 - They will **not** pay for my time. (I'm doing fine financially)
   - However, it might go towards tools used in development that I wouldn't buy otherwise.
 - Server costs of the forum and other infrastructure
 - Bounties on issues
 - Funding other open source projects that ActivityWatch depends on

All expenses will be entirely transparent for community review. But I reserve the right to spend donations however I think is best.

#### Donation methods

We want to offer people their preferred donation method to make it as easy as possible for them (and make sure that people who want to can reduce the fees paid).

 - [x] Bitcoin: 1NSxJs1wYUrRv53ZVH2DX9fquXdSPAdyYh
    - Kept by Erik Bjäreholt on Coinbase
 - [ ] Litecoin
 - [x] Ether: 0x8A8D0B2BeDa2E29A859cB95d6541Ef19608b234A
    - Kept by Erik Bjäreholt in a wallet file
 - [x] Bountysource ([link](https://salt.bountysource.com/teams/activitywatch))
 - [x] Patreon ([link](https://www.patreon.com/erikbjare))
 - [ ] Paypal?

All donations, regardless of method, should end up in a spreadsheet so we can keep track of them.

#### What should the kind people who donate get in return?

 - Their names on the next release (á la git-annex)
 - Their name and their total donation amount on a dedicated page on the website
 - People/organizations who donate large amounts could become "sponsors" and get a banner/logo in the README and on the website

#### Final tasks

 - [x] Put the donation methods in some visible location (README, the website) with a motivation for why donations are important to the project and why users should donate.

**Comment by ErikBjare** [comment]
Added a Donate page to the website in: https://github.com/ActivityWatch/activitywatch.github.io/commit/a12f3619b8410ed7410206cfea02e0810fe38d26

Added link to README in: https://github.com/ActivityWatch/activitywatch/commit/364638b9cf5f4e691b1963497e9d974dc9abe792

Done for now.

**Comment by ErikBjare** [comment]
Just discovered [OpenShot's donations page](http://www.openshot.org/donations/), I really like it.

**Comment by johan-bjareholt** [comment]
@ErikBjare Lol, top donator of October 2017 on OpenShot paid with bitcoin by anon

> $1083.88 USD - Please read TKOGIWY

**Comment by ErikBjare** [comment]
Lol, Tolstoy 😍
