### ISSUE TITLE
Start and end of day incorrect for timezone

### ISSUE THREAD

**Issue by johnhamilton** [ActivityWatch/activitywatch#117]
# Problem description 
When i start ActivityWatch it shows the wrong day not that current day as its recording today's data for the 15th but its the 16th in Australia and on my computer clock.

# What i think the problem is
The code that is recording the the Activity is using a USA data and code showing the page is using the Australia data/my computers data.

**Comment by johnhamilton** [comment]
# Update

Seams to change to the next day at lunch/midday my time it should be switched to mid night maybe?

**Comment by ErikBjare** [comment]
Definitely! I thought we had fixed this, but apparently, it persists.

The data is likely logged correctly, it's just the web UI that doesn't query the data correctly. I'll take a look at this.

**Comment by ErikBjare** [comment]
I think I fixed this issue here: https://github.com/ActivityWatch/aw-webui/pull/49

**Comment by ErikBjare** [comment]
I'm closing this, please let me know if the new release fixed it for you @johnhamilton!

**Comment by ErikBjare** [comment]
This was not fixed. I did some digging and we seem to have slightly deeper problems, but a fix should be easy.

Example code:
```py
from datetime import datetime, timezone, timedelta
import aw_client

api = aw_client.ActivityWatchClient(testing=True)
buckets = api.get_buckets()

window_bid = next(bid for bid in buckets.keys() if "window" in bid and "testing" not in bid)
print(window_bid)

utcplus2h = timezone(timedelta(hours=2))
start = datetime(year=2017, month=10, day=27, hour=0, tzinfo=utcplus2h)
end = start + timedelta(hours=24)

events = api.get_events(window_bid, start=start, end=end, limit=-1)
print(len(events))
print(events[0].timestamp)
print(events[-1].timestamp)
```

Output:
```
aw-watcher-window_erb-main2-arch
8080
2017-10-27 13:26:10.608000+00:00
2017-10-27 00:09:23.451000+00:00
```

This output is wrong since the first event should not be from 00:09 UTC, but rather from 22:09 UTC.

**Comment by ErikBjare** [comment]
Alright, found the issue and implemented a fix: https://github.com/ActivityWatch/aw-core/commit/b57564c16a81f5ae7c96f8749a3161eabc2c7376

**Comment by ErikBjare** [comment]
Wrote a test here: https://github.com/ActivityWatch/aw-core/commit/4b89fafb34ce4916e29a66542d2c166852064308

Works great now, closing.
