### ISSUE TITLE
Fixing packaging on macOS

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#119]
There has been this annoying bug with the macOS builds:

```
Error loading Python lib '/Applications/activitywatch/.Python': dlopen(/Applications/activitywatch/.Python, 10): image not found
```

@jwiese had [the same issue](https://github.com/ActivityWatch/activitywatch/issues/78#issuecomment-325065686)

Then [someone on reddit had the same issue](https://www.reddit.com/r/Entrepreneur/comments/76qnbq/tell_us_about_your_startupbuisness/dojs27u/).

I thought a bit about it, and the fix might be stupidly easy: `cp src/* dest/` doesn't copy files beginning with a dot.

**Comment by ErikBjare** [comment]
Now I just need someone with a Mac (like @exoji2e) to try the new build out.

**Comment by ErikBjare** [comment]
@exoji2e go ahead and close this issue if it works for you!

**Comment by jwiese** [comment]
This is great, works very well with this fix! Thanks @ErikBjare

**Comment by ErikBjare** [comment]
@jwiese Happy to hear it :smile:
