### ISSUE TITLE
Add notice in the web UI to install aw-watcher-web

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#121]
Right now the web watcher isn't really used except by friends and people who hunted it down on their own.

We should add a notice to get them to install the web watcher when they open the web UI. We could autodetect if the watcher has created a bucket and if so avoid recommending it.

This might apply to other watchers as well. Might be useful to have an overview of which buckets are "active" (have recent data).

**Comment by johan-bjareholt** [comment]
It should be clear in the notice that it is just optional though even if it is recommended.

**Comment by ErikBjare** [comment]
The easiest thing to do would be to simply direct users to the list of watchers in [the docs](https://activitywatch.readthedocs.io/en/latest/watchers.html). So perhaps we could just start with that.

 - [ ] Add link to "watchers" page in docs

**Comment by ErikBjare** [comment]
This is practically done in the yet unmerged https://github.com/ActivityWatch/aw-webui/pull/48

Closing.
