### ISSUE TITLE
Take new screenshots

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#122]
## Before taking them

 - Get some good example data
 - Wait for the top domains feature to land?

## How to take them

Stylize/frame and scale them appropriately. Maybe give them borders or include a minimal browser window frame.

## What to screenshot?

 - [x] Activity view
 - [ ] Bucket view
 - [x] Trayicon
 - [ ] Web extension

## Where to put them

 - [x] README
 - [x] Website
 - [ ] Chrome Web Store
 - [ ] Mozilla Addons
 - [ ] AlternativeTo
 - [x] ProductHunt

**Comment by ErikBjare** [comment]
[Someone on reddit wanted more screenshots](https://www.reddit.com/r/QuantifiedSelf/comments/7dkrei/activitywatch_an_open_source_automated/dpzvtyu/). They are probably instrumental to people actually installing ActivityWatch so we should try to get several nice screenshots to show off. 

Bumping priority.

**Comment by ErikBjare** [comment]
Here's a screenshot for the tray icon on Windows:

![aw-qt-trayicon](https://user-images.githubusercontent.com/1405370/33553162-f0151fe4-d8f7-11e7-833e-e8a25948d73f.PNG)

**Comment by shaund** [comment]
You really need screenshots of the UI. Just take some of your install, blur your data, and post them on the website and readme until you can get something better.

**Comment by ErikBjare** [comment]
Here's one, will update the README as v0.8 is released.

![image](https://user-images.githubusercontent.com/1405370/40657029-a8d791c8-6346-11e8-80ba-1f401d703183.png)

**Comment by ErikBjare** [comment]
Just updated the README with new screenshots and removed the notice

**Comment by ErikBjare** [comment]
This was done to a satisfactory degree. There will undoubtedly come a time when we need to do it again, but closing for now.
