### ISSUE TITLE
Create variations of logo

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#123]
Right now our logo is only available in banner-form and a zero-padding circular logo (this looks terrible in some places like Twitter).

I'd be interested in creating:
 - A version with padding (Chrome Webstore have some guidelines) 
 - A version without the circle
 - Start playing with something sunburst-like

**Comment by rafaelhipercg** [comment]
![activitywatch](https://user-images.githubusercontent.com/10676754/34028845-81b48df2-e14c-11e7-9ff1-f0d746f32038.png)
Something like that?

**Comment by rafaelhipercg** [comment]
@ErikBjare
