### ISSUE TITLE
Add spent time to AFK periods

### ISSUE THREAD

**Issue by alex-bender** [ActivityWatch/activitywatch#130]
Hi! Thanks for such a great tool!
I'd like to help with developing, but before that I need to read the code little bit.

I'm using `aw` for a ~5 hours and found out that It doesn't show AFK time for `Timeline`:
![image](https://user-images.githubusercontent.com/3628862/32566564-fcfc024a-c4c0-11e7-92ec-db6897a34693.png)
This section is not hoverable.
Would be great to have this hover effect.

**Comment by johan-bjareholt** [comment]
Thanks for the feedback :)

>  I'm using aw for a ~5 hours and found out that It doesn't show AFK time for Timeline
> This section is not hoverable.
> Would be great to have this hover effect.

Yeah, it might be confusing that you can't see the afk-time in the timeline. The timeline design isn't complete and we are not even sure if we will keep it. If you want this functionality right now the best option would be to use the "Today View" which you can see a early preview of if you click on "Open today view" in the notice on the top of the page. We are open for suggestions on how a proper design could look if you have any opinions.

> I'd like to help with developing, but before that I need to read the code little bit.

The docs are WIP but should give a decent overview of how all components work together. We have a lot of example code such as example clients as well as extensive unittests for aw-core if you want to understand the internals, and if you are a front-end guy our webui needs a fair bit of improvements and the only thing needed should be vue2 experience and using the activitywatch rest API which you can find at localhost:5600/api

Good luck :)

**Comment by alex-bender** [comment]
Thanks for detailed explanations!

I'm a python web dev, know little bit of vue.
As far as I know you're using Flask, so It could be pretty easy to jump in, I suppose.
Personally I think that this "timeline" view is a god one, but it's right that design should be improved.
As about "Today View" -- yeah, it's really cool.
I'd be glad to pick up something like "easy-to-start" issues. Is it "good-first-issue"?
Thanks again for the tool.
Let's stay tuned.

**Comment by johan-bjareholt** [comment]
Revamping/redesigning/rewriting the timeline could be a good start task since you will get used to the event model we use everywhere in activitywatch but without having to dig deep into the rest of the codebase. The webui is pretty clean and is pretty much only vanilla Vue with bootstrap so it shouldn't be too complicated. The visualizations are done with d3 which we are not very experienced with, so there is probably a lot of possibilities to make the code cleaner aswell.

Fun to see the project being appreciated and used :)

**Comment by ErikBjare** [comment]
Hi @alex-bender! Great to see interest :)

I just wrote a bit about how we could improve the timeline in this issue: https://github.com/ActivityWatch/aw-webui/issues/50

Let me know if you have any questions at all, or if you'd like to [chat in our gitter](https://gitter.im/ActivityWatch/activitywatch). We're a little short on good-first-issues right now but let me know what interests you and we'll find something :slightly_smiling_face:

**Comment by alex-bender** [comment]
@ErikBjare @johan-bjareholt Hi guys!
I've read some part of code in a few repositories, and... well... I'm really like to contribute.
Such a solid work was done, It was pleasure to read that code.
I have couple suggestions what to add to functionality, for example ability to comment time line events or how much it is cost (AFK or not doing work; some kind of salary rate divided by work hours).
Would be great to chat with you guys!

I'm in GMT+2 timezone (Eastern Europe)

**Comment by ErikBjare** [comment]
Those features sound like something that'd go well in the web UI. We are trying to keep the backend simple, but perhaps the thing you want could be implemented using some form of tagging? 

We've discussed this a little bit before in https://github.com/ActivityWatch/activitywatch/issues/95. Let me know your thoughts on the topic!

**Comment by ErikBjare** [comment]
Stale. Closing.
