### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by rgarrigue** [ActivityWatch/activitywatch#138]
Hello

I gave a quick shot at activitywatch. Was a bit buggued by a port issue, I already had something running on port 5000 and couldn't find a conf file or a command switch to change this.

So I gave a shot at a container for activitywatch. That won't work since it requires some system stuff and got some Qt dependencies that won't go easily in a container. But maybe this could be useful to someone, so here's the Dockerfile

```
FROM ubuntu:bionic

ENV UID=8426
ENV GID=8426
ENV VERSION=0.7.1

# Requirements
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y dumb-init curl unzip \
    && groupadd -g ${GID} aw \
    && useradd -g aw -u ${UID} -d /activitywatch -m aw \
    && apt-get autoremove -y \
    && apt-get clean all

USER aw:aw
WORKDIR /activitywatch

# Installation
RUN curl -L -o /tmp/activitywatch.zip https://github.com/ActivityWatch/activitywatch/releases/download/v${VERSION}/activitywatch-v${VERSION}-linux-$(uname -m).zip \
    && unzip /tmp/activitywatch.zip -d / \
    && chmod -x /activitywatch/*.so* \
    && rm /tmp/activitywatch.zip

ENTRYPOINT ["/usr/bin/dumb-init","--"]
CMD ["/activitywatch/aw-qt"]

EXPOSE 80
```

and here's a docker-compose.yml

```
version: "3"

services:
  activitywatch:
    build: .
    ports:
      - 80:80
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
```

**Comment by ErikBjare** [comment]
You don't need to run `aw-qt` if you don't want the trayicon/service manager functionality it provides. You should try to run `aw-server` directly instead.

Also, `aw-server` should accept a `--port` argument, so you could try that. Not sure if the watchers accept it but you could check and see :)

Anyway, fun to see you experimenting with ActivityWatch in Docker! Although I'm guessing it won't work very well until we open up the server to nonlocal connections.

**Comment by johan-bjareholt** [comment]
> Also, aw-server should accept a --port argument, so you could try that. Not sure if the watchers accept it but you could check and see :)

You can change the port on all of your local clients in the aw-client config file (in linux it is for example located at `.config/activitywatch/aw-client/aw-client.ini`)

You can actually also change the default port of aw-server aswell in its config file if you don't want to pass the --port argument (located at a similar location, `.config/activitywatch/aw-client/aw-client.ini`)

I don't believe this is documented anywhere though, we should probably do that

- [ ] Document where all config files are located and what properties can be changed there

**Comment by ErikBjare** [comment]
Created #141 as a documentation issue, closing this.
