### ISSUE TITLE
Hide the taskbar icon when minimized on Windows?

### ISSUE THREAD

**Issue by lewisxy** [ActivityWatch/activitywatch#139]
I use `aw-qt.exe` to run the activitywatch in Windows 7. When the program started, it created an icon in system tray, but also leave the icon in taskbar even when the command line window is minimized. 
This does not look nice when there is a lot of icons on the taskbar.
Can the program hide command line window automatically after being launched, or hide the icon on the taskbar when command line window is minimized (only leave the icon in the system)?

**Comment by ErikBjare** [comment]
We are working on this in the following PR: https://github.com/ActivityWatch/aw-qt/pull/31

**Comment by ErikBjare** [comment]
Was solved in the before mentioned PR, closing.
