### ISSUE TITLE
Document APIs in-code with docstrings

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#14]
Would make it easier to document while you code, autodoc to the rescue!

**Comment by ErikBjare** [comment]
We should also use: autodoc-typehints for nice typing-module support.

**Comment by johan-bjareholt** [comment]
Did some further improvements

ActivityWatch/aw-server@c4fe4bd7480eb2189941020acbd5e90b315fb892

**Comment by ErikBjare** [comment]
I don't think we need to keep this issue open as there has been some progress. What's left is simply to increase documentation coverage, but that will naturally take a while.

Closing.
