### ISSUE TITLE
Feedback from a reddit user

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#144]
Someone who wishes to remain anonymous reached out to me on reddit with some amazing feedback. All bolded text is mine.

> Hi Erik, **(redacted)**. I'm dumping some thoughts/opinions/first time experience with ActivityWatch. I hope you find this information well because I'm excited for AW.
> - Change "Official Website" outbound link on https://alternativeto.net/software/activitywatch/ to actual website http://activitywatch.net/. I got lost navigating github.
>    - [x] **A good idea now that the website is a bit better**
> - Screenshots are definitely a high priority for marketing. It was a roadblock for me on whether I should download or not
>   - [x] **Tracked in #122**
> - Clarifying what it can do for me, giving me the selling points above fold on website. Something along the lines of how you can see the biggest time drainers via top applications or top window title. In turn, let's you better decide what things to spend time on when you are on your browser/using documents/specific applications that would have the biggest impact/give you the most progress on your project/work for your time
> - Would not mind seeing a video that demonstrates how the application is used, walking through beginning post installation.
> - I'd love to minimize the ActivityWatch task to my icon tray on Windows. On the same note, I'd like to open the dashboard upon double clicking the icon in the icon tray.  
>    - [x] **This is worked on [here](https://github.com/ActivityWatch/aw-qt/pull/31)**
> - I read somewhere in the documentation or github that I can set ActivityWatch to run on start up, but cannot find that information or intuitively set it when the program is running
>    - [x] **Definitely a priority**
> - A mini-guide on the ActivityWatch home page on how to improve your productivity + use ActivityWatch to do so can build a bit of value/brand/love from first time visitors
> - Being able to delete entry logs/items from the dashboard in a click of a button would be great, or having it password protected somehow would be awesome
>    - [ ] **Tracked in issue #1 and #136**
> - It would be great to open the dashboard and immediately see my stats instead of a welcome message. This is certainly retail space for some marketing.
> - The first thing I did after learning about ActivityWatch from AlternativeTo is to search on Reddit about it. Perhaps https://www.reddit.com/r/Windscribe/ can be a leading example of using Reddit to build momentum and draw attention. u/o2pb has done a great job with his brand
> - One concern I have when it comes to open source projects is to know whether it is alive and well. I would not mind seeing on the website some Twitter API showing recent tweets from https://twitter.com/ActivityWatchIt
>    - [x] **Easy to do and would probably increase our twitter following, great idea**
> - Occasional blog posts would be great when you have the momentum, where visitors can see what more goodies they can do with ActivityWatch
>
> Thank you for developing ActivityWatch. I'm pretty confident you're onto something here as RescueTime is a dominating software in this productivity subniche. Hopefully this message and information does you well. I really look forward to seeing how AW turns out a year or two from now.

And then a few days later once I replied to him:

>Now that I've used it for few days, I'd like to pass on few more insights:
>
> - I always forget to turn it on. This might be the #1 reason I would delete the application
I'm having trouble analyzing my general trend. I'm aware RescueTime labels each type of activity or lets you do so yourself so that you can make an educated guess on how you have been spending your time. 
>   - **Mentioned above, I agree that this is important**
> - Wouldn't mind a feature where I can tag or label each activity as important or not important. It might be a great way to simplify the data and still allow customization at user level. #2 reason why I would delete the application
>    - [ ] **Tracked in #95**
> - There are certain sensitive things I would like to still leave out from the tracker. Password protected wouldn't be a bad idea still. Having the option to exclude website domains/certain applications would be awesome
>   - **Already mentioned above, but is indeed an important feature**
> - I think when I'm watching videos longer than 3 minutes, AW doesn't track since this is the default time for going into AFK mode. Netflix, Youtube, and such aren't tracked.
>   - [ ] **This can be solved in the future by using the browser watcher's *audible* info. Additionally, [the fact that 3 minutes are logged despite no input is incorrect behavior](https://github.com/ActivityWatch/activitywatch/issues/135#issuecomment-346676797)**
>
>All the best, Erik. I'm still excited for ActivityWatch.

**Comment by LeBaux** [comment]
A lot of things woven inhere touch the monetization (marketing) or forming some revenue model. **Not that I am opposing it**, but being clear about future plans is perhaps the most important "marketing" for FOSS people.

**Comment by johan-bjareholt** [comment]
@LeBaux A short summary of how me and @ErikBjare discussions on monetization has been that we would love to develop ActivityWatch more if we got some revenue for it, but it's hard to do without sacrificing some of our core ideals for this projects (FOSS and privacy). For now we only do this in our spare time. Crowdfunding works but there's not enough money in that for us to sustain the project on, it only helps us pay the server costs.

So our only plan for monetization and marketing is to improve ActivityWatch and being active on social media by notifying our users of the new features so more people use it and can help us get either more contributors or more money from crowdfunding.

**Comment by ErikBjare** [comment]
Closing since the action points have been moved/references to other issues.
