### ISSUE TITLE
[Question] Why are there so many C dependencies on the release? 

### ISSUE THREAD

**Issue by manugarri** [ActivityWatch/activitywatch#145]
Given how the repo's codebase is mostly python, I was surprised to see that the latest release has a big number of C files on it.  Sounds a little suspicious.

**Comment by ErikBjare** [comment]
If you by release mean the zips we build for Linux/macOS/Windows and by C dependencies mean the library files in them then the answer is that we use PyInstaller to build binaries that do not depend on Python or anything else non-standard being installed on the system.

It effectively bundles up the Python interpreter and all Python packages we use into a single self-contained package to make installation as easy as possible.

If you don't want to use these builds, then you can [build it yourself from source](https://activitywatch.readthedocs.io/en/latest/installing-from-source.html).

**Comment by ErikBjare** [comment]
By the way, I took a look at your projects and looks like we have some shared interests in recommendation systems.

I [wrote this article](https://erik.bjareholt.com/wiki/importance-of-open-recommendation-systems/) a while back. Let me know what you think and send me an email if you want to discuss it at erik@bjareho.lt :slightly_smiling_face:

**Comment by manugarri** [comment]
yeah i got it, still lots of c files bundled together. I guess seeing them all added to the release raised a red flag for me.

Very nice article btw, I completely agree. Sometimes we DS forget that there is more to our models than the optimization function we define!
