### ISSUE TITLE
Add version information into dashboard or somewhere

### ISSUE THREAD

**Issue by xtotdam** [ActivityWatch/activitywatch#147]
Hi! 
Today I wanted to see if a new version is present and found out there is no (or I could not find it) method to get AW's version.

**Comment by ErikBjare** [comment]
Hi @xtotdam,

You're right that there's no way to do this currently. We are tracking the issue in https://github.com/ActivityWatch/activitywatch/issues/114. Closing this to avoid duplicates, but thanks for reaching out! 🙂

**Comment by xtotdam** [comment]
Heh, I was pretty sure there were no similar issues while looking through them :)

**Comment by ErikBjare** [comment]
@xtotdam Don't worry about it, your reminder was appreciated :)
