### ISSUE TITLE
Disable any-origin CORS by default in testing mode

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#148]
Add a parameter to pass to aw-server if you really need it.

Should probably give the flag a huge warning in the docs and `--help` as well.

**Comment by johan-bjareholt** [comment]
I prefer it as it is, will be annoying and confusing for developers that you would have to add a flag to be able to test the webui.

**Comment by ErikBjare** [comment]
@johan-bjareholt I thought the same, then I realized most people running a testing server are unlikely to ever use it for developing the web UI. The current situation is just not acceptable from a security point of view imo.

**Comment by johan-bjareholt** [comment]
@ErikBjare If it's just when running --testing and it only binds to localhost by default I personally think it is acceptable from a security stand point.

**Comment by ErikBjare** [comment]
@johan-bjareholt Nope, it isn't. 

Any malicious website in the user's browser could just do an XHR request and get access to all the data, that is why CORS exists. It's a severe security flaw that is trivial to take advantage of.

An alternative would be to simply add `localhost:27180` to the list of allowed origins when run in testing mode. That way we could do without the flag entirely.

**Comment by johan-bjareholt** [comment]
> An alternative would be to simply add localhost:27180 to the list of allowed origins when run in testing mode. That way we could do without the flag entirely.

@ErikBjare Good point, didn't think of that.

**Comment by ErikBjare** [comment]
Will be closed by https://github.com/ActivityWatch/aw-server/pull/44
