### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#15]
I've recently become a fan of MPL2, a "file-level" copy left license used by Firefox, Syncthing among others. It is GPL and Apache compatible. 

I've considered the GPL, but I've had concerns about it being "too much". I also considered the MIT License but it isn't copy left, which I think is needed for a project like this.

Thoughts @johan-bjareholt?

**Comment by ErikBjare** [comment]
So, I'm kind of torn on this one. It's between GPL and MPL2. I kind of want to make the decision and get this out of the way as soon as possible.

**Comment by ErikBjare** [comment]
After reading [this](https://www.mozilla.org/en-US/MPL/2.0/FAQ/), we're probably going to go with the MPL2.

**Comment by johan-bjareholt** [comment]
I also vote for the MPL.

Seems to be a good in-between license, being copyleft while still allowing bundling of proprietary libraries if we would ever want to do that.

**Comment by johan-bjareholt** [comment]
So, is this pretty much decided then or is there anything else?

**Comment by ErikBjare** [comment]
It's decided. I just haven't gotten around to putting LICENSE files in all the repos.

**Comment by ErikBjare** [comment]
In progress:

 - [x] activitywatch
 - [x] aw-core
 - [x] aw-server
 - [x] aw-client
 - [x] aw-webui
 - [x] aw-watcher-afk
 - [x] aw-watcher-window

**Comment by ErikBjare** [comment]
Done in 04e32bc and updated submodules in d20ccba.
