### ISSUE TITLE
[bug] [investigate] False-positive virus archive scan results

### ISSUE THREAD

**Issue by BoulaZa5** [ActivityWatch/activitywatch#152]
1. ActivityWatch Version:
   - 0.7.1
2. What made the issue/bug appear? (steps to reproduce)
   - Scanning the [_windows archive_](https://github.com/ActivityWatch/activitywatch/releases/download/v0.7.1/activitywatch-v0.7.1-windows-x86_64.zip) with avast!, [_VirusTotal_](https://www.virustotal.com/#/file/320a3ed29ee87fa9de5b497f396f597ce51b74d91a5bbb9673d68ad5b7cbdb8b) or [_Jotti_](https://virusscan.jotti.org/en-US/filescanjob/5jfkyaejmt)
3. Include a logfile:/
   - Its not a bug with the program itself.

**Comment by BoulaZa5** [comment]
After some digging, I don't think it has anything to do with any of your scripts. The machine where you froze all py scripts and/or the used freezing script itself was infected -because all executables are identified as false-positives.

![image](https://user-images.githubusercontent.com/32979932/33796341-097afa4c-dcfb-11e7-987f-84004a230420.png)
![image](https://user-images.githubusercontent.com/32979932/33796343-1011176a-dcfb-11e7-86f8-f8c76484d21c.png)
![image](https://user-images.githubusercontent.com/32979932/33796345-16388092-dcfb-11e7-915c-f20340c9ddfb.png)
![image](https://user-images.githubusercontent.com/32979932/33796347-1adfee0a-dcfb-11e7-8c09-86f951dccd12.png)

**Comment by johan-bjareholt** [comment]
aw-watcher-afk works like a keylogger, so it is technically not a false-positive. There is no API in windows/mac/linux which only detects that any key is pressed, so aw-watcher-afk has to fetch which key is pressed aswell which is exactly how a keylogger works. Your anti-virus only detects that aw-watcher-afk uses this API and assumes that it's a virus, but in reality aw-watcher-afk uses this API to fetch the most recently pressed key, but then just throws away the data about which key it was, so it never logs which specific keys are getting pressed.

**Comment by BoulaZa5** [comment]
It doesn't get to start so the behavioral shield doesn't identify it as a keylogger. Also this doesn't explain why other executables are detect as filecoders(which i'm pretty sure it has something to do with the freezing script -because the antivirus have no way to know it is a filecoder unless it actually execute coding activity).
Anyway in those cases you have to submit the files and the program's download link for review and they will just exclude it in the next database update. I'm going to submit this to avast and see where it is going.

**Comment by johan-bjareholt** [comment]
I have no experience with Avast, but it could also be something related to PyInstaller. Since the whole python interpreter and its standard library is included, anything within those could also be the reason why Avast reports it as a filecoder.

It wouldn't surprise me if the most common filecoder ransomwares for windows were written in python with PyInstaller since python is easy to use with built-in encryption algorithms and PyInstaller makes it easy to distribute.

We should probably add checksums to our downloads though, we currently don't have that.

> Anyway in those cases you have to submit the files and the program's download link for review and they will just exclude it in the next database update. I'm going to submit this to avast and see where it is going.

I also have no idea how this works, would this whitelist this specific version or all forthcoming versions?

**Comment by ErikBjare** [comment]
This has already been discussed in https://github.com/ActivityWatch/activitywatch/issues/140

Closing since it's a duplicate.

**Comment by ErikBjare** [comment]
>There is no API in windows/mac/linux which only detects that any key is pressed, so aw-watcher-afk has to fetch which key is pressed aswell which is exactly how a keylogger works. Your anti-virus only detects that aw-watcher-afk uses this API and assumes that it's a virus, but in reality aw-watcher-afk uses this API to fetch the most recently pressed key, but then just throws away the data about which key it was, so it never logs which specific keys are getting pressed.

This is false. aw-watcher-afk uses platform-specific APIs on Windows and macOS to get the time passed since last input without listening to every keystroke/mouse-movement since some time now.

**Comment by BoulaZa5** [comment]
Avast flagged the app as safe. I truly suggest that you submit the file to other anti-virus softwares because really' anyone who downloads the app and then the av pops up saying that it is unsafe to use will just delete it.
