### ISSUE TITLE
AFK watcher incorrectly logging AFK time

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#153]
Today I was surprised to see I had an AFK event that stretched into the future:

![image](https://user-images.githubusercontent.com/1405370/33829691-9cc2a72e-de71-11e7-98ec-10ab5c5ab7e9.png)

After looking further into the data, I found that it had happened on previous occasions as well.
So presumably something went wrong with the AFK watcher when my computer woke from suspend.

To prevent something similar happening in the future we should:

 - [x] Add a check in aw-server that incoming events don't stretch into the future. (Done in https://github.com/ActivityWatch/aw-server/pull/40)

There is also another issue we should try to resolve at the same time:

 - [ ] https://github.com/ActivityWatch/activitywatch/issues/135#issuecomment-346673027

Not sure if it matters, but this happened on Windows.

**Comment by johan-bjareholt** [comment]
Possibly also
- [ ] aw-analysis tool for checking for overlapping events in a bucket

**Comment by johan-bjareholt** [comment]
I had a 134h afk event on my laptop, after switching to the sqlite datastore that afk event suddenly became 45min as it was supposed to. Not sure what actually fixed it, but considering this it might be an issue with the datastore rather than with the watcher.

**Comment by ErikBjare** [comment]
As far as I can tell this is no longer an issue. Closing.
