### ISSUE TITLE
aw-watcher-window makes aw-server use a lot of CPU resources

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/activitywatch#156]
If I turn off aw-watcher-window but still have aw-watcher-web and aw-watcher-afk running, the CPU usage of aw-server drops from constant ~15-17% CPU usage to ~0-3% on a 7700K processor.

My guess is that something makes aw-watcher-window send heartbeats every second even though it does not have to. Will provide logs and debug once I have some spare time.

Debian 8, packaged activitywatch 0.7.1 release.

**Comment by rplnt** [comment]
Do you have a browser plugin as well? I noticed high CPU usage with it.

**Comment by johan-bjareholt** [comment]
@rplnt Yes, aw-watcher-web is the browser plugin which works on both firefox and chrome. As mentioned it only seems to be aw-watcher-window for me atleast,

**Comment by ErikBjare** [comment]
I'm guessing this will get solved once https://github.com/ActivityWatch/activitywatch/issues/98 is fixed.

**Comment by ErikBjare** [comment]
Solved along with https://github.com/ActivityWatch/activitywatch/issues/98. Closing.
