### ISSUE TITLE
Highly frequent disk writes

### ISSUE THREAD

**Issue by ptoews** [ActivityWatch/activitywatch#157]
Since I'm not an expert, I don't know if this is an issue, but I noticed pretty high disk usage after installing this tool. `iotop` shows me that almost every second aw-server is writing to disk. Isn't this unhealthy for the hard drive? No other process on my system is using the disk that often. Wouldn't it be better to buffer the data for 1-5 minutes to do a bulk write?

**Comment by johan-bjareholt** [comment]
> Since I'm not an expert, I don't know if this is an issue, but I noticed pretty high disk usage after installing this tool. iotop shows me that almost every second aw-server is writing to disk.

This is an issue we have been looking to improve. We have a PR which i recently commented on for a few more possible optimizations for this https://github.com/ActivityWatch/aw-server/pull/32

> Isn't this unhealthy for the hard drive?

It should be negligable, but I'm no hardware expert on HDDs. It might take up a bit of battery on laptops with a HDD though if ActivityWatch keeps the HDD from suspending (probably also negligable though).

> Wouldn't it be better to buffer the data for 1-5 minutes to do a bulk write?

1-5 minutes is a bit excessive in my opinion, but 10-30s would be nice.

**Comment by ErikBjare** [comment]
Thanks for the feedback @ptoews! I'm tracking solutions to this issue in https://github.com/ActivityWatch/activitywatch/issues/98 and one ob the two proposed solutions are in the PR that @johan-bjareholt linked above. We're working on it :)

Closing.
