### ISSUE TITLE
Decide on format for window/tab/application data

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#16]
This data format should be similar for the following watchers, accommodating all their needs:

 - Executable path/URL (could be URL, we might want to have arguments as well, such as when the executable is Python/Java running a program) 
 - Window/tab title (could be title) 
 - Window class (could be tags/labels)

**Comment by ErikBjare** [comment]
Right now I just put everything in labels, a good improvement which would settle this would be to label them "title:<actual title>", "class:<class>" etc.

**Comment by ErikBjare** [comment]
We will settle on prepending strings with "title", "class", and so forth for now.

**Comment by johan-bjareholt** [comment]
I don't think this is good enough, I would like more discussion about this and other cases on where we need to do classification in general
