### ISSUE TITLE
Logo and title gets replaced after hovering the clock view

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#169]
![image](https://user-images.githubusercontent.com/1405370/35442511-cc5d18ca-02a7-11e8-873a-229281dbf890.png)

Fun bug lol

**Comment by johan-bjareholt** [comment]
Yeah I've seen this before, it starts when you hover an item in the sunburst view.

**Comment by ErikBjare** [comment]
Fixed it in the mentioning commit: https://github.com/ActivityWatch/aw-webui/commit/c5d26a24c92906655b25e5aa00be331f21e17686
