### ISSUE TITLE
Spotify Watcher

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#17]
Apparently Spotify has clean API for getting playing song. Would be nice to use this for logging. @emarforio knows more. 

Might want to do this on Android too, so a watcher that works on all platforms would be nice. 

An event would look something like:

```
{
  "label": ["title:chns", "artist:Hannes Nilsson", "album:Unfinished shit"], 
  "duration": 115, 
  "timestamp": ...
} 
```

**Comment by emarforio** [comment]
Spotify has (I hope at least, they had before, will check) a local webapi which you can get data from through a REST interface. All kinds of information is available. Take a look at this plugin for Rainmeter (a desktop decorating software, Windows equivalent to Conky) that does exactly this: https://github.com/RobertFrydenlund/SpotifyPlugin

**Comment by ErikBjare** [comment]
Spotify has LastFM support which works, so closing this for now.

**Comment by ErikBjare** [comment]
There has been a request for such an API for a long time, see issue: https://github.com/spotify/web-api/issues/12

However, Spotify has recently released a new API endpoint: https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/

Should make the watcher easy to implement. Just ask the user for keys via Oauth and then poll the endpoint.

**Comment by ErikBjare** [comment]
So, I threw this together in about an hour this morning: https://github.com/ActivityWatch/aw-watcher-spotify

Requires some trickery to start using (getting API keys via Oauth), but works.

Closing.
