### ISSUE TITLE
Harden aw-client

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#170]
aw-client is currently not as resilient against failure as it ought to be.

Problems:
 - RequestQueue [does not safely write back to disk on failure](https://github.com/ActivityWatch/aw-client/blob/master/aw_client/client.py#L296).
 - RequestQueue currently supports arbitrary queued requests, but it's not written with such things in mind (only heartbeats).

I found this library [`persist-queue`](https://pypi.python.org/pypi/persist-queue/0.3.4) which might be a better way to handle this.

Related issues:
 - https://github.com/ActivityWatch/activitywatch/issues/164

**Comment by ErikBjare** [comment]
See my attempt at switching to persist-queue here: https://github.com/ActivityWatch/aw-client/pull/28

**Comment by ErikBjare** [comment]
Downgrading priority since we merged the `persist-queue` PR.

**Comment by johan-bjareholt** [comment]
All problems specified in the issue are now fixed, why not close this issue?
If we find some other place where aw-client is not resilient enough we could create a new issue for that.

**Comment by ErikBjare** [comment]
Oh, I guess it is. Closing :smile:
