### ISSUE TITLE
Log as AFK when suspending computer

### ISSUE THREAD

**Issue by MaZZly** [ActivityWatch/activitywatch#172]
Would it be possible to log an AFK event, when(just before) the computer is suspended?

Related to: https://github.com/ActivityWatch/activitywatch/issues/135 and possibly https://github.com/ActivityWatch/activitywatch/issues/153

**Comment by johan-bjareholt** [comment]
By default aw-watcher-window has an accuracy of 1 second and aw-watcher-afk has an accuracy of 5 seconds so it should never be more off than 5 seconds regarding when going into suspend, how much off is it for you?

**Comment by MaZZly** [comment]
well I might have errors in my hour-logging script so don't rule that out as a total impossibility.

Usually it is off by 10-50minutes, can be hours some days (I guess this depends on when a previous AFK event has been saved, before the suspend).

**Comment by ErikBjare** [comment]
@MaZZly Which operating system are you using?

10-50min is way too long, must be a bug of some sort. Are you running the latest development version or v0.7? Might have been fixed in the development version since it has seen some changes to the relevant code.

**Comment by johan-bjareholt** [comment]
I am running 0.7 on my work computer and master on my home computer which both seem to be working fine with suspend, I'd bet on some environment dependent bug if it's that out of whack.

**Comment by MaZZly** [comment]
@ErikBjare Fedora 27
0.7 from somewhere in October.

I should probably try to fetch some later version and see if the behaviour gets fixed

**Comment by MaZZly** [comment]
I've tried upgraded to 0.7.1 and used it for 3 days, still same problem exists there.

**Comment by johan-bjareholt** [comment]
Can you provide an example of the aw-watcher-afk and aw-watcher-window events when this occurs?

**Comment by ErikBjare** [comment]
There's a high probability that this issue has been fixed. If that isn't the case, please reply with more details. Closing.
