### ISSUE TITLE
Microsoft Edge is recognized as `ApplicationFrameHost.exe`

### ISSUE THREAD

**Issue by neilsustc** [ActivityWatch/activitywatch#182]
Thanks for this really nice app!

I found a little problem that Microsoft Edge (the new browser on Windows 10) is recognized as `ApplicationFrameHost.exe`

![image](https://user-images.githubusercontent.com/7588612/38077016-0afa8ffc-336a-11e8-9f3f-feddac873420.png)

**Comment by johan-bjareholt** [comment]
After some googling it seems like ApplicationFrameHost.exe is sometimes a kind of container for Windows 10 UWP apps (apparently for Microsoft Weather aswell for example).

Here's some solution for C# and its windows API:
https://stackoverflow.com/questions/39702704/connecting-uwp-apps-hosted-by-applicationframehost-to-their-real-processes

@ErikBjare wrote the aw-watcher-window support for windows so I don't know much about how those windows APIs work, but my guess would be that we need to add support for UWP apps in the wmi and/or pypiwin32 libraries.

**Comment by neilsustc** [comment]
Thanks 👍

**Comment by ErikBjare** [comment]
Thanks for reporting! We will probably find a way around this in the future but don't hold your breath; developing on Windows is a real pain for me.

I'm sure we'll find a solution to stuff like this in the future though, I think something similar applies to certain Java apps (such as the Java/original edition of Minecraft).

**Comment by johan-bjareholt** [comment]
Moving this issue to aw-watcher-window, closing

https://github.com/ActivityWatch/aw-watcher-window/issues/31
