### ISSUE TITLE
Installing from source fails with npm dependency problems

### ISSUE THREAD

**Issue by unode** [ActivityWatch/activitywatch#183]
While installing from source.

Created a virtualenv, activated the virtualenv and `make build` resulted in:

```
(...)
Successfully installed aw-client-0.3 aw-core-0.4.0
make[1]: Leaving directory '/home/u/projects/activitywatch/aw-client'
make --directory=aw-server build DEV=
make[1]: Entering directory '/home/u/projects/activitywatch/aw-server'
make --directory=aw-webui build DEV=
make[2]: Entering directory '/home/u/projects/activitywatch/aw-server/aw-webui'
npm install
npm WARN bootstrap-vue@1.5.1 requires a peer of vue@^2.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN vue-awesome@2.3.5 requires a peer of vue@^2.2.6 but none is installed. You must install peer dependencies yourself.

+ aw-webui@1.0.0
added 1 package in 0.995s
npm run build

> aw-webui@1.0.0 build /home/u/projects/activitywatch/aw-server/aw-webui
> node build/build.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/u/projects/activitywatch/aw-server/aw-webui/build/build.js:2:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aw-webui@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aw-webui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/u/.npm/_logs/2018-04-06T09_45_27_866Z-debug.log
make[2]: *** [Makefile:6: build] Error 1
make[2]: Leaving directory '/home/u/projects/activitywatch/aw-server/aw-webui'
make[1]: *** [Makefile:10: build] Error 2
make[1]: Leaving directory '/home/u/projects/activitywatch/aw-server'
make: *** [Makefile:35: build] Error 2
```

Versions are:

```
$ npm --version
5.6.0
$ node --version
v9.4.0
```

Any suggestions?

**Comment by johan-bjareholt** [comment]
> Error: Cannot find module 'shelljs/global'

apparently it did not seem to build this npm package for some reason.
It doesn't indicate what made it not install, so my first guess would to simply try it once again and if that doesn't work go into the aw-webui folder yourself and run "npm install shelljs" which should hopefully fix it.

The WARN messages on the top also reminded me that we need to update our npm package versions, but that's unrelated to this issue.

**Comment by johan-bjareholt** [comment]
My guess would be that it's due to we having old package versions in our packages.json.
Works for me and on travis though, so not sure what makes it break in your environment specifically.
Will try to update the package versions in a few hours when I get home.

**Comment by unode** [comment]
Probably a cache in both environments saving the day.
Thanks I'll try again after your update.

**Comment by johan-bjareholt** [comment]
Fixed, pull master and it should be working!

https://github.com/ActivityWatch/aw-webui/commit/a0f55320d97b30a89b52916afbad366f51f87591

**Comment by unode** [comment]
So pulling wasn't enough to fix it... Turned out I had an `~/.npmrc` with `global = true` and this caused the failure.
Commenting that line solved the issue.

Perhaps it could make sense to force `npm` to do a local install or otherwise ignore `~/.npmrc` if it exists and conflicts with expectations of npm or the installation scripts.

**Comment by johan-bjareholt** [comment]
> Perhaps it could make sense to force npm to do a local install or otherwise ignore ~/.npmrc if it exists and conflicts with expectations of npm or the installation scripts.

Honestly, setting global=true in your .npmrc sounds like asking for trouble and if someone has modified their .npmrc themselves I will assume that they know what they are doing. So I'm not going to do anything about such corner cases. Closing the issue.
