### ISSUE TITLE
add manual data

### ISSUE THREAD

**Issue by 1000i100** [ActivityWatch/activitywatch#184]
I woud like to save a manual event : invoice sent
so when i want to count time spent since last invoice for this client/project, i can do it easly.

An other usecase is : traveling time.
Sure i was afk, i was driving !
But i want record this. (automatically by phone gps tracking ?) or manualy with one click on my phone to say : i was traveling since you see me afk.
Yes, this feature with smartphone is for 1.x or 2.x version, but it's what i would like to use.

**Comment by ErikBjare** [comment]
Thanks for adding the issue. We want to add this feature in the future, but it might take a while until we get more urgent matters done. 

I'll close this for now, but thanks for your patience :heart:
