### ISSUE TITLE
Not capturing the movie time properly

### ISSUE THREAD

**Issue by TrigonaMinima** [ActivityWatch/activitywatch#186]
It does not capture the running time of a movie properly. I finished watching a 1 hr 30 min movie and it's only showing 23 minutes of it. This has happened previously as well where it only showed 5-10 minutes. Is this an issue or am I missing something?

**Comment by ErikBjare** [comment]
If there is no mouse or keyboard input we think you're AFK, this is why it doesn't show up. We still capture the window, but it won't be included in the analysis. 

It might be possible to work around this if the window title contains some special symbol like [▶️](https://emojipedia.org/black-right-pointing-triangle/) but for now that's not something we support.

**Comment by TrigonaMinima** [comment]
Can't another work around be that we check if the current active application is among some widely used media players (eg. vlc)? Or we check if some audio driver is active? The second one seems far fetched though.

If there's something I can help with to handle this (by code) then please direct me to the relevant place.

**Comment by johan-bjareholt** [comment]
@TrigonaMinima Yes it would be possible to work around it by checking popular applications such as VLC, but that would give false positives in case the user leaves his computer with a paused video.
That's the reason why the solution with a UTF-8 play icon or similar in the title would be more accurate, but unfortunately that isn't supported on many media players. It should work with YouTube however which is rather popular.

**Comment by ErikBjare** [comment]
>Or we check if audio driver is active?

I'd actually really like that, I've considered it before and would find interesting to build, but it would probably be a bit messy (and likely pretty hard to get working cross-platform), so I'm afraid we don't have the time to do that anytime soon (since it has a relatively low benefit/cost ratio).

You might also be interested in [Trakt.tv](https://trakt.tv/), which does movie/TV-show logging really well (and has a VLC plugin).

**Comment by TrigonaMinima** [comment]
> it would probably be a bit messy (and likely pretty hard to get working cross-platform), so I'm afraid we don't have the time to do that anytime soon (since it has a relatively low benefit/cost ratio).

Yeah true. 

I used Trakt.tv for some time, but sadly, there, I don't have control of my data. To get a dump I need to buy the subscription. Thanks for the suggestion though.

**Comment by ErikBjare** [comment]
@TrigonaMinima I think Trakt.tv has to offer data export for free according to GDPR. Might be worth sending them a mail.

I've connected it to Zenobase.com and export that way.
