### ISSUE TITLE
Add date picker widget

### ISSUE THREAD

**Issue by unode** [ActivityWatch/activitywatch#187]
When browsing history, it quickly gets annoying if you want to check records older than a couple of days.

Changing the URL manually is a reasonable workaround but for the sake of convenience and usability, could [some kind](https://material.angularjs.org/latest/demo/datepicker) [of datepicker](https://jqueryui.com/datepicker/) be added to the activity report page?

**Comment by ErikBjare** [comment]
We agree, and I'm happy to say that I have really good news for you :tada: 

It's [actually implemented in the development version](https://github.com/ActivityWatch/aw-webui/issues/22). We just haven't made a release that includes it yet :upside_down_face:

**Comment by ErikBjare** [comment]
All thanks to @johan-bjareholt :star2:

**Comment by unode** [comment]
The best feature requests are the ones that are already done :smile: .
Thanks, looking forward to it.
