### ISSUE TITLE
No weekly, monthly, quarterly, yearly, global statistics.

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#189]
No weekly, monthly, quarterly, yearly, global statistics - it can be helpfull. If we can compare to previous period too.

**Comment by ErikBjare** [comment]
I think this has been an undocumented TODO for a while now, thanks for reminding us!

Would take a long time to query the data if there are a lot of events, but I'm sure we'll find a way.

**Comment by ErikBjare** [comment]
This has been partially implemented (weekly/monthly, yearly will be back soon). Closing.
