### ISSUE TITLE
Activity not showing correctly if events cross day mark

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#190]
When I play some game I was counter before 24:00, and no counted after 24:00 until I was not switch again to game with alt+tab. Looks like problem with 0:00.

**Comment by johan-bjareholt** [comment]
This issue is explained here, we have it planned and know the solution but it might take a while:
https://github.com/ActivityWatch/activitywatch/issues/179#issuecomment-379439592

**Comment by ErikBjare** [comment]
@Chemrat Correct, that is one possible case where the issue occurs.

**Comment by ErikBjare** [comment]
It should be solved in aw-server-rust if I'm not mistaken, @johan-bjareholt should know.

Work was also done to get this working in aw-server-python, but I'm not sure how much progress was made.

**Comment by johan-bjareholt** [comment]
@ErikBjare It's solved in aw-server-rust and in the sqlite datastore for aw-server-python.

**Comment by johan-bjareholt** [comment]
Closing this, it's fixed in aw-server-rust and if you are using aw-server-python it's easy to work-around by setting the "end-of-day" setting in the web-ui.
