### ISSUE TITLE
Regular development updates

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#193]
[James Flynn commented on Patreon](https://www.patreon.com/posts/17206179):

> How have things been going the last few months? Recurring updates, even just to say thanks every now and then, could be a good way to help keep Patron support consistent. Maybe start small with like bimonthly or quarterly updates, and just keep with it. Anyway, great project, can't wait to see what you guys come up with!

Bimonthly updates sounds like a good idea, now the question just remains where we should post them?

I suppose the forum, Patreon (copy/paste), and Twitter (link).

What do you think @johan-bjareholt?

**Comment by ErikBjare** [comment]
Just wrote the first one: https://forum.activitywatch.net/t/development-update-may-2018/108

**Comment by johan-bjareholt** [comment]
Awesome!
This link is also pretty useful to see what issues have been opened/closed the past month, not very readable for users but useful to get a grasp of if we are gaining backlog or working it off.
https://github.com/ActivityWatch/activitywatch/pulse/monthly

**Comment by ErikBjare** [comment]
Kinda fixed. We're at least doing development updates now, even though they are only once or twice a year.
