### ISSUE TITLE
aw-watcher-afk quit unexpectedly on start

### ISSUE THREAD

**Issue by swayson** [ActivityWatch/activitywatch#199]
Hi there, 

I am a new user trying this tool out. It appears the program doesn't actually start correctly. I run `aw-qt.exe` but one of the programs, namely, `aw-watcher-afk`, seem to fail executing. Restarting the Module, results in the same behaviour.

When I go to the dashboard. There is no data.

![image](https://user-images.githubusercontent.com/1834241/40883572-df5a19ba-6700-11e8-9496-224a5b512239.png)

Version: v0.8.0b3
OS: Windows 10

**Comment by lktvlm** [comment]
Same here on WIndows 8 x64
Doesn't happen on v 0.7.1, there's nothing about this in logs

**Comment by ivanji** [comment]
same here. (Using the latest version).

**Comment by ErikBjare** [comment]
Sorry for keeping you all on hold, I expect to boot into Windows sometime next week and resolve the issue then once and for all.

**Comment by ErikBjare** [comment]
I think this line is the issue: https://github.com/ActivityWatch/aw-watcher-afk/compare/0e7e95637aca11e0bf358cb1efc4e72cbd2d6a9c...master#diff-0ff018684df749f769a7b5b421fce5a3L17

**Comment by ErikBjare** [comment]
I'm just gonna ninja-push a fix, I think it'll work.

**Comment by ErikBjare** [comment]
Created a new beta that should (hopefully) work. Releases should get built soon in CI: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.8.0b4

**Comment by ErikBjare** [comment]
Aw shit. Apparently the Appveyor now fails for some reason: https://ci.appveyor.com/project/ErikBjare/activitywatch/build/1.0.474

Seems unrelated to this issue. The Linux and macOS builds work fine so still a Windows issue.

Here is a working build: https://ci.appveyor.com/project/ErikBjare/activitywatch/build/1.0.473

I noticed that the working build uses `v5.10.2` while the faulty one uses `v5.11.2`. I'll check release notes/look for a fix, and if all else fails pin the PyQt5 version to `v5.10.2`.

**Comment by johan-bjareholt** [comment]
Runs fine for me from source on windows, likely has something to do with PyInstaller.

**Comment by ErikBjare** [comment]
@johan-bjareholt You ran v0.8.0b4 I presume where I fixed the issue? It could not have worked in v0.8.0b3 as I fixed a pretty critical bug.

All left now is a failing `test-integration` step on macOS, this means we have no idea if the PyInstaller binary will start properly on end users machines, but it could just be something acting up in CI or the scripts.

**Comment by ErikBjare** [comment]
This was never a pyinstaller bug, just https://github.com/ActivityWatch/activitywatch/issues/210 and then the PyQt5 version bump that caused issues (the macOS bug is a seperate issue altogether). 

Tried running v0.8.0b5 in Wine and it works fine, closing.
