### ISSUE TITLE
Rework the buckettype names and data formats

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/activitywatch#201]
I have a suggestion to migrate the buckettype formats to the following:

**Name:** currentwindow -> os.window.current
**Data format:** The same

**Name:** afkstatus -> os.hid.activity
**Data format:** `{ activity: boolean }` (previously `{ status: string ("afk" or "not-afk") }`)

We could bump up all the datastore versions for this migration, the solution would be identical to all datastores since it's just a matter of exporting the old buckets and importing them to the new ones

**Comment by ErikBjare** [comment]
There is still work to do here in the long-term. It's now being discussed in #424.
