### ISSUE TITLE
Add styleguides to contributing.md

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/activitywatch#202]
I think it would be helpful to link the preferred styleguides (python, javascript, ...) and some styleguide checking tools (e.g. pylint) in the contributing.md

For javascript I'd recommend this comprehensive [styleguide from airbnb](https://github.com/airbnb/javascript) and jslint.
I am not so familiar with python, but I guess [PEP 8](https://www.python.org/dev/peps/pep-0008/) would be a good choice for this together with the [pep 8 styleguide checker](https://pypi.org/project/pep8/) or pylint.

Of course, we can't enforce or even expect everyone to completely read these docs, but in the past I personally found it helpful to have a styleguide, where I can look up certain things.

**Comment by johan-bjareholt** [comment]
Agree

Our python code mostly follows pep8 but our JavaScript code is all over the place. We had a PR once which added jslint support on aw-webui but it was so broke it actually broke functionality so we had to roll it back. Should be pretty easy to automate this with travis.

**Comment by ErikBjare** [comment]
I still think we should do this, and with the Black Python linter/code-formatter we should be able to do this automatically (just like how Prettier does it for Javascript).

**Comment by Otto-AA** [comment]
If you want a style guide for javascript, I'd suggest [standard](https://github.com/standard/standard). It is a pre-configured style guide, which means that it is super easy to add it to the project. It also supports automatically fixing style errors (`npx standard --fix`) and seems to be pretty popular.

**Comment by ErikBjare** [comment]
We currently have a working eslint + prettier config for aw-webui, and that isn't going to change anytime soon. Standard looks good, but it isn't designed for use with Vue.js.

I'm interested in properly documenting the fact that we use eslint + prettier for aw-webui and maybe start using Black for all the Python code.
