### ISSUE TITLE
Create aw-watcher-vscode repository

### ISSUE THREAD

**Issue by Otto-AA** [ActivityWatch/activitywatch#203]
Should I move the [aw-watcher-vscode](https://github.com/Otto-AA/aw-watcher-vscode) repository from my profile to this organization?
If yes, are there some things I should keep in mind?

**Comment by johan-bjareholt** [comment]
Oh you have migrated fully to aw-client-js now, nice.
Seems to me like the project is of pretty good quality so we could do that if you want.
I created an empty repository for it and gave you full write-access, should be possible to push all your previous commits on top of this repo now https://github.com/ActivityWatch/aw-watcher-vscode

Then you probably want to change the source on microsoft marketplace, then it should be done :)

**Comment by johan-bjareholt** [comment]
The extension on Microsoft marketplace still points to the old repo

**Comment by Otto-AA** [comment]
> The extension on Microsoft marketplace still points to the old repo

This will automatically be updated with the next publishing (or in other words: as soon as the other repo becomes outdated)
