### ISSUE TITLE
Decoding error when building from source

### ISSUE THREAD

**Issue by pahofmann** [ActivityWatch/activitywatch#209]
I tried building activity watch from scratch, to see if that help with my issue #208 

I get the following error, seems to be a decoding problem: 

> make --directory=aw-core build DEV=
> make[1]: Entering directory '/opt/activitywatch/aw-core'
> pip3 install . -r requirements.txt --upgrade
> Processing /opt/activitywatch/aw-core
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-y10quhhg/setup.py", line 14, in <module>
>         exec(f.read(), about)
>       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 386: ordinal not in range(128)
>     
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-y10quhhg/
> make[1]: *** [Makefile:10: build] Error 1
> make[1]: Leaving directory '/opt/activitywatch/aw-core'
> make: *** [Makefile:33: build] Error 2

I'm running the build on archlinux wtih python 3.6.5. Are there any dependencies not mentioned in the _Install from source_ guide I might be missing?

**Comment by Otto-AA** [comment]
I guess that it can't decode "Bjäreholt"

So... please change your surname @ErikBjare :stuck_out_tongue:

**Comment by Otto-AA** [comment]
Cant't test it, but this could possibly fix it:
```python
with open(os.path.join(base_dir, "aw_core", "__about__.py"), 'r', encoding='utf-8') as f:
   exec(f.read(), about)
```

**Comment by ErikBjare** [comment]
Might be something with your system configuration (it should try to read the file as unicode and not ascii), but here's a fix that should hopefully resolve the issue that we could apply globally:

Replace the lines in setup.py that @Otto-AA mentioned with:

```py
import codecs
with codecs.open(os.path.join(base_dir, "aw_core", "__about__.py"), "utf-8") as f:
    exec(f.read(), about)
```

**Comment by johan-bjareholt** [comment]
Personally I believe that you both might be wrong, encoding=None is the default which calls `locale.getprefferedencoding()` which should on any sane OS should be "UTF-8".

Prior to python3 the encoding was always "ascii" by default, so my assumption here is that while he has python3 installed it is actually running inside a python2 instance which he probably also has installed. You can see in setup.py that we have written `#!/usr/bin/env python` which on most systems (with a exception on fedora and arch) would default to python2 rather than python3, so if he is simply running it with `./setup.py install` it is highly likely that this is in python2. We should replace this with `#!/usr/bin/env python3`

**Comment by johan-bjareholt** [comment]
Okay I am wrong, it explicitly says right in the log message that it runs on python3.6

> File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode

**Comment by pahofmann** [comment]
Thanks for the quick suggestions!
I modified `./aw-server/setup.py` and `./aw-core/setup.py` with the suggestion from @Otto-AA, there is no aw-research after cloning the repo though.  
The build continues now, but there still is a problem when building the client:

> make[1]: Entering directory '/opt/activitywatch/aw-client'
> pip3 install . -r requirements.txt --upgrade
> Processing /opt/activitywatch/aw-client
> Collecting aw-core from git+https://github.com/ActivityWatch/aw-core.git@master#egg=aw-core (from -r requirements.txt (line 1))
>   Cloning https://github.com/ActivityWatch/aw-core.git (to master) to /tmp/pip-build-qvod5moe/aw-core
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-qvod5moe/aw-core/setup.py", line 14, in <module>
>         exec(f.read(), about)
>       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 386: ordinal not in range(128)

There is no `about{}...` section in the `./aw-client/setup.py` for the change  you mentioned and changeing  `Bjäreholt` to `Bjaereholt` there did not help either :P
What should I change in the client setup file?

**Comment by Otto-AA** [comment]
You can try it again after removing the first line of the requirements.txt file in aw-core and aw-server. ([this line](https://github.com/ActivityWatch/aw-client/blob/3702ff6ee2b3fdef5f4a56e16cbb1c06995d9f2c/requirements.txt#L1))
Maybe that helps...

**Comment by ErikBjare** [comment]
Yeah, what @Otto-AA wrote should work. But I just pushed https://github.com/ActivityWatch/aw-core/commit/c29d28a8a0b634c1b51d639f2bc018c7b9498a75 which should just make things work without any changes on your side @pahofmann

**Comment by pahofmann** [comment]
I pulled the lastest version for aw-server and aw-core, now the build went though fine.
Thanks for the quick help!

Any tips on how to further troubleshoot #208 would be much appreciated.
