### ISSUE TITLE
Use configparser when possible

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#21]
Config files in JSON really shouldn't be a thing.

configparser looks nice, had no idea it existed: https://docs.python.org/3/library/configparser.html

One possible argument for keeping config files in JSON is that they would be easy to send and edit over the wire. But really that shouldn't be done with the entire file anyway (for security reasons).

**Comment by johan-bjareholt** [comment]
This was fixed a few days ago, closing.
