### ISSUE TITLE
No browser data shown on dashboard although it shows up on API and Raw Data

### ISSUE THREAD

**Issue by cook2011** [ActivityWatch/activitywatch#213]
I posted on the forum but it has been down now for a few days. 

I can tell that AW is recording browser data from the API and Raw Data tabs for aw-watcher-web-firefox, but it doesn't show up under Activity - it just says no data.

the dashboard says "Version: v0.8-dev-unknown" but I downloaded the most recent version from the website a week ago (7/20).

**Comment by cook2011** [comment]
I'm on Windows 7 64-bit. I'm running normal Firefox, 61.0.1 up to date.

The appname of firefox in the aw-watcher-window tab is app: firefox.exe

**Comment by johan-bjareholt** [comment]
I found that I actually fixed that in the beginning of July, but the latest beta version does not have that fix yet.

So this issue will be fixed in the next release

Here's the commit which fixed it:
https://github.com/ActivityWatch/aw-webui/commit/44bb4cfefb74404e559ffefc18a52a0612c12152

Closing

**Comment by cook2011** [comment]
Great, thanks!

**Comment by nicolae-stroncea** [comment]
Commit did not solve the issue for me. aw-watcher-web-chrome shows the data, whereas aw-watcher-web-firefox, still doesn't

**Comment by johan-bjareholt** [comment]
@nicolae-stroncea In that case, please do the same thing as @cook2011 and provide appname of firefox so we can debug.

Please also specify which git commit of aw-webui you are running.

**Comment by nicolae-stroncea** [comment]
i'm on Windows 10, 64-bit, running Firefox 61.0.1 (64-bit).
App name is firefox.exe.
Last commit of aw-webui is: 93de4fec2afb44c76368718b42f1ad9495517df4

**Comment by johan-bjareholt** [comment]
That commit is the commit specified in the aw-webui git submodule in aw-server and is not the latest one, check out the master branch and pull the latest changes in aw-webui and it should work.
