### ISSUE TITLE
Where do I include a new python module for the project to import automatically?

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#215]
I'm trying to use two new modules in the file: activitywatch/aw-watcher-window/aw_watcher_window

I put this at the top of the file.
from selenium import webdriver
import tldextract

The command prompt issues an error:
ModuleNotFoundError: No module named 'selenium'.

Where else should I include the names of the modules?

**Comment by Otto-AA** [comment]
You need to install the module on your computer first: `pip install selenium` or `pip3 install selenium` or `sudo pip install selenium`

**Comment by nicolae-stroncea** [comment]
Thanks, this solved it.
