### ISSUE TITLE
Unable to make front-end changes

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#216]
I tried to make changes to file App.vue.

Example:
b-nav-item(to="/")
        icon(name="home")
        | HomeTest

However, upon building the makefile, frontend was still the same. What am I missing?

**Comment by Otto-AA** [comment]
You can try to test it directly in the aw-webui directory. This worked for me
See https://github.com/ActivityWatch/aw-webui/#build-setup

But I don't know why it shouldn't work like you did -_-

**Comment by nicolae-stroncea** [comment]
That works, thanks. If I want to pull them to the actual production environment, how do I do that? I tried `npm run build`
but that didn't apply the changes I worked on in the testing environment

**Comment by nicolae-stroncea** [comment]
Tried it. No changes to front end when in build, though the changes are present in dev

**Comment by Otto-AA** [comment]
Ok, then I can't help you any further with this problem.

Do you know how to do this, @johan-bjareholt ?

**Comment by johan-bjareholt** [comment]
"make build" will create the files for aw-server to serve, but it does not copy them to the folder where aw-server looks for its files to serve. Copy the contents from aw-webui/dist to aw-server/aw_server/static and it should work! (The makefile in aw-server does this I believe if you don't want to do this manually, don't remember the name of the make target though and I'm not at the computer right now).

**Comment by nicolae-stroncea** [comment]
Thanks, it works now.
