### ISSUE TITLE
Hovering over the bars showing the periodusage displays the wrong date

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#218]
Often, two bars next to each other will show me the exact same date(bug happens with a large part of the bars). I suspect this is something to do with activitywatch logging events continously over midnight when the date switches. Any time that happens, it also skips a date, in this case 2018-07-27.

![issue1](https://user-images.githubusercontent.com/39338488/43882124-392973ec-9bb7-11e8-9f86-31f033bff0a4.png)
![issue2](https://user-images.githubusercontent.com/39338488/43882125-3a7199f0-9bb7-11e8-8984-b8df900234c8.png)
![issue3](https://user-images.githubusercontent.com/39338488/43882233-a6a41c2e-9bb7-11e8-8e17-cefad618c944.png)
![issue4](https://user-images.githubusercontent.com/39338488/43882235-a7fef62a-9bb7-11e8-8be6-8bf884cff78b.png)

**Comment by ErikBjare** [comment]
Fix merged, will be available in next release.
