### ISSUE TITLE
Merge several subrepos into bundle repo (monorepoify)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#227]
Right now I'm really bothered by the overhead of managing submodules, CI, and releases. Things would be a lot simpler if a lot of things were brought into one repo.

Then I read this: https://danluu.com/monorepo/

Has been discussed a little before in: https://github.com/ActivityWatch/activitywatch/issues/70

Things that would improve:

 - Most issues would go in the standard activitywatch repo (easier overview, less cross-referencing)
 - Open PRs would become easier to overview and cross-repo changes could be put in a single PR instead of spread across repos
 - CI would be easier to maintain and run full integration tests on all projects for every commit
 - Easier to install

Things that would worsen:

 - CI build times
 - The contributor stats stuff would have to be rewritten

Repos I'd merge in:

 - aw-core
 - aw-server
 - aw-webui
 - aw-client
 - aw-client-js
 - aw-watcher-afk
 - aw-watcher-window
 - aw-watcher-web

Things we'd have to do:

 - For each repo to be merged:
    - In original repo, check out a new branch, move all files into subfolder with same name as repo, commit.
    - In destination repo, `git merge` the original repo's pre-merge branch.
 - Move all issues and open PRs

**Comment by ErikBjare** [comment]
@staltz Any comments or opinions?

**Comment by johan-bjareholt** [comment]
I don't like monorepos, but if we want fewer repos this would be my suggestion of merging more stuff into aw_server like this:

- aw_server
    - aw_server
    - aw_webui
    - aw_datastore
    - aw_transform

I like when the clients are in seperate repos, makes more sense for third-party watchers also.

**Comment by staltz** [comment]
Hi! Thanks for asking for my comment. I think as long as the architecture remains modular (not monolithic), then I think it's fine to make a monorepo. You can use [this git trick](https://stackoverflow.com/questions/277029/combining-multiple-git-repositories) to merge in the commits from all repos.

**Comment by ErikBjare** [comment]
@staltz Woah, that's an extremely useful link, thanks!

@johan-bjareholt That sounds sensible. Would fix most of the overhead I'm bothered by.

**Comment by ErikBjare** [comment]
These plans have been put on hold, we're not doing this anytime soon. Closing.
