### ISSUE TITLE
Basic data analysis

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#23]
After discussion with @exoji2e and @johan-bjareholt we concluded that some basic data analysis would be necessary for the project to have any non-minor appeal.

Basic analysis includes:
- [x] Historical overview of non-afk tim
- [x] Time spent per application/website (after filtering using afkwatcher data)

**Comment by johan-bjareholt** [comment]
Where will the analysis be made? On the server, or the client or somewhere else?

**Comment by johan-bjareholt** [comment]
This works for aw-watcher-window and aw-watcher-afk in both a timeline and summary view. I'd guess that we probably want a better looking version for the 1.0 release though, so should we close this and create a new issue for the new design?

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah sure, I have a PR here that changes the design of the webui (removes the sidemenu, makes everything black-on-white): https://github.com/ActivityWatch/aw-webui/pull/10

It will be easier to design a nice visualization when you don't have to deal with the dark colorscheme on the sidemenu.

**Comment by ErikBjare** [comment]
I'm closing this, since a minimum viable solution is in place in this PR: https://github.com/ActivityWatch/aw-webui/pull/13
