### ISSUE TITLE
When querying with a start parameter do not use default limit

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#232]
A sort of unexpected behavior when using aw-client, you want to query all events within a timeperiod, so you set the `start` (and maybe the `end`) parameter. But you don't get all the events you expected, because the default `limit` is 100. This is bad API ergonomics, and should be fixed.

Fix should be applied here: https://github.com/ActivityWatch/aw-client/blob/0cf3de54dd60ded57832b0e6a88649f6bf8f67fd/aw_client/client.py#L117-L129

Something similar might apply for aw-client-js, and aw-server itself (is there a default limit if none is given?).

**Comment by JustinDDavis** [comment]
After looking through the code, this issue still appears to be valid. If it hasn't been assigned to anyone else, can I try to remediate?

**Comment by johan-bjareholt** [comment]
Please do! :)

**Comment by xylix** [comment]
This should probably be closed now that the fix has been merged in the subprojects?

**Comment by ErikBjare** [comment]
@xylix Ah yes, thanks!
