### ISSUE TITLE
Use Python's ast module to parse query2

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#234]
Since query2 is a subset of Python, we should probably switch to the `ast` module in Python to make parsing easier. It would also make it easier to extend the capabilities of the query language.

Example:

```py
import ast
a = ast.parse("a = query_bucket('test'); return events")
print(a.body)   # [<_ast.Assign object at 0x7ff1c807c828>, <_ast.Return object at 0x7ff1c807c940>]

# Inspect Assign object
print(a.body[0].targets[0])  # <_ast.Name object at 0x7ff1c807c860>
print(a.body[0].targets[0].id)  # "a"
print(a.body[0].value)  # <_ast.Call object at 0x7ff1c807c898>
print(a.body[0].value.func.id)  # "query_bucket"
print(a.body[0].value.args)  # [<_ast.Str object at 0x7ff1c807c908>]

# Inspect Return object
print(a.body[1].value)  # <_ast.Name object at 0x7ff1c807c978>
print(a.body[1].value.id)  #  "events"
```

Benefits:

 - Better parsing (and error handling)
 - Easier to extend query2 specification
    - Add support for comments, kwargs, lambdas
 - Turn query2 into a proper subset of Python

**Comment by johan-bjareholt** [comment]
Wow, had no idea that this existed.

Due to this I also assumed that there would be some kind of lexer in python aswell and apparently it does!

https://docs.python.org/3/library/shlex.html

Would make it trivial to add for example support for comments in queries.

**Comment by ErikBjare** [comment]
With the query language now also having an implementation in aw-server-rust and it no longer being a strict subset of Python this probably won't happen. Closing.
