### ISSUE TITLE
Build won't work on Windows 10

### ISSUE THREAD

**Issue by aftabnaveed** [ActivityWatch/activitywatch#237]
I am able to run make on windows 10, however, I am unable to run `make install` and instead got this error: 
```
make[1]: Entering directory `C:/Users/Naveed/Projects/activitywatch/aw-qt'
bash scripts/config-autostart.sh
Platform not supported in script, exiting
make[1]: Leaving directory `C:/Users/Naveed/Projects/activitywatch/aw-qt'

(activitywatch) C:\Users\Naveed\Projects\\activitywatch>
```

**Comment by ErikBjare** [comment]
That's fine, it's not an error. `make install` isn't needed to use ActivityWatch, everything is installed in the `make build` step.

**Comment by aftabnaveed** [comment]
@johan-bjareholt Can you please point me in the right direction for running it on windows? I tried running the aw-server  using `python __main__.py` but I get this error

```
C:\Users\Naveed\Projects\activitywatch\aw-server>python __main__.py
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
    import aw_server
  File "C:\Users\Naveed\Projects\activitywatch\aw-server\aw_server\__init__.py", line 8, in <module>
    from .server import app
  File "C:\Users\Naveed\Projects\activitywatch\aw-server\aw_server\server.py", line 8, in <module>
    from aw_datastore import Datastore
ModuleNotFoundError: No module named 'aw_datastore'
```
Which is understandable because aw_datastore exists under aw_core.  Which script should be executing get the server started?

Thank you
