### ISSUE TITLE
Not using production WSGI server

### ISSUE THREAD

**Issue by MatthewScholefield** [ActivityWatch/activitywatch#240]
Any reason not to using something like `gunicorn` instead of the default `flask.serve`? At the very least, it will get rid of the warning message that always comes up in the logs:
```
 * Serving Flask app "aw-server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
```

**Comment by johan-bjareholt** [comment]
The only actual reason we have for serving it with flash.serve is that aw-server is not supposed to be served outside of the local machine, so performance and security is not really a priority. We might in the future, but as of now it doesn't really matter.

@ErikBjare What do you think, should we fix this or let it be for now?

**Comment by ErikBjare** [comment]
Using something like gunicorn is probably a good idea, but I'm really not sure if there'd be any noticeable difference. The only issue with the built-in WSGI server is that "it doesn't scale well" (according to docs), but scale isn't really an issue here (I think).

**Comment by thomas725** [comment]
Hey there. I've just "found" ActivityWatch yesterday and thought it be a great idea to try if for myself.
Installed it through AUR and got spooked a bit by the very prominent red **"WARNING: This is a development server. Do not use it in a production deployment."** followed by the suggestion "Use a production WSGI server instead.".

If I understand the above thread correctly, this functions "as designed" and a simple user does not need to concern himself with it. Maybe you could either mention that it's harmless in the https://docs.activitywatch.net/en/latest/getting-started.html guide or filter out the log message so it doesn't spook anyone?

Thank you :)

**Comment by mx1up** [comment]
exactly my thoughts @thomas725 

or even print a message on the console to ignore the warning above ;)
