### ISSUE TITLE
AFK watcher counting superhot.exe as afk time.

### ISSUE THREAD

**Issue by ewen-lbh** [ActivityWatch/activitywatch#244]
I tested in both fullscreen and windowed mode, and it seems like Superhot is registered as AFK time. Tho the .exe is detected in the activity board

System info:
Windows 10 Build 1803 64bits

**Comment by ErikBjare** [comment]
Funny thing, one of the reasons I started ActivityWatch was so that I could have proper logging for VR applications (not available at the time). 

Issue #2 would fix your problem, and [aw-watcher-openvr](https://github.com/ActivityWatch/aw-watcher-openvr) has been a (not quite working) thing.

**Comment by ewen-lbh** [comment]
Well I wasn't playing VR superhot, just regular pc game (VR is expensive!), But I'll look into that thanks! Going to try this with other Steam and non Steam games too

**Comment by ErikBjare** [comment]
Oh, that's weird. We're you using a game controller or just mouse & keyboard?

**Comment by ewen-lbh** [comment]
Nope, just mouse & keyboard. Thos the thing I might have done wrong is that, because they were multiple exe files, I launched the one with the app icon (aw-qt.exe), but maybe it's just a UI launcher, I don't know.

**Comment by ErikBjare** [comment]
Starting with the aw-qt executable is the recommended way. Python is bundled and therefore not necessary (but won't hurt).

It probably has to do with how Superhot handles input which isn't taken into account by the Windows API we use for AFK detection.

**Comment by ewen-lbh** [comment]
That's why I said I'll try with other games too. Going to give feedback asap about that.

**Comment by ewen-lbh** [comment]
Update: Tried with Overwatch and Titanfall2, both games are detected as expected (they don't count as AFK time)

**Comment by ErikBjare** [comment]
@ewen-lbh Thanks for checking! Seems like Superhot is a weird edge case.

**Comment by ErikBjare** [comment]
Since this is such an exotic and weird edge case I'm going to close this since we're unlikely to ever investigate further.
