### ISSUE TITLE
Using multiple clients but one server

### ISSUE THREAD

**Issue by MarcManhart** [ActivityWatch/activitywatch#249]
Great project (just wanted to say).
Im interested in collection data centralized on one server but from multiple clients (e.g. from my host which is also running the server and additional from my working VM which is running on the same host).

Is it possible to accomblish that?

**Comment by ErikBjare** [comment]
Yes, see the documentation here: https://activitywatch.readthedocs.io/en/latest/getting-started.html#config

You need to modify the aw-server config files to allow connections from the virtual machine (changing the host setting) and then make the aw-client config files use the right IP and port.

Note that setting the aw-server `host` setting to anything else than the default is a major security risk, as the API has no authentication at the moment.

**Comment by pascalwhoop** [comment]
@ErikBjare are there plans to add some SSL encryption? A shared secret ought to do it, or a full authentication library, if the work is worth the trouble. But I think most people track their own activity not their teams so I think a shared secret for personal use across systems would be sufficient.

I'm currently building a suite of systems running under my personal domain and I'd be happy to look into securing the communication with symmetric crypto.

**Comment by johan-bjareholt** [comment]
@pascalwhoop Yep, here's the issue https://github.com/ActivityWatch/activitywatch/issues/32

The past weeks when I've talked to @ErikBjare it seems like we pretty much have decided to go with OAuth and a shared secret in a local file for local authentication.
