### ISSUE TITLE
Unable to download from Firefox 63.0.3 and Chrome 70.0

### ISSUE THREAD

**Issue by luzb3l** [ActivityWatch/activitywatch#250]
Both browsers cancel the download automatically and mark it as dangerous.
Is there a way around this? Is this a known issue?

**Comment by ErikBjare** [comment]
Woah, we've never heard about this before. Which platform are you using/trying to download?

**Comment by luzb3l** [comment]
It's Windows 10 Enterprise 64bits.

This is Firefox 63.0.3

![2018-11-20 17_09_21-releases activitywatch_activitywatch](https://user-images.githubusercontent.com/36280942/48808780-a125a700-ece7-11e8-800a-a98a463383bd.jpg)

This is Chrome 70.0

![2018-11-20 17_10_33-releases activitywatch_activitywatch github](https://user-images.githubusercontent.com/36280942/48808803-b69ad100-ece7-11e8-8f70-39f69c9a2ae6.jpg)

I specified in Firefox to "Allow the Download", and when I scanned it with Windows Defender, it gave me this:

![2018-11-20 17_15_46-windows defender security center](https://user-images.githubusercontent.com/36280942/48808867-f95ca900-ece7-11e8-997d-78a1bfefa863.jpg)

Let me know if you need anything else to reproduce it.

**Comment by ErikBjare** [comment]
Related to #181 and #140. I don't really know what to do about it that would give a reliable result.

Does the same thing happen in v0.8.0b6?

v0.8.0b7 is broken on Windows (see #248) so not much use in using that anyway.

**Comment by HarveyWilliams** [comment]
Firefox complained at me for downloading b7 but seemed to download it anyway (as I found it in my downloads folder).

**Comment by greysondn** [comment]
Just going to add this snapshot here.

![image](https://user-images.githubusercontent.com/3652901/49242763-69da8880-f3c0-11e8-8f65-e4a188a6808e.png)

Have you considered submitting it to vendors as a potential false positive? Especially if you get a known working build it may be a good idea.

**Comment by ErikBjare** [comment]
@greysondn Yes, it's discussed in #181. We encourage users to do so themselves as we (maintainers) would rather spend time on further development and don't really have the time. If someone can let us know of a way to submit false positives automatically, that would of course be considered.

**Comment by ErikBjare** [comment]
Closing, further discussion should go in #181.
