### ISSUE TITLE
Dashboard, API browser & log folder all opened in Chromium

### ISSUE THREAD

**Issue by jancborchardt** [ActivityWatch/activitywatch#251]
Currently when you open the dashboard, the API browser or the log folder, no matter which default browser you set, they open in Chromium.

I have Firefox and Chromium installed, with Firefox set as primary browser. Other desktop apps like Nextcloud open links in Firefox, so I guess there’s some way to check that?

Also, the log folder would probably best be opened in the normal system file manager (Explorer, Finder, Nautilus etc.)?

**Comment by jancborchardt** [comment]
Here are some relevant lines (I think :) from the Nextcloud desktop client, maybe they are helpful:
- "Open Nextcloud in browser" entry in tray icon menu: https://github.com/nextcloud/desktop/blob/9f6bb617e9ae755adfd61ad323df71781a48b319/src/gui/owncloudgui.cpp#L375
- "Open Nextcloud in browser" button in first run wizard: https://github.com/nextcloud/desktop/blob/84b7ed04e6b95de6050f5d6757b0d4385b297abb/src/gui/wizard/owncloudwizardresultpage.cpp#L48

**Comment by ErikBjare** [comment]
Likely duplicate of #208

**Comment by ErikBjare** [comment]
This is indeed a likely duplicate of #208, closing.
