### ISSUE TITLE
Generated OpenAPI spec gives $schema errors in the Swagger Editor

### ISSUE THREAD

**Issue by OlivierMary** [ActivityWatch/activitywatch#252]
Hi,

Somes returns on `http://localhost:5600/api/swagger.json`

swagger.json isn't valid -> put it in `https://editor.swagger.io/` to see error:

![image](https://user-images.githubusercontent.com/4348675/48906267-36e64100-ee64-11e8-9800-01d8f0ef68f8.png)

Maybe set an abstract type for `event.data` or a type including all possibles fields?

in any case thanks for the swagger 👍

**Comment by johan-bjareholt** [comment]
I went ahead and tried to find the issue and found this schema for event

https://github.com/ActivityWatch/aw-server/blob/master/aw_server/rest.py#L57

Seems to be correct, so I also tested the swagger editor which you used. Apparently it for some reason adds this $schema property when converting from JSON to YAML, so it seems like this is simply an issue with the swagger editor actually. If you simply remove that added property it no longer complains.

**Comment by OlivierMary** [comment]
Hi,

It's not on convert json to yaml:
![image](https://user-images.githubusercontent.com/4348675/48908724-63518b80-ee6b-11e8-86ac-3595b805caaf.png)

**Comment by OlivierMary** [comment]
I think it's here : https://github.com/ActivityWatch/aw-core/blob/c33ea2e9ad56009fc46d44d731b6643eefe01ddf/aw_core/schemas/event.json
Only event is fetch like that.

**Comment by OlivierMary** [comment]
I see this TOTO https://github.com/ActivityWatch/aw-server/blob/master/aw_server/rest.py#L60

Care another json contains this $schema https://github.com/ActivityWatch/aw-core/search?q=http%3A%2F%2Fjson-schema.org%2Fdraft-04%2Fschema&unscoped_q=http%3A%2F%2Fjson-schema.org%2Fdraft-04%2Fschema

**Comment by johan-bjareholt** [comment]
Oh, you are correct, just got confused when it was reordered.

> I see this TOTO https://github.com/ActivityWatch/aw-server/blob/master/aw_server/rest.py#L60

That's not related to this issue, shouldn't impact.

> Care another json contains this $schema https://github.com/ActivityWatch/aw-core/search?q=http%3A%2F%2Fjson-schema.org%2Fdraft-04%2Fschema&unscoped_q=http%3A%2F%2Fjson-schema.org%2Fdraft-04%2Fschema

Good catch.

I still don't understand why Swagger editor is complaining though, it is a valid property as far as I understand.

https://json-schema.org/latest/json-schema-core.html#rfc.section.7

**Comment by OlivierMary** [comment]
It's valid for a json-schema, not valid for swagger generator: https://swagger.io/docs/specification/data-models/keywords/  #Unsupported Keywords

**Comment by johan-bjareholt** [comment]
@OlivierMary But in that case, why does it give an error about it and not just simply ignore it?
Doesn't seem like it should break anything.

**Comment by ErikBjare** [comment]
Still waiting for OpenAPI v3 support in flask-restplus
