### ISSUE TITLE
Activity view does not use correct timezones for start time.

### ISSUE THREAD

**Issue by steventrouble** [ActivityWatch/activitywatch#254]
Version: v0.8.0b6

Repro:
1) Visit http://localhost:5600/#/activity/my-comp/2018-11-26.

What happens:
If in PST, the first 8 hours of the day are ~missing~ duplicated.

Expected:
Shows all the events from that day

Request log shows the problem is in date formatting:
```
query: ["events = flood(query_bucket("aw-watcher-window_DESKTOP-OHN8LDN"));",…]
timeperiods: ["2018-11-26/2018-11-27T00:00:00-08:00"]
```

It is using the date in the URL as the start date, rather than a proper ISO date.

**Comment by steventrouble** [comment]
Should be fixed by https://github.com/ActivityWatch/aw-webui/pull/117

**Comment by ErikBjare** [comment]
Did you actually fix it? Your second commit looked correct to me

**Comment by steventrouble** [comment]
Aw, dang. I committed but didn't amend it correctly, so it'll probably be broken. I'll have the amended version out shortly.

It's been a while since I've used git, sorry about that.

**Comment by steventrouble** [comment]
Alright, fixed it proper: https://github.com/ActivityWatch/aw-webui/pull/118

Thanks for your patience!
