### ISSUE TITLE
How to import data from ActivityWatch into new ActivityWatch database?

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#263]
I am going to switch Distros(also switching DE from Gnome to KDE). What is the best way of preserving the data I've saved up until now? I haven't switched yet, so I could either
1. Use the import functionality and download the json files.
The issue: I looked through the documentation, and I didn't see any clues on how to export it back to the new database if I redownload activitywatch on the new distro.
2. Copy the database file, and just paste it into the same directory, once I redownload activitywatch on new distro.
The issue: no real issue. I'm just wondering if this will produce any unintended consequences?

Which one is the best option?

**Comment by ErikBjare** [comment]
For reference, the PR for adding the import API endpoint is here: https://github.com/ActivityWatch/aw-server/pull/41

Closing as the question has been answered.
