### ISSUE TITLE
Add way to merge buckets

### ISSUE THREAD

**Issue by akufta** [ActivityWatch/activitywatch#267]
**Is your feature request related to a problem? Please describe.**
When I was doing local development, I got another set of buckets and so it switched to those 2 for a day and I was trying to merge the export, but wasn't able to. 

**Describe the solution you'd like**
I think a GUI option when you click open bucket or something that lets you add events from another set might be useful!

**Comment by Otto-AA** [comment]
I am not familiar with this pull request but I guess https://github.com/ActivityWatch/aw-server/pull/41 should solve your issue.

> The import functionality is practically done, I just haven't thrown a UI on top of the API. Something we'll (finally) get done this year for sure.

\- https://github.com/ActivityWatch/activitywatch/issues/263#issuecomment-453181997

I think that's the current status of this feature

**Comment by ErikBjare** [comment]
This is slightly different from the import/export in progress but definitely something I want to look into. It's currently possible via the API (load the export, send the events to the bucket) but having something user-friendly that prevents mistakes (duplicate/overlapping events, wrong bucket, etc) would be nice.

**Comment by johan-bjareholt** [comment]
Related to this

https://github.com/ActivityWatch/activitywatch/issues/454
