### ISSUE TITLE
zsh: no such file or directory: ./aw-qt

### ISSUE THREAD

**Issue by Sathish-n** [ActivityWatch/activitywatch#269]
## Describe the bug
Cannot start the application in nix os.

## To Reproduce
1. Download the linux archive
2. unzip and enter the folder
3. run ./aw-qt

## Expected behavior
App running

## Documentation
If applicable, add screenshots or logfiles to help explain your problem.

Logfiles can be found in different places depending on platform:
 - Windows: `C:\Users\<USER>\AppData\Local\ActivityWatch\Logs`
 - macOS: /Users/<USER>/Library/Logs/activitywatch
 - Linux: /home/<USER>/.cache/SuperApp/log

## Environment

 - OS: nix-os

**Comment by ErikBjare** [comment]
Please provide terminal output of `pwd` and list directory contents for us (preferably with permissions, as given by `ls -l`).

**Comment by Sathish-n** [comment]
/home/nusspc/Apps/activitywatch

total 103660
-rwxr-xr-x 1 nusspc users   197367 Nov  3 18:16 array.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 aw_core
-rwxr-xr-x 1 nusspc users  1393784 Nov  3 18:16 aw-qt
-rwxr-xr-x 1 nusspc users      283 Nov  3 18:16 aw-qt.desktop
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 aw_server
-rwxr-xr-x 1 nusspc users  3165688 Nov  3 18:16 aw-server
-rwxr-xr-x 1 nusspc users  1993544 Nov  3 18:14 aw-watcher-afk
drwxr-xr-x 2 nusspc users     4096 Nov  3 18:14 aw_watcher_window
-rwxr-xr-x 1 nusspc users  1951224 Nov  3 18:14 aw-watcher-window
-rw-r--r-- 1 nusspc users   793840 Nov  3 18:16 base_library.zip
-rwxr-xr-x 1 nusspc users    80785 Nov  3 18:16 binascii.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    32782 Nov  3 18:16 _bisect.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 2 nusspc users     4096 Nov  3 18:16 bson
-rwxr-xr-x 1 nusspc users    62794 Nov  3 18:16 _bz2.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 2 nusspc users     4096 Nov  3 18:14 certifi
-rwxr-xr-x 1 nusspc users   179325 Nov  3 18:16 _codecs_cn.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   182600 Nov  3 18:16 _codecs_hk.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    92746 Nov  3 18:16 _codecs_iso2022.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   308416 Nov  3 18:16 _codecs_jp.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   165113 Nov  3 18:16 _codecs_kr.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   134474 Nov  3 18:16 _codecs_tw.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   635916 Nov  3 18:16 _ctypes.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   413419 Nov  3 18:16 _datetime.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users  1687965 Nov  3 18:16 _decimal.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    46587 Nov  3 18:16 fcntl.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 4 nusspc users     4096 Nov  3 18:16 flask_restplus
-rwxr-xr-x 1 nusspc users    33404 Nov  3 18:16 grp.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    74227 Nov  3 18:16 _hashlib.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    50145 Nov  3 18:16 _heapq.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 include
-rwxr-xr-x 1 nusspc users   170468 Nov  3 18:16 _json.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 jsonschema
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 lib
-rwxr-xr-x 1 nusspc users   138096 Nov  3 18:16 libatk-1.0.so.0
-rwxr-xr-x 1 nusspc users   173304 Nov  3 18:16 libatk-bridge-2.0.so.0
-rwxr-xr-x 1 nusspc users   178328 Nov  3 18:16 libatspi.so.0
-rwxr-xr-x 1 nusspc users    66632 Nov  3 18:16 libbz2.so.1.0
-rwxr-xr-x 1 nusspc users    34880 Nov  3 18:16 libcairo-gobject.so.2
-rwxr-xr-x 1 nusspc users  1086808 Nov  3 18:16 libcairo.so.2
-rwxr-xr-x 1 nusspc users  1934624 Nov  3 18:16 libcrypto.so.1.0.0
-rwxr-xr-x 1 nusspc users    26512 Nov  3 18:16 libdatrie.so.1
-rwxr-xr-x 1 nusspc users   281552 Nov  3 18:16 libdbus-1.so.3
-rwxr-xr-x 1 nusspc users   151824 Nov  3 18:16 libEGL.so.1
-rwxr-xr-x 1 nusspc users   170056 Nov  3 18:16 libexpat.so.1
-rwxr-xr-x 1 nusspc users    30952 Nov  3 18:16 libffi.so.6
-rwxr-xr-x 1 nusspc users   244712 Nov  3 18:16 libfontconfig.so.1
-rwxr-xr-x 1 nusspc users   666080 Nov  3 18:16 libfreetype.so.6
-rwxr-xr-x 1 nusspc users    31488 Nov  3 18:16 libgbm.so.1
-rwxr-xr-x 1 nusspc users    90160 Nov  3 18:16 libgcc_s.so.1
-rwxr-xr-x 1 nusspc users   680376 Nov  3 18:16 libgdk-3.so.0
-rwxr-xr-x 1 nusspc users   134496 Nov  3 18:16 libgdk_pixbuf-2.0.so.0
-rwxr-xr-x 1 nusspc users  1513096 Nov  3 18:16 libgio-2.0.so.0
-rwxr-xr-x 1 nusspc users   153824 Nov  3 18:16 libglapi.so.0
-rwxr-xr-x 1 nusspc users  1078368 Nov  3 18:16 libglib-2.0.so.0
-rwxr-xr-x 1 nusspc users    14592 Nov  3 18:16 libgmodule-2.0.so.0
-rwxr-xr-x 1 nusspc users   330904 Nov  3 18:16 libgobject-2.0.so.0
-rwxr-xr-x 1 nusspc users   157864 Nov  3 18:16 libgraphite2.so.3
-rwxr-xr-x 1 nusspc users     6112 Nov  3 18:16 libgthread-2.0.so.0
-rwxr-xr-x 1 nusspc users  5297920 Nov  3 18:16 libgtk-3.so.0
-rwxr-xr-x 1 nusspc users   347024 Nov  3 18:16 libharfbuzz.so.0
-rwxr-xr-x 1 nusspc users 25048256 Nov  3 18:16 libicudata.so.56
-rwxr-xr-x 1 nusspc users  3368288 Nov  3 18:16 libicui18n.so.56
-rwxr-xr-x 1 nusspc users  2069136 Nov  3 18:16 libicuuc.so.56
-rwxr-xr-x 1 nusspc users   137400 Nov  3 18:16 liblzma.so.5
-rwxr-xr-x 1 nusspc users   315672 Nov  3 18:16 libpango-1.0.so.0
-rwxr-xr-x 1 nusspc users    52528 Nov  3 18:16 libpangocairo-1.0.so.0
-rwxr-xr-x 1 nusspc users    86056 Nov  3 18:16 libpangoft2-1.0.so.0
-rwxr-xr-x 1 nusspc users   252032 Nov  3 18:16 libpcre.so.3
-rwxr-xr-x 1 nusspc users   686872 Nov  3 18:16 libpixman-1.so.0
-rwxr-xr-x 1 nusspc users   153936 Nov  3 18:16 libpng12.so.0
-rwxr-xr-x 1 nusspc users 12227849 Nov  3 18:16 libpython3.5m.so.1.0
-rwxr-xr-x 1 nusspc users  5552632 Nov  3 18:16 libQt5Core.so.5
-rwxr-xr-x 1 nusspc users   558520 Nov  3 18:16 libQt5DBus.so.5
-rwxr-xr-x 1 nusspc users  6165560 Nov  3 18:16 libQt5Gui.so.5
-rwxr-xr-x 1 nusspc users  1658584 Nov  3 18:16 libQt5Network.so.5
-rwxr-xr-x 1 nusspc users   349728 Nov  3 18:16 libQt5Svg.so.5
-rwxr-xr-x 1 nusspc users  6528632 Nov  3 18:16 libQt5Widgets.so.5
-rwxr-xr-x 1 nusspc users  1772200 Nov  3 18:16 libQt5XcbQpa.so.5
-rwxr-xr-x 1 nusspc users   282352 Nov  3 18:16 libreadline.so.6
-rwxr-xr-x 1 nusspc users   134296 Nov  3 18:16 libselinux.so.1
-rwxr-xr-x 1 nusspc users   754880 Nov  3 18:16 libsqlite3.so.0
-rwxr-xr-x 1 nusspc users   387272 Nov  3 18:16 libssl.so.1.0.0
-rwxr-xr-x 1 nusspc users   979056 Nov  3 18:16 libstdc++.so.6
-rwxr-xr-x 1 nusspc users    36936 Nov  3 18:16 libthai.so.0
-rwxr-xr-x 1 nusspc users   167096 Nov  3 18:16 libtinfo.so.5
-rwxr-xr-x 1 nusspc users    52400 Nov  3 18:16 libwayland-client.so.0
-rwxr-xr-x 1 nusspc users    31104 Nov  3 18:16 libwayland-cursor.so.0
-rwxr-xr-x 1 nusspc users    68936 Nov  3 18:16 libwayland-server.so.0
-rwxr-xr-x 1 nusspc users  1265072 Nov  3 18:16 libX11.so.6
-rwxr-xr-x 1 nusspc users     5992 Nov  3 18:16 libX11-xcb.so.1
-rwxr-xr-x 1 nusspc users    14456 Nov  3 18:16 libXau.so.6
-rwxr-xr-x 1 nusspc users    92240 Nov  3 18:16 libxcb-glx.so.0
-rwxr-xr-x 1 nusspc users    10320 Nov  3 18:16 libxcb-present.so.0
-rwxr-xr-x 1 nusspc users    34912 Nov  3 18:16 libxcb-render.so.0
-rwxr-xr-x 1 nusspc users    10336 Nov  3 18:16 libxcb-shm.so.0
-rwxr-xr-x 1 nusspc users    22624 Nov  3 18:16 libxcb-sync.so.1
-rwxr-xr-x 1 nusspc users    26704 Nov  3 18:16 libxcb-xfixes.so.0
-rwxr-xr-x 1 nusspc users    10232 Nov  3 18:16 libXcomposite.so.1
-rwxr-xr-x 1 nusspc users    39232 Nov  3 18:16 libXcursor.so.1
-rwxr-xr-x 1 nusspc users    10248 Nov  3 18:16 libXdamage.so.1
-rwxr-xr-x 1 nusspc users    22616 Nov  3 18:16 libXdmcp.so.6
-rwxr-xr-x 1 nusspc users    73288 Nov  3 18:16 libXext.so.6
-rwxr-xr-x 1 nusspc users    22584 Nov  3 18:16 libXfixes.so.3
-rwxr-xr-x 1 nusspc users    10376 Nov  3 18:16 libXinerama.so.1
-rwxr-xr-x 1 nusspc users    63880 Nov  3 18:16 libXi.so.6
-rwxr-xr-x 1 nusspc users   235864 Nov  3 18:16 libxkbcommon.so.0
-rwxr-xr-x 1 nusspc users    39192 Nov  3 18:16 libXrandr.so.2
-rwxr-xr-x 1 nusspc users    39352 Nov  3 18:16 libXrender.so.1
-rwxr-xr-x 1 nusspc users     6096 Nov  3 18:16 libxshmfence.so.1
-rwxr-xr-x 1 nusspc users    22720 Nov  3 18:16 libXxf86vm.so.1
-rwxr-xr-x 1 nusspc users   100728 Nov  3 18:16 libz.so.1
-rwxr-xr-x 1 nusspc users   116701 Nov  3 18:16 _lzma.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 2 nusspc users     4096 Nov  3 18:16 markupsafe
-rwxr-xr-x 1 nusspc users   212619 Nov  3 18:16 math.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    49443 Nov  3 18:16 _md5.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   157944 Nov  3 18:16 _multibytecodec.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    19494 Nov  3 18:16 _opcode.cpython-35m-x86_64-linux-gnu.so
-rw-r--r-- 1 nusspc users        0 Feb  3 10:35 output.txt
-rwxr-xr-x 1 nusspc users   446340 Nov  3 18:16 _pickle.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    84731 Nov  3 18:16 _posixsubprocess.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   941921 Nov  3 18:16 pyexpat.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 2 nusspc users     4096 Nov  3 18:16 pymongo
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:16 PyQt5
-rwxr-xr-x 1 nusspc users    37867 Nov  3 18:16 _random.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    94583 Nov  3 18:16 readline.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    38210 Nov  3 18:16 resource.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    80995 Nov  3 18:16 select.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    40219 Nov  3 18:16 _sha1.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    76425 Nov  3 18:16 _sha256.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    77947 Nov  3 18:16 _sha512.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   166940 Nov  3 18:16 sip.so
-rwxr-xr-x 1 nusspc users   368669 Nov  3 18:16 _socket.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   292857 Nov  3 18:16 _sqlite3.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   351829 Nov  3 18:16 _ssl.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:14 _struct
-rwxr-xr-x 1 nusspc users   158308 Nov  3 18:16 _struct.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users    46071 Nov  3 18:16 termios.cpython-35m-x86_64-linux-gnu.so
-rwxr-xr-x 1 nusspc users   941913 Nov  3 18:16 unicodedata.cpython-35m-x86_64-linux-gnu.so
drwxr-xr-x 3 nusspc users     4096 Nov  3 18:14 zlib
-rwxr-xr-x 1 nusspc users   113410 Nov  3 18:16 zlib.cpython-35m-x86_64-linux-gnu.so

**Comment by johan-bjareholt** [comment]
This isn't really an activitywatch issue as activitywatch isn't even started, it's zsh which is unable to start the appplication. The application is obviously there and has the correct permissions at least, so I have no idea what's going on. Does it work to start it with `/home/nusspc/Apps/activitywatch/aw-qt` directly?

**Comment by ix5231** [comment]
This is a limitation of NixOS.
You have to `patchelf` the binary.

```
for x in aw-{qt,server,watcher-afk,watcher-window}; do
    patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" $x;
done
```

I think this issue can be also solved by rebuilding but I have never tested it.

[Reference](https://unix.stackexchange.com/questions/91577/cannot-execute-binary-in-nixos-no-such-file-or-directory)

**Comment by ErikBjare** [comment]
Closing, the solution above hopefully solves the issue.
