### ISSUE TITLE
Switch from Appveyor to Travis for Windows

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#273]
Now that Travis supports Windows it'd be nice to switch over to it. Would significantly simplify our CI pipeline.

**Comment by ErikBjare** [comment]
Started working on it here: https://github.com/ActivityWatch/activitywatch/pull/274

**Comment by ErikBjare** [comment]
As Windows builds are super slow on Travis, we might want to maybe postpone this even if we get it working. What do you think @johan-bjareholt? Consistent CI configuration or fast CI build times?

**Comment by johan-bjareholt** [comment]
> As Windows builds are super slow on Travis, we might want to maybe postpone this even if we get it working. What do you think @johan-bjareholt? Consistent CI configuration or fast CI build times?

Oh, missed this comment.

I think we should just keep both for a while since they both work fine and remove appveyor if we start feeling that it becomes a maintenance burden.
