### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Rakleed** [ActivityWatch/activitywatch#275]
Please translate the interface into Russian and then help. I can help with the translation or make it completely myself (if there are not very many lines).

**Comment by ErikBjare** [comment]
We haven't set up internationalization in the web UI yet, but there is an issue for it: https://github.com/ActivityWatch/aw-webui/issues/2

I'll note that you could contribute with a Russian translation, for when we get to that stage :tada:

**Comment by Rakleed** [comment]
@ErikBjare and are you planning to translate the aw-qt.exe interface?

**Comment by ErikBjare** [comment]
@Rakleed The web UI is the priority. But if someone contributes translation support for aw-qt we'd be happy to merge them (shouldn't be that difficult).
