### ISSUE TITLE
not compatible with my os

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#276]
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/webpack/lib/webpack.js:7:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! aw-webui@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aw-webui@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aw-webui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aw-webui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aw-webui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shri13/activitywatch/aw-server/aw-webui/npm-debug.log
Makefile:6: recipe for target 'build' failed
make[2]: *** [build] Error 1
make[2]: Leaving directory '/home/shri13/activitywatch/aw-server/aw-webui'
Makefile:10: recipe for target 'aw_webui' failed
make[1]: *** [aw_webui] Error 2
make[1]: Leaving directory '/home/shri13/activitywatch/aw-server'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by johan-bjareholt** [comment]
Your NPM version is below version 5 so we cannot support your OS.
Install NPM from another source than your distribution or change distribution to one which has a newer node version.
Requirements for installing ActivityWatch can be found here https://activitywatch.readthedocs.io/en/latest/installing-from-source.html#checking-dependencies
