### ISSUE TITLE
aw-webui is not in the npm registry

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#277]
shri13@ubuntu:~/activitywatch/aw-server/aw-webui$ npm owner aw-webui
npm ERR! Usage: 
npm ERR! npm owner add <user> [<@scope>/]<pkg>
npm ERR! npm owner rm <user> [<@scope>/]<pkg>
npm ERR! npm owner ls [<@scope>/]<pkg>
shri13@ubuntu:~/activitywatch/aw-server/aw-webui$ npm owner ls aw-webui
npm ERR! owner ls Couldn't get owner data aw-webui
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "owner" "ls" "aw-webui"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : aw-webui
npm ERR! 404 
npm ERR! 404  'aw-webui' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shri13/activitywatch/aw-server/aw-webui/npm-debug.log

**Comment by johan-bjareholt** [comment]
It's not supposed to be either since it's an webapp rather than a library or standalone application.
It's supposed to be bundled with aw-server and without aw-server it serves no purpose.
