### ISSUE TITLE
python setup.py egg_info failed

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#279]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ppewnvp_/python-xlib/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Makefile:10: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/shri13/activitywatch/aw-watcher-afk'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by johan-bjareholt** [comment]
Full log is not supplied, we need more info to be able to help you

**Comment by shri120kant** [comment]
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make[1]: Leaving directory '/home/shri13/activitywatch/aw-client'
make --directory=aw-server build DEV=true
make[1]: Entering directory '/home/shri13/activitywatch/aw-server'
make --directory=aw-webui build DEV=true
make[2]: Entering directory '/home/shri13/activitywatch/aw-server/aw-webui'
(cd aw-client-js; make build)
make[3]: Entering directory '/home/shri13/activitywatch/aw-server/aw-webui/aw-client-js'
npm install

> aw-client@0.1.0 prepare /home/shri13/activitywatch/aw-server/aw-webui/aw-client-js
> npm run compile


> aw-client@0.1.0 compile /home/shri13/activitywatch/aw-server/aw-webui/aw-client-js
> tsc

audited 89 packages in 10.903s
found 0 vulnerabilities

npm run compile

> aw-client@0.1.0 compile /home/shri13/activitywatch/aw-server/aw-webui/aw-client-js
> tsc

make[3]: Leaving directory '/home/shri13/activitywatch/aw-server/aw-webui/aw-client-js'
npm install
npm WARN eslint-plugin-vue@4.7.1 requires a peer of eslint@^3.18.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 1116 packages and audited 10832 packages in 61.026s
found 324 vulnerabilities (2 low, 322 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
(cd node_modules/vis; npm install; npm run build; true)

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> sinon@4.5.0 postinstall /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/sinon
> node scripts/support-sinon.js

Have some ❤️ for Sinon? You can support the project via Open Collective:
 > https://opencollective.com/sinon/donate


> vis@4.21.0-SNAPSHOT postinstall /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis
> opencollective postinstall

                                .,;riS522225isr:,.           
                             .;sS2XXXXXXXXXXXXX22Sr;.        
                           :s2XXXXXXXXXXXXXXXXXXXXXi,        
                         :i2XXXXXXX2Sirrrrrri52X2s:          
                       .r2XXXXXX2s;,.        .,;:      .:,   
                      .sXXXXXX2r,                    .:;;;:  
                      rXXXXXXS:                     ,;;;;;;, 
                     :2XXXXX5,                      .;;;;;;;.
                     iXXXXXX;                        ,;;;;;;:
                     2XXXXX2,                        .;;;;;;;
                     2XXXXX2,                        .;;;;;;;
                     iXXXXXX;                        ,;;;;;;:
                     :2XXXXX5,                      .;;;;;;;.
                      rXXXXXX5:                     ,;;;;;;, 
                      .sXXXXXX2r,                    .:;;;,  
                        r2XXXXXX2s;,.        .,;:      .:,   
                         ,s2XXXXXXX2Ssrr;;rriS2X2s:          
                           :s2XXXXXXXXXXXXXXXXXXXXXi,        
                             .;sS2XXXXXXXXXXXXXX2Ss;.        
                                .,;riS222222Sir;,.           
                                         

                            Thanks for installing vis 
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 135
                               Number of backers: 9
                              Annual budget: US$ 730
                             Current balance: US$ 730

               Donate: https://opencollective.com/vis/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1116 packages from 1117 contributors and audited 9561 packages in 58.769s
found 18 vulnerabilities (2 low, 10 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> vis@4.21.0-SNAPSHOT build /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis
> gulp

[13:33:00] Using gulpfile ~/activitywatch/aw-server/aw-webui/node_modules/vis/gulpfile.js
[13:33:00] Starting 'clean'...
[13:33:00] Starting 'bundle-js'...
[13:33:00] Starting 'bundle-js-individual'...
[13:33:00] Starting 'bundle-css'...
[13:33:00] Starting 'bundle-css-individual'...
[13:33:01] Finished 'clean' after 384 ms
[13:33:01] Starting 'copy'...
[13:33:10] Error: vis-timeline-graph2d.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-timeline-graph2d.min.js:216,54]
[13:33:10] Error: vis-graph3d.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-graph3d.min.js:216,54]
[13:33:11] Finished 'bundle-css-individual' after 11 s
[13:33:11] Error: vis-network.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-network.min.js:216,54]
[13:33:11] Finished 'bundle-js-individual' after 11 s
[13:33:13] Finished 'bundle-js' after 13 s
[13:33:13] Starting 'minify'...
[13:33:13] 'minify' errored after 73 ms
[13:33:13] SyntaxError: Unexpected token operator «=», expected punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/gulp/bin/gulp.js:165:18)
    at Gulp.<anonymous> (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:264:8)
    at /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:275:23
    at finish (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:273:3)
[13:33:13] Finished 'bundle-css' after 13 s
[13:33:13] Finished 'copy' after 13 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vis@4.21.0-SNAPSHOT build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vis@4.21.0-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shri13/.npm/_logs/2019-02-23T21_33_13_844Z-debug.log
npm run build

> aw-webui@1.0.0 build /home/shri13/activitywatch/aw-server/aw-webui
> node build/build.js

  Tip:
  Built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

Hash: a152d12685381ba78848
Version: webpack 4.10.2
Time: 82747ms
Built at: 2019-02-23 13:34:47
                                            Asset       Size  Chunks                    Chunk Names
 static/fonts/varela-round-latin-400.4ae78b6.woff   24.3 KiB          [emitted]         
static/fonts/varela-round-latin-400.f74b65e.woff2   19.6 KiB          [emitted]         
                                            0.css    206 KiB       0  [emitted]         vendor
              static/js/0.cc2f6102790eb34dcfa5.js    1.2 MiB       0  [emitted]  [big]  vendor
            static/js/app.d30eb96452880a926618.js     92 KiB       1  [emitted]         app
                                        0.css.map    263 KiB       0  [emitted]         vendor
          static/js/0.cc2f6102790eb34dcfa5.js.map   5.03 MiB       0  [emitted]         vendor
        static/js/app.d30eb96452880a926618.js.map    284 KiB       1  [emitted]         app
                                       index.html  566 bytes          [emitted]         
Entrypoint app [big] = 0.css static/js/0.cc2f6102790eb34dcfa5.js 0.css.map static/js/0.cc2f6102790eb34dcfa5.js.map static/js/app.d30eb96452880a926618.js static/js/app.d30eb96452880a926618.js.map

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  static/js/0.cc2f6102790eb34dcfa5.js (1.2 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.49 MiB)
      0.css
      static/js/0.cc2f6102790eb34dcfa5.js
      static/js/app.d30eb96452880a926618.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
make[2]: Leaving directory '/home/shri13/activitywatch/aw-server/aw-webui'
mkdir -p aw_server/static/
cp -r aw-webui/dist/* aw_server/static/
pip3 install --editable . -r requirements.txt --upgrade
Obtaining file:///home/shri13/activitywatch/aw-server
Collecting aw-core from git+https://github.com/ActivityWatch/aw-core.git@master#egg=aw-core (from -r requirements.txt (line 1))
  Cloning https://github.com/ActivityWatch/aw-core.git (to master) to /tmp/pip-build-0osjv3np/aw-core
Requirement already up-to-date: flask>=0.10 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: flask-restplus>=0.9.2 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: flask-cors>=2.1 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: pymongo>=3.2 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: appdirs>=1.4.0 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: python-json-logger>=0.1.5 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: mypy>=0.511 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: jsonschema in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: peewee==3.* in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: strict-rfc3339 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: iso8601 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: takethetime>=0.3.0 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: Jinja2>=2.10 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask>=0.10->-r requirements.txt (line 3))
Requirement already up-to-date: click>=5.1 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask>=0.10->-r requirements.txt (line 3))
Requirement already up-to-date: itsdangerous>=0.24 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask>=0.10->-r requirements.txt (line 3))
Requirement already up-to-date: Werkzeug>=0.14 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask>=0.10->-r requirements.txt (line 3))
Requirement already up-to-date: aniso8601>=0.82 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask-restplus>=0.9.2->-r requirements.txt (line 4))
Requirement already up-to-date: pytz in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask-restplus>=0.9.2->-r requirements.txt (line 4))
Requirement already up-to-date: six>=1.3.0 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from flask-restplus>=0.9.2->-r requirements.txt (line 4))
Requirement already up-to-date: typed-ast<1.4.0,>=1.3.1 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from mypy>=0.511->-r requirements.txt (line 9))
Requirement already up-to-date: mypy-extensions<0.5.0,>=0.4.0 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from mypy>=0.511->-r requirements.txt (line 9))
Requirement already up-to-date: typing in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from takethetime>=0.3.0->aw-core->-r requirements.txt (line 1))
Requirement already up-to-date: MarkupSafe>=0.23 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from Jinja2>=2.10->flask>=0.10->-r requirements.txt (line 3))
Installing collected packages: aw-core, aw-server
  Found existing installation: aw-core 0.4.1
    Uninstalling aw-core-0.4.1:
      Successfully uninstalled aw-core-0.4.1
  Running setup.py install for aw-core ... done
  Running setup.py develop for aw-server
Successfully installed aw-core-0.4.1 aw-server-0.8.dev0+c6433ea
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make[1]: Leaving directory '/home/shri13/activitywatch/aw-server'
make --directory=aw-watcher-afk build DEV=true
make[1]: Entering directory '/home/shri13/activitywatch/aw-watcher-afk'
pip3 install --editable . -r requirements.txt --upgrade
Ignoring pyobjc-framework-Quartz: markers "sys_platform == 'darwin'" don't match your environment
Obtaining file:///home/shri13/activitywatch/aw-watcher-afk
Collecting aw-core from git+https://github.com/ActivityWatch/aw-core.git@master#egg=aw-core (from -r requirements.txt (line 1))
  Cloning https://github.com/ActivityWatch/aw-core.git (to master) to /tmp/pip-build-j27z93m8/aw-core
Collecting aw-client from git+https://github.com/ActivityWatch/aw-client.git@master#egg=aw-client (from -r requirements.txt (line 2))
  Cloning https://github.com/ActivityWatch/aw-client.git (to master) to /tmp/pip-build-j27z93m8/aw-client
Collecting python-xlib from git+https://github.com/python-xlib/python-xlib.git@master#egg=python-xlib (from -r requirements.txt (line 5))
  Cloning https://github.com/python-xlib/python-xlib.git (to master) to /tmp/pip-build-j27z93m8/python-xlib
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j27z93m8/python-xlib/setup.py", line 9, in <module>
        assert setuptools_version in setuptools_require, '{} is required'.format(setuptools_require)
    AssertionError: setuptools>=30.3.0 is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j27z93m8/python-xlib/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Makefile:10: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/shri13/activitywatch/aw-watcher-afk'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by johan-bjareholt** [comment]
AssertionError: setuptools>=30.3.0 is required
