### ISSUE TITLE
python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#281]
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-j27z93m8/python-xlib/setup.py", line 9, in
assert setuptools_version in setuptools_require, '{} is required'.format(setuptools_require)
AssertionError: setuptools>=30.3.0 is required

----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j27z93m8/python-xlib/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Makefile:10: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/shri13/activitywatch/aw-watcher-afk'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by johan-bjareholt** [comment]
Uprade pip
