### ISSUE TITLE
issue while making package

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#282]
error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for aw-server
  Running setup.py clean for aw-server
Failed to build aw-server
Installing collected packages: peewee, aw-core, aw-server
  Found existing installation: peewee 2.10.2
    Uninstalling peewee-2.10.2:
      Successfully uninstalled peewee-2.10.2
  Found existing installation: aw-core 0.4.1
    Uninstalling aw-core-0.4.1:
      Successfully uninstalled aw-core-0.4.1
  Running setup.py install for aw-core ... done
  Running setup.py install for aw-server ... done
Successfully installed aw-core-0.4.1 aw-server-0.8.dev0+564d1dc peewee-3.8.2
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make[2]: Leaving directory '/home/shri13/activitywatch/aw-server'
pyinstaller aw-server.spec --clean --noconfirm
212 INFO: PyInstaller: 3.4
212 INFO: Python: 3.5.2
213 INFO: Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
232 INFO: UPX is not available.
234 INFO: Removing temporary files and cleaning cache in /home/shri13/.cache/pyinstaller
Traceback (most recent call last):
  File "/home/shri13/.local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/shri13/.local/lib/python3.5/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/shri13/.local/lib/python3.5/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/shri13/.local/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/shri13/.local/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 9, in <module>
ImportError: No module named 'flask_restplus'
Makefile:28: recipe for target 'package' failed
make[1]: *** [package] Error 1
make[1]: Leaving directory '/home/shri13/activitywatch/aw-server'
Makefile:129: recipe for target 'package' failed
make: *** [package] Error 2

**Comment by johan-bjareholt** [comment]
Upgrade pip

**Comment by kw-pr** [comment]
I had the same problem on Ubuntu 18.04 LTS
Not sure what pip version is required... but Ubuntu comes with `pip 9.0.1`

I fixed it with:

```
pip install wheel
```
