### ISSUE TITLE
error in aw-qt

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#283]
make[1]: Entering directory '/home/shri13/activitywatch/aw-qt'
pip3 install mypy
Requirement already satisfied: mypy in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (0.670)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.0 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from mypy) (0.4.1)
Requirement already satisfied: typed-ast<1.4.0,>=1.3.1 in /home/shri13/activitywatch/venv/lib/python3.5/site-packages (from mypy) (1.3.1)
pip3 install --editable . --upgrade --process-dependency-links

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --process-dependency-links
Makefile:10: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/shri13/activitywatch/aw-qt'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by johan-bjareholt** [comment]
There's a fix for this on the master version of aw-qt, checkout the master branch and it should work.

**Comment by shri120kant** [comment]
Can you please send me the link

**Comment by shri120kant** [comment]
Because I'm trying to build it on Linux and it is showing me the same
errors again and again even after copying the master
