### ISSUE TITLE
aw-qt,aw-window-watcher

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#284]
Successfully installed aw-client-0.3 aw-core-0.4.1 aw-watcher-window
make[1]: Leaving directory '/home/shri13/activitywatch/aw-watcher-window'
make --directory=aw-qt build DEV=true
make[1]: Entering directory '/home/shri13/activitywatch/aw-qt'
pip3 install mypy
Requirement already satisfied: mypy in /home/shri13/venv/lib/python3.5/site-packages (0.670)
Requirement already satisfied: typed-ast<1.4.0,>=1.3.1 in /home/shri13/venv/lib/python3.5/site-packages (from mypy) (1.3.1)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.0 in /home/shri13/venv/lib/python3.5/site-packages (from mypy) (0.4.1)
pip3 install . --upgrade --editable

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

--editable option requires 1 argument
Makefile:10: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/shri13/activitywatch/aw-qt'
Makefile:32: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by ErikBjare** [comment]
Stop spamming us with issues that can easily be solved by upgrading your system (this is your 10th issue in the past hour or something...). I've blocked you for 30 days.
