### ISSUE TITLE
Monitoring stops after computer sleeps and wakes the next day

### ISSUE THREAD

**Issue by rosareven** [ActivityWatch/activitywatch#285]
## Describe the bug
After waking up computer from sleep mode on a new day, ActivityWatch stopped gathering data even though it's still running. I played a game for an hour after waking up PC from sleep, and nothing has been shown on the dashboard.

## To Reproduce
1. Run ActivityWatch
2. Put PC to sleep mode
3. Wait till next day (have not tested if it stops capturing after every sleep, or if it sleeps till next day)
4. Wake PC up and do stuff for an hour
5. Open AW dashboard, nothing is captured

I paused and unpaused by re-ticking aw-qt window, still won't start capturing again.

## Expected behavior
AW dashboard should continue to show data of my usage after PC wakes up.

## Environment
 - ActivityWatch version: v0.8.0b6
 - OS: Win10

**Comment by johan-bjareholt** [comment]
Can you take a look at what are the most recent events in the aw-watcher-afk and aw-watcher-window buckets in the "Raw Data" section? Data in those two buckets are what is needed for the web ui to make a report.

I'd assume that either aw-watcher-afk or aw-watcher-window has malfunctioned somehow, when you say "re-ticking aw-qt window" do you mean restarting aw-qt completely or restarting some module?

**Comment by ErikBjare** [comment]
Closing due to no reply from @rosareven.
