### ISSUE TITLE
Unable to run on macOS 10.12

### ISSUE THREAD

**Issue by anjagusev** [ActivityWatch/activitywatch#286]
**For us to be able to understand the issue you're having you need to follow this template.** Please make sure there isn't already an issue for the bug you've found, otherwise it'll just take more resources, which means less time for us to actually fix bugs. Thanks for reporting!

## Describe the bug
When following installation instructions, I get an error which prevents me from installing activitywatch. 

## To Reproduce
1. [Download macOS zip](https://github.com/ActivityWatch/activitywatch/releases/download/v0.8.0b8/activitywatch-v0.8.0b8-macos-x86_64.zip). 
2. Move it to /Applications folder and unzip it. 
3. Navigate to folder in terminal and run `./aw-qt`

> [72837] Error loading Python lib '/Applications/activitywatch/Python': dlopen: dlopen(/Applications/activitywatch/Python, 10): Symbol not found: _futimens
>   Referenced from: /Applications/activitywatch/Python (which was built for Mac OS X 10.13)
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Applications/activitywatch/Python!

[Screen Shot 2019-03-17 at 13 22 58](https://user-images.githubusercontent.com/3604461/54495161-d28a3a00-48b7-11e9-804e-4ed614add3b3.png)

## Expected behavior
I expected to see the icon appear in the system tray. 

## Documentation
See screenshot above. I followed these installation instructions: https://activitywatch.readthedocs.io/en/latest/getting-started.html

## Environment
 - ActivityWatch version: v0.8.0b8
 - OS: macOS v10.12.6

## Additional context
I hope this is the right place to post this error. Forgive me if it's not or if I am following the installation instructions incorrectly

**Comment by ErikBjare** [comment]
We haven't seen this before, but it's probably related to us now building on macOS 10.13 since v0.8.0b7 (as the error seems to suggest).

An easy fix would be to upgrade to macOS 10.13, but if you're not able then try the older v0.8.0b7 and let us know if that works.

**Comment by anjagusev** [comment]
That worked like a charm. Thank you @ErikBjare!

**Comment by ErikBjare** [comment]
Great to hear! 

Closing since I think it's reasonable for us to not support macOS 10.12, as the extended support officially ends in September 2019, at which point it will be three years old.
