### ISSUE TITLE
Disable startup notification

### ISSUE THREAD

**Issue by pcuci** [ActivityWatch/activitywatch#287]
Would be great to tweak off the startup notification in Windows 10 that says that `aw.exe` is starting 

I get annoyed every time it pops up, I know it's starting - it was me who set it up :-)

The launch bar icon is sufficiently informing that I'm self-monitoring.

![image](https://user-images.githubusercontent.com/2169849/54796558-0b633f80-4c27-11e9-9661-f6cb7d457a4b.png)

**Comment by johan-bjareholt** [comment]
Good point, this notification is kind of odd in terms of UX IMO.

@ErikBjare Do you have any opinion on this?

**Comment by ErikBjare** [comment]
@johan-bjareholt Not really, I'm fine with removing it altogether.

**Comment by DrFelder** [comment]
I think a good solution would be to display a "currently starting up" message inside the dashboard itself.
Even if the server is not started yet, it would be possible to use some sort of hardcoded splash screen.

**Comment by johan-bjareholt** [comment]
Forgot about this issue until now, made a PR here

https://github.com/ActivityWatch/aw-qt/pull/45

@DrFelder The aw-server really shouldn't take more than a few seconds to start up, I don't think that it would be necessary to add that to the dashboard.

**Comment by ErikBjare** [comment]
The PR was merged in January and will be in the next release. Closing.
