### ISSUE TITLE
Poll user satisfaction and suggest user engagement/donations after some usage

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#291]
We should display a dialog or some other cue when we detect a user has been running ActivityWatch for over a week/month, something of the sort:

> You've used ActivityWatch for over a week/month. How do you like it so far?
>  (Show 1-5 rating scale)

If rated >3:

>We're really happy to hear you are enjoying ActivityWatch, but we think we can do even better! To help us help you, here are a few things you can do:
>
> - Support us on Patreon or OpenCollective
>    - If you're using ActivityWatch in the workplace, consider asking your employer to support us!
> - Tell your friends and coworkers! Post about it on social media
> - Sign up for the newsletter
> - Vote for new features on the forum
> - Fill out the feedback form
> - Rate us on AlternativeTo
> - Star us on GitHub

If rated <=3:

>We're sorry to hear you weren't that positive, but we want to improve! We would be very thankful if can help us by:
>
> - Filling out the feedback form
> - Vote on features on the forum
>
>This helps us get to know why your experience was a bit disappointing, and how we can fix that!

The above needs links and good styling (not just a list, see the below picture for an example).

I realized this is something mobile apps do frequently, which makes me assume that it works. Probably helps loads with getting feedback, supporters, and community building.

I was inspired by [this dialog that Firefox linked to](https://www.mozilla.org/en-US/etc/firefox/retention/thank-you-a/):

![image](https://user-images.githubusercontent.com/1405370/57154675-b8f67080-6dd9-11e9-82f7-f6d71b835cd9.png)

**Comment by ErikBjare** [comment]
One question that remains is: How can we detect the user has been using it for a week/month? We could check the oldest events in the bucket, but how do we not show the dialog again if shown once? We could do this by setting a flag in localStorage, but that won't persist between browsers.

**Comment by sarneeh** [comment]
@ErikBjare Awesome idea!

> One question that remains is: How can we detect the user has been using it for a week/month? We could check the oldest events in the bucket, but how do we prevent the dialog from getting shown several times? We could do this by setting a flag in localStorage, but that won't persist between browsers.

You will have to store the rating/feedback somewhere in the storage (database) anyways, so how about storing the flag also there and fetch it from the server in the web UI? 

Sorry if this idea doesn't make sense, I started using AW a week ago and I really like it! I would even like to help in development somehow but not right now as I'm totally out of time :sweat_smile:

**Comment by ErikBjare** [comment]
A different thing I thought about: Ask the user how much they would be willing to pay for ActivityWatch (how much money you'd be willing to pay in order to continue using it, as if it had a SaaS revenue model) and then ask them kindly to donate (for example) half of it using Patreon (or some other recurring method).

No forcing them to pay, just make them think about how valuable it is to them, report that to us (valuable information!), and then make it as easy as possible for them to support us with some fraction of that amount.

The economics of this could be pretty great, as we'd ask our users to value us and then let them decide how much of that value we deserve to capture.

**Comment by ErikBjare** [comment]
@sarneeh 

>You will have to store the rating/feedback somewhere in the storage (database) anyways, so how about storing the flag also there and fetch it from the server in the web UI?

We'd probably send the request directly to some type of analytics server. So the answer to the question won't require any new type of local storage on the machine.

>I would even like to help in development somehow but not right now as I'm totally out of time 

That's great to hear! Let us know when you do find time and what you'd be interested in working on, specifically! :smiley:

**Comment by sarneeh** [comment]
@ErikBjare I'm sorry, but I may have been too enthusiastic about this :smile: What I've had in mind was trying to improve the UI design a little, as I see it could be a lot prettier! But after giving it another thought I think I still won't manage to find time to work on something big like this, as I have many other things in life that I need to find time to and those are a lot more important :sweat_smile: Sorry for my indecision :smile:

**Comment by ErikBjare** [comment]
This is still a good idea, but I'm lowering the priority.

**Comment by ErikBjare** [comment]
I just want to add to this issue that we have a survey since some time back that's linked from the home view. Results are positive and have been discussed between me and @johan-bjareholt, we're up for more discussion sometime in the future :slightly_smiling_face:

**Comment by ErikBjare** [comment]
@billangli If you're still looking for a good issue to work on, this would be very high-value and has some parts in common with the update-check PR you worked on before.

The most important part of this issue, now that we know roughly what users want/think (they all want sync asap, basically), is to encourage users to donate. I'll edit the title to reflect that fact.

**Comment by billangli** [comment]
Hey @ErikBjare, thanks for sending this! I'd be happy to work on it :). It has been pretty hectic the past couple of weeks welcoming the new students who just moved in.

So what I am getting from this is to display a rating question in the UI after the user has used it for a bit. After the user has rated it, then display other ways that the user could help in, such as using the willingness to pay to ask for donations if the rating was good. 

You mentioned that we should send the request from the web application to some sort of analytics server. Do you already have some thoughts on how this should be implemented or is something that I will explore? So would I have to create a simple server that receive the ratings?

**Comment by ErikBjare** [comment]
Welcoming students is always fun (sounds like the good kind of hectic)!

Most of what I wrote was just me throwing out some ideas (ignore the analytics part). Right now I'm just interested in getting the MVP-version of this feature done. 

What's important is that we get the user to think "how much do I like this?" and then either (1) donate/spread the word, and/or (2) give us feedback on how to improve.

In the user survey we've sent out before we've asked how much people would be willing to pay, the mean seems to be ~$5/mo, but a lot of people seem confused by the question (despite clearly stating ActivityWatch will be free forever, they don't seem to understand it's purely theoretical).

I think a 1-10 scale with "How likely are you to recommend ActivityWatch to a friend/colleague?" (Net Promoter Score) is the best way to go. See the attached stats from the survey (sorry for phone screenshot).

![Screenshot_2020-09-15-07-38-46-804_com.google.android.apps.docs.editors.sheets.jpg](https://user-images.githubusercontent.com/1405370/93169976-93e07480-f726-11ea-847c-61a8f0aeb4db.jpg)

**Comment by billangli** [comment]
Haha yep, it is good fun! For the MVP, I'm thinking of embedding an iframe for Google Forms onto the UI. And we can display different follow-up responses like donations depending on what has been entered into the survey (which I think is possible from the UI from what I've looked at).

**Comment by ErikBjare** [comment]
>I'm thinking of embedding an iframe for Google Forms onto the UI

I'd rather avoid iframes, and there's no way to get the response from the iframe (especially since it has a different origin).

We don't really need to know the responses for the MVP, we just need them to funnel users into the categories "I like ActivityWatch and could consider supporting development" and "I'm not super excited about ActivityWatch and might consider leaving feedback explaining why". 

That's basically it. Could be a simple Yes/No question even, anything to make it as quick and easy for the user as possible.

**Comment by billangli** [comment]
Ok sounds good, that makes a lot of sense. I will start with that then!

**Comment by billangli** [comment]
Hey @ErikBjare, dang it's been pretty busy lately too, I'll try to get it done this week. Thanks for understanding!

I originally thought of displaying the poll and the links to contribute on the home page because it also contains the links. We might even be able to use the new design as the new home page, because the current one is a bit cluttered. It would be really cool if it looked something like the Firefox screenshot you took. But I think something minimal like a b-alert will do for now. 

Let me know if you're on the same page about this.

**Comment by ErikBjare** [comment]
@billangli Totally understand! Don't worry about it, make the most of your undergrad days! 

That being said, yeah, something minimal like a b-alert (or perhaps a b-modal rather) sounds good. It shouldn't take long to implement, we can always iterate on it. We don't have the Firefox team's graphic designers, and are trying to run a much leaner operation 😅

We've had several requests to do away with the home page altogether (people want to drop straight into the Activity view), which I'd feel more comfortable with doing once this is done 🙂

**Comment by billangli** [comment]
Haha thanks :smiley:, I appreciate it.

Sounds good, I'll keep it simple then. And yes, a b-modal would be more appropriate. It's good to know that people want to remove the home page, I'll keep that in mind when making this.
