### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by inbalboa** [ActivityWatch/activitywatch#295]
Hey, guys! Your app is amazing!

There is one thing that annoys me. The tray icon looks ugly on macOS.

![](https://i.imgur.com/KHdnbtN.png)

**Comment by ErikBjare** [comment]
Hey, thanks!

If you could provide a prettier version of the logo for macOS, I'd gladly add it to aw-qt and use it for the tray icon on macOS! (The relevant line is here: https://github.com/ActivityWatch/aw-qt/blob/fcb59268c43d7a0f61658d78c1f6ace8ef38d012/aw_qt/trayicon.py#L171)

**Comment by heatheriskander** [comment]
The standard way to make tray icons in MacOS is to create a monochrome PDF that the OS colors based on the color of the menu bar, but I've created black and white monochrome PNGs that should look less out-of-place on MacOS, and maybe as a systray icon in general.
![logo-black](https://user-images.githubusercontent.com/4367909/67802098-e78b9600-fa60-11e9-80a0-444c148acad5.png)
![logo-white](https://user-images.githubusercontent.com/4367909/67802100-e78b9600-fa60-11e9-872e-36178d1290d8.png)

**Comment by xylix** [comment]
Used the icons above to make [PR#1](https://github.com/ActivityWatch/media/pull/1) in ActivityWatch/media and [PR#52 in Aw-qt](https://github.com/ActivityWatch/aw-qt/pull/52).

The PR uses the new tray icons, and does so only on MacOS. On MacOS they do fit a lot better.

<img width="306" alt="Screenshot 2019-12-30 at 15 15 10" src="https://user-images.githubusercontent.com/13387304/71583863-dfaba900-2b18-11ea-96d8-19ddba0cb973.png">

**Comment by ErikBjare** [comment]
Fixed by @xylix in https://github.com/ActivityWatch/aw-qt/pull/52!
