### ISSUE TITLE
CPU usage consistently high (even when not actively using the system)

### ISSUE THREAD

**Issue by pcuci** [ActivityWatch/activitywatch#296]
![image](https://user-images.githubusercontent.com/2169849/61179656-204c5000-a5d5-11e9-8c39-31d752589aa0.png)

The behavior seems new, thought I noticed these two previous issues:
- https://github.com/ActivityWatch/activitywatch/issues/262
- https://github.com/ActivityWatch/activitywatch/issues/156

Not sure what's going on, the annoying part is that the CPU usage has been moderate for so long that it heats up my laptop. 😄 

--- will loop back re: ---
**For us to be able to understand the issue you're having you need to follow this template.** Please make sure there isn't already an issue for the bug you've found, otherwise it'll just take more resources, which means less time for us to actually fix bugs. Thanks for reporting!

## Documentation
If applicable, add screenshots or logfiles to help explain your problem.

Logfiles can be found in different places depending on platform:
 - Windows: `C:\Users\<USER>\AppData\Local\ActivityWatch\Logs`
 - macOS: /Users/<USER>/Library/Logs/activitywatch
 - Linux: /home/<USER>/.cache/SuperApp/log

## Environment
 - ActivityWatch version: [e.g. v0.8.0b7]
 - OS: [e.g. Windows 10, Linux (Ubuntu), macOS (High Sierra)]

**Comment by pcuci** [comment]
Went off and deleted all the buckets (thought maybe there was too much data?), still all aw-* services are on average each double-digits %CPU usage, with aw-server leading the pack!

**Comment by ErikBjare** [comment]
Please provide the rest of the information in the issue template.

**Comment by johan-bjareholt** [comment]
If you turn off all watchers, does aw-server till take up a fair amount of CPU time?

**Comment by petRUShka** [comment]
Suddenly 

`top` output:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                
1991817 user      20   0    9468   3784   3172 R  11.8   0.0   0:00.03 top                           
```
OS: Archlinux, aw-watch version: v0.9.2

**Comment by johan-bjareholt** [comment]
@petRUShka Your comment only shows that the "top" command uses up 11.8% CPU, it does not show much CPU activitywatch uses.

**Comment by Butanium** [comment]
> P.S. Command
> 
> ```
> kill `pgrep aw-wat`
> ```
> 
> helped.

This fixed my 100% CPU usage too

**Comment by m-GDEV** [comment]
aw-watcher-window was also using 100% of one of my cores.

The comments above saying to use the command: 
```kill pgrep aw-wat``` while technically not wrong, are misguided. This command does fix the issue but also just kills any activity watchers as far as I know (I might be wrong, let me know).

What worked for me was to just kill ActivityWatch which can be done by either:
1. right-clicking the applet, clicking "Quick ActivityWatch"
2. running `pkill -f 'aw-'`

And then to start it again.
