### ISSUE TITLE
Possible issue running more than one desktop in W10

### ISSUE THREAD

**Issue by jmmogollon** [ActivityWatch/activitywatch#299]
I don't have time to check, but I'd say that since I am running 2 desktops in W10 aw stopped working properly. I observed that my activity was not being added up in the current day, but in the previous one (?).

Version: v0.8.0b6

Does it make any sense?

**Comment by johan-bjareholt** [comment]
> I don't have time to check, but I'd say that since I am running 2 desktops in W10 aw stopped working properly.

What do you mean with two desktops? Two monitors or two virtual desktops?
Two monitors should work, I believe two virtual desktops should work as well but I'm not certain.

> I observed that my activity was not being added up in the current day, but in the previous one (?).

What do you mean with this? Your activity is being tracked on the day before instead of the current day?

As long as the clock on your computer is correct this should work.

**Comment by jmmogollon** [comment]
I mean two virtual desktops. The thing started working fine again after I
went back to a single desktop (all the time working on two physical
screens).

The system clock was ok. To be precise the raw data was ok, but in the
summary the activity was being added to the previous day, not the present
day.

**Comment by ErikBjare** [comment]
If the raw data is fine then it sounds to me like this has nothing to do with virtual desktops and is probably just because you didn't expect the data to appear on the previous day even though it was past midnight (see the "end of day" setting). 

Can you reproduce?

**Comment by ErikBjare** [comment]
If the raw data is fine then it sounds to me like this has nothing to do with virtual desktops and is probably just because you didn't expect the data to appear on the previous day even though it was past midnight (see the "end of day" setting). 

Can you reproduce?
