### ISSUE TITLE
Failed events causes havoc in terms of order-of-requests

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#30]
If aw-server and a watcher is running and then the server suddenly dies the client will start queueing up failed requests to store events, as it should.

However, when the server comes back up, the watcher could try to send another event *before* it tried to empty it's `failed_events_queue`. This leads to the events getting out of order, effectively ruining `replace_last_event`.

Should be an easy fix, simply always add the request to the queue when it is non-empty. However, the added complexity makes for an argument for moving towards a heartbeat-based API since that would only require queueing heartbeat-objects instead of requests to different endpoints (new event, replace last event, new event, etc.).

**Comment by ErikBjare** [comment]
This is fixed, right @johan-bjareholt?

**Comment by johan-bjareholt** [comment]
Yep, was fixed in ActivityWatch/aw-client/pull/5

Closing
