### ISSUE TITLE
Using the Django framework to consolidate and better secure running processes

### ISSUE THREAD

**Issue by bengineerdavis** [ActivityWatch/activitywatch#301]
**Is your feature request related to a problem? Please describe.**
You have a roadmap for secure usage, but no clear implementation as of yet: https://activitywatch.readthedocs.io/en/latest/security.html

I noticed that you're running your flask aw-server with message `WARNING: This is a development server. Do not use it in a production deployment`, which made me a little concerned. 

You also have a huge spread of various workers/servers, which also increases your attack surface.

I want to offer my suggestions on what I see as a great project.

**Describe the solution you'd like**
1. Create the aw-server into a Django backend.
2. Turn the watchers into Django apps that can fit into a well-tested and reliable framework that could reduce future technical debt over time. 

**Describe alternatives you've considered**
I felt confident from reading the documentation and going through issues, that this project is covering it's use cases well in discussion. I believe in your mission to respect a user's choice with their own data, and would not trust a lot of the various other frameworks to reliably deliver that promise without extensive lower-level expertise in web app development.

**Additional context**
My hope is this switch, while potentially expensive now, would reduce future technical debt and widen the potential developer community that could contribute to your cause.

I would like to see an experimentation with Django where all the different `watchers` could benefit from an established platform with well-tested security features. This is not to say that flask isn't itself a well-established platform, but it increases security risks because flask is deliberately a barebones microframework that requires a lot of dev decisions and maintenance of addons required to make a complete product. Each of the those addons may or may not be supported over time. So while it can make the startup cost of developing the app easier now, it could multiply the complexity of the app as it develops more sophisticated features. 

Other reasons to use Django: 
- built-in encryption capabilities 
- a solid admin interface, 
- a reliable ORM that can let both the dev and user select and migrate between databases easily
- let your wider community contribute other apps that can plug new, interesting, or important features into the Django architecture while benefiting from its base features.
- expand the potential development community by covering some of the more difficult challenges of app dev.
- make use of Django-CORS https://github.com/adamchainz/django-cors-headers
- make of the modularity of the Django infrastructure, such as templating.

I hope this can help you, I respect that this might not be a direction you can afford to change towards in the immediately or near future, but I'd like to see this project evolve. Looking forward to a good discussion.

Django has a solid ORM that can let a user or dev choose from different databases easily, increasing options for file syncing.

Admittedly, I don't know if this would complicate use with syncthing (another tool I've found recently and have really enjoyed), or how much this framework would bloat the app in a mobile context.

**Comment by johan-bjareholt** [comment]
> Create the aw-server into a Django backend.

We are currently rewriting aw-server in Rust. Python is a great tool to get things quickly working, but its performance is sub-par for us when doing queries over longer periods of time and it's easy to write something incorrect in python so it's more likely that bugs will exist no matter how good the developer is (a developer is just a human in the end after all). I'm also not a fan of ORMs as I find them to be more in the way than actually helping me, but that's a personal preference.

Django also has the issue that "everything is in one package" so once you have written a Django app and don't like one of its components it's either rewrite the whole thing or live with it. I also believe that Django has way more features than we'll ever need so it would mean a bit of bloat for us.

> Turn the watchers into Django apps that can fit into a well-tested and reliable framework that could reduce future technical debt over time.

The watchers have no need for a webserver as it only does requests. Nowadays we barely have any maintenance at all on our stable watchers as they are very lean so this is not an issue currently. If you look at aw-watcher-window you can see that the only changes we have done to it the last year has been to make our buildscript for CI work better.


Is it OK if I close this issue?
