### ISSUE TITLE
Web interface doesn't work at all without cookies

### ISSUE THREAD

**Issue by 1j01** [ActivityWatch/activitywatch#304]
The tab shows a completely blank screen when cookies are disabled. (Also refreshing after enabling cookies seemed never finish; I had to close the tab and open a new one to get it to work.)

Accessing the `localStorage` object at all causes an error when cookies are disabled.

**Comment by ErikBjare** [comment]
This is not a bug, we need localStorage to store settings. There's no reason for you to disable it since everything is local anyway, so just don't.

**Comment by 1j01** [comment]
I have cookies disabled by default. It should just show a message if it needs cookies, instead of a completely blank tab.

**Comment by ErikBjare** [comment]
You're always welcome to contribute code that does that.
