### ISSUE TITLE
opera / vivaldi reporting

### ISSUE THREAD

**Issue by icf20** [ActivityWatch/activitywatch#305]
![image](https://user-images.githubusercontent.com/17784575/67146689-da66ee00-f28d-11e9-9ef6-8859c878ef2e.png)

## Describe the bug
the browser add dont report data corectly

## To Reproduce
1 install the addon
2 go to daily activity browser tab

## Expected behavior
get the same stuff that i get for firefox

the extension on vivaldi produce the next debug

```
Number of active tabs: 1
Tabs:
{
    "active": true,
    "audible": false,
    "autoDiscardable": true,
    "discarded": false,
    "extData": "{\"read\":true,\"vivaldi_tab_muted\":false}",
    "favIconUrl": "https://github.githubassets.com/favicon.ico",
    "height": 950,
    "highlighted": true,
    "id": 84,
    "incognito": false,
    "index": 8,
    "mutedInfo": {
        "muted": false,
        "reason": "capture"
    },
    "pinned": false,
    "selected": true,
    "status": "complete",
    "title": "GitHub - ActivityWatch/activitywatch: Log what you do on your computer. Cross-platform, extensible, privacy-focused.",
    "url": "https://github.com/ActivityWatch/activitywatch",
    "width": 1682,
    "windowId": 12
}

{"testing":null,"lastSyncSuccess":true}
```

**Comment by ErikBjare** [comment]
You have not provided information about the version you're using.

**Comment by icf20** [comment]
> You have not provided information about the version you're using. We can't help you if you don't.

Version: v0.8.0b9

**Comment by johan-bjareholt** [comment]
We got a fix for Vivaldi on Linux a few days ago so that should be fixed in the next version of activitywatch https://github.com/ActivityWatch/aw-webui/pull/146

Are you running Windows, Mac or Linux?

**Comment by icf20** [comment]
> We got a fix for Vivaldi on Linux a few days ago so that should be fixed in the next version of activitywatch [ActivityWatch/aw-webui#146](https://github.com/ActivityWatch/aw-webui/pull/146)

perfect then

yes i am running linux
