### ISSUE TITLE
Network error on Windows with 0.8.3

### ISSUE THREAD

**Issue by TowerCrow** [ActivityWatch/activitywatch#312]
![image](https://user-images.githubusercontent.com/46613876/69008334-ea87f100-0951-11ea-96d1-4e8418364868.png)

![image](https://user-images.githubusercontent.com/46613876/69008371-38045e00-0952-11ea-9e2b-cd1cab791e92.png)

**Comment by ErikBjare** [comment]
You haven't provided any of the things we ask you for in the issue template. If you don't we can't help you.

**Comment by johan-bjareholt** [comment]
Very likely the same as #313 though

**Comment by ErikBjare** [comment]
@johan-bjareholt The second screenshot could be, but the error doesn't look quite right. The first one definitely isn't.

Since @TowerCrow hasn't detailed his issue enough for us to do anything about it, I'm closing.
