### ISSUE TITLE
Chrome extension is not logging data

### ISSUE THREAD

**Issue by LeBaux** [ActivityWatch/activitywatch#314]
I use Vivaldi browser and I installed the extension for chromium-like web browsers. The logging from websites worked in 8.0 or maybe even 8.1 (I do not recall) but I noticed it is broken with 8.3.0.

![image](https://user-images.githubusercontent.com/5657511/69232515-7fc1fa00-0b8b-11ea-8cb9-49b1b2b00f99.png)

```json
Number of active tabs: 1
Tabs:
{
    "active": true,
    "audible": false,
    "autoDiscardable": true,
    "discarded": false,
    "extData": "{\"useDefaultIcon\":false,\"read\":true,\"ext_id\":\"ck375lp3o01ab3h5oc4gn111c\",\"urlForThumbnail\":\"https://github.com/ActivityWatch/activitywatch/issues/new?assignees=&labels=&template=bug_report.md&title=\",\"thumbnail\":\"data:image/jpeg;base64,/9j/********TRUNCATED*******f/9k=\"}",
    "favIconUrl": "https://github.githubassets.com/favicon.ico",
    "height": 963,
    "highlighted": true,
    "id": 933,
    "incognito": false,
    "index": 13,
    "mutedInfo": {
        "muted": false,
        "reason": "capture"
    },
    "openerTabId": 190,
    "pinned": false,
    "selected": true,
    "status": "complete",
    "title": "New Issue · ActivityWatch/activitywatch",
    "url": "https://github.com/ActivityWatch/activitywatch/issues/new?assignees=&labels=&template=bug_report.md&title=",
    "width": 1700,
    "windowId": 158
}

{"testing":null,"lastSyncSuccess":true}
```

GUI is not showing the data, nor the "Dropdown".

![image](https://user-images.githubusercontent.com/5657511/69233287-eeec1e00-0b8c-11ea-9934-f546283949a9.png)

I tried installing Chrome (ugh) and it works there. It seems like Vivaldi specigic issue. Potentially other chromium-based browsers. I tried Brave too, and it works. To sum it up:

1. Vivaldi stable 2.9 ❌
2. Vivaldi snapshot 1719.3 ❌
3. Chrome stable ✅
4. Chrome canary ✅
5. Brave ✅

## Environment
 - ActivityWatch version: 8.3.0
 - OS: Manjaro Linux i3 18.1 with 5.3.11-1 kernel

## Additional context
In your bug report template, you refer to log files for Linux being in `/.cache/SuperApp/` but it seems the standard path is `/.cache/activitywatch/`. I can send you some of them in private, but I consider my "activity" history private so I will only forward it if absolutely necessary (ideally using keybase). If I was you, I would specify what logs are most relevant and what personal data would be the person sharing if they chose to upload it to Github.

**Comment by johan-bjareholt** [comment]
If it's not even available in the "Browser" tab I'll assume that the extension for some reason failed to create the bucket for some reason.

Can you see it in the "Raw Data" tab? If not, please go into your browser settings and debug the extension and look at its logs.

**Comment by LeBaux** [comment]
Hey, http://127.0.0.1:5600/#/buckets/aw-watcher-web-chrome seems to have proper data. So it is just not showing in overview for some reason? I tried clearing browser cache but to no avail.

**Comment by ErikBjare** [comment]
What is the "app" field of the window event for Vivaldi?

**Comment by LeBaux** [comment]
`app: Vivaldi-snapshot` and for stable, it is `app: Vivaldi`

**Comment by ErikBjare** [comment]
Found the issue:
https://github.com/ActivityWatch/aw-webui/blob/10d931767d0ed6f41b9bf479f49ecb660b029972/src/queries.ts#L89

Adding Vivaldi-snapshot and a plain Vivaldi should fix it. Can you send a
PR?

**Comment by LeBaux** [comment]
I did, I love when I get to submit 1 line PRs :yum: While this issue is solved, we should still consider the larger issue opened. We need an exhaustive list of browsers or a more pragmatic approach to browser detection. Possible help with this one https://gs.statcounter.com/browser-market-share

**Comment by ErikBjare** [comment]
Since we're dealing with cross-platform appnames that are not uniform (packagers sometimes decide to add suffixes, for example) and specific to however the watcher retrieves them for each particular platform, I think this is the best we can do for now. 

It's not  a priority anyway, and adding support for new browsers should be pretty rare once we've covered the basics.

**Comment by ChenDanCMU** [comment]
Same issue here with Firefox-esr 68.2 on Debian 10 stable. I think just add 'firefox-esr' to https://github.com/ActivityWatch/aw-webui/blob/10d931767d0ed6f41b9bf479f49ecb660b029972/src/queries.ts#L89
 should fix the bug.

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/aw-webui/pull/158

**Comment by ErikBjare** [comment]
@ChenDanCMU If you want a fix for that, verify that the string is correct and send us a PR.

**Comment by LeBaux** [comment]
Just to confirm, vivaldi and vivaldi snapshot are both `vivaldi.exe` on Windows platform. Thank you for the fix.
