### ISSUE TITLE
Editor tab (VSCode) in Activity View only show current day

### ISSUE THREAD

**Issue by austil** [ActivityWatch/activitywatch#316]
## Describe the bug
On "Activity" view, when I select a day other than the current one, the Editor tabs still show the information of the current day (being the files and project I worked on today in VSCode).

## To Reproduce

0. You need VSCode with the Activity Watch plugin running with data on two different days
1. Go to 'Activity'
2. Click on 'Editor'
3. Take note of today's activity
4. Select a previous day in the timeline
5. Click on 'Editor'
3. Check if anything is different compared to what you've seen on 3

## Expected behavior
I should see the Editor Activity for the selected day.

## Environment
- ActivityWatch v0.8.3
- OS: Ubuntu 18.04.3 LTS
- VSCode 1.40.2
- aw-watcher-vscode 0.4.0

Thx for this useful piece of software :smiley:

**Comment by ErikBjare** [comment]
Woops, looks like I missed this in testing!

I use any editor watcher right now, so would be nice if someone else could fix this.

The quick way is to just add a watch on the date prop that runs the query, the correct way is to move the query into the Vuex store.

**Comment by ErikBjare** [comment]
Maybe @johan-bjareholt? Would be a good opportunity to better understand Vuex.

**Comment by johan-bjareholt** [comment]
Solved in https://github.com/ActivityWatch/aw-webui/pull/160, will be fixed in the next release
