### ISSUE TITLE
Duplicated "Today" bar

### ISSUE THREAD

**Issue by austil** [ActivityWatch/activitywatch#320]
## Describe the bug
The timeline of the "Activity View" as a duplicated "Today" bar.

## Expected behavior
Only one bar (and one label) should be displayed.

## Documentation
![ActivityWatch_doubleTodayEntry](https://user-images.githubusercontent.com/3978482/70854187-ad634000-1eb8-11ea-83e8-989c112c4da9.png)

## Environment
 - ActivityWatch version: 0.8.3
 - OS: Ubuntu 18.04.03 LTS

## Additional context
I've not used my computer yesterday but used it 16min after midnight.

Clicking on the smaller bar select today's day but it's the bigger one that's highlighted.

**Comment by ErikBjare** [comment]
I've never seen this, and you haven't provided any steps to reproduce. If we can't reproduce it, we can't fix it.

**Comment by austil** [comment]
Yup, totally aware of that and I have no idea what can be provided for this bug, guidance is welcomed.
It's still appearing today tho.

So, I had a look at the different queries made by the browser on the activity view and found one for the afk-bucket that seems to be the one providing data to the timeline (?). I've saved the dump of this query's response as well as the aw-server log from the 11th to the 14th of december : [activitywatch_duplicated_timeline.zip](https://github.com/ActivityWatch/activitywatch/files/3964742/activitywatch_duplicated_timeline.zip).

Notice that : 

- the server started at 00:16 on the 14th
- the query receive data for the 13th starting at 23:16

```json
{
    "id": null,
    "timestamp": "2019-12-13T23:16:37.252000+00:00",
    "duration": 1682.156,
    "data": {
        "status": "not-afk"
    }
}
```

Tell me if you think of anything else relevant that I can provide to help you with this issue.
Best regards.

Augustin

**Comment by ErikBjare** [comment]
>Notice that :
> - the server started at 00:16 on the 14th
> - the query receive data for the 13th starting at 23:16

This is just due to the fact that logs are in your local timezone (UTC+1, I assume) while event timestamps are in UTC, so it has nothing to do with the issue.

Also note that activity before 04:00 will count towards the previous day, you can adjust this time in the settings.

Overall, I have no idea what could be going wrong here. But thanks for providing logs and a dump of the query response!
