### ISSUE TITLE
Export as JSON functionality not working for individual buckets

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#322]
Pressing on "more"->"Export as JSON" for an individual bucket does not trigger any actions.

**Comment by johan-bjareholt** [comment]
Fixed after you created the issue, I just forgot to respond. 

https://github.com/ActivityWatch/aw-webui/commit/0a60cf7b6f43194f3cdcc32b1372d2835face88c

So will be available in next release.
