### ISSUE TITLE
Google Calendar Importer

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#325]
**The Problem**: This is the basic user event-tagging problem: I want to be able to tag different parts of my day, in order to later analyse how productive they were, and see from a specific event("Attending lecture"), what I actually spent my time on. 

**Solution**: Google Calendar Importer which takes all the events for the day, and places them in a bucket, very similar in structure to the stopwatch bucket. There is a clear use case for this where a user might not want to have 2 places where they're annotating events(both in their calendar + in activitywatch), so they can just do it in their calendar, if that is their preferred method of choice. 

**Implementation**:
1. Implement a web-hook which always listens to event changes.
2. Webhook initially pulls in ALL of the events starting with a specific date, and adds them to the bucket.
3. Whenever a change happens(adding, modifying, deleting event), Notification is sent to the web-hook, which then modifies the data in the bucket.
**Note**: This basically treats the online calendar as the complete source of truth, so whenever you make a change, it will make a change to the 

**Alternatives**
* Alternatives to this implementation are polling instead of web-hooks. With a web-hook, the user will need to create a project in google console, and change some settings, whereas simply making API calls might simplify the set-up process, but at the expense of performance. To overcome the long set-up process, good documentation can be added which explains everything step by step.

What are your thoughts on the feature and its implementation? I can begin work on implementing it over the next days.

**Comment by ErikBjare** [comment]
I want something like this as well. I even built a small prototype that imports `.ical` files here: https://github.com/ActivityWatch/aw-import-ical

The stopwatch-events and similar user-constructed data (like calendar imports) are still not used when constructing the Activity view, but that should be somewhat easy to fix.

**Comment by nicolae-stroncea** [comment]
What are your thoughts on using webhooks/polling or do you think .ical is enough?

I think the advantage of polling/webhooks that the user does not need to manually update files, the bucket will be continuously updated as long as the server is running + the backend has to just watch for modified changes.

**Comment by nicolae-stroncea** [comment]
A way to perform polling is syncrhonization(https://developers.google.com/calendar/v3/sync). Every time we synchronize the data, we get a token. When we synchronize again, we pass the old token, which tells the API the last time we synchronized. We can poll once a day, or at certain intervals, i.e every 15 minutes. If there are no changes, I imagine that we will get something along an empty list, so we don't do anything else. It seems like a fairly efficient way to do polling, as we send an API request every X minutes, but only perform computations on actual changes.

**Comment by ErikBjare** [comment]
Using some smart way of synchronizing with Google Calendar is definitely preferred. WebHooks probably won't work since Google Calendar can't call out to aw-server, but polling should be fine. 

I just opted for the `.ical` thing when experimenting because I wanted something quick to play with. Google Calendar does offer a "subscribe to .ical" which gives you an URL to an up-to-date iCal which we could just fetch regularly. That has benefits since it's not tied to Google Calendar specifically but is bad because syncing will be horribly inefficient and the URLs effectively become secrets.

I'd try out that sync API you found and go from there :)

**Comment by nicolae-stroncea** [comment]
Submitted a working pull request into [aw-import-ical](https://github.com/ActivityWatch/aw-import-ical/pull/1)

Currently functions as an importer, where you have to add a credentials.json file that you get from Google developer console(instructions are in the PR) and it will automatically download all the events to a new bucket whenever you run it. While the setup part is not the most user friendly, once you do that , you just have to run the file periodically to get the latest updates

It would also be trivial to turn it into a watcher by having it automatically run multiple time each day
