### ISSUE TITLE
Sponsor button not showing the GitHub sponsors program

### ISSUE THREAD

**Issue by stared** [ActivityWatch/activitywatch#328]
## Describe the bug

When clicking on the **Sponsor**, it shows the Patreon and Open Collective links, but not - GitHub. It shows:

```
Some errors were encountered when parsing the FUNDING.yml file:

Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
Learn more about formatting FUNDING.yml.
```

@ErikBjare and @johan-bjareholt - did you apply to the https://github.com/sponsors ?

## To Reproduce

1. Click on "Sponsors"

**Comment by ErikBjare** [comment]
I've applied but my verification process is blocked since I can't provide a proof of residence at this time, but it will be resolved eventually (They're sending an email reminding me about it every day). 

I don't think @johan-bjareholt has applied at all, but I'm not sure.

**Comment by johan-bjareholt** [comment]
@ErikBjare Should we sign up for GitHub sponsors as a organization or do it individually?

**Comment by ErikBjare** [comment]
Individually since we don't have a dedicated bank account for ActivityWatch
(and it seems signing up to the sponsors program as an org is still in
limited beta).

**Comment by ErikBjare** [comment]
I've now submitted the needed documents as well, should hopefully work soon.

**Comment by ErikBjare** [comment]
Fixed! Both the org, me, and @johan-bjareholt now show up.
