### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by Rik44444** [ActivityWatch/activitywatch#329]
hi all,
this is a message to thank you for your very helpful information on your page, comparing all open-source time/activity tracking software, this is exactly what i had been looking for. This is also a question: i saw from your page that there are currently no open source solutions for this an Android: do you know of any that are in development? Are you yourselves planning to do this?

**Comment by Rik44444** [comment]
sorry just seeing now that you have an Android version in early development. Great that that will become available! Are you aware of other initiatives to develop this for Android?

**Comment by ErikBjare** [comment]
As far as we know, we're the only open source automated time tracker on Android at the moment.

The Android version works, but it isn't great, and we haven't done any polish at all. You might even say we're actively discouraging use by having such a shitty starting screen for it, but you can try it yourself: https://play.google.com/store/apps/details?id=net.activitywatch.android&hl=en
