### ISSUE TITLE
Excessive split on `:`

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#33]
![screenshot_2017-03-13_13-48-15](https://cloud.githubusercontent.com/assets/1405370/23854920/f333780e-07f3-11e7-8b77-b07fd2b5b858.png)

In the bucket viewer it shows up as `title:[Main:python3] aw-watcher-afk /home/erb/.local/share/activitywatch/aw-server (/home/erb/.local/share/activitywatch/aw-server)`, so I suspect something is going wrong in the webui. But I'm not sure.

**Comment by johan-bjareholt** [comment]
Huh, i thought i had fixed that but apparently not. Will look into it

**Comment by johan-bjareholt** [comment]
Apparently i had fixed it in chunks but not in the timeline. Will fix then please test again

**Comment by johan-bjareholt** [comment]
Should be fixed now, please test again

**Comment by ErikBjare** [comment]
Working!
