### ISSUE TITLE
Upgrade Ubuntu version in Travis

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#333]
We're currently using 14.04, which reached end of standard support in 2018-04. We should switch to either 16.04 (Xenial) or 18.04 (Bionic). 

Might even solve some hard-to-debug bugs like https://github.com/ActivityWatch/aw-qt/issues/29 and our maybe outdated fontconfig stuff (https://github.com/ActivityWatch/aw-qt/issues/34).

**Comment by johan-bjareholt** [comment]
@ErikBjare can we close this? GitHub actions works for the main repo right?

**Comment by ErikBjare** [comment]
The PyInstaller bundles produced in GitHub Actions don't yet work (see the issue about moving to GitHub Actions).

This issue should maybe still be closed though, as we should just fix the issues in GitHub Actions.

**Comment by ErikBjare** [comment]
Closing since we're moving to GitHub Actions, so efforts are better spent there.
