### ISSUE TITLE
Is it possible to run watchers and the server seperately on different machines?

### ISSUE THREAD

**Issue by Rapiz1** [ActivityWatch/activitywatch#335]
*Not sure if it is a new feature. I suppose it may be easy to accomplish with some configuration.*
Here's the things: I have a virtual machine of Win7 on Linux to run some Windows-only softwares (I believe many people do the same). Given that ActivityWatch applies C/S architecture, maybe I can simply modify some configuration like address and port and run watchers separately to send data to the server running in the host.
I think it's very useful to run server and watchers separately. For the people who have computers both in their workplace and home, they can send all the data to a remote server they set up.

**Comment by ErikBjare** [comment]
This has already been answered, I easily found it by searching: https://github.com/ActivityWatch/activitywatch/issues/249

Closing.

**Comment by ErikBjare** [comment]
I should add that this has also been discussed on the forum: https://forum.activitywatch.net/t/accessible-from-remote-computer/236
