### ISSUE TITLE
Save "Show last" value in timeline view (web-ui)

### ISSUE THREAD

**Issue by riscie** [ActivityWatch/activitywatch#338]
**Is your feature request related to a problem? Please describe.**
Everytime we navigate back to the timeline view in the web-ui, the value `show last` is set to 1h.

**Describe the solution you'd like**
It would be nice if the interface remembered our last choice when we come back. One solution would be to persist the value into the local storage like it was done for `classes` and `startOfDay`. 
We could introduce a new item eg. `showLast`. If it is set to a value, the ui could take this, otherwise it could take the default.

**Describe alternatives you've considered**
We could also introduce a new option in the Settings-view. In my opinion, it would be a bit of an overkill.

Thanks so much for the tool, it's a breeze to work with and I am very happy it exists.

**Comment by riscie** [comment]
I forgot to mention. I could try to tackle this issue with a PR. But first we would need some clarification wether this feature is desirable and wether the suggested implementation above is a fine way for the activity-watch devs to go with.

**Comment by ErikBjare** [comment]
I personally wouldn't expect the drop down to persist which timeframe I last used. I sometimes switch to the 12/24h one and wouldn't want to wait for all that data to be loaded the next time I open the timeline, for example.

Which time-frame do you use most frequently? I'm open to changing the default, and possibly creating a setting for it if there's demand.

**Comment by riscie** [comment]
Thanks for the quick answer! I am using the timeline to get an overview of my workday. Then, when I need more detail for a specific timespan, I just scroll in. The 12h setting does this job for me at the moment (on most normal days at least ^.^).

I've just made a small contribution to the project. There seems to be an error in the `FUNDING.yml` if you wanna check this.

**Comment by ErikBjare** [comment]
@riscie Feel free to contribute a PR that adds it as a setting!

The FUNDING.yml issue is known and has to do with Stripe's KYC practices requiring proof of residence (utility bill, bank statements), which is rare to come by here in Sweden where I get both digitally. It's tracked in https://github.com/ActivityWatch/activitywatch/issues/328.

**Comment by riscie** [comment]
Here is the PR: https://github.com/ActivityWatch/aw-webui/pull/169
Let me know if this suits or if we need some optimizations.

**Comment by johan-bjareholt** [comment]
This is merged, closing
