### ISSUE TITLE
Dashboard filter failing to tag some web content

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/activitywatch#340]
## Describe the bug
Problem with dashboard regex filters. For me youtube videos watched in firefox aren't being categorized correctly.

## To Reproduce
- Have a youtube tab open for long enough that it shows up in the dashboard
- Set up a filter for YouTube content to get tagged somehow

## Expected behavior
I expected youtube media to get grouped inside the "media" category when I set my filter but it's just showing up under uncategorized.

## Documentation
<img width="470" alt="Screenshot 2020-02-09 at 20 31 02" src="https://user-images.githubusercontent.com/13387304/74133177-a888e700-4bf0-11ea-9e33-4a10e52555e4.png">
<img width="360" alt="Screenshot 2020-02-09 at 20 31 10" src="https://user-images.githubusercontent.com/13387304/74133181-aaeb4100-4bf0-11ea-94b4-c891dd60843b.png">

Logfiles can be found in different places depending on platform:
 - Windows: `C:\Users\<USER>\AppData\Local\ActivityWatch\Logs`
 - macOS: /Users/<USER>/Library/Logs/activitywatch
 - Linux: /home/<USER>/.cache/SuperApp/log

## Environment
 - ActivityWatch version: v0.8.4
 - OS: macOS Mojave

**Comment by ErikBjare** [comment]
I have no idea how to debug/reproduce this. I need more info: does it happen with anything else other than YouTube? Is anything else in that rule being correctly classified? Does this happen with all YouTube activity or only some of it? 

In some future version you'll be able to categorize by domain/URL which will make it a lot easier to classify by URL.

**Comment by xylix** [comment]
Yes, The iina (a local media player) windows (for example the 2 ones beginning with [Erai-raws] in the screenshot) are being correctly classified.

I tried adding more filters in other categories filtering for firefox tab titles and they fail too (for example filter `pocket` fails to categorize my pocket tabs). 

Just noticed my activitywatch firefox plugin was also disabled, enabled it and will report if it fixes anything.

**Comment by johan-bjareholt** [comment]
> Just noticed my activitywatch firefox plugin was also disabled, enabled it and will report if it fixes anything.

Currently the categorization only works for window titles and appnames.
In the future we will add support for URLs from the browser, but it does not work yet.

Personally it works fine for me for matching YouTube though as firefox exposes that in the window title. My regex is simply "YouTube"

**Comment by xylix** [comment]
Hm okay. I'll try to find a way to make my configuration detect youtube

**Comment by Cardosaum** [comment]
I'm facing an issue related to tag some web pages too...

In my case, the regex fail to match `Matrícula Web | Dados da Oferta - Mozilla Firefox`. My regex rule is: `matr.+cula\s*web` (ignore case is set to `True`).

Is it fine to comment in this issue or is it better to create another thread?

Thanks you all for investing time on this amazing software! (Hope soon be able to help in its development as well)

**Comment by xylix** [comment]
@Cardosaum I think it's fine to comment here. My current bet is that it has something to do with the matching, but will need to investigate to figure out what.

**Comment by xylix** [comment]
Looking into it I found that a youtube moment probably did get tagged correctly today. Unsure if there was a problem previously, or if I just got confused by the way the application colors aren't in sync with the category colors.

I'll try keeping an eye on my categorisations.

**Comment by johan-bjareholt** [comment]
@xylix If you go back to the previous days, are the categories still shorter than the time spent?

If they are we should still consider it to be broken, no events should be missed as we want to be as accurate as possible. The categories are recalculated every time you refresh the web-ui so changing categories back and forth is not an issue.

**Comment by xylix** [comment]
The days I can eyeball look fine, but it's hard to say for sure since there's no way to "break down" the uncategorized time I have on my dashboard.

Could also add a feature request for a way to look "inside" the categories on the dashboard (or to find window title specific breakdowns). That would help a lot in confirming this issue / the lack of an issue in the category summing. Also would be a useful feature for at least my use.

**Comment by johan-bjareholt** [comment]
@xylix That's actually possible in the master version of the web-ui, so it'll be available in the next release!

Not the best UI for it (just a dropdown to filter by category on the Activity page), but it works.

**Comment by ErikBjare** [comment]
@johan-bjareholt That feature is in the latest release. I think @xylix
means something different, but I'm not quite sure what.

**Comment by xylix** [comment]
I meant that for example here
![Screenshot 2020-02-13 at 14 39 31](https://user-images.githubusercontent.com/13387304/74436231-be0b4480-4e6e-11ea-849a-d6337d29994e.png)

It would be useful to see what window titles make up the "Programming" category. So basically another layer of possible zoom to the view.

**Comment by johan-bjareholt** [comment]
> That feature is in the latest release

Oh, I thought I was on the latest one one of my computers but I was on 0.9.3, 0.9.4 has it!

> It would be useful to see what window titles make up the "Programming" category. So basically another layer of possible zoom to the view.

You can't see it in that visualization specifically because it only shows categories and no window titles, but you can see all window titles in a category by selecting it in the dropdown on the bottom of the Activity Summary page.

**Comment by xylix** [comment]
Thanks @johan-bjareholt, that's just what I wanted. Just didn't see the dropdown before :p. My times look correct, now looking with the improved information.

@Cardosaum Can you try using the dropdown at the bottom to confirm your missing categorizatins and maybe add some information about how much content is not getting categorized correctly? (For example is _all_ youtube content not getting tagged for you?)

**Comment by Cardosaum** [comment]
Sure, @xylix !

I was already using this `Show category` at the bottom, actually. For now, I can't see anything mismatching other than the previously mentioned `Matrícula Web | Dados da Oferta - Mozilla Firefox`.

I can confirm that all my YouTube content is being correctly matched.

If I set _pattern_ as `Matrícula Web` the content is indeed caught. However, if I set _pattern_ to `matr.+cula\s*web` (which should match the window title - as it is `ignoreCase = True`), nothing happens in regex search, and I end up getting uncategorized window titles..

I suspect that the reason I'm getting this error in matching patterns is due to a character that contain acute accent, perhaps?

---

@xylix , would you mind to copy and paste some window titles that are not being recognized by your regex rules? (as well as you current regex rules)

I know you already showed them, but maybe is some little detail we didn't see.

**Comment by johan-bjareholt** [comment]
> However, if I set pattern to matr.+cula\s*web (which should match the window title - as it is ignoreCase = True), nothing happens in regex search, and I end up getting uncategorized window titles..

Maybe you've already tested this, but have you tried without "/s"? Not sure if that's supported on all versions of regex.

**Comment by Cardosaum** [comment]
I hadn't tried that, and you are right, `\s*` was the problem!
If I change `\s*` to ` ` (white space) the window title is indeed matched.

Now I wonder, why is this regex pattern not supported? 

Could we change the code to a more modern version of regex?

**Comment by ErikBjare** [comment]
We're using Python's re module, which should support `\s`:
https://docs.python.org/3/library/re.html

It is possible that the backslash isn't getting passed correctly. Are any
other escape sequence commands working?

**Comment by Cardosaum** [comment]
@ErikBjare , 

As far as I tested, I couldn't use any escape sequence command successfully (`\s`, `\w`, `\d`, etc). 
However, patterns like `.*` are working.

**Comment by johan-bjareholt** [comment]
@Cardosaum I have a theory why they don't work.

Does using double backslashes work?

**Comment by Cardosaum** [comment]
@johan-bjareholt 

I think I got what you thought, but unfortunately double backslashes does not work..

**Comment by johan-bjareholt** [comment]
I think it was fixed in this commit https://github.com/ActivityWatch/aw-webui/commit/554d05ac4ed9cca968b74f979d3bbfedc49e69fa

Please test again once the next version is released.
