### ISSUE TITLE
Submit FUUG.fi grant application

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#343]
Long ago I started writing a grant application for https://fuug.fi, unfortunately work on it stalled, and I never submitted it.

Now since @xylix is working with us and actually lives in Finland it would make a lot of sense to complete the application and get the grant, so we can increase the rate of development and attract more users and contributors.

Related to #259.

**Comment by xylix** [comment]
@ErikBjare I updated the grant application with my information, and made some suggestion on updates.

**Comment by ErikBjare** [comment]
@xylix I assume this means you've sent it in? :)

**Comment by xylix** [comment]
Rough eta is 1-3 months. I only got an automated "Thanks for sending in your application, we go through them a few times per year so response times can be slow." response.
