### ISSUE TITLE
mongodb support for aw-server

### ISSUE THREAD

**Issue by Ishwaridutt** [ActivityWatch/activitywatch#349]
I tried running the activitywatch server in the ubuntu environment. Installed mongodb and pymongo but after changing the configuration to mongodb, serves throws a error.

## the bug
![Capture-activitywatch ](https://user-images.githubusercontent.com/28801698/74805864-7a02be80-530a-11ea-85be-09b15a6f5e8b.PNG)

## To Reproduce
1. download activitywatch for linux from https://github.com/ActivityWatch/activitywatch/releases
2. change the storage configuration to mongodb in ~/.config/activitywatch/aw-server/aw-server.ini
2. go to the aw-server directory inside activitywatch
3. execute aw-server executable file. ' ./aw-server '

## Environment
 - ActivityWatch version: [e.g. v0.8.4]
 - OS: [Linux (Ubuntu 16)]
 - mongodb: [ MongoDB shell version v4.2.3  
                      git version: 6874650b362138df74be53d366bbefc321ea32d4  
                      OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
                      allocator: tcmalloc
                      modules: none
                      build environment:
                          distmod: ubuntu1604
                          distarch: x86_64
                          target_arch: x86_64
                 ]

**Comment by ErikBjare** [comment]
Looks like the CI build doesn't install MongoDB.

This won't be fixed however, as we will drop support for MongoDB entirely in an upcoming version. Indeed the only version that will be supported is `sqlite` (the current default is `peewee`, and automatic migration will be performed only from it).

**Comment by Ishwaridutt** [comment]
Hello @ErikBjare ,
If you have any documentation for the source please share with me. Since we will be extending it, we will share the same with you.

**Comment by ErikBjare** [comment]
Instructions for installing from source can be found here: https://activitywatch.readthedocs.io/en/latest/installing-from-source.html

**Comment by ErikBjare** [comment]
As per my previous comment (https://github.com/ActivityWatch/activitywatch/issues/349#issuecomment-588091497), MongoDB support is being removed. Closing.
