### ISSUE TITLE
doubt about mongodb 

### ISSUE THREAD

**Issue by snwnst** [ActivityWatch/activitywatch#350]
good day. I would like to know if the information on each pc running activitywatch can be unified into a single database with mongodb. And if so, what is required?

**Comment by ErikBjare** [comment]
It can but it shouldn't. The MongoDB datastore is deprecated and will no longer be available once we've migrated to aw-server-rust.

If you want to have data from several devices on the same device, your options are:

   1. Do a manual export and import of all the buckets from one host to another.
   2. Wait for development on sync to complete (might take a while, but we're working on it).

If your use case involves not only several devices but several users then that's a different question entirely, so if I've misunderstood your use case please let me know.

**Comment by snwnst** [comment]
there are several users

**Comment by ErikBjare** [comment]
I don't think there is. If there are they are awfully quiet.

They can always use old versions or can contribute MongoDB support for
aw-server-rust themselves if they want to keep it that way going forward.

**Comment by johan-bjareholt** [comment]
@ErikBjare I think he meant that his use-case is that there's several users on one database?

**Comment by ErikBjare** [comment]
Oh, my bad.

@snwnst That's a use-case which ActivityWatch wasn't designed for and that we don't have any plans to support. The reason being that we are concerned about the privacy implications for our users. We don't want ActivityWatch to become a spying tool used by malicious actors or forced upon employees.

The feature suggested in #233 would enable much of the same functionality without actually sharing a database with all the sensitive data. If you have any comments or concerns about that approach, please leave them there.

Closing.
