### ISSUE TITLE
macOS - Quit doesn't work

### ISSUE THREAD

**Issue by rtpHarry** [ActivityWatch/activitywatch#359]
**For us to be able to understand the issue you're having you need to follow this template.** Please make sure there isn't already an issue for the bug you've found, otherwise it'll just take more resources, which means less time for us to actually fix bugs. Thanks for reporting!

## Describe the bug
Was just going to restart to test if it fixed #358 but the menu option doesn't seem to work:

![image](https://user-images.githubusercontent.com/1038062/75668572-6b54c980-5c71-11ea-9115-944b258d9e33.png)

## To Reproduce
1. Click AW icon in trat
1. Choose Quit
1. Nothing quits

## Environment
- ActivityWatch version:Version: v0.8.dev+c6433ea
 - OS: macOS Catalina

**Comment by ErikBjare** [comment]
Can you reproduce @xylix?

**Comment by xylix** [comment]
I did have this issue at some point but can't reproduce right now.

Sometimes the "Are you sure you want to quit? Yes | no" dialog hides behind other windows. @rtpHarry can you confirm this isn't the case by minimizing your other windows and then trying to quit?

**Comment by ErikBjare** [comment]
Maybe we should get rid of the confirmation dialog altogether?

**Comment by xylix** [comment]
Hm yes that is an option. I don't really find it too useful, since it's not too often I misclick the quit button.

**Comment by xylix** [comment]
I created a PR removing the dialog if we want to go through with it.

https://github.com/ActivityWatch/aw-qt/pull/54

Would probably also be useful to add some error handling, but I don't really know how the exit() function could detect if the process can't be killed. Any ideas?

**Comment by rtpHarry** [comment]
double checked and you are right, the confirmation dialog was getting caught behind.
