### ISSUE TITLE
Changing Class Name in Categorization Settings causes 'Property" name error and naming bug

### ISSUE THREAD

**Issue by abhirupdutta0** [ActivityWatch/activitywatch#362]
![Steps to Reproduce](https://user-images.githubusercontent.com/31652124/76158702-ba51a180-613e-11ea-8d2d-74fda53fd99e.gif)
[aw-server_2020-03-08T11-49-25.log](https://github.com/ActivityWatch/activitywatch/files/4302971/aw-server_2020-03-08T11-49-25.log)

**Comment by ErikBjare** [comment]
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/361
