### ISSUE TITLE
Release 0.9.0 tasks

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/activitywatch#364]
To-do:
- [x] bump aw-server / aw-server-rust version numbers
  - [x] merge aw-server-rust blinking test workaround https://github.com/ActivityWatch/aw-server-rust/pull/97
- [x] update all submodules to latest stable versions
- [x] main repo:  aw-qt, aw-server and aw-server-rust https://github.com/ActivityWatch/activitywatch/pull/365
   - [x] aw-webui in aw-server-rust https://github.com/ActivityWatch/aw-server-rust/pull/96
  - [x] review & merge ready PRs
- [x] test 0.9.0 on windows
- [x] ~~@ErikBjare new android release~~ (will not happen until after 0.9 release)
- [x] automate release notes (it's 2 git commands, instructions coming in at https://github.com/ActivityWatch/docs/pull/33 )
- [x] Test aw-server-rust on Windows and macOS? (https://github.com/ActivityWatch/activitywatch/issues/353)
- [ ] Publish developer update on the forum

**Comment by xylix** [comment]
@ErikBjare I used https://github.com/release-it/release-it to generate a changelog of my branch (with updated submodules). Sadly most automated changelog tools I could find can't understand submodules very well, so there is still some handwriting to be done. But I think this is much easier to work with than nothing.

Auto-generated changelog:
* Update submodules (depends on aw-server-rust submodule update) (c4b0be1)
* Merge pull request #356 from ActivityWatch/dev/less-breaking-travis-improvements (4d8dfc5)
* Update submodule aw-server-rust (0a62d83)
* Merge pull request #354 from ActivityWatch/dev/aw-server-rust-app (b1e9ead)
* Add caching Fix travis warnings (9109c63)
* Add aw-server-rust binary to pyinstaller bundles (a567003)
* Merge pull request #347 from ActivityWatch/dev/flask-restx (d709526)
* updated aw-server submodule (fefb479)
* migrated to flask-restx, updated submodules (e2d57b7)
* Update stale.yml (dc89d60)
* Create stale.yml (d73b97b)
* Merge pull request #331 from ActivityWatch/dev/aw-server-rust (6762125)
* Update aw-qt submodule (2ca1e6e)
* updated aw-server-rust (865b7e4)
* correctly placed aw-server-rust module in subdirectory, updated aw-server-rust submodule to correctly name executable as aw-server-rust (50346bd)
* readded aw-server-python (cbdc3b4)
* Replace aw-server with aw-server-rust (2ddeef5)
* aw-watcher-window: Update submodule (5bfdb3d)
* Merge pull request #336 from ActivityWatch/dev/macos-app (f8cb9fd)
* removed unused requirements.txt (c123849)
* fixed .dmg building in CI (d189007)
* Fix wrong filename in merged aw.spec (d5495a4)
* Merge branch 'dev/macos-app' of https://github.com/ActivityWatch/activitywatch (90183cd)
* Merge https://github.com/ActivityWatch/activitywatch (e23d750)
* Add dmg building (3657247)
* Add version info to aw.spec, update dev version of pyinstaller (eca1c03)
* fixed building .app, tried fixing error in Ubuntu CI: 'libQt5Xml.so.5: cannot open shared object file' (5e4de1e)
* fixed icon and version for .app, added .app building to CI (0bbddfb)
* Merge branch 'master' of https://github.com/xylix/activitywatch into xylix-macos-app (3d01b39)
* updated submodule (3eb6349)
* updated submodules (90ec663)
* Working .app package require version 4.0 of pyinstaller for building mega-bundle (3c19049)
* Start building mega spec (1c68175)
* updated submodule (f0bfde4)
* updated submodules (9f3b91e)
* updated submodules with poetry/pyproject.toml changes (609429a)

**Comment by ErikBjare** [comment]
Nice! I guess we'll have to run release-it on submodules too to get a complete changelog.

**Comment by xylix** [comment]
Hmm yeah. Release-it compares to the latest tag to see what changes are new, so automating submodule's without writing additional logic to figure out new releases would mean also tagging points in the submodules (probably just tag releases in submodules in sync with the main repo). I guess that wouldn't cause any harm?

It's also possible to CI-automate the tagging and notes, I just wanted to do it manually the first time to see how it works.

**Comment by xylix** [comment]
Release-it logs for submodules:

aw-client:
Changelog:
* changed Makefile use of pip to pip3 (6846551)
* fixed version in pyproject.toml (2e11d4b)
* updated poetry.lock (f084ae2)
* fixed make build DEV=true (79b5a9f)
* Merge pull request #48 from ActivityWatch/dev/poetry (83db6bc)
* switched to using pyproject/poetry (d66f319)
* Merge pull request #47 from JustinDDavis/232-event-limit-default-change (b7e0cd4)
* Change default limit from 100 to return all by default (d35449a)

aw-core:
Changelog:
* changed Makefile use of pip to pip3 (f43bbf4)
* fixed make build DEV=true (4f4b4b2)
* moved from Pipfile/setup.py/pipenv to pyproject.toml/poetry (#85) (c7d74e7)
* added strict-rfc3339 (c5e9d34)
* added type ignore (f3e5c3b)
* upgraded jsonschema (a803443)
* moved from Pipfile/setup.py/pipenv to pyproject.toml/poetry (e751355)

aw-qt
Changelog:
* Merge pull request #55 from xylix/dev/improved-exit-handling (481ace6)
* Instead of calling exit() on Gui button binding actually bind a lambda to the functions (bd20f05)
* Remove unnecessary exit_dialog() function (e61ece5)
* Use manager to stop all modules (ac40452)
* Remove confirm dialog (246ff05)
* Merge pull request #53 from ActivityWatch/dev/windows-regex-fix (8b03043)
* Makefile: Replace perl regex with grep (9d77022)
* Merge branch 'master' of github.com:ActivityWatch/aw-qt (97086cc)
* changed logging level for message (bb128ee)
* Remove startup notification (#45) (b1f66c3)
* switched to using pyproject/poetry (#51) (ecc7e0d)
* changed regex replace command to be compatible with macOS (649344b)
* another needed travis fix for xvfb in xenial (9edb3dd)
* workaround for xcb issue (74a3859)
* added workaround for poetry include issue (68ba08c)
* added resources.py to poetry include (0ef8e66)
* added aw-server-rust to possible modules (b4e9411)
* updated media submodule (a22fd41)
* Merge branch 'master' into dev/poetry (a4a50f7)
* added poetry install to install dev dependencies (faf4ffd)
* fixed Makefile and travis config (90f1d81)
* Merge pull request #52 from xylix/monochrome-logos (bc19dff)
* Add dark mode detection to MacOS logo logic (502b77d)
* Use monochrome-black trayicon on MacOS (901e16d)
* updated Makefile to not need poetry for building (565892a)
* fixed make build DEV=true (72d8056)
* switched to using pyproject/poetry (7e531dc)
* Remove startup notification (836d434)

aw-server
Changelog:
* Merge pull request #65 from xylix/dev/stop-removing-node-modules (af1f5c0)
* Remove node-modules rm which shouldn't be necessary after https://github.com/ActivityWatch/activitywatch/pull/300 (037ae0a)
* kept werkzeug version at <1.0 to prevent bug: https://github.com/ActivityWatch/activitywatch/issues/346 (c085217)
* Merge pull request #63 from ActivityWatch/dev/flask-restx (4a6624d)
* migrated from flask-restplus to flask-restx, updated submodule (36e970e)
* changed Makefile use of pip to pip3 (47a208b)
* updated poetry.lock (c2fdfe1)
* fixed make build DEV=true (817723b)
* Merge pull request #62 from ActivityWatch/dev/poetry (e509f52)
* added aw-server script to pyproject.toml (3e7b707)
* switched to pyproject.toml/poetry (f28cff0)

aw-server-rust:
* Added in 0.8.5

aw-watcher-afk
Changelog:
* switched to using pyproject.toml/poetry (#38) (75b0d38)
* switched to using pyproject.toml/poetry (d30ef25)

aw-watcher-window
Changelog:
* readded script that disappeared in previous PR (1e424e4)
* switched to using pyproject/poetry (#39) (a5758bb)
* fixed typing (92d3fde)
* switched to using pyproject/poetry (a63e133)
* Merge pull request #37 from cunidev/master (d3360ad)
* remove print statement (ad87b0f)
* revise exclude_title logic (b1bd00d)
* Set exclude_title to false by default (6867378)
* Update config.py (75cd8dc)
* Update main.py (ba762b1)

aw-webui:
Changelog:
* buckets: Fix broken export bucket button (0a60cf7)
* Merge pull request #171 from xylix/update-vis-timeline (4449d30)
* Swtich from timeline-plus to vis-timeline (98cd372)
* Merge pull request #169 from riscie/master (d0b01ba)
* added setting for 'show last' duration default value (20ca6fa)
* Merge pull request #168 from ActivityWatch/dev/query-explorer-no-single-quotes (af8042b)
* QueryExplorer: Replace single quotes with double quotes (b3d29e2)
* Improvements to Stopwatch and EventEditor (#166) (2040a92)
* fixed long lines (c502787)
* fixed bugs in event editor and stopwatch (d121fcb)
* fixed editing events in bucket view (b6c1405)
* added ability to edit start and end in EventEditor, added ability to edit events from Bucket view (10dc80f)
* Update aw-client-js (25e4cbe)
* Merge pull request #165 from ActivityWatch/dev/stopwatch-fix (8009221)
* stopwatch: Fixes broken "stop" and "edit" (06be96b)
* Merge pull request #164 from ActivityWatch/dev/vulnerability-fixes (e6dcb4f)
* package.json: Update to fix vulnerabilities (a2f48a8)
* queries: Removed trailing lines (d25cf09)
* Merge pull request #163 from chrsep/master (7c48c9f)
* Fix firefox developer edition browser data not showing up in activity view. (4a05131)
* Merge pull request #160 from ActivityWatch/dev/editor-activity-fix (112c2bc)
* views/activity: Fix so subview is kept between date changes (c0ae191)
* Add vuex support for editor activity (47fed8b)


Even without making aw-server-rust the default here this is starting to look much more like an 0.1 bump than an 0.0.1 bump to me. This is a lot of changes. (Altough many of the commits can be cleaned up from the final release notes). Also currently I tagged only my local copies but I can go and add the version tags to the submodules as well

**Comment by johan-bjareholt** [comment]
Go ahead and call it 0.9, there's a lot of changes indeed.
