### ISSUE TITLE
Create a feature comparison matrix

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#37]
We should compare ActivityWatch to: RescueTime, arbtt, selfspy, ...

Features to compare:
 - [x] User owns the data
 - [x] Platforms supported
 - [x] Sync
 - [x] Open Source
 - [x] Browser plugin/URL logging
 - [x] Available watchers (active window, afk, browser, editor)
 - [x] ~~More?~~

**Comment by ErikBjare** [comment]
Closed in https://github.com/ActivityWatch/activitywatch/pull/34/commits/81ef797786ecbf8d036ec2328ff46065a4a73ac2

**Comment by karlicoss** [comment]
Would be cool to add arbtt to the comparison :)
