### ISSUE TITLE
Improvements to changelog

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#377]
Just a few things I thought about which would improve the changelog and its generation.

 - [x] Generate it in markdown format, with subheaders + links to repo for submodules. (fixed in https://github.com/ActivityWatch/activitywatch/pull/381/)
 - [x] Assign commits to issues/PRs, and include correct links to them. Right now GitHub assumes PRs/issues in subrepos are in the main repo, leading to it generating bad links. (fixed in https://github.com/ActivityWatch/activitywatch/pull/381/)
 - [x] With the guideline changes in #391 we should additionally group changes by type (feat, fix, docs, etc.) to make it easy to read at a glance. (fixed in https://github.com/ActivityWatch/activitywatch/pull/505)
 - [x] ~~Make the changelog page in the docs include a md file with the actual changelog, so we don't need to maintain it in two markup languages.~~ Will have to go with future improvements.

**Comment by xylix** [comment]
Seems good to me. I'll look into this.

**Comment by ErikBjare** [comment]
I started looking into this, began writing a python script that generates it nicely. Here's what I have so far: 

```python
```

I also updated the changelog for the v0.9 release to make it look a bit more like what I had in mind.

**Comment by ErikBjare** [comment]
Updated it a bit (will update the script I created above).

Here's an example output:

### activitywatch (bundle repo)
 - (tag: v0.9.0, origin/master, master) Merge pull request [#375](https://github.com/ActivityWatch/activitywatch/issues/375) from xylix/dev/fix-.dmg-naming ([`bdf4fa1`](https://github.com/ActivityWatch/activitywatch/commit/bdf4fa1))
 - Add platform and arch info to .dmg ([`3525d0b`](https://github.com/ActivityWatch/activitywatch/commit/3525d0b))
 - [travis] switched back to skip_cleanup ([`55c4c90`](https://github.com/ActivityWatch/activitywatch/commit/55c4c90))
 - Merge pull request [#371](https://github.com/ActivityWatch/activitywatch/issues/371) from xylix/dev/use-new-travis-cleanup ([`bf789e5`](https://github.com/ActivityWatch/activitywatch/commit/bf789e5))
 - Merge pull request [#373](https://github.com/ActivityWatch/activitywatch/issues/373) from xylix/dev/release-note-script ([`0ae4632`](https://github.com/ActivityWatch/activitywatch/commit/0ae4632))
 - Add release note script to main repo ([`198bfa1`](https://github.com/ActivityWatch/activitywatch/commit/198bfa1))
 - Actually use travi's new cleanup boolean ([`54178f2`](https://github.com/ActivityWatch/activitywatch/commit/54178f2))
 - Merge pull request [#369](https://github.com/ActivityWatch/activitywatch/issues/369) from xylix/submodule-update-fixedt-test ([`51a484a`](https://github.com/ActivityWatch/activitywatch/commit/51a484a))
 - Add node_modules fix in appveyor back to aw-server, update version number in aw.spec ([`a6bf09b`](https://github.com/ActivityWatch/activitywatch/commit/a6bf09b))
 - Merge pull request [#365](https://github.com/ActivityWatch/activitywatch/issues/365) from xylix/master ([`cd75c71`](https://github.com/ActivityWatch/activitywatch/commit/cd75c71))
 - Update submodules (depends on aw-server-rust submodule update) ([`c4b0be1`](https://github.com/ActivityWatch/activitywatch/commit/c4b0be1))
 - Merge pull request [#356](https://github.com/ActivityWatch/activitywatch/issues/356) from ActivityWatch/dev/less-breaking-travis-improvements ([`4d8dfc5`](https://github.com/ActivityWatch/activitywatch/commit/4d8dfc5))
 - Update submodule aw-server-rust ([`0a62d83`](https://github.com/ActivityWatch/activitywatch/commit/0a62d83))
 - Merge pull request [#354](https://github.com/ActivityWatch/activitywatch/issues/354) from ActivityWatch/dev/aw-server-rust-app ([`b1e9ead`](https://github.com/ActivityWatch/activitywatch/commit/b1e9ead))
 - Add caching Fix travis warnings ([`9109c63`](https://github.com/ActivityWatch/activitywatch/commit/9109c63))
 - Add aw-server-rust binary to pyinstaller bundles ([`a567003`](https://github.com/ActivityWatch/activitywatch/commit/a567003))
 - Merge pull request [#347](https://github.com/ActivityWatch/activitywatch/issues/347) from ActivityWatch/dev/flask-restx ([`d709526`](https://github.com/ActivityWatch/activitywatch/commit/d709526))
 - (origin/dev/flask-restx, dev/flask-restx) updated aw-server submodule ([`fefb479`](https://github.com/ActivityWatch/activitywatch/commit/fefb479))
 - migrated to flask-restx, updated submodules ([`e2d57b7`](https://github.com/ActivityWatch/activitywatch/commit/e2d57b7))
 - Update stale.yml ([`dc89d60`](https://github.com/ActivityWatch/activitywatch/commit/dc89d60))
 - Create stale.yml ([`d73b97b`](https://github.com/ActivityWatch/activitywatch/commit/d73b97b))
 - Merge pull request [#331](https://github.com/ActivityWatch/activitywatch/issues/331) from ActivityWatch/dev/aw-server-rust ([`6762125`](https://github.com/ActivityWatch/activitywatch/commit/6762125))
 - (origin/dev/aw-server-rust) Update aw-qt submodule ([`2ca1e6e`](https://github.com/ActivityWatch/activitywatch/commit/2ca1e6e))
 - updated aw-server-rust ([`865b7e4`](https://github.com/ActivityWatch/activitywatch/commit/865b7e4))
 - correctly placed aw-server-rust module in subdirectory, updated aw-server-rust submodule to correctly name executable as aw-server-rust ([`50346bd`](https://github.com/ActivityWatch/activitywatch/commit/50346bd))
 - readded aw-server-python ([`cbdc3b4`](https://github.com/ActivityWatch/activitywatch/commit/cbdc3b4))
 - Replace aw-server with aw-server-rust ([`2ddeef5`](https://github.com/ActivityWatch/activitywatch/commit/2ddeef5))
 - aw-watcher-window: Update submodule ([`5bfdb3d`](https://github.com/ActivityWatch/activitywatch/commit/5bfdb3d))
 - Merge pull request [#336](https://github.com/ActivityWatch/activitywatch/issues/336) from ActivityWatch/dev/macos-app ([`f8cb9fd`](https://github.com/ActivityWatch/activitywatch/commit/f8cb9fd))
 - removed unused requirements.txt ([`c123849`](https://github.com/ActivityWatch/activitywatch/commit/c123849))
 - fixed .dmg building in CI ([`d189007`](https://github.com/ActivityWatch/activitywatch/commit/d189007))
 - Fix wrong filename in merged aw.spec ([`d5495a4`](https://github.com/ActivityWatch/activitywatch/commit/d5495a4))
 - Merge branch 'dev/macos-app' of https://github.com/ActivityWatch/activitywatch ([`90183cd`](https://github.com/ActivityWatch/activitywatch/commit/90183cd))
 - Merge https://github.com/ActivityWatch/activitywatch ([`e23d750`](https://github.com/ActivityWatch/activitywatch/commit/e23d750))
 - Add dmg building ([`3657247`](https://github.com/ActivityWatch/activitywatch/commit/3657247))
 - Add version info to aw.spec, update dev version of pyinstaller ([`eca1c03`](https://github.com/ActivityWatch/activitywatch/commit/eca1c03))
 - fixed building .app, tried fixing error in Ubuntu CI: 'libQt5Xml.so.5: cannot open shared object file' ([`5e4de1e`](https://github.com/ActivityWatch/activitywatch/commit/5e4de1e))
 - (origin/xylix-macos-app-2) fixed icon and version for .app, added .app building to CI ([`0bbddfb`](https://github.com/ActivityWatch/activitywatch/commit/0bbddfb))
 - Merge branch 'master' of https://github.com/xylix/activitywatch into xylix-macos-app ([`3d01b39`](https://github.com/ActivityWatch/activitywatch/commit/3d01b39))
 - updated submodule ([`3eb6349`](https://github.com/ActivityWatch/activitywatch/commit/3eb6349))
 - updated submodules ([`90ec663`](https://github.com/ActivityWatch/activitywatch/commit/90ec663))
 - Working .app package require version 4.0 of pyinstaller for building mega-bundle ([`3c19049`](https://github.com/ActivityWatch/activitywatch/commit/3c19049))
 - Start building mega spec ([`1c68175`](https://github.com/ActivityWatch/activitywatch/commit/1c68175))
 - updated submodule ([`f0bfde4`](https://github.com/ActivityWatch/activitywatch/commit/f0bfde4))
 - updated submodules ([`9f3b91e`](https://github.com/ActivityWatch/activitywatch/commit/9f3b91e))
 - updated submodules with poetry/pyproject.toml changes ([`609429a`](https://github.com/ActivityWatch/activitywatch/commit/609429a))

### aw-client a8c9fd7...9e4cdb5
 - switched to only using poetry install in Makefile
 - changed Makefile use of pip to pip3
 - fixed version in pyproject.toml
 - updated poetry.lock
 - fixed make build DEV=true
 - Merge pull request [#48](https://github.com/ActivityWatch/aw-client/issues/48) from ActivityWatch/dev/poetry
 - Merge pull request [#47](https://github.com/ActivityWatch/aw-client/issues/47) from JustinDDavis/232-event-limit-default-change

### aw-core f6bcbd9...a62a299
 - switched to only using poetry install in Makefile
 - changed Makefile use of pip to pip3
 - fixed make build DEV=true
 - moved from Pipfile/setup.py/pipenv to pyproject.toml/poetry ([#85](https://github.com/ActivityWatch/aw-core/issues/85))

### aw-qt 3f8d416...3de8095
 - switched to only using poetry install in Makefile
 - Merge pull request [#55](https://github.com/ActivityWatch/aw-qt/issues/55) from xylix/dev/improved-exit-handling
 - Merge pull request [#53](https://github.com/ActivityWatch/aw-qt/issues/53) from ActivityWatch/dev/windows-regex-fix
 - Merge branch 'master' of github.com:ActivityWatch/aw-qt
 - changed logging level for message
 - switched to using pyproject/poetry ([#51](https://github.com/ActivityWatch/aw-qt/issues/51))
 - Merge pull request [#52](https://github.com/ActivityWatch/aw-qt/issues/52) from xylix/monochrome-logos

### aw-server f95ec5e...908e0e3
 - switched to only using poetry install in Makefile
 - Merge pull request [#67](https://github.com/ActivityWatch/aw-server/issues/67) from xylix/dev/add-back-rm-node-modules
 - Merge pull request [#65](https://github.com/ActivityWatch/aw-server/issues/65) from xylix/dev/stop-removing-node-modules
 - kept werkzeug version at <1.0 to prevent bug: https://github.com/ActivityWatch/activitywatch/issues/346
 - Merge pull request [#63](https://github.com/ActivityWatch/aw-server/issues/63) from ActivityWatch/dev/flask-restx
 - changed Makefile use of pip to pip3
 - updated poetry.lock
 - fixed make build DEV=true
 - Merge pull request [#62](https://github.com/ActivityWatch/aw-server/issues/62) from ActivityWatch/dev/poetry

### aw-server-rust 0000000...d91a4a6
 - aw-transform: Fix clippy warnings

### aw-watcher-afk 55528c3...4d357eb
 - added installation of pyinstaller to before_install
 - switched to only using poetry install in Makefile
 - switched to using pyproject.toml/poetry ([#38](https://github.com/ActivityWatch/aw-watcher-afk/issues/38))

### aw-watcher-window 0c14d77...751e682
 - added installation of pyinstaller to before_install
 - switched to only using poetry install in Makefile
 - readded script that disappeared in previous PR
 - switched to using pyproject/poetry ([#39](https://github.com/ActivityWatch/aw-watcher-window/issues/39))
 - Merge pull request [#37](https://github.com/ActivityWatch/aw-watcher-window/issues/37) from cunidev/master

**Comment by ErikBjare** [comment]
What's notably missing there are commit hashes for submodules. I'll see if I can fix that somehow.

**Comment by tulir** [comment]
Would something like [towncrier](https://github.com/twisted/towncrier) be an acceptable solution? It requires a bit more work when making pull requests (creating the newsfiles), but changelogs should be better when they're compiled from newsfiles written with changelogs in mind rather than from commit messages (which often contain more technical details).

**Comment by ErikBjare** [comment]
Using towncrier would be in addition the changes this issue is about, not really a substitute. 

I've looked into it in the past but I'm not so sure it's a great fit with git submodules, and I'd also rather not introduce additional requirements for contributors who submit PRs.

**Comment by ErikBjare** [comment]
Just pushed something that could become final in https://github.com/ActivityWatch/activitywatch/pull/505

**Comment by ErikBjare** [comment]
Closing since #505 was merged.
