### ISSUE TITLE
Should we store all datetimes in UTC? 

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#39]
Found this article, I think it makes a convincing argument with the DST madness. The issues with Python aware vs naive datetime I (hope) think is a non-issue for us right now. But the DST thing annoys me a bit. 

Link: http://lucumr.pocoo.org/2011/7/15/eppur-si-muove/

**Comment by johan-bjareholt** [comment]
I read through the article and found this

> One gives the time in UTC, the other in local time. However it will not tell you what local time is (because it does not have a timezone information object, at least before 3.3), and it does not give you way to know which one was UTC.


Went to the python docs and then found this

> Changed in version 3.3: Equality comparisons between naive and aware datetime instances don’t raise TypeError.

So according to the articles conclusion, as long as we continue and don't forget to set it to UTC everywhere we will hopefully be fine.

**Comment by ErikBjare** [comment]
Yeah it's really not the aware vs naive thing that I'm afraid of as that has been fixed in Python as you've discovered.

I'm more concerned about changes to and from DST.

**Comment by ErikBjare** [comment]
I'm closing this for now, doesn't seem like we will be doing this until we get a better argument in favor of it.

**Comment by ErikBjare** [comment]
We ended up doing this. Now looking to add timezones as a separate field in the database representation of the event model: https://github.com/ActivityWatch/activitywatch/issues/109
