### ISSUE TITLE
Modification in timeline view

### ISSUE THREAD

**Issue by Nabraz** [ActivityWatch/activitywatch#390]
can you make timeline in vertical mode. like this 

![Screenshot (1)](https://user-images.githubusercontent.com/62595862/77417384-61943100-6ded-11ea-8caf-b52ccfefd476.png)

**Comment by ErikBjare** [comment]
We've been talking about implementing a calendar-like timeline view before, which should be pretty similar in practice: https://github.com/ActivityWatch/aw-webui/issues/16

Would that be a good alternative to the feature that you're requesting?
