### ISSUE TITLE
Improve commit messages

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#391]
Since we've started auto-generating changelogs I started looking into how other projects do it and many do so by enforcing a standard format for commit messages. 

One prominent standard is [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). A few examples:

```
fix: fixed bug #X
docs: updated README
ci: added platform to CI
```

Types I propose we use are: `fix`, `feat`, `build`, `chore`, `ci`, `docs`, `style`, `refactor`, `perf`, `test`

It's important that we strike a good balance. We don't want to discourage new contributors by being nitpicky. Worst case we can always clean up the changelog manually, but having at least most commit follow the convention would make things easier.

 - [x] Update CONTRIBUTING.md with guidelines

Related to #377

Thoughts @johan-bjareholt, @xylix?

**Comment by xylix** [comment]
I'm unsure about some of the proposed types though. Most style and perf changes could go under fix/feat/refactor so they overlap quite a bit.

Otherwise looks good to me.

**Comment by ErikBjare** [comment]
I took the types from https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

> - perf: A code change that improves performance
> - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)

**Comment by johan-bjareholt** [comment]
Such a rule sounds a bit too strict in my opinion.
I love clear commit messages, but as long as each commit title is descriptive and it's clear what part of the code it impacts I think this is an non-issue.
We should instead just have a guideline of making clear commit messages and tell people to squash their commits if some of them are a fix/typo/refactoring in code which is not even merged yet.

**Comment by ErikBjare** [comment]
As I said, I'm not enforcing any strictness, just a guideline. Prefixing commits with a type helps loads with autogenerating the changelog, and going through the commit history in general.

>...and tell people to squash their commits if some of them are a fix/typo/refactoring in code which is not even merged yet, that's what I find our current issues with our commit messages are.

Agreed, I've been better at doing this myself recently, which is partly what led me to also want this.

**Comment by xylix** [comment]
Hm yeah being able to drop most `refactor`, `ci` and `chore` commits from the changelog automatically would make generating changelogs much nicer, so I think I agree with adding this to the guidelines and will try to follow it in the future.

**Comment by ErikBjare** [comment]
@xylix Added grouping of changelog entries by type as a subtask in #377.

Submitted a PR in #415
