### ISSUE TITLE
Autostart setup on Windows starts several instances of aw-qt

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#392]
Some action on Windows (wake from suspend? automatic restore of running apps after restart?) leads to multiple instances of aw-qt being started (over time).

It would be interesting to see what causes this and if it can be avoided, maybe simply make aw-qt check that it isn't already running on start.

**Comment by xylix** [comment]
I haven't had this happen on my windows box, but seems annoying enough to fix. 

If it's happening on wake from suspend are we hooking to the correct autostart event on windows? What autostart are we using to start aw-qt on system boot?

**Comment by ErikBjare** [comment]
@xylix Do you use the installer on your Windows box? I think it sets up autostart by putting a shortcut to the executable in the autostart folder.

I've seen it happen both on a friend's computer and on my Shadow instance. I basically haven't seen a machine where it doesn't happen, so if it doesn't happen for you it'd be interesting as to why not.

**Comment by xylix** [comment]
Right now I don't have access to my windows box for a week or so, so I can't access logs etc :/.

But I've always installed aw-qt on windows with the installer. I might've been able to avoid this issue by frequently hard shutdowning my windows with no automatic application restart, if this is related to extra aw-qt's starting when restoring apps. 

I do use suspend quite normally though and haven't seen multiple aw-qt instances related to that.

**Comment by ErikBjare** [comment]
I think it only happens when Windows restarts with auto-resume (not
suspend) which happens with Windows updates, for example. But I'm not sure.

Weirdly enough I don't get any aw-server crashes from the port being in
use, which I would expect from running two aw-qt instances (definitely
happens on Linux).

**Comment by xylix** [comment]
I'll keep an eye on my aw-qt instances when I get on my windows box again. 

With multiple aw-qt's on windows, are the server's being allocated separate ports or are they just silently starting without a free port / on the same port?

**Comment by ErikBjare** [comment]
I'm closing this since I haven't been able to reproduce or seen it elsewhere and it in at least one instance seems to have been my own fault.
