### ISSUE TITLE
Import button should be inactive until no file is selected

### ISSUE THREAD

**Issue by Rakleed** [ActivityWatch/activitywatch#395]
**Is your feature request related to a problem? Please describe.**
If user clicks Import while no file is selected, the error `{"message": "Internal Server Error"}` will appear on a new page.

**Describe the solution you'd like**
Until a file was selected, the Import button was inactive (user could not click on it).

**Describe alternatives you've considered**
When user clicked on the Import button when a file was not selected, a new page did not load, and next to the Import button an inscription appeared that user first needs to select a file.

**Additional context**
I mean the Import button on the Raw Data tab.

**Comment by johan-bjareholt** [comment]
I redesigned the import field about a month ago where this is fixed so this will be available in next release. Closing.
