### ISSUE TITLE
Rust Server Requires GLIBC_2.8

### ISSUE THREAD

**Issue by the-architech** [ActivityWatch/activitywatch#396]
Hey guys, when running the aw-server-rust on CentOS 7 I get the following error:

```
./aw-server-rust
./aw-server-rust: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./aw-server-rust)
```

I built the packages in CentOS  8 Docker container and it worked just fine. As far as I know upgrading GLIBC to 2.18 on CentOS 7 at the moment is not possible.

Are there any plans to support CentOS 7 on rust server?

**Comment by ErikBjare** [comment]
Since CentOS 7 was released in 2014 and has it's "full updates" EOL in just a few months (2020-08-06) we will probably not make this a priority in time. 

Doesn't it work if you also build it in a CentOS 7 environment?

**Comment by johan-bjareholt** [comment]
I'll close this, please re-open if you have any further questions.
