### ISSUE TITLE
Take and upload new screenshots

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#397]
All screenshots we have are old and lack categorization (which I know is a highly desirable feature which catches people's attention).

Since this type of issue is a chore destined to happen again every now and then, I've been working on automatic screenshots in CI (including demo data) here: https://github.com/ActivityWatch/aw-webui/pull/179

See this previous issue for a checklist: https://github.com/ActivityWatch/activitywatch/issues/122

**Comment by johan-bjareholt** [comment]
This is fixed in the PR referenced above, closing

**Comment by ErikBjare** [comment]
@johan-bjareholt Not really. The screenshots are taken but not uploaded (the ones we currently have on the website are from v0.8.0b9 or something). 

I've been working on updating them but stumbled into an issue with the png is somehow getting mangled by jekyll or jekyll-bliss (to the point where only half was shown in my browser, and `feh` refusing to open it).

**Comment by ErikBjare** [comment]
Now it's fixed. Worked around the issue by reducing the image to 8-bit/256 colors which didn't really impact the image quality.
