### ISSUE TITLE
cannot track browser history from Microsoft Edge?

### ISSUE THREAD

**Issue by weeshinwang** [ActivityWatch/activitywatch#399]
I have installed the extension from Chromeweb on Microsoft Edge, after using some while, 'Top Browser Domains' section doesn't show any data. 
But there is a bucket exists named 'aw-watcher-web-edge' and I can see the history in 'Timeline' section. 

Debug info:
Number of active tabs: 1
Tabs:
{
    "active": true,
    "audible": false,
    "autoDiscardable": true,
    "discarded": false,
    "favIconUrl": "https://github.githubassets.com/favicons/favicon.svg",
    "height": 1006,
    "highlighted": true,
    "id": 2,
    "incognito": false,
    "index": 0,
    "mutedInfo": {
        "muted": false
    },
    "pinned": false,
    "selected": true,
    "status": "complete",
    "title": "New Issue · ActivityWatch/activitywatch",
    "url": "https://github.com/ActivityWatch/activitywatch/issues/new",
    "width": 2048,
    "windowId": 1
}

**Comment by ErikBjare** [comment]
This should be easy to fix for the next release. 

Could you tell us the value of the  `app` property for Edge (in the window watcher bucket)?

**Comment by weeshinwang** [comment]
@ErikBjare Thanks for the response! 
I actually don't understand the 'app property' you mentioned. 
Do you mean the **Hostname** or such thing. I have a screenshot attached.
![image](https://user-images.githubusercontent.com/14191453/78273152-04ad1f00-7541-11ea-952b-d5fe29f4c9c2.png)

**Comment by ErikBjare** [comment]
Ah sorry, should have been more clear!

Open the aw-watcher-window bucket (that's in the screenshot) and find a entry for Edge and provide the `app` value for that entry. We need that to attribute the web watcher events to your browser window :)

**Comment by weeshinwang** [comment]
@ErikBjare 
it is `"app": "msedge.exe"` :)

**Comment by ErikBjare** [comment]
Should be fixed in https://github.com/ActivityWatch/activitywatch/issues/399, which will be available in the next release.

**Comment by weeshinwang** [comment]
@ErikBjare  Thanks for the fix!
