### ISSUE TITLE
Buckets should store hostname of client as metadata

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#4]
Such that "afk" becomes "afk@erb-main2-arch". This way we avoid collisions when several clients share a datastore.

**Comment by ErikBjare** [comment]
We might want to store metadata for buckets instead, this way we can keep additional information about them without cluttering the name with symbols. Might not be as visible though...

**Comment by johan-bjareholt** [comment]
Fixed in create-bucket pullrequest in aw-core and aw-server and the new api is fixed in aw-watcher-afk and aw-watcher-x11
