### ISSUE TITLE
Documentation tweak suggestion: AFK explanation

### ISSUE THREAD

**Issue by gwynevans** [ActivityWatch/activitywatch#400]
It's a minor issue once you know, but it turns out that there doesn't appear to be any explanation of what "AFK" is/means in the project - even the README for `aw-watcher-afk` just says:

> Watches keyboard and mouse activity to determine if you are AFK or not (for use with ActivityWatch)

I actually found the definition in a cached Google-search, from where it used to be in the documentation but had been removed...

(For anyone searching: AFK = "away from keyboard" - yes, obvious in hindsight, but not before.)

**Comment by ErikBjare** [comment]
Could you please contribute a fix for your suggestion? I agree with you, but unless you do it it's unlikely to get done :)

**Comment by ErikBjare** [comment]
Closed in #401
