### ISSUE TITLE
Unable to run aw-client/afk/window on Windows 

### ISSUE THREAD

**Issue by rathishkumar** [ActivityWatch/activitywatch#402]
![image](https://user-images.githubusercontent.com/3918929/78240284-6a2aec80-74fc-11ea-9f0e-e59e8b00942b.png)

Unable to run the aw-client, aw-watcher-afk & aw-watcher-window after installing

## To Reproduce
1. python3 -m venv venv
2. source ./venv/Scripts/activate
3. make --directory=aw-client build
4. make --directory=aw-watcher-afk
5. make --directory=aw-watcher-window
6. aw-client

## Documentation
![image](https://user-images.githubusercontent.com/3918929/78241193-a6128180-74fd-11ea-95c5-74546212d60d.png)

## Environment
ActivityWatch version: latest
OS: Windows 10

## Additional context
I am trying to install client, afk, and windows watchers on this machine and server on other machine.

**Comment by johan-bjareholt** [comment]
Something seems to be broken with your aw-client install it seems, I have no idea what though as I can't reproduce.

I would look into what version of persistqueue is being used and maybe use python to debug it after import.

    import persisqeueue
    dir(persistqueue)

**Comment by rathishkumar** [comment]
@johan-bjareholt 

The required info below:

![image](https://user-images.githubusercontent.com/3918929/78528872-0ce5b280-77fe-11ea-88b1-166c32dcd795.png)

**Comment by ErikBjare** [comment]
Looks like you should take care of that warning you get first of all...

I have no idea what else could be wrong. Try:

```
import persistqueue
print(persistqueue.__version__)
from persistqueue import FIFOSQLiteQueue
```

**Comment by rathishkumar** [comment]
@ErikBjare The error is with python 3.7.4, now I recreating a virtualenv with Python 3.6. I will check and update. Thank you.

**Comment by ErikBjare** [comment]
The Python version is unlikely to be the issue.

**Comment by rathishkumar** [comment]
@ErikBjare While I am installing aw-cient with Python 3.7 getting error installing Pyhook, and I tried installing with whl file downloaded from internet.

When I tried again, it is fetching whl file from github and failed again stating 36 not supported on 37. So I have installed python 3.6 and checking now.

**Comment by rathishkumar** [comment]
@ErikBjare 

I am able to start the aw-watcher-window and it is successfully connected to the server running on other machine.

But I could not see any data on server page. Could you please help me understand, Do I need to start aw-client to send data or only watcher & afk will send data to server.

![image](https://user-images.githubusercontent.com/3918929/78538302-66ee7400-780e-11ea-84c3-43fe06643469.png)

I have installed Windows executable earlier, and it created client folder with configuration file, I thing it is able to connect to server there. But in a new setup, Do I need to install and start Client?

**Comment by ErikBjare** [comment]
>While I am installing aw-cient with Python 3.7 getting error installing Pyhook, and I tried installing with whl file downloaded from internet. When I tried again, it is fetching whl file from github and failed again stating 36 not supported on 37. So I have installed python 3.6 and checking now.

Oh, yeah sorry about that. Pyhook is actually not even needed anymore, I've made a PR that removes it for aw-watcher-afk: https://github.com/ActivityWatch/aw-watcher-afk/pull/39

>I have installed Windows executable earlier, and it created client folder with configuration file, I thing it is able to connect to server there. But in a new setup, Do I need to install and start Client?

You need to have both a window and afk watcher for the Activity view to be available. If you look in the "Raw Data" view you should see data appearing.

**Comment by rathishkumar** [comment]
@ErikBjare Thank you, yes I am seeing data in dashboard now.

Can I bundle window & afk and as distributable package and install it in my desktop? Or do I need any other dependencies like core/client?

I am focusing on building usage pattern analytics application for productivity enhancement and I am just started learning, any guidance will be helpful. Thank you.

**Comment by rathishkumar** [comment]
Installing Python 3.6 resolved the issues, since one of the whl (PyHook) is looking for specific Python version (3.6).

**Comment by ErikBjare** [comment]
If you've managed to build the watchers with PyInstaller then they already include aw-core and aw-client. Nothing else needs to be done.
