### ISSUE TITLE
Unknown App on Windows 

### ISSUE THREAD

**Issue by the-architech** [ActivityWatch/activitywatch#404]
Hey guys,

I installed the application on my virtual desktop and when I RDP in I get the following error any time my RDP Window gets locked: 

2020-04-06 18:42:31 [ERROR]: Exception thrown while trying to get active window: (-2147217385, 'OLE error 0x80041017', None, None)  (aw_watcher_window.main:66)

Also, I periodically get the same error on my laptop, though I have not been able to identify which application causes the error on my laptop yet. 

In the dashboard it reports the application as name as "Unknown". 

I am doing some research to find the cause but at the moment have not found anything conclusive.

**Comment by ErikBjare** [comment]
This is unlikely to be a bug, the windows window manager just might not have a real window active when your RDP is locked. 

Similar things can occur on macOS and Linux under some circumstances.

**Comment by ErikBjare** [comment]
Feel free to update the issue if you find the direct cause. Closing since there is no action for us to take.
