### ISSUE TITLE
Updating to a new release

### ISSUE THREAD

**Issue by freesig** [ActivityWatch/activitywatch#405]
## Documentation
How do I update to a newer release on linux? I just downloaded a release a while ago and added it to my autostart but wanted to update. If I swap out the whole directory is there any chance of loosing my data or is it stored somewhere else?

**Comment by ErikBjare** [comment]
The data is stored elsewhere (on Linux in `~/.local/share/activitywatch`) so you can safely delete the application directory and replace it with a newer version.
