### ISSUE TITLE
Wrong version number in 0.9.2 macos downloads

### ISSUE THREAD

**Issue by suschizu** [ActivityWatch/activitywatch#409]
the latest download still contains version 0.9.0 (instead of 0.9.2)

see:
![Screenshot 2020-04-15 at 17 57 29](https://user-images.githubusercontent.com/16004333/79359392-d5d07900-7f42-11ea-85bf-d8b99404416c.png)

**Comment by xylix** [comment]
This happens sice we haven't yet automated updating the version number in the pyinstaller .spec file. Should be as simple as retrieving one variable value into the macos metadata in bottom of the spec.

**Comment by xylix** [comment]
Fixed in 47cd07e72d0f82524bc4b5ddb868e20fa77aa11f

**Comment by suschizu** [comment]
thanks!
