### ISSUE TITLE
Add colors to categorization rules

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#416]
We currently use some ~~randomly generated~~ colors in the web UI, it would be nice to have them actually mean something *significant*.

Similarly to how GitHub has colors for tags, we could add colors to categorization rules which gives categorized events the color in it's `$color` data key, which visualizations can then use.

I'm suggesting:

 - That categorization rules can have a color.
 - That the categorization rule color gets assigned to events with that category by setting the `$color` key.
 - Unsure if good solution: If a categorization rule doesn't have a color it inherits the parent category color (potentially +random noise to slightly differentiate). If none of the parents have a color, it will set `$color` to `null`/`None`.

Not a priority, but I've had this in the back of my mind for a long time and finally realized it would be neat to do this using categories.

Similar changes, but for productivity: https://github.com/ActivityWatch/aw-webui/pull/162

This is a requested feature on the forum: https://forum.activitywatch.net/t/add-percentage-or-improve-colorizing-for-better-visualization/981

**Comment by johan-bjareholt** [comment]
While it's true that the colors are semi-randomly generated its not true that they don't have a purpose today.

Window titles have the same color as their respective appnames.

I'm not saying that your proposal is a bad idea, I'm just pointing out that it's not true that the colors today don't have a purpose.

**Comment by ErikBjare** [comment]
Updated issue to reflect that, hiding both our comments to avoid going off-topic.

**Comment by ErikBjare** [comment]
While thinking about this, I realize that it'll be difficult to assign a color to certain elements in the web UI with the proposed method.

Take `Top Applications` as an example, which color should be chosen? Each application might have activities from a wide range of categories, the same goes for URLs.

Maybe choosing the dominant/most common color is acceptable, but I'm not a fan of it.
