### ISSUE TITLE
Ask active users for donations

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#417]
If a user has been using ActivityWatch for 7, 30, 90 days (as an example) and opens the web UI they should be shown a dialog/modal that asks them to support the project financially (on Patreon or elsewhere). 

This would serve as an effective reminder to users that we're building this mostly for free and need our users support to keep doing it for the long-term.

It also serves as a dual-purpose of getting business users' attention to the need for them to pay their share, perhaps a paragraph should be targeted directly to them.

Related to #291

**Comment by johan-bjareholt** [comment]
Kind of improved now with the webui feedback poll, should we consider this to be a duplicate or do we think that this issue has a little different angle?

**Comment by ErikBjare** [comment]
@johan-bjareholt I think we can consider it resolved. There will always be room for improvement, but I see no point in keeping it open.
