### ISSUE TITLE
Categorization Rules deleted when chrome browser cookies cleared

### ISSUE THREAD

**Issue by 8bitgentleman** [ActivityWatch/activitywatch#420]
**For us to be able to understand the issue you're having you need to follow this template.** Please make sure there isn't already an issue for the bug you've found, otherwise it'll just take more resources, which means less time for us to actually fix bugs. Thanks for reporting!

## Describe the bug
I had to clear chrome's browser cookies the other day which unintentionally deleted all my Categorization Rules as well. I do see that the settings pages says _"These settings are only saved in your browser"_ but I did not realize that meant clearing cookies would delete them.

## To Reproduce
1. Set up and save custom Categorization Rules
2. Delete chrome cookies for the last hour

## Expected behavior
Categorization Rules should be persistent, perhaps saved in the server database?

## Environment
 - ActivityWatch version: v0.9.2
 - OS: [macOS (Mojave)]

**Comment by ErikBjare** [comment]
We're already working on this, as is said at the top of the settings page.

**Comment by 8bitgentleman** [comment]
Ok, great I didn't see an issue open with a quick search. Sorry if this was spam

**Comment by ErikBjare** [comment]
One of the issues (I think there might be another one as well) is here: https://github.com/ActivityWatch/activitywatch/issues/348

Closing.

**Comment by ErikBjare** [comment]
The PR that implemented the necessary API in aw-server-rust is here: https://github.com/ActivityWatch/aw-server-rust/pull/87

And congrats to issue #420 :)

**Comment by 8bitgentleman** [comment]
> And congrats to issue #420 :)
haha funny coincidence 


> The PR that implemented the necessary API in aw-server-rust is here: [ActivityWatch/aw-server-rust#87](https://github.com/ActivityWatch/aw-server-rust/pull/87)
Just switching from aw-server to aw-server-rust throws a 404. Is the rust server not ready yet or is there something else I need to do to switch? (I'm on macOS)

**Comment by ErikBjare** [comment]
It's implemented in aw-server-rust, but we're still working on migrating the web UI to use it.

If you get a 404 for localhost:5600 with aw-server-rust, that probably means the web UI files haven't been built. How do you run aw-server-rust?

**Comment by 8bitgentleman** [comment]
Thanks for these quick responses!
I have been running Activity Watch with the latest .app and starting it using [the window watcher workaround](https://github.com/ActivityWatch/activitywatch/issues/380#issuecomment-613587011) from #380 (I'm on Mojave)

**Comment by xylix** [comment]
When you switch to aw-server-rust did you first shut down aw-server in the UI? They will both try to use the same port if not closed so that could cause a failure.

**Comment by 8bitgentleman** [comment]
Yes I did, I unchecked aw-server before I checked aw-server-rust

**Comment by johan-bjareholt** [comment]
@xylix If it's a 404,maybe we need to add some extra path here?
https://github.com/ActivityWatch/aw-server-rust/blob/642a5315cd7ccbcb5aa24df73ce1b6096881616a/aw-server/src/main.rs#L102
