### ISSUE TITLE
My MSc thesis on ActivityWatch and BCIs

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#422]
So I now finally have a plan for my masters thesis which will also include some work on ActivityWatch.

When I started ActivityWatch, I did it with the hopes that some day we could use that data to track even more about what goes on in our minds all day. So this thesis will be a next step in that journey to get "closer to the hardware" and actually measures what goes on in our brains.

I created this issue for a place for myself to keep track of the work I might do as part of my thesis. 

 - [ ] What should the the goal/main question of the thesis?
 - [ ] Would be worth taking some intro courses to neural signal processing. Like: https://www.reddit.com/r/neurallace/comments/g72d3i/introduction_to_eeg_and_neural_signal_processing
 - [ ] What sensors would be useful?
      - EEG
      - Electrodermal (for sensing "arousal")
      - Tracking activity of input methods
      - Muscle activity (unlikely to be useful)
 - More...

**Comment by xylix** [comment]
I'm not really an expert on anything neural but could tracking eye movement be another "sensor" to consider? It's one of the most important indicators of attention when using a computer.

Sounds like a cool thesis though! Good luck.

**Comment by TrigonaMinima** [comment]
Not exactly inline with your thesis but they do talk about what data they captured as a part of the experiment - https://www.microsoft.com/en-us/research/publication/design-and-evaluation-of-intelligent-agent-prototypes-forassistance-with-focus-and-productivity-at-work/

**Comment by nikanar** [comment]
Great ! Looking forward to hear more about what that actual subject becomes. What's the plan for now ?
