### ISSUE TITLE
aw-watcher-window dies sometimes

### ISSUE THREAD

**Issue by rhdxmr** [ActivityWatch/activitywatch#423]
Log messages are attached below.

> 2020-04-25 17:26:00 [WARNING]: Unable to get window class, got a BadWindow exception.  (aw_watcher_window.xlib:85)
> 2020-04-25 17:26:00 [ERROR]: Exception thrown while trying to get active window: [Errno 5] Input/output error  (aw_watcher_window.main:66)

aw-watcher-window process dies sometimes.

But I don't know how to reproduce this symptom manually.

activitywatch version is 0.9.2
OS is Pop!_OS 19.10 x86_64

**Comment by johan-bjareholt** [comment]
That error message doesn't crash aw-watcher-window, it just says that it's unable to get the tile and/or appname of the current window and continues running but with the title and appname both set to "unknown".

If you are sure that it actually crashes, please try to run it from the terminal instead until it crashes. I think stderr is missing from the logs unfortunately so running it in the terminal should give a better error message.

**Comment by rhdxmr** [comment]
OK, I am going to run it from terminal. If I get something new messages, I'll let you know.

**Comment by johan-bjareholt** [comment]
I'll close this issue, feel free to open it if you are able to reproduce it in the terminal so we can see the crash traceback.
