### ISSUE TITLE
Activitywatch doesn't see Wine windows under linux

### ISSUE THREAD

**Issue by petRUShka** [ActivityWatch/activitywatch#425]
## Describe the bug
There is no evidence in Dashboard about hours spent in Windows application that was launched under Wine.

## To Reproduce
0. Run `aw-qt`
1. Run Windows app under Wine
2. Use it for several ours
3. Open Dashboard
4. See nothing on that windows app

## Expected behavior
I expected ActivityWatch to count time in that app.

## Documentation
Unfortonately I don't see any problem-related logs

## Environment
 - ActivityWatch version: v0.9.2
 - OS: Linux (ArchLinux)

**Comment by ErikBjare** [comment]
What events do you have in the aw-watcher-window bucket (in the Raw Data tab) during the time you used Wine?

**Comment by petRUShka** [comment]
Nothing there is no sign of wine or of  `.exe` processes that actualy running few moments ago:

```
$ ps aux | grep exe
user 1762946  0.4  0.2 2690292 40296 ?       S    15:43   0:00 HD_Launcher.exe
...
user 1763354 83.4  1.3 2976140 221896 ?      Sl   15:43   1:07 h3hota HD.exe
```

But there is definetely windows title my WM (dwm) shows it. And there is playonlinux item (launcher for exe) in the RAW data.

**Comment by ErikBjare** [comment]
So I assume you're running a Wine app with PlayOnLinux in full screen/virtual desktop mode? (no floating window)

The issue is likely with Wine/PlayOnLinux and that it doesn't update the window class or title to the application running in it.

Since this isn't really on our end, I don't think there's anything we can do about this. I'm therefore closing the issue, but thanks for reporting.

**Comment by ErikBjare** [comment]
Hmm, I missed the part where you said that your window manager could pick it up. Could you inspect the window with `xprop` and find the title string?

**Comment by petRUShka** [comment]
There are two Wine (windows) apps that aren't under watch:

1. [HD launcher](https://sites.google.com/site/heroes3hd/). `xprop` output

```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):
	               ▒░               
	              ▒ ▒░              
	             ▒   ▒░             
	 ▒░        ░▒     ▒▒         ░░ 
	 ▒▒▒▒▒▒▒▒▒░░        ▒▒▓▓▓▓▓▓▒▒▓ 
	 ▒░░░░░░░      ░      ░░░░▒░░▒▒ 
	 ░░░░░░       ░▒▒░    ░░▒░░░░▒  
	  ▒░░       ░▒▒▒▒▒▒░  ░░░░░░░░  
	  ░▒░░▒▒▒▒▒▒▒▒▒░▓▒▒▒▒▒▒▒▒░▒▒▒   
	   ▒░░░▒▒▒▒▒▒▒░░▓▒▒▒▒▒▒▒▒░░▒▒   
	   ▒░░░▒▒▒▒▒▒░░░▒░▒▒▒▒▒▒▒░░░░   
	   ▒░▒░▒▒▒▒▒░▒░░░ ░░░▒▒▒▒░▒▒    
	   ▒▒░░▒▒▒▒▒░░▒▒░░░▒▓▒▒▒▒░▒▒    
	   ░▒░░▒▒▒▒░▒ ░▒▒  ░▓▒▒▒▒░░▒    
	   ░▒░░▒▒▒▒▒▒▒░░░▒ ░▒▒▒▒▒░░▒    
	    ▒░░▒▒▒▒▒▒▒▒▒░░  ░▓▒▓░  ▒    
	    ▒  ░▒▒▒▒▒▒▒▒░░ ░▒▒▒▒░  ░    
	    ▒  ░▒░▒▓▒▒▓▓░▒░▒▒░▒▒   ░    
	    ▒  ░▒▒▒▒▒▒▒░░▒▒░▒▓▒▒  ░     
	    ░░░░▒▒░░▒▒▒ ▒▒▓▒▒▒▒▒  ▒     
	    ░▒░░▒▒▒░▒▒░ ░▓▒▒▒▒▒░  ▒     
	     ▒░▒░▒▒▒▒▒▒░░▒▒▒░░▒  ░▒     
	     ▒▒▒░▒░░▒▒░▒▒▒▓▒░░▒  ░░     
	     ░▒▒░▒░░░▒▒▓▒▒▒▒▒░░  ▒      
	      ▒░░▒░░░▒░▒▒▒▒▒▒▒   ▒      
	      ▒░░░▒░░▒░ ▒░░░▒░  ░       
	       ▒░░░▒░░▒▒▒░░░░   ▒       
	       ░▒▒▒░░░░░░░▒░   ▒        
	        ░▒▒▒░░░▒░     ▒░        
	          ▒▒░░      ░▒          
	            ▒▒    ░▒░           
	              ░▒▒░              


_NET_WM_STATE(ATOM) = 
_NET_WM_NAME(UTF8_STRING) = "HoMM3 HD 5.0 RC93 Launcher"
WM_ICON_NAME(STRING) = "HoMM3 HD 5.0 RC93 Launcher"
WM_NAME(STRING) = "HoMM3 HD 5.0 RC93 Launcher"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
		bitmap id # to use for icon: 0x880005f
		bitmap id # of mask for icon: 0x8800061
		window id # of group leader: 0x8a00001
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x2c, 0x3a, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 641, 277
		program specified minimum size: 639 by 546
		program specified maximum size: 639 by 546
		window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x8800017
XdndAware(ATOM) = BITMAP
_NET_WM_PID(CARDINAL) = 697543
WM_LOCALE_NAME(STRING) = "ru_RU.utf8"
WM_CLIENT_MACHINE(STRING) = "lparch"
WM_CLASS(STRING) = "hd_launcher.exe", "hd_launcher.exe"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, WM_TAKE_FOCUS
```

2. [Heroes 3](https://h3hota.com/en/documentation) binary itself. `xprop` output:

```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (32 x 32):
	    ▒▒                          
	    ▒▒▒▒░                       
	    ▒▒▒░░ ░░                    
	    ▒▒░ ░░░░░▒▒                 
	    ▒▒░    ░▒▒▓                 
	   ░▒      ░░▓                  
	   ▒▒░░░  ▒░▒░                  
	   ▒      ░░▒▒░                 
	   ▓▒░    ░░▒  ░▒               
	   ▒▒▒   ░▒▓     ░░             
	  ░░    ░░▒▒      ▒░            
	  ░░░    ░▒░       ▒            
	  ░▒░    ░▒        ░░           
	  ░▒░    ░▒         ░           
	  ░░░   ░░▒         ░           
	  ░▒░    ░▒         ░░          
	  ░▒    ░▒▒          ▒          
	   ▒░   ░▒▒           ▒         
	   ▒░   ░▒▒            ▒▒       
	   ▒░░  ░▒▒             ▒▒▒     
	   ▒▒░  ░░▓               ░▒    
	    ▒░   ░▒                ░░   
	    ▒▒░  ░▒▒                ▒   
	    ░▒░░ ░░▓                ▒   
	     ▒▒░░ ░▒▒▒              ░░  
	      ▓▒░  ▒░▒▓░             ▒  
	      ░▒▒░░  ░▒▒▒    ░░░▓▓▒▒▒▒  
	       ░▓▒▒    ▒▒▒▒▒▒▒░░   ░▒▒  
	        ░▓▒░ ░░░░░░░    ▒▒░  ░▒ 
	          ▒▒▒▒▒░░░░░▒▒▒▒▒░  ▒░  
	            ░▒▒▓▓▒▒▒░        ░  
	                                

	Icon (16 x 16):
	  ▒░            
	  ▒░ ░░         
	  ░   ▒         
	 ░░  ░▒         
	 ░░  ▒  ░       
	 ░  ░▒   ░      
	 ▒   ░    ░     
	 ▒  ░░    ░     
	 ▒  ░░    ░░    
	 ░░ ░░     ░░   
	  ░ ░░       ░  
	  ▒  ▒        ░ 
	   ▒ ░▒░      ░ 
	   ░▒  ░▒░░░░░▒░
	    ░▒░░░░░ ░░░░
	      ░▒░░░   ░ 


_NET_WM_STATE(ATOM) = 
_NET_WM_NAME(UTF8_STRING) = "Heroes of Might and Magic III: Horn of the Abyss"
WM_ICON_NAME(STRING) = "Heroes of Might and Magic III: Horn of the Abyss"
WM_NAME(STRING) = "Heroes of Might and Magic III: Horn of the Abyss"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
		bitmap id # to use for icon: 0x6400042
		bitmap id # of mask for icon: 0x6400044
		window id # of group leader: 0x6c00001
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 22
		window gravity: Static
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x640002f
XdndAware(ATOM) = BITMAP
_NET_WM_PID(CARDINAL) = 707603
WM_LOCALE_NAME(STRING) = "ru_RU.utf8"
WM_CLIENT_MACHINE(STRING) = "lparch"
WM_CLASS(STRING) = "h3hota hd.exe", "h3hota hd.exe"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, WM_TAKE_FOCUS
```

My windows manager show both of the titles.

I try to check `aw-watcher-window` raw data and it doesn't contain any sign of wine apps, only browser and etc...

P.S. Heroes 3 is still a great and actual game to my surprise. As I discovered recently community works on it a lot and there is stable and good addon with all the fixes of original gameplay and bugs and a lot of improvements (including new playable town, improved usability, online lobby and HD mod integrated and etc). Latest version was released on 01.02.2020. I've tried it and have enjoyed forgotten feel the past.

I've just leave links to [official web-page with docs](https://h3hota.com/en/documentation) and [forum thread](http://heroescommunity.com/viewthread.php3?TID=39830) with brief info and screenshots :)

**Comment by petRUShka** [comment]
I've tried to exclude PlayOnLinux from the process: just run `wine h3hota\ HD.exe`. Still no sign of it i in Raw Data or in any other part of Dashboard.

**Comment by johan-bjareholt** [comment]
Personally when I use wine the title is always correct but the appid is unfortunately always "Wine" (the preferred in my opinion would be that it for example would be "h3hota HD.exe", or in my case "WoW.exe").

The application has a "_WM_CLASS" and a "_NET_WM_NAME" so I don't see no reason why it shouldn't work. Even if it doesn't work the window watcher should fall back to the title and/or appname "unknown" so I would assume that something non-obvious is going on here.

**Comment by petRUShka** [comment]
@johan-bjareholt could you please repeat that behavior on your machine? I think it can help to find the source of that misbehaving.

The downloading page is https://h3hota.com/en/download
