### ISSUE TITLE
Special characters not working in regex categorization rule

### ISSUE THREAD

**Issue by Scurgery-git** [ActivityWatch/activitywatch#427]
If you put a special character into a regex it breakes. (I only tried with '+')

**Comment by johan-bjareholt** [comment]
This has been reported in the forum as well

https://forum.activitywatch.net/t/help-with-regex/541

**Comment by johan-bjareholt** [comment]
The + symbol seems to work for me however (I just replaced "ActivityWatch" with "(ActivityWatch)+" and both matched.

**Comment by Scurgery-git** [comment]
Yes I have: notepad++

**Comment by johan-bjareholt** [comment]
Since it's a regular expression and + there means "one or more of the previous character" you need to specify "notepad\+\+", otherwise it's an invalid regular expression.

**Comment by Scurgery-git** [comment]
Oh I see, I wasn't aware of this. Thank you!

**Comment by ErikBjare** [comment]
@johan-bjareholt Is the escaping broken or not? Can the issue be closed?

**Comment by Scurgery-git** [comment]
Yes it can.

**Comment by johan-bjareholt** [comment]
@ErikBjare Escaping is broken, but not for the + character specified here but for the specials like `\w` which use a backslash, see forum post linked above for more info.
