### ISSUE TITLE
Pin Buckets To Tray Menu / Set Start Page

### ISSUE THREAD

**Issue by rtpHarry** [ActivityWatch/activitywatch#428]
## Feature requests belong on the forum [here](https://forum.activitywatch.net/c/features)!

Below is a template suggestion you should preferably use.

------------

**Is your feature request related to a problem? Please describe.**
My primary use case for ActivityWatch is quick reference for my recent activity. I track my time with an online service (Toggl) but regularly forget to start the clock when I switch between tasks.

I just need an easy way to quickly see my recent activity.

**Describe the solution you'd like**
I would like to be able to pin my bucket to the menu:

![image](https://user-images.githubusercontent.com/1038062/81400298-ad443500-9124-11ea-9b95-eaef221499a6.png)

At the moment the dashboard opens on a welcome page, then I have to click Raw Data, then I have to stop and read the bucket names because the sort order is set to the most recently updated which could be the windows, or the afk bucket, so they are always in a different order, then I can start looking at my data.

I do this multiple times a day, so any way to improve this flow would be great. Pinning the bucket to the menu, or allowing a "set as start page" setting to open the dashboard directly to my bucket seems like the obvious solutions.

**Comment by ErikBjare** [comment]
Why don't you just bookmark the URL?

Given that, I don't think this feature request makes much sense. I agree that we need a better "start page" or similar but that's beyond the scope of a feature request.

Closing.
