### ISSUE TITLE
Firefox-addon bug(?)

### ISSUE THREAD

**Issue by osauldmy** [ActivityWatch/activitywatch#430]
Hello! It's about one and half month since I found ActivityWatch and started to use and enjoy it, thank you guys!

There is one thing I noticed some time ago, but I'm only now writing the issue here. I use ActivityWatch vim plugin and an addon for firefox and some backend I found in the AUR.

I check stats in the browser, page shows me time I have spent in vim, but from some day it stopped  to show logged websites and categories, so Browser tab shows only "no data" (Earlier it worked).
If I got it right, it does log the sites (Raw Data -> aw-watcher-web-firefox -> Open), but doesn't show the stats.

So the versions:

OS: Arch Linux (with 5.6.10 kernel)
Firefox: 75.0
Firefox addon: 0.4.0
Backend: aur/activitywatch-bin 0.9.2-1

I hope I didn't duplicate already existing issue (didn't find similar) and it's the right repository for bug reports.
If it's not a bug, but some my misunderstanding - I'm sorry and would like to know how to fix it.

And here some screenshots.
![DeepinScreenshot_select-area_20200509175450](https://user-images.githubusercontent.com/28873119/81478906-8539fc00-9220-11ea-9202-79f00b1e572c.png)
![DeepinScreenshot_select-area_20200509175524](https://user-images.githubusercontent.com/28873119/81478909-879c5600-9220-11ea-9d88-107c6b349beb.png)
![DeepinScreenshot_select-area_20200509180941](https://user-images.githubusercontent.com/28873119/81478910-89661980-9220-11ea-84ec-75feaa0f2030.png)

**Comment by johan-bjareholt** [comment]
Web watcher indeed seems to work.

You mentioned that you are running aw-server (the backend), but for browser activity stats you also need aw-watcher-window and aw-watcher-afk (which are started automatically if you use aw-qt). Are you doing that or only using the web/editor watchers. The reason why those are needed is because chrome/firefox cannot know when the window is focused or if the user is afk, so those watchers are merged with the web watcher to give accurate browser usage.

**Comment by osauldmy** [comment]
I did a little research and found out that I have installed all the things you mentioned (possibly that activitywatch-bin package from the AUR installs aw-server, aw-watcher-window and aw-watcher-afk all-in-one).
I used to launch only aw-server, so that's possibly a problem, I needed to launch aw-qt, like it was mentioned in the documentation:
```
If you are using Arch Linux you can install ActivityWatch directly from the AUR.
Download the latest release from GitHub, unzip the archive into an appropriate directory,
and add the aw-qt executable to your autostart applications.
```

Thanks, seems like not a bug and just my inattention.
