### ISSUE TITLE
aw-watcher-window captures no information

### ISSUE THREAD

**Issue by MetaStasisa** [ActivityWatch/activitywatch#431]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 Home
- **ActivityWatch version**: v0.9.2

## Describe the bug
aw-watcher-window doesn't capture any information during the day

## Documentation
Just returns this exception
![image](https://user-images.githubusercontent.com/34990678/81729218-da585680-9448-11ea-898d-6d7c3017b355.png)

## Additional context
I've setup a couple of my new categories and went to sleep it was working the day before.

Also it appears to capture the windows lock screen and nothing else:
![image](https://user-images.githubusercontent.com/34990678/81729283-fa881580-9448-11ea-9728-3e0e7a29545b.png)

**Comment by ErikBjare** [comment]
That's very weird. I assume a reboot fixes the issue?

**Comment by MetaStasisa** [comment]
It did not initially but it seems to have just started working 2 days later, I'm not quite sure why it stopped working in the first place.
