### ISSUE TITLE
Incorrect version for aw-server-rust in 0.9.2 Linux package

### ISSUE THREAD

**Issue by timwsuqld** [ActivityWatch/activitywatch#436]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 18.04
- **ActivityWatch version**: 0.9.2

## Describe the bug
When running aw-server-rust, the version number in the web interface is wrong, it shows 0.8.0 instead of 0.9.2.

## To Reproduce

1. Start aw-qt
2. Visit 127.0.0.1:5600 and look at version, see 0.9.2
3. Stop aw-server module
4. Start aw-server-rust module
5. Visit 127.0.0.1:5600 and look at version, see 0.8.0

## Expected behavior
Version should show as 0.9.2

## Documentation

![image](https://user-images.githubusercontent.com/6201617/83607855-80156600-a5ae-11ea-848a-fac06f29616e.png)
![image](https://user-images.githubusercontent.com/6201617/83607916-991e1700-a5ae-11ea-97d8-a5701b72258a.png)

**Comment by ErikBjare** [comment]
This has been fixed in v0.10.0, closing.
