### ISSUE TITLE
Infected byfilerepmalware Avast detection

### ISSUE THREAD

**Issue by ChameleonRed** [ActivityWatch/activitywatch#438]
https://www.google.com/search?client=firefox-b-d&q=filerepmalwarehttps://www.google.com/search?client=firefox-b-d&q=filerepmalware

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by ChameleonRed** [comment]
https://github.com/ActivityWatch/activitywatch/releases/download/v0.9.2/activitywatch-v0.9.2-windows-x86_64-setup.exe

**Comment by ErikBjare** [comment]
>In Avast’s case, a file will receive the FileRepMalware tag if all of the following conditions are met:
>
> - The file is not added to the Antivirus cleanset
> - The file is not signed by any publisher or the AV doesn’t trust the signature.
> - The file isn’t prevalent enough – meaning that not enough users have tried to download, launch or use the file yet

So looks like a false positive by Avast.
