### ISSUE TITLE
aw-qt not starting on Windows 10 (seems like #161)

### ISSUE THREAD

**Issue by heliocarbex** [ActivityWatch/activitywatch#444]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: MS Windows 10
- **ActivityWatch version**: 0.9.2

## Describe the bug
When trying to start aw-qt.exe the following message appears: "Failed to execute script ____main____" and the application crashes.

This appears to be a duplicate bug, but to another OS. So, I can't apply the same solution. I think that the same proble happend here at Linux: #161 

## To Reproduce
1. Go to ".\activitywatch folder"
2. Click "aw-qt.exe"
3. See error "Failed to execute script __main__"

## Expected behavior
Activity Watch should start and I should see in the browser all the graphs at http://localhost:5600.

## Documentation
Log file aw-qt_2020-06-22T13-59-57.log:
2020-06-22 13:59:57 [INFO ]: Starting module aw-server  (aw_qt.manager:49)

Log file aw-watcher-afk_2020-03-02T10-35-38.log
2020-03-02 10:35:38 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
2020-03-02 10:35:44 [WARNING]: Not connected to server, 0 requests in queue  (aw_client.client:380)
2020-03-02 10:36:00 [WARNING]: Not connected to server, 2 requests in queue  (aw_client.client:380)
2020-03-02 10:36:15 [WARNING]: Not connected to server, 3 requests in queue  (aw_client.client:380)
2020-03-02 10:36:30 [WARNING]: Not connected to server, 4 requests in queue  (aw_client.client:380)
2020-03-02 10:36:45 [WARNING]: Not connected to server, 6 requests in queue  (aw_client.client:380)
2020-03-02 10:37:01 [WARNING]: Not connected to server, 7 requests in queue  (aw_client.client:380)
2020-03-02 10:37:20 [WARNING]: Not connected to server, 8 requests in queue  (aw_client.client:380)

**Comment by ErikBjare** [comment]
Do you run ActivityWatch using the zip or using the installer?

Can you run aw-qt.exe from the command line and report the output?

**Comment by heliocarbex** [comment]
Using the zip. I tried to run using CLI, but the exe is not producing any output.

**Comment by heliocarbex** [comment]
Do you recommend to use the installer version?

**Comment by ErikBjare** [comment]
>Using the zip. I tried to run using CLI, but the exe is not producing any output.

Try running aw-server.exe from the command line, that should hopefully give you some output.

>Do you recommend to use the installer version?

It really shouldn't make a difference, since the installer uses the same files as those in the zip. But please try the installer version anyway, maybe you've extracted the files over an older version or something.

**Comment by heliocarbex** [comment]
Dear ErikBjare,

There is no aw-server.exe in my activity watch folder. Here I'm showing the search results for .exe files:

![image](https://user-images.githubusercontent.com/249042/86009207-4f2f2200-b9f0-11ea-89db-12ec98585595.png)

**Comment by johan-bjareholt** [comment]
In the zip there is a aw-server folder which contains aw-server.exe (same thing goes for the watchers, they all have their own folder except for aw-qt).

**Comment by heliocarbex** [comment]
> 
> 
> In the zip there is a aw-server folder which contains aw-server.exe (same thing goes for the watchers, they all have their own folder except for aw-qt).

For me, there is no .exe inside aw-server folder, XD
![image](https://user-images.githubusercontent.com/249042/86393788-eb1c9000-bc73-11ea-96c7-7cd88bcde74d.png)

**Comment by johan-bjareholt** [comment]
@heliocarbex It is there in the original zip file do then you have either done something wrong when unpacking it or your anti-virus has removed it automatically or something like that.

**Comment by heliocarbex** [comment]
Right, I will check it out.

**Comment by ErikBjare** [comment]
I'm assuming the aw-server.exe has been deleted by an AV system or something, so closing the issue.
