### ISSUE TITLE
Browser application time different from active browser time

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#445]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: 
Fedora 32, Gnome 3.36, Xorg
- **ActivityWatch version**: 
0.92

## Describe the bug

1. Look at the browser application time reported in the Summary tab (in the Top Applications section)
2. Look at the total Browser time reported in the Browser window.
3. The numbers are different when they should be equivalent. Occurs both on days when you use one browser or multiple(summation of individual app time will still be different from total Browser time)

*Note*: Occurs both for aw-server and aw-server-rust

**Comment by ErikBjare** [comment]
Can you tell us roughly how different the times are? Which one is larger? By how much? etc.

This will probably look somewhat different in the next version of ActivityWatch as the window/afk and browser queries have been merged into a single query since v0.9.2.

**Comment by nicolae-stroncea** [comment]
@ErikBjare  here's a comparison:

Legend: F(Firefox) and C(Chromium)

| Date | Application Time (summary tab) | Active browser time(browser tab) | Difference (Active Browser Time / Application Time ) | 
| ---- |  ---- | ---- | --- |
|  26 June | (F) 30m 51s+(C) 2m 41s   | 33m 8s | (couple seconds) 1.2% |
| 24 June | (F) 1h 10m 54s+(C) 1h 2m 17s | 2h 3m 35s | (~7min) 7.8% |
| 22 June | (F) 52m 45s + (C)3h 58m 5s | 4h 35m 59s| (~15min) 5.3% |
| 20 June | (F) 4h 1m 50s + (C) 52m 10s | 4h 14m 15s | (~39min) 15.6% |

Shouldn't the difference be 0 altogether?

**Comment by johan-bjareholt** [comment]
I can't reproduce this (aw-server-rust master and aw-webui master).
Mine is always off by just a few seconds.
I have only been using one browser however, I don't think that should make a difference though.

total app time for firefox / total browser time
- Week 21: 4h 28m 57s / 4h 28m 51s
- Week 22: 6h 29m 42s / 6h 29m 29s
- Week 23: 11m 48s / 11m 45s
- Week 24: 1h 34m 57s / 1h 34m 47s

**Comment by nicolae-stroncea** [comment]
@johan-bjareholt  could the same issue for https://github.com/ActivityWatch/aw-server-rust/issues/140 have caused this issue? For the date I sent you, the difference is currently 5 minutes

**Comment by johan-bjareholt** [comment]
@nicolae-stroncea If there are events in your browser bucket that has the exact same timestamp that's certainly possible.

**Comment by nicolae-stroncea** [comment]
After trying out the recent fix from aw-server-rust, issue still persists there, so I think this is a different bug

**Comment by SlinSo** [comment]
I think, this might affect more than the browsing time. Today I worked for about 2 hours in the morning. And the AFK watcher shows that time, which corresponds to my manual tracking. But in the summary tab I get an active time of about 1h 5m, which is almost 50% less.
I don't know where to start to help tracking down the problem.
For example I used Postman today and in the "window" tab or timeline I see about 20 events for the window watcher, but in the summary only the time of a single event was shown/used. I am not sure if it only reflects a single event or summed up a few of the shorter events, but I am missing a lot of time in the summary.

**Comment by johan-bjareholt** [comment]
@SlinSo Since it's so few events, could you export them and attach them here? Optionally you can replace the app/title data fields from the window watcher if it's something sensitive in the data.

We are not aware of any bugs with the window/afk watcher, so it would be interesting to see.

**Comment by SlinSo** [comment]
@johan-bjareholt Sorry, but how do I export a specific time range? I could not find any docs regarding this. I only know the bucket export. So my workaround would be to export the two buckets and delete all unneeded data?

**Comment by johan-bjareholt** [comment]
@SlinSo Yes, exporting them is one way but then you get all data and can remove the data which is not within the specific timerange (the events are ordered by timestamp, so you only need to find the start and end and remove everything in between).

You could however also use the API to get events in an interval, but then you have to make some slight modifications to the end result to be able to import it again, so not sure if that's easier for you or not. The API looks as follows `http://localhost:5600/api/0/buckets/aw-watcher-window_johan-laptop2/events?start=2020-01-28T23:00:00Z&end=2020-03-29T21:59:59Z` (then you replace the bucketname, starttime and endtime to whatever you need).

**Comment by SlinSo** [comment]
I have exported the afk events and the window events filtered on Postman. I have the same problem with other window title like "code", but I hope this is enough to analyze the problem.

[afk and postman gist](https://gist.github.com/SlinSo/4c0941a1aa5040423dcfa360ee4ecb0f)

I think the events from the window watcher are correct. But the afk watcher tracks the "afk" events twice with different durations. That does look strange.

**Comment by johan-bjareholt** [comment]
@SlinSo Thanks, will take a loot at it this weekend. Looks like it's enough.
