### ISSUE TITLE
Watchers and the server run twice in the Process table

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#447]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**:  Fedora 3.32, Gnome 3.36
- **ActivityWatch version**:  0.92

## Describe the bug

1. Launch each server and watcher
```bash
~/activitywatch/aw-server/./aw-server &
~/activitywatch/aw-watcher-afk/./aw-watcher-afk &
~/activitywatch/aw-watcher-window/./aw-watcher-window &
```
2. Execute `ps aux | grep aw-`
3. Output
```
nicolae     3772  0.0  0.0   2556   628 ?        S    00:00   0:00 /home/nicolae/Software/activitywatch/aw-server/./aw-server
nicolae     3773  0.0  0.0   2556   628 ?        S    00:00   0:00 /home/nicolae/Software/activitywatch/aw-watcher-afk/./aw-watcher-afk
nicolae     3774  0.0  0.0   2556   628 ?        S    00:00   0:00 /home/nicolae/Software/activitywatch/aw-watcher-window/./aw-watcher-window
nicolae     3782  0.5  0.1 389076 28016 ?        Sl   00:00   0:11 /home/nicolae/Software/activitywatch/aw-watcher-window/./aw-watcher-window
nicolae     3784 48.3  0.3 353228 58020 ?        S    00:00  16:48 /home/nicolae/Software/activitywatch/aw-server/./aw-server
nicolae     3789  1.6  0.1 538260 31060 ?        Sl   00:00   0:34 /home/nicolae/Software/activitywatch/aw-watcher-afk/./aw-watcher-afk
```

Is this expected behaviour or are the processes duplicated for some reason?

Events are being stored normally in the database, but that is expected as even if they were sent twice, they would be merged together due to heartbeats.

*Note*: If I launch aw-server-rust, aw-server-rust will run in 1 single process, however the watchers will still take 2 processes each

**Comment by johan-bjareholt** [comment]
This is because of how PyInstaller works, run it from source and you will see that it will only be one process.

See the following link for more information: https://stackoverflow.com/questions/33405338/how-to-eliminate-two-instances-of-exe-compiled-by-pyinstaller
