### ISSUE TITLE
macOS Big Sur breaks AW

### ISSUE THREAD

**Issue by alexriabtsev** [ActivityWatch/activitywatch#448]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: 
macOS 11.0 Beta (20A4299v)
- **ActivityWatch version**: 
0.9.2

## Describe the bug

ActivityWatch app doesn't start in macOS Big Sur. 
localhost:5600 is uavailable

## To Reproduce
1. Upgrade to macOS Big Sur beta
2. Launch ActivityWatch app
3. Nothing happens

## Expected behavior
ActivityWatch should started

**Comment by fr-kyleli** [comment]
```
➜  ~ open /Applications/ActivityWatch.app
LSOpenURLsWithRole() failed with error 2 for the file /Applications/ActivityWatch.app.
```

**Comment by ErikBjare** [comment]
Googling for the particular error code ("LSOpenURLsWithRole() failed with error 2", with quotes) gave no result...

The only somewhat similar results were for the [infamous error code -10810](https://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite), it would be nice if someone could double-check the workarounds in that link because I really have no idea how to make progress on this with the information given.

**Comment by alexriabtsev** [comment]
`WARNING:root:Could not import pymongo, not available as a datastore backend`
maybe this helps?

**Comment by ErikBjare** [comment]
So you could start it but it crashes? Please provide full logs.

That particular warning isn't relevant. There is no debug mode that would be useful for this particular issue (not without building from source anyway).

**Comment by alexriabtsev** [comment]
I can start it only with command line
`open /Applications/ActivityWatch.app/Contents/MacOS/aw-server&`
but not the icon

**Comment by alexriabtsev** [comment]
I tried both `chmod +x` and `xattr` via link above - nothing worked for me

**Comment by alexriabtsev** [comment]
I wrote above that JOSM doesn't start too but it threws another error
` ~ open /Applications/ActivityWatch.app
LSOpenURLsWithRole() failed with error 2 for the file /Applications/ActivityWatch.app.
➜  ~ open /Applications/JOSM.app 
LSOpenURLsWithRole() failed with error 1 for the file /Applications/JOSM.app.`

**Comment by fr-kyleli** [comment]
If I do this to launch AW, 

```
/Applications/ActivityWatch.app/Contents/MacOS/aw-server
```

it will work.

**Comment by alexriabtsev** [comment]
@fr-kyleli confrimed

**Comment by alexriabtsev** [comment]
Found an issue with running `/Applications/ActivityWatch.app/Contents/MacOS/aw-server`
AW doesn't understand host this way:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/8425396/87233795-63512700-c3d3-11ea-9b10-72fcf85ed9b8.png">

**Comment by alexriabtsev** [comment]
OK, today I managed to run AW via launchd
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>KeepAlive</key>
		<true/>
		<key>Label</key>
		<string>local.ActivityWatch.keepAlive</string>
		<key>ProgramArguments</key>
		<array>
			<string>/usr/bin/open</string>
			<string>-W</string>
			<string>/Applications/ActivityWatch.app</string>
		</array>
	</dict>
</plist>
`
BUT :)
localhost:5600 says that there are no afk and window watchers :(

**Comment by NightMachinary** [comment]
Has this been fixed? Mine gets stuck:
![image](https://user-images.githubusercontent.com/36224762/109293116-98b26400-7840-11eb-8fd0-92509565057a.png)

The menu is also very ugly:
![image](https://user-images.githubusercontent.com/36224762/109293749-7b31ca00-7841-11eb-9c22-47250861f3d5.png)

**Comment by johan-bjareholt** [comment]
@NightMachinary You seem to have a different issue, please file a new bug report.

**Comment by ErikBjare** [comment]
@NightMachinary I think that's the same issue as reported in
https://github.com/ActivityWatch/aw-webui/issues/266, it's fixed and will
be in the next release.
