### ISSUE TITLE
Timeline loads before finishing selecting the date range

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#449]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x]  I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**:  Fedora 32, Gnome 3.36, Xorg
- **ActivityWatch version**: 0.92

## Describe the bug

* It seems that often if I'm selecting a new date range for the timeline, and I put in the new *start/end* date, aw-webui already sends a request instead of waiting for me to put in the *end/start* date as well (it will just take the current date for the other side). 
* As a result, the new date range will not load, and will instead stay on the old request until I refresh the page. Another side-effect is that the page can become unresponsive.

## To Reproduce

1. Select 1 date range June 1st - June 2nd
2. Select new date start: April 1st
3. Wait 1 second
4. Select new date end April 2nd
5. If you check the browser console, you'll see "timeout of 30000ms exceeded" which means it likely started creating a timeline for April 1st - June 2nd

## Expected behavior

* New date range appears correctly, and interaction with the ui is smooth during the whole process

## Possible solution

* Add a button "Show Timeline" which the user will click once they selected the date range. This will make sure AW doesn't send any requests before the user settles on the final range.

**Comment by billangli** [comment]
Currently working on this

**Comment by YuriiZhydetskyi** [comment]
@billangli Can this issue be closed?

**Comment by billangli** [comment]
Hi @YuriiZhydetskyi, I think this issue was closed when the the pull request was merged.
