### ISSUE TITLE
Unable to generate Windows Installer Upon following the documentation

### ISSUE THREAD

**Issue by shyamshyre** [ActivityWatch/activitywatch#455]
Hi Team,

I am unable to generate build for windows, I could able to successfully execute make package distributions, but in case of windows unable to generate installers on top of windows machine.
Even none of the commands executed successfully.
Please help in providing the necessary steps followed for generating Windows Installer.

**Comment by ErikBjare** [comment]
You need to say exactly what you did, what step didn't work, and what you tried to fix it in order for anyone to help you. If you need specifics, see how it's done in the CI configuration. 

Since you haven't followed the required issue template (and we don't have time to answer vague questions) I'm closing this.

**Comment by shyamshyre** [comment]
@ErikBjare ,

Thanks for your quick response.
Followed the following steps specified by you in the document but no luck.
https://docs.activitywatch.net/en/latest/installing-from-source-on-windows.html
I am looking for generating an installer using windows please guide.
1) Cloned all the repos.
2) Tried to run make build - > But it failed.

Please find the below screenshot
![Error](https://user-images.githubusercontent.com/1207919/87350037-e9f13a00-c574-11ea-8f53-9257e5f488ed.png)

I could able to generate on mac machine successfully using the following guide.
https://docs.activitywatch.net/en/latest/installing-from-source.html

**Comment by johan-bjareholt** [comment]
The error is right there in the in the log: "fatal: not a git repository (or any of the parent directories): .git"

So you have not downloaded the repository properly, likely because you downloaded it as a zip instead of cloning it with git.
