### ISSUE TITLE
Stopwatch should not allow starting event while another is running

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#457]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Fedora 32
- **ActivityWatch version**: 0.92

## Describe the bug

You can currently start  a stopwatch event while another is running. Since you should never have multiple events that intersect in a bucket(from documentation), this should not be allowed

**Comment by johan-bjareholt** [comment]
> Since you should never have multiple events that intersect in a bucket(from documentation), this should not be allowed

This is a very good point.

Intersecting events are supported, but not recommended because:
1. some visualizations like the timeline can't display them properly
1. they don't work at all with heartbeats (and the stopwatch doesn't use that though)

We should decide how we want to support this in the future. It also seems like having two timers at the same time should be a common use-case, so I'm not sure what the best way to solve this is.

**Comment by ErikBjare** [comment]
>Since you should never have multiple events that intersect in a bucket(from documentation), this should not be allowed

Key word *shouldn't*, it basically only applies for buckets which use heartbeats. It would probably mess up some of the visualization stuff, as you can't form a single non-overlapping timeline from overlapping events.

The reason I wrote it as I did was that's how Toggl works (and I just verified that's indeed how it works). I can't quickly come up with a solid usecase where you'd actually want to have several overlapping stopwatches, but I'm sure there are some.

**Comment by johan-bjareholt** [comment]
The more I think about this the more I realize that the current solution is probably best even though it's not perfect. I'm considering whether we should just accept it as-is and close this issue.

> A way around this could be to simply allow multiple stopwatch buckets (from a dropdown), but I haven't thought that through.

Would work but would probably become messy and hard to manage pretty quickly if someone is a heavy user of the stopwatch feature.

**Comment by nicolae-stroncea** [comment]
@ErikBjare  wouldn't simultaneous events also mess up transforms functions?

**Comment by johan-bjareholt** [comment]
@nicolae-stroncea Depends on what kind of transform function. But if we want to be able to be able to have more than one timer running at a time it doesn't matter what the solution is, this will be an issue anyway.
