### ISSUE TITLE
Where can I change the config?

### ISSUE THREAD

**Issue by Alwinator** [ActivityWatch/activitywatch#459]
I am working on my own watcher which I have already mentioned [here](https://github.com/ActivityWatch/activitywatch/issues/453).

I also implemented a [config like in the official aw-watcher-afk](https://github.com/ActivityWatch/aw-watcher-afk/blob/master/aw_watcher_afk/config.py). Where can I change the values of this configuration? On the web interface under settings I cannot find something like *Watcher Config*.

**Comment by ErikBjare** [comment]
Configuration locations and options are described in the documentation: https://docs.activitywatch.net/en/latest/getting-started.html#config

**Comment by Alwinator** [comment]
Okay thanks, I missed this information. Do you also plan to add these configuration directly to the web interface? It would be very  practically.

**Comment by ErikBjare** [comment]
No worries! And no, there are no plans for that.
