### ISSUE TITLE
Sleep mode breaks Dashboard/aw-server

### ISSUE THREAD

**Issue by VelocityRa** [ActivityWatch/activitywatch#460]
I always use Sleep mode instead of shutting down my PC, and every time I want to open the ActivityWatch Dashboard after waking from sleep I run into this bug and have to restart it (just aw-server is enough), else it just keeps loading and not showing data.

I _think_ you also have to try to open the Dashboard once before restarting it via the tray icon for it to finally work, but I'm not sure.

Thanks for working on this! Really nifty.

**Comment by johan-bjareholt** [comment]
Hm, that's strange.

I also often put my computer to sleep and the only bug for me is that I can't select the new day (for example if I put the computer to sleep on a thursday and resume it on a friday I can't select friday until I refresh the page). Restarting aw-server has never been necessary for me and nothing else seems to be broken as far as I know.

What version are you running and what platform? Have you only experienced this once or multiple times?

**Comment by VelocityRa** [comment]
If I refresh, it keeps loading like so:
![image](https://user-images.githubusercontent.com/6632271/88118504-65329b80-cbc6-11ea-8643-935b011f69a2.png)

I experience this every time I use Sleep, so tens of times so far.

I'm on Windows 10 x64 1909, latest Chrome.

Update:
Huh, I clicked Activity after it was stuck there and it works.

**Comment by Maracko** [comment]
I am experiencing this issue as well
