### ISSUE TITLE
How to deploy a custom watcher?

### ISSUE THREAD

**Issue by Alwinator** [ActivityWatch/activitywatch#462]
I have now nearly finished my table height watcher. How can I deploy it? At the time I always start it with:
```
poetry run aw-watcher-table
```
How can I setup that my watcher automatically starts when ActivityWatch starts?

**Comment by johan-bjareholt** [comment]
There's a PR in progress which unfortunately seems to be stalled to run other modules in aw-qt, but it is not merged yet.

https://github.com/ActivityWatch/aw-qt/pull/56

Hopefully you could help out with testing it on windows, contributing or just comment that you are interested in the feature to revive the discussions on it.

**Comment by Alwinator** [comment]
I'm back from vacation and want to continue with this task. Unfortunately there is no documentation available about this topic yet. I have read through the linked pull request and looked a little bit in the installation directory from ActivityWatch, but I am not fully understand how it works. Should I build my watcher with pyinstaller and than move it in the ActivityWatch installation directory? And which tool should I use for Linux? Or is there a better way?

**Comment by Alwinator** [comment]
@johan-bjareholt @ErikBjare Could you please answer my question?

**Comment by ErikBjare** [comment]
@Alwinator Sorry for the slow reply. 

The PR Johan mentioned is now merged, and will be in the next release. You said in the thread that you would try it out on Windows, did you?

Using the latest aw-qt (unreleased), you should be able to just edit `~/.config/activitywatch/aw-qt/aw-qt.ini` and add your watcher to the list of autostart modules. For aw-qt to detect the module, the executable needs to:

 1. Begin with `aw-` (such as `aw-server`, `aw-watcher-afk`, etc)
 1. Exist either in your PATH or in a subdir (which also needs to begin with `aw-`) of the main activitywatch folder (where the aw-qt executable is)

If the module is detected, it should show up in the trayicon menu under "Modules".

See the code here for the exact module detection login: https://github.com/ActivityWatch/aw-qt/blob/3db74cddd1cfd0c5aa8baf1a989ba27fa0145b3c/aw_qt/manager.py#L55-L92

**Comment by Alwinator** [comment]
@ErikBjare Thank you for your reply! Now I think i know how it works. And yes I will try it on Windows.

**Comment by Alwinator** [comment]
I think this should be closed. It works like a charm with my [aw-watcher-table](https://github.com/Alwinator/aw-watcher-table). Even on Windows!

**Comment by ErikBjare** [comment]
Excellent! It'll be properly available in the next release.
