### ISSUE TITLE
Module aw-server quit unexpectedly 

### ISSUE THREAD

**Issue by oschubert** [ActivityWatch/activitywatch#464]
For the past week or so, I keep getting this message.  I installed the latest version, but am still getting this message.  Any idea what could be causing this?

The "Show Details" button doesn't display any information either.

I am using Windows 10.

**Comment by ErikBjare** [comment]
We can only help you if you follow the issue template. Closing.

**Comment by oschubert** [comment]
I did do a search, but couldn't find anything.  
Here are some of my logs.  I included a log file from before the issue started and some after.  It appears that the issue started July 24.  I have more logs if you need them.
[Logs.zip](https://github.com/ActivityWatch/activitywatch/files/5221139/Logs.zip)
I used the latest Windows installer available from your website (v0.9.2).

Hope you can help.
