### ISSUE TITLE
Browser data not showing up in Activity page

### ISSUE THREAD

**Issue by Mimotal** [ActivityWatch/activitywatch#466]
Hi,

I am using MS Edge (Version 84.0.522.52). I installed the ActivityWatch into my browser it reports connected and syncs data.

I can even see the raw data and browser data in timeline view, but it is not showing up in Activity window. The Browser section and Browser tab says no data. I believe it is caused by the fact that the Raw browser data records for hostname: Unknown.

Not sure if this is issue with the browser ActivityWatch or the core ActivityWatch.

ActivityWatch version: 0.9.2.

Best Regards

Michal

**Comment by ErikBjare** [comment]
You did not follow the issue template. If you had, you would have first searched for similar issues, and then found: https://github.com/ActivityWatch/activitywatch/issues/399

If the application name of the Edge in ActivityWatch is `msedge.exe` as in that issue, it has already been fixed and will be in the next release.
