### ISSUE TITLE
React App for andoid ios pwa

### ISSUE THREAD

**Issue by charilaouc** [ActivityWatch/activitywatch#467]
- [ ] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

I am willing to work on the backend, anyone willing to help with graphics?

**Comment by ErikBjare** [comment]
There's already a perfectly fine Rust backend and a Vue frontend working on Android. 

Why rewrite everything in React?
