### ISSUE TITLE
Colour coding of activities is incosistent and confusing.

### ISSUE THREAD

**Issue by JordanAnthonyKing** [ActivityWatch/activitywatch#468]
- [X] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Having recently installed ActivityWatch I found the activity screen initially rather confusing: Here's a screen shot:

![image](https://user-images.githubusercontent.com/58787893/89719097-63cde500-d9b4-11ea-8a52-090846a9a814.png)

Due to the mismatched colour coding it is difficult to tell if programs and websites are being categorised correctly or not. Is Youtube uncategorised? Are Firefox and Anki video? Why is uncategorised red in the top list and purple in the sunburst. This makes it harder to get a quick overview of where I am spending most of my time.

Although I don't think this is a 'bug' it would be a nice improvement.

Please let me know if this should be made as a proper FR or if I'm misunderstanding something about the interface.

**Comment by ErikBjare** [comment]
There's a plan on fixing coloring by letting category rules have a color which will be used in the UI, but it's currently not a priority so might take a while.

We welcome PRs to fix this.

**Comment by johan-bjareholt** [comment]
If you want to see what category different apps/titles have you can still figure that out today by using the category filter at the bottom of the page.

**Comment by ErikBjare** [comment]
Closing in favor of #416
