### ISSUE TITLE
disable or reduce notifications

### ISSUE THREAD

**Issue by rinaldi6109** [ActivityWatch/activitywatch#471]
AW often advices me that is unable to send event to the server and right after that the issue is solved. However, such behaviour is annoying because I get the notifications in the bottom right border covering my other windows. 
Is it possible to suppress such notifications or reduce the time they stay on the screen?  
Thank you.

![screenshot](https://i.imgur.com/FR9Zjif.png)

**Comment by johan-bjareholt** [comment]
Those messages mean that activitywatch is either:
- not running
- is very slowed down for some reason and cannot keep up with reporting the activity from the web watcher

The question should rather be, what makes aw-server running so slow?
Do these messages pop up randomly or is it when you run some heavy workload on your computer?

**Comment by rangedsp** [comment]
I'd like to add on to this, I close ActivityWatch for privacy during the weekends (i don't really want to log how much hours I've played certain games). But if I have chrome running it pops up a notification all the time.

I just want a checkbox in the settings to say "turn off notifications"
