### ISSUE TITLE
Information regarding public APIs?

### ISSUE THREAD

**Issue by midopooler** [ActivityWatch/activitywatch#474]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue
Is there any public API which gives out the information which the application is storing/logging?

I don't want to go through the source code, is it possible to get the API in the swagger docs only?

**Comment by johan-bjareholt** [comment]
I'm not sure what you mean.

The swagger UI shows how to fetch events from the buckets which is all data that is stored. It can even generate a request to fetch it right there in the UI.
