### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by BeatLink** [ActivityWatch/activitywatch#476]
This issue is to track the development of flatpack packaging. I will be attempting to implement it myself then push the code upstream

**Comment by BeatLink** [comment]
To start with, the flatpak  app id will be net.activitywatch.ActivityWatchWeb

**Comment by BeatLink** [comment]
The work will be done on this fork 

https://github.com/BeatLink/activitywatch/tree/flatpak_packaging

I will post updates to this issue as i go

**Comment by BeatLink** [comment]
The Flatpak sdk and platform will be the FreeDesktop platform

**Comment by johan-bjareholt** [comment]
I've attempted this before, got aw-server working but never got around to aw-watcher-window and aw-watcher-afk or aw-qt to work.

Good luck! If you have any questions feel free to ask!

**Comment by BeatLink** [comment]
Sure thing

**Comment by BeatLink** [comment]
My life got a bit hectic all of a sudden so my work on this may slow down, But I'll work on this with any free time I have. Also an update, I'm going to create a new repo for the flatpak packaging to make it easier to upload to flathub.

**Comment by ErikBjare** [comment]
Awesome to see! 

>My life got a bit hectic all of a sudden so my work on this may slow down

No worries, just happy to see you work on it.

>flatpak app id will be net.activitywatch.ActivityWatchWeb

"ActivityWatchWeb" should probably simply be "ActivityWatch".

**Comment by BeatLink** [comment]
Can do

**Comment by Oymate** [comment]
@BeatLink  Any update?

**Comment by BeatLink** [comment]
@Oymate unfortunately, I've recently taken on a new job and time has got a bit scarce. But I could try knocking it out this weekend if there aren't any showstoppers.

**Comment by Oymate** [comment]
@BeatLink  actively waiting!

**Comment by BeatLink** [comment]
Unfortunately, this weekend is turning out to be busier than next weekend. I did do a bit of work on it but there are some dependency issues I need to figure out

**Comment by Victor239** [comment]
@BeatLink any update?

**Comment by BeatLink** [comment]
Work got more hectic than I would expect. I wont be able to say for now when I'd be able to work on it

**Comment by GeoffreyCoulaud** [comment]
Commenting here to say that I'd love a flatpak version, and I'd be willing to work on it since I have some free time.

@BeatLink I can't find your code, did you move it or delete it ?

**Comment by BeatLink** [comment]
Unfortunately yes. There wasn't any work that was done in any case. Additionally, I cant find the time in the near future to work on this issue.

**Comment by CodeCubeNeo** [comment]
Any update on this?

**Comment by GeoffreyCoulaud** [comment]
Not yet on my side. I've been quite busy at work and I'll keep being busy until July.

Please don't refrain from contributing, my efforts will go towards the more active project anyway when I'll be available.

**Comment by CodeCubeNeo** [comment]
amogus

**Comment by RokeJulianLockhart** [comment]
This should be reopened.

**Comment by pchmykh** [comment]
Any chances to have flatpak package?

**Comment by BeatLink** [comment]
Good idea
