### ISSUE TITLE
"Show Last" doesn't update in timeline if set from settings

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#477]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**:  Fedora 32, Gnome 3.36, Xorg
- **ActivityWatch version**:  v0.92

## To Reproduce

    1. Go to Settings
    2. Set "Duration Default Value" to 6 hours
    3. Go to timeline
    4. Choose different "Show Last" value than default
    5. Timeline updates, however "Show Last" value still shows settings value

![image](https://user-images.githubusercontent.com/39338488/92849005-cdc51a00-f3b8-11ea-9932-6cfa22fdc50c.png)
In the picture, I set "Show Last" in timeline to 15 minutes, and visually it only displays 15. The "Show Last" option still shows 6 hours

**Comment by ErikBjare** [comment]
I could reproduce this on my main instance but when I tried to reproduce on the latest aw-webui master it worked as expected. So it's likely already fixed, and will hopefully work fine in the next release.

Thanks for reporting!
