### ISSUE TITLE
ModuleNotFoundError: No module named 'aw_core' when using pyinstaller (aw_client package)

### ISSUE THREAD

**Issue by Alwinator** [ActivityWatch/activitywatch#478]
I tried to pack my self-programmed watcher using pyinstaller, but unfortunately I always get the error:

```
ModuleNotFoundError: No module named 'aw_core'
```

I noticed something similar when I tried to install  the aw_client package via pip:
```
pip install aw_client
```
Output:
```
ERROR: Could not find a version that satisfies the requirement aw_client (from versions: none)
ERROR: No matching distribution found for aw_client
```
With` git+https://github.com/ActivityWatch/aw-client.git` the installation works, but the .exe also has the ModuleNotFoundError error.

OS: Windows 10

**Comment by ErikBjare** [comment]
You're likely not in a virtualenv, which is needed.

**Comment by Alwinator** [comment]
@ErikBjare I have used Conda, but I will change to venv if i have to. I have also tried to install both packages directly frok git with pip.

**Comment by ErikBjare** [comment]
Regardless, this is very unlikely to be an issue with ActivityWatch itself. You just need to check your environment and make sure you're using PyInstaller correctly.

**Comment by Alwinator** [comment]
Now I have used virtualenv and poetry and it worked. It is also important to use the pyinstaller installed in the virtualenv and not the global installed one.
