### ISSUE TITLE
Module aw-server quit unexpectedly

### ISSUE THREAD

**Issue by oschubert** [ActivityWatch/activitywatch#479]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- Windows 10 Home 64-bit 
-  ActivityWatch v0.9.2

## Describe the bug
"Module aw-server quit unexpectedly" error message after restarting the computer.  
"aw-server" doesn't have a check mark in the "Modules" sub-menu.

## To Reproduce
Restart the computer

## Expected behavior
aw-server starting

## Documentation
[Logs.zip](https://github.com/ActivityWatch/activitywatch/files/5221212/Logs.zip)
![image](https://user-images.githubusercontent.com/22156863/93141473-1589c100-f699-11ea-884e-cc47f9bb8bad.png)
![image](https://user-images.githubusercontent.com/22156863/93141540-36521680-f699-11ea-9728-e619e48f0acd.png)

## Additional context
It started on July 24, 2020.

**Comment by ErikBjare** [comment]
Thanks for filling out the template (old #464). What is shown when you click 'Show Details...'? Could you paste that here please?

**Comment by oschubert** [comment]
It's empty.  Nothing is displayed there.Oliver ---- On Mon, 14 Sep 2020 23:00:51 -0700  notifications@github.com  wrote ----
Thanks for filling out the template (old #464). What is shown when you click 'Show Details...'? Could you paste that here please?

**Comment by ErikBjare** [comment]
Can you check if there's another aw-server or aw-qt process already running? Windows can be weird sometimes and start two processes (one that's trying to resume the applications that ran before reboot, another for the actual autostart entry).

Have you tried reinstalling?

**Comment by oschubert** [comment]
These are the only aw related processes that are running:



 

I installed the program again after it failed, but it didn’t make any difference.  Not sure how to do an uninstall as Activity Watch isn’t listed in the “Add Remove Programs”.

 

Oliver

**Comment by ErikBjare** [comment]
Are you trying to attach an image by email? I cannot see it.

**Comment by oschubert** [comment]
These are the only aw related processes that are running:
 
![Processes](https://user-images.githubusercontent.com/22156863/93259336-90fc7880-f754-11ea-8428-3006842fe731.png)

I installed the program again after it failed, but it didn’t make any difference.  Not sure how to do an uninstall as Activity Watch isn’t listed in the “Add Remove Programs”.

**Comment by alnixon** [comment]
Hi - I just got this issue today after a reboot.  I'd been running without issues since January on v0.8.4  
After this happened I tried a reinstall.
I also tried an upgrade to v0.9.2
This didn't sort it.

I got it working as follows:

**1.** renamed
C:\Users\MyAccount\AppData\Local\activitywatch\
to 
C:\Users\MyAccount\AppData\Local\activitywatch.old\

**2.** reinstalled, started it, quit it all.

**3.** restored my previous data: copied
C:\Users\MyAccount\AppData\Local\activitywatch.old\activitywatch\aw-server\peewee-sqlite.v2.db
to 
C:\Users\MyAccount\AppData\Local\activitywatch\activitywatch\aw-server\peewee-sqlite.v2.db

Not sure what could have caused the issue, I had a few power cuts today - maybe it quit in an unstable state.
On further investigation the following files files were corrupt (just had NUL characters in them).
aw-client.ini
aw-server.ini
aw-watcher-afk.ini 
aw-watcher-window.ini

To check it was just these files affected I restored the .old folder, copied over the healthy configs - all is good.

My theory - ini files got messed up during power cut madness.

**Comment by ErikBjare** [comment]
This has happened before in:

 - https://github.com/ActivityWatch/activitywatch/issues/456
 - https://github.com/ActivityWatch/activitywatch/issues/297
 - https://github.com/ActivityWatch/activitywatch/issues/245
 - https://github.com/ActivityWatch/activitywatch/issues/271 (not quite the same: It's on macOS and there it was the sqlite db that got corrupted)

We should probably figure out what causes this, but only seems to happen on Windows.

**Comment by alnixon** [comment]
I forgot to mention - one thing that confused the situation for a little while was that the error presented in the UI was simply the most recent entry from the log files (which was before the power cuts). Once I was in the situation of having a corrupt config nothing else useful was being put in the log files.

**Comment by oschubert** [comment]
I was able to get it working again, and recover my data that was already stored in the main database using @alnixon method.

I noticed there is a "queued" section in the aw-client folder and looking at the aw-watcher logs there seems to be some sort of queue of events that weren't stored in the main database.  Any chance of getting those into the main database?

**Comment by Norlandz** [comment]
I had the same issue. 

### situtation

- When ActivityWatch auto started at computer startup. The Error popped up `Module aw-server quit unexpectedly`. 

- Log Details::
  ```
  2023-01-22 10:39:36 [INFO ]: Using storage method: peewee  (aw_server.main:32)
  2023-01-22 10:39:36 [INFO ]: Starting up...  (aw_server.main:37)
  2023-01-22 10:39:36 [INFO ]: Using database file: C:\Users\Zlgtx\AppData\Local\activitywatch\activitywatch\aw-server\peewee-sqlite.v2.db  (aw_datastore.storages.peewee:116)
  2023-01-22 10:39:36 [ERROR]: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions  (aw_server.server:112)
  2023-01-22 10:39:36 [ERROR]: Unhandled exception  (root:43)
  Traceback (most recent call last):
    File "__main__.py", line 3, in <module>
    File "aw_server\main.py", line 43, in main
    File "aw_server\server.py", line 113, in _start
    File "aw_server\server.py", line 109, in _start
    File "flask\app.py", line 990, in run
    File "werkzeug\serving.py", line 1052, in run_simple
    File "werkzeug\serving.py", line 1005, in inner
    File "werkzeug\serving.py", line 863, in make_server
    File "werkzeug\serving.py", line 740, in __init__
    File "socketserver.py", line 452, in __init__
    File "http\server.py", line 137, in server_bind
    File "socketserver.py", line 466, in server_bind
  OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
  ```

#### minor

<details>
  <summary>what operation happened before & after</summary>

1.
    Windows10 automatic force update abruptly restarted my computer, when I was not using the computer. (Happened couple times before, but ActivityWatch didnt complain much before.)
    (Then, update failed due to some issue, and later I manually updated and restarted the computer, update succeed.)
    After a restart, the ActivityWatch Error shown up.

2.
    Searched online, regarding some methods from the other posts::
    1. the port 5600 was not used by others
    2. (tried restart ActivityWatch, issue persisted.)
    3. (didnt try reinstall ActivityWatch )
    4. deleted the `C:\Users\Zlgtx\AppData\Local\activitywatch\activitywatch\aw-server\peewee-sqlite.v2.db` seemed not helping
    5. (I do have `docker` on my computer, but I only used it a long time ago, not sure if thats the cause of issue.)

</details>

### solution

- **Run the following command as admin:**
  **`net stop hns && net start hns`**
  https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi

- Reopen ActivityWatch, no Error pop up.

- (I dont know why. & May not work for everyone.)
