### ISSUE TITLE
I can't even open the app

### ISSUE THREAD

**Issue by atienzar81** [ActivityWatch/activitywatch#480]
Problems opening the app. There ir any kind of security problem. I already gave it permision in my preferences, but after trying to open the app nothing happens appart from this floating window that is showed every some seconds.

I am not sure if the problem is from my system (macOS Mojave) or the app, but I guess I am not the only one with this problem.  I am looking forward to using this app! 

Best,
Pilar

**Comment by ErikBjare** [comment]
Can you not browse to http://localhost:5600? 

The permissions issues should not affect the ability to open the app, but will impact the ability to track window titles (see #380 and #229)

**Comment by bfosterscripps** [comment]
I am having the same issue on macOS Catalina. I gave permission, I have the icon in the topbar, but the localhost:5600 won't load despite the program running.
