### ISSUE TITLE
aw-server-rust disables on restart

### ISSUE THREAD

**Issue by awesomehaze** [ActivityWatch/activitywatch#483]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Using activitywatch on windows, when I right click the aw-qt icon in the taskbar, disable aw-server, then enable aw-server-rust, everything works perfectly. The issue, however, is that every time activitywatch is restarted, you must switch manually, which is very tedious. Am I missing an easy way to select which modules to open on startup?

**Comment by ErikBjare** [comment]
You can configure which modules to autostart by editing the config file for aw-qt, the location is in the documentation.

**Comment by awesomehaze** [comment]
Where, exactly, should I look in the documentation? I've been looking for a while, and can't find it. The closest I've come is here: https://docs.activitywatch.net/en/latest/getting-started.html#config.

**Comment by awesomehaze** [comment]
> You can configure which modules to autostart by editing the config file for aw-qt, the location is in the documentation.

Where can I find this? I'm lost.

**Comment by ErikBjare** [comment]
@awesomehaze Looks like it's actually undocumented, sorry about that!

In the same folder as the one written about in the docs, there should be an `aw-qt.ini` config file (on my system it's `~/.config/activitywatch/aw-qt/aw-qt.ini`) which determines which modules to autostart.

**Comment by awesomehaze** [comment]
> @awesomehaze Looks like it's actually undocumented, sorry about that!
> 
> In the same config folder as the one written about in the docs, there should be an `aw-qt.ini` config file (on my system it's `~/.config/activitywatch/aw-qt/aw-qt.ini`) which determines which modules to autostart.

Perfect, thank you so much for the help and your time, I really appreciate it.

**Comment by awesomehaze** [comment]
@ErikBjare What option would I put in the file? I've been looking through config.py and it seems to be called autostart_modules. Would I just add the following to that file? (I had to manually create it)
`autostart_modules = ["aw-server-rust", "aw-watcher-afk", "aw-watcher-window",]`

**Comment by ErikBjare** [comment]
You shouldn't need to manually create it, it should always be created for you (so you probably need to find the right location for Windows or whatever platform you're on, as specified in the docs).

But yes, mine looks like this:

```ini
[aw-qt]
autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]

[aw-qt-testing]
autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
```

**Comment by awesomehaze** [comment]
@ErikBjare Should I make this a separate issue? Creating the config file myself doesn't work.

**Comment by ErikBjare** [comment]
@awesomehaze After investigating this, it appears that support for the config file has not yet been included in a release (which is why it isn't there, and why it isn't being respected). 

I'll look into making a new release as soon as possible.
