### ISSUE TITLE
Python lock files of submodules have different versions

### ISSUE THREAD

**Issue by ppessi** [ActivityWatch/activitywatch#484]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

## Describe the bug
The lock files of submodules have different versions of some dependencies. I'm now running `make build` and for example six has different versions:
```
make[1]: Entering directory '/home/pinja/muita/activitywatch/aw-core'
poetry install
Installing dependencies from lock file


Package operations: 14 installs, 8 updates, 0 removals

  - Updating six (1.14.0 -> 1.13.0)
```
```
make[1]: Entering directory '/home/pinja/muita/activitywatch/aw-watcher-afk'
poetry install
Installing dependencies from lock file


Package operations: 2 installs, 7 updates, 0 removals

  - Updating six (1.13.0 -> 1.14.0)
```

## To Reproduce

My repo is at `42bf20c` and I simply did a fresh install.

**Comment by ErikBjare** [comment]
Is this causing an actual problem?

I understand it's not ideal, but unless there's an actual issue here there's not much we can do about deps sometimes getting out of sync. Regularly updating all deps so they match is a risky operation that requires a lot of testing (largely due to PyInstaller), so we want to avoid that.

**Comment by ppessi** [comment]
It reinstalls all the dependencies (that have "wrong" versions) every time you run `make build`, so it takes some time to run it.

**Comment by ppessi** [comment]
I just ran ´make build´ again and it took over 10min. Not sure how big a portion of the time was spent on reinstalling Python dependencies.

**Comment by ErikBjare** [comment]
FWIW, you should rarely need to re-run `make build` as all Python source files will be installed in editable mode by poetry.

I don't think installing a few out of sync deps will contribute significantly to the build times. It's more likely to be things like checking package locks against installed versions, and rebuilding aw-webui.

**Comment by ErikBjare** [comment]
They've been updated several times since. It's not a perfect workflow, but it works.

Closing.
