### ISSUE TITLE
Support Python 3.8 (update PyInstaller and PyQt5)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#491]
To support Python 3.8, we need to move to a recent version of PyQt5 (see https://github.com/ActivityWatch/activitywatch/issues/433#issuecomment-703236106) and update PyInstaller (the recently released 4.0 doesn't support it, but the develop branch does).

I've successfully built aw-qt with PyInstaller 4.0 and PyQt 5.15.1 on my machine, but we need testing on macOS and Windows as well.

Checklist:
 - [x] First update to Python 3.7 (https://github.com/ActivityWatch/activitywatch/pull/492)
   - Will get extensive testing in ActivityWatch 0.10.0 (#490)
 - [x] Get rid of PyHook dependency for aw-watcher-afk (https://github.com/ActivityWatch/aw-watcher-afk/pull/39)
 - [x] Update to a recent version of PyQt5
 - [x] Update to PyInstaller 4.1 (when released)
 - [x] Update all CI to use Python 3.8

**Comment by 2br-2b** [comment]
After this, should we try to support Python 3.9?

**Comment by ErikBjare** [comment]
@2br-2b Eventually, but it'll have to wait until our dependencies do.

**Comment by ErikBjare** [comment]
This is basically done. And Python 3.9 support should work too!
