### ISSUE TITLE
werkzeug < 1.0 not found  AUR Manjaro

### ISSUE THREAD

**Issue by sniperlucian** [ActivityWatch/activitywatch#494]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: testing + manjaro
- **ActivityWatch version**: via AUR - 0.9.2-1

## Describe the bug

cant start server with aq-qt , getting error message:

The 'werkzeug<1.0.0' distribution was not found and is required by aw-server.

`Pip install werkzeug`:
Requirement already satisfied: werkzeug in /usr/lib/python3.8/site-packages (1.0.1)

## To Reproduce

 install 
 call aw-qt

## Expected behavior

support werkzeug version 1.x

## Additional context

It's clear nobody can support all library version. But installation guideline mentions AUR, so I would expect it works out of the box. ;)  - and manjaro typically behind ARCH

**Comment by sniperlucian** [comment]
maybe its actually a feature request - but cant edit anymore.

**Comment by johan-bjareholt** [comment]
Even if it would be nice to support the newest version of every dependency it's not a realistic thing to be able to do. Instead I'd recommend installing activitywatch in an virtualenv and only make activitywatch use this older version fo werkzeug.

werkzeug is not a direct dependency but an indirect one, so our dependencies such as flask-restplus needs to be updated first to the newer version.

**Comment by ErikBjare** [comment]
Which AUR package? The `activitywatch-bin` doesn't use system libraries at all (so you shouldn't get the error), and the plain `activitywatch` is unsupported by us (due to things like this).

**Comment by ErikBjare** [comment]
Closing since this only affects the unsupported `activitywatch` (not `activitywatch-bin`) AUR package.
