### ISSUE TITLE
Module auto-start does not save selection

### ISSUE THREAD

**Issue by Alwinator** [ActivityWatch/activitywatch#496]
Here you can see the module selection:
![0](https://media.githubusercontent.com/media/Alwinator/aw-watcher-table/main/img/aw-watcher-table-deployment.jpg)

After checking my module it works, but after rebooting the computer I need to select it again in order to start my module.

**Comment by ErikBjare** [comment]
You need to change the config files, as I've mentioned before.

**Comment by Alwinator** [comment]
@ErikBjare Thank you, you are right. Completely forgot about it.
