### ISSUE TITLE
Windows client "activity" data miscalculated 

### ISSUE THREAD

**Issue by vitaalz** [ActivityWatch/activitywatch#498]
Hello, 

First I wanted to thank you for the awesome piece of software. The idea is brilliant and cross-platform feature is priceless. However in my tests I encountered with some weird issue. 

On linux aw-client data is collected and reflected correctly, but on windows in the "timeline" everything looks good and legit, but under the "activity", summary tab the calculations are wrong - after all day working it shows only 15 minutes of total work only. Furthermore sometimes during the day it even reduces the total time worked - meaning that during the day I checked the activity page few times and later check shows less time worked than it showed before. But again - at the same time "timeline" reflects correct data. 

My setup is:
aw-server-rust running on remote Debian linux server and aw-clients (aw-watcher-afk and aw-watcher-window) running on one "linux mint 20" and one "windows 10" workstation. 
I know officially in the documentation it says that currently there's no "server - client" option, but I don't see the difference sending data to remote server rather than localhost. And for me everything works, except that activity page time calculation issue and specifically only from windows aw-client. 

Maybe you can share some information on how that activity summary is calculated or help me to understand where could be the cause of such (mis)behavior? 

Thank you in advance

**Comment by johan-bjareholt** [comment]
>  I know officially in the documentation it says that currently there's no "server - client" option, but I don't see the difference sending data to remote server rather than localhost. And for me everything works, except that activity page time calculation issue and specifically only from windows aw-client.

As long as it's not the remote server part that we don't officially want to support that breaks things we'll help you out anyway of course.

> On linux aw-client data is collected and reflected correctly, but on windows in the "timeline" everything looks good and legit, but under the "activity", summary tab the calculations are wrong - after all day working it shows only 15 minutes of total work only. Furthermore sometimes during the day it even reduces the total time worked - meaning that during the day I checked the activity page few times and later check shows less time worked than it showed before. But again - at the same time "timeline" reflects correct data

The first thing to look at is if the buckets have reported their data correctly. The view on the "Activity" page will only show non-afk activity, so you should validate that the buckets in your timeline has events during the times that you expect and that there is both data from the window watcher and the afk watcher and that the afk watcher events have the value "not-afk". The final report in the Activity page will be an intersection of the "not-afk" events and the events from the window watcher.

**Comment by mrcinv** [comment]
I've noticed the same problem on windows running the server locally. It seems that the afk-watcher dont report the "not-afk" events corectly. The "not-afk" events in the timeline are scarse even thow I was active.
