### ISSUE TITLE
Category Filter not Working on Browser Domains

### ISSUE THREAD

**Issue by watertrainer** [ActivityWatch/activitywatch#499]
If I try to Filter for all Uncategorized Browser Domains, the Filter does not seem to apply. Window Title and Applications are filtered, however the Browserdomains are not

**Comment by johan-bjareholt** [comment]
This is a known bug that has been discussed multiple times.

I'm trying to find if it's a duplicate of some other issue but I'm unable to so maybe there are none and it's only been discussed in comments.

**Comment by watertrainer** [comment]
The Categories don't seem to take the browser domain into account at all. It only applies the regex to the Window title. Is this the same bug?

**Comment by johan-bjareholt** [comment]
Yes it's the same bug. It only categories by appid (ex. "Firefox", "Word", "Notepad") and window titles right now.

**Comment by watertrainer** [comment]
I just found that this Issue is an duplicate of #352, so I'll close it
