### ISSUE TITLE
BLD: build containers: Dockerfile, repo2docker

### ISSUE THREAD

**Issue by westurner** [ActivityWatch/activitywatch#501]
BLD: create a (multi-stage) Dockerfile for building aw (and then running the built binary)?

- https://github.com/ActivityWatch/activitywatch/blob/master/Makefile links to
  - https://docs.activitywatch.net/en/latest/installing-from-source.html
    - which isn't executable

  - A conda python container could install an environment.yml which installs ``python==3.7``

  - There's a pending PR to add support for Poetry to repo2docker:
    https://github.com/jupyterhub/repo2docker/pull/972/files
    - pending that, a `postBuild` script that calls poetry would probably work

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
  - re: dockerizing Activity Watch. this issue is re: dockerizing the build
- [ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by ErikBjare** [comment]
Is this a request or something you'd want to work on?

There's a lot more to building ActivityWatch than just Python/poetry. There's also building the web UI (with node/npm), as well as building aw-server-rust with rust/cargo (which will eventually replace aw-server-python, aka aw-server).

**Comment by westurner** [comment]
I suppose this is a request for a Dockerfile for building ActivityWatch on and for Linux?

Which distros are supported?
Which distro should the Dockerfile extend FROM?

Is this: enough? This could be added to the Makefile as e.g. `install_conda` so that a Dockerfile can just `make install_conda build as one or more RUN instuctions?

```bash 
conda install -c conda-forge python=3.7 nodejs rust
conda env export -f environment.yml
conda env export -f environment.fromhistory.yml
```

```Dockerfile
FROM continuumio/miniconda:latest
RUN make install_with_conda
RUN make build

FROM continuumio/miniconda
COPY --from=0 /../bin/aw-* /usr/local/bin/
```

Or, instead of a Dockerfile, if there's just an environment.yml:
```
pip install jupyter-repo2docker
repo2docker .
# r2d builds container, adds current JupyterLab
```

With a conda-forge feedstock, conda-forge could build ActivityWatch on Win/Mac/Lin such that AcitivityWatch could be installed with:

```bash
conda install -c conda-forge ActivityWatch
```

**Comment by westurner** [comment]
https://github.com/conda-forge/rust-feedstock/blob/master/recipe/meta.yaml looks like it installs `cargo`

**Comment by ErikBjare** [comment]
I'm not sure I understand the reason for putting it in Docker, since the watchers won't work from within a container. It could be used as a build env on Linux, sure, but that's about it.

Have you read https://github.com/ActivityWatch/activitywatch/issues/166?

>Which distros are supported?
>Which distro should the Dockerfile extend FROM?

I suppose Debian would be the most reasonable option, since we run Ubuntu in CI.

**Comment by johan-bjareholt** [comment]
I just realized that we could use the [container option for GitHub actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer), but it still wouldn't provide much value for us maintainers because a container made to build and package activitywatch can't be made for other platforms than Linux so we'd still need to keep maintaining the non-container solution for all other platforms.

**Comment by westurner** [comment]
Reframed objectives:
*****
BLD,ENH: One command to build the Linux binaries

Makefile:

```makefile
make build_on_docker:
    docker run --rm -i -t activitywatch/activitywatch:latest -v
output:output
    ls -al output/*
    sha256sum output/*
```


******

BLD,ENH: Create conda-forge/activitywatch-feedstock

```make
install_with_conda:
    conda install -c conda-forge -y activitywatch
```

```bash
make install_with_conda
```
Or, just:
```bash
conda install -c conda-forge -y activitywatch
```

https://github.com/conda-forge/activitywatch-feedstock

Benefits of conda-forge packaging:
- Build scripts and CI runners for [Win, Mac,] Lin (build.sh, build.bat),
and now arm64

**Comment by johan-bjareholt** [comment]
We already have a single build script for all platforms, it's our CI build file. If you want to run that locally with a single command you can do that with tools like [act](https://github.com/nektos/act).

Sure it's not a perfect solution, but switching to conda wouldn't be much of an improvement either as that has other issues.

**Comment by ErikBjare** [comment]
Wow. I always assumed something like act to exist, but it looks amazing. I'll have to give it a shot.

**Comment by johan-bjareholt** [comment]
@ErikBjare Such tolls are alright to use, just a bit slow sometimes. I remember that there was some equivalent for travis so I googled for the same thing for github actions and was not surprised that it existed.

**Comment by pablopezunizar** [comment]
Hi @westurner!
I am also interested in this feature. I would be happy to sync and help you to get this done.
