### ISSUE TITLE
You were added to awesome-humane-tech

### ISSUE THREAD

**Issue by aschrijver** [ActivityWatch/activitywatch#509]
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Health' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by ErikBjare** [comment]
That was quite a while ago... (I made the PR myself), but thanks for maintaining the list :)

Closing.

**Comment by aschrijver** [comment]
Oops, I may have made a mistake. I am going category by category to notify about the badge program, and afraid I sent duplicates for the entire Health category. Truly sorry!
