### ISSUE TITLE
Fix mypy on Appveyor

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#51]
Been making some attempts in https://github.com/ActivityWatch/activitywatch/pull/49.

Should probably skip the mypy step for now. Possibly done the easiest by overriding the mypy program in  `$PATH` with echo.

**Comment by johan-bjareholt** [comment]
Is this fixed?

**Comment by ErikBjare** [comment]
No, aw-core's `make typecheck` is never run on Appveyor, just `make test`. Haven't bothered trying to fix it.
