### ISSUE TITLE
It overwrite categories when save or edit new one

### ISSUE THREAD

**Issue by johnnestebann** [ActivityWatch/activitywatch#511]
I have the server installed on Windows 10 and when I edit a category/subcategory, it changes another category too at the same level, with the same data. So it overwrite what I wrote and loose the filter. That is really annoying

**Comment by johnnestebann** [comment]
Moved to web-ui

**Comment by ErikBjare** [comment]
Duplicate of https://github.com/ActivityWatch/activitywatch/issues/361
