### ISSUE TITLE
Playing with gamepad counts as AFK on Windows 7

### ISSUE THREAD

**Issue by Liosan** [ActivityWatch/activitywatch#512]
Hi folks,

First I'd like to say how much I appreciate AW. We use it for tracking game time in our family, and it works much better than commercial solutions that I've tried out.

The main problem I'm seeing right now is playing on pads. When there is no keyboard or mouse activity, AW stops tracking time. This is, to some degree, expected. The problem is playing with gamepads. They are not detected as valid input, so AW kicks into AFK mode.

Windows 10 and Windows 7 both have this behaviour.

With some guidance, I could probably contribute a patch. Anybody willing to walk me through the basics of setting up a dev environment and contributing?

**Comment by ErikBjare** [comment]
Weird, the use of gamepads is tracked correctly for me on Windows (just double checked), although I do have a bit of a special setup.

Are you running the latest version of ActivityWatch? (v0.9.2)

**Comment by Liosan** [comment]
Hey @ErikBjare, possibly not the latest. I'll do some more debugging and get back to you.

The game in question is Spelunky. I'll double check if the issue occurs on different games.

**Comment by ErikBjare** [comment]
@Liosan I don't think the game itself should matter (but it's possible).

Updating ActivityWatch may or may not help, we merged https://github.com/ActivityWatch/aw-watcher-afk/pull/14 back in 2017 which I thought would handle it. So if you have a somewhat recent version of ActivityWatch it might not make a big difference, but it would be appreciated if you could check the latest version anyway, just to be sure.

What gamepad do you use?

**Comment by ErikBjare** [comment]
>With some guidance, I could probably contribute a patch. Anybody willing to walk me through the basics of setting up a dev environment and contributing?

Regarding this, you should only need to modify https://github.com/ActivityWatch/aw-watcher-afk to fix the behavior. No need to build the entirety of ActivityWatch (which is a lot more involved, but there are instructions here: https://docs.activitywatch.net/en/latest/installing-from-source.html).

**Comment by Liosan** [comment]
OK, I've managed to narrow down the issue. It seems to occur only on Windows 7. Windows 10 works fine.

Game doesn't matter. Type of pad doesn't matter.

So, this seems to be an edge case.

**Comment by ErikBjare** [comment]
Ah, that explains things. Although I'm surprised to hear ActivityWatch runs on Windows 7 at all (see for example: https://github.com/ActivityWatch/activitywatch/issues/374).

It's very unlikely that someone will work on resolving this, especially since we've made the decision to not to put effort into supporting Windows 7 (which is EOL anyway).

**Comment by Liosan** [comment]
Understandable. Feel free to drop the issue :)

**Comment by MagentaPuppy** [comment]
This happens for me on linux, might be due to proton or steam input

**Comment by 8Dion8** [comment]
Currently also happens on Arch Linux with what seems to be any game. Is there any way to programmatically edit the data to set all time in `steam_app_*.` to `not_afk`?

**Comment by 8Dion8** [comment]
> It will be fixed! [webui#375](https://github.com/ActivityWatch/aw-webui/pull/375)

ah nice! been waiting for this feature for forever. any rough estimates for when the next release goes live?

**Comment by BelKed** [comment]
A new beta release [`v0.12.2b1`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.2b1) was released yesteday, which also includes [that PR](https://github.com/ActivityWatch/aw-webui/pull/375).
