### ISSUE TITLE
Write report for FUUG.fi grant

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#514]
We received a 3,000 EUR grant from FUUG.fi earlier this year (#343), and we're supposed to write a report on what we've accomplished with the funds received ASAP.

This will probably include a summary of general development progress since receiving the grant, as well as comments/updates on the specific goals we specified in the grant application.

**Comment by xylix** [comment]
Thanks to Erik for writing the base report and Tekla and me for the Finnish translation and finishing touches, the report is now done and published at https://fuug.fi/2020/activitywatchin-edistaminen-fuugin-apurahan-avulla

As such I would like to close this issue as solved.
