### ISSUE TITLE
0.10.0 release contains no installation files

### ISSUE THREAD

**Issue by Rakleed** [ActivityWatch/activitywatch#515]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue
[The 0.10.0 release](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.10.0) contains no installation files. Please add them.

**Comment by ErikBjare** [comment]
Build is in progress, give it an hour or two :)

**Comment by ErikBjare** [comment]
Builds for macOS and Windows are now done. Linux builds might take a while longer since Linux builds are backlogged on Travis CI: https://www.traviscistatus.com/
