### ISSUE TITLE
How to get time spent on computer with a commandline / script

### ISSUE THREAD

**Issue by PEPERSO** [ActivityWatch/activitywatch#518]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

I would like to write a script that I can put in my  `.bashrc`, or somewhere it is often executed, which can compute the time spent on my computer during the day. I've seen that this time is shown in the activity dashboard, but I would like to get it without having to start the user interface. 
I can write python, but I really did not understand anything in the query documentation, so I'm asking here.

Thanks for ActivityWatch, it's a very nice and neat product !

**Comment by ErikBjare** [comment]
@PEPERSO There are a few ways to do this, but if you're only interested in the total time spent the easiest way is to: (1) fetch all AFK events for the time period you're interested in, (2) filter by non-AFK events, and (3) sum up the durations.

Example:

```py
from datetime import datetime, time, timedelta
import aw_client
import socket

# Set this to your AFK bucket
bucket_id = "aw-watcher-afk_{}".format(socket.gethostname())

daystart = datetime.combine(datetime.now().date(), time())
dayend = daystart + timedelta(days=1)

awc = aw_client.ActivityWatchClient("testclient")
events = awc.get_events(bucket_id, start=daystart, end=dayend)
events = [e for e in events if e.data["status"] == "not-afk"]
total_duration = sum((e.duration for e in events), timedelta())
print("Total time spent on computer today: {}".format(total_duration))
```

I added the example to the aw-client repo in https://github.com/ActivityWatch/aw-client/commit/120b1f7a89d17ada10a19a34e12990cbbf13afee

**Comment by PEPERSO** [comment]
Hi, thank you for the code ! I'll try to see if it works soon :)
