### ISSUE TITLE
Where the database locate?

### ISSUE THREAD

**Issue by weathon** [ActivityWatch/activitywatch#521]
My has a 500 error when i load the UI, i guess it is because one time I start it with root by mistake. So now I want to change them back. Where is the file locate?

**Comment by ErikBjare** [comment]
The location of the data files depends on your operating system and is decided by [appdirs](https://pypi.org/project/appdirs/). On Unix it is `~/.local/share/activitywatch`.

If you accidentally started it with root, then make there aren't any processes still running in the background (on unix systems, check with: `ps aux | grep aw-`).

If you can't resolve the issues, please provide a more detailed bug report (follow one of the [issue templates](https://github.com/ActivityWatch/activitywatch/issues/new/choose)).
