### ISSUE TITLE
Error when building from source (404 wheel not found)

### ISSUE THREAD

**Issue by osacn** [ActivityWatch/activitywatch#522]
Tried to build from source, but it fails when it can't find a particular wheel file. 

I'm on a Macbook Pro: MacOS Mojave using iTerm
```

Installing the current project: aw-client (0.3.1)
make --directory=aw-watcher-afk build
poetry install
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  HTTPError

  404 Client Error: Not Found for url: https://github.com/ActivityWatch/wheels/raw/master/pyHook-1.5.1-cp37-cp37m-win_amd64.whl

  at /usr/local/lib/python3.9/site-packages/requests/models.py:943 in raise_for_status
      939│         elif 500 <= self.status_code < 600:
      940│             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      941│ 
      942│         if http_error_msg:
    → 943│             raise HTTPError(http_error_msg, response=self)
      944│ 
      945│     def close(self):
      946│         
      947│         called the underlying ``raw`` object must not be accessed again.
make[1]: *** [build] Error 1
make: *** [build] Error 2
```

**Comment by ErikBjare** [comment]
Ah sorry, we made a change in the wheels repo which broke the old commit that's in master. An easy fix for that is to `cd aw-watcher-afk; git checkout master; git pull`. I'll have a general fix done asap.

However, I also notice you're running Python 3.9, which won't work. Please read the building from source guide: https://docs.activitywatch.net/en/latest/installing-from-source.html

**Comment by ErikBjare** [comment]
Should be fixed in https://github.com/ActivityWatch/activitywatch/commit/d76c5ed2347240b0e84285da22f21f3049c7bba7

**Comment by ErikBjare** [comment]
Nevermind, that caused another issue. I'll look into fixing it tomorrow.

**Comment by ErikBjare** [comment]
Alright, now it should be fixed.
