### ISSUE TITLE
Error when Categorization too long

### ISSUE THREAD

**Issue by weathon** [ActivityWatch/activitywatch#536]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**:Lubuntu 20.04
- **ActivityWatch version**: latest (not sure how to check the version)

## Describe the bug

When you add too many things in Categorization, it will have 500 error

## To Reproduce
1. go to setting
2. set the Categorization like this
![image](https://user-images.githubusercontent.com/41298844/102366807-ad3fc980-3f7e-11eb-990d-89104dc57911.png)
3. Go back to Activity
4. 
![image](https://user-images.githubusercontent.com/41298844/102366846-baf54f00-3f7e-11eb-93f9-4f050caf971f.png)
![image](https://user-images.githubusercontent.com/41298844/102366948-d4969680-3f7e-11eb-93da-aacad1416642.png)

![image](https://user-images.githubusercontent.com/41298844/102366980-dc563b00-3f7e-11eb-8e29-bffd09f11e85.png)

**Comment by ErikBjare** [comment]
Why do you think it's caused by a long categorization rule? That's very unlikely.

Your `Work` category looks like it's an empty string, which could cause problems (but shouldn't cause a 500 error).

If you click the 'Response' tab in the request inspector, what does it say?

**Comment by ErikBjare** [comment]
It also looks like you have an unescaped `+` in your regex, which will most definitely cause problems. This is because `+` has special meaning in regular expressions, so it can't be used as a normal character.

The easiest fix is to just remove them, but you can replace `++` with `[+][+]` (or in the next version, where escaping is fixed, with `\+\+`).

**Comment by weathon** [comment]
Oh， it must be the "+" cause the problem. Thank you
