### ISSUE TITLE
Window titles not visible when running Firefox and Firefox Dev Edition

### ISSUE THREAD

**Issue by Valentin-N** [ActivityWatch/activitywatch#538]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: MacOS 10.14.6
- **ActivityWatch version**: 0.10.0

## Describe the bug
When running 2 separate Firefox instances, one using release Firefox and the other one using Firefox Developer Edition, only the titles belonging to the oldest Firefox instance show up in aw-watcher-window. Since both Firefox instances get grouped together under app name "firefox", when using the 2 instances for different purposes it is not possible to reliably categorize the windows as the 2 instances can be started in any order.

## To Reproduce
  1. Install Firefox release edition, e.g. [link](https://ftp.mozilla.org/pub/firefox/releases/84.0/mac/en-US/)
  2. Install Firefox Developer Edition, e.g. [link](https://ftp.mozilla.org/pub/devedition/releases/84.0b8/mac/en-US/)
  3. Start one instance of each Firefox edition, using different profiles.
  4. Navigate to a unique page for each Firefox instance.
  5. Observe the data in bucket aw-watcher-window and notice that only the oldest Firefox instance shows window titles; the youngest Firefox instance shows blank window titles.

## Expected behavior

Titles are recorded for both Firefox instances.

## Additional context

As an alternative or workaround, a way is to be provided to distinguish between the different Firefox instances, e.g. the ability to unbundle "Firefox Developer Edition" from the "firefox" meta-app.

**Comment by Mattwmaster58** [comment]
Using different profiles and Firefox Nightly, I wasn't able to reproduce this. That'd be surprising if it was the stable + dev edition causing this.

**Comment by Valentin-N** [comment]
Using the same steps described above I can still replicate this on a new Macbook running Catalina (10.15.7) and ActivityWatch version 0.11.0. The difference is that now I no longer get an app name at all.

<img width="1437" alt="Screen Shot 2022-01-04 at 14 04 58" src="https://user-images.githubusercontent.com/1926716/148072306-bd733715-b16a-4d26-b773-c41ca17773c0.png">
