### ISSUE TITLE
Unimportant startup problem with aw-qt.ini

### ISSUE THREAD

**Issue by qillerr** [ActivityWatch/activitywatch#539]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 (20H2) 19042.665
- **ActivityWatch version**: v0.10.0

## Describe the bug
Somehow I've had ~20 NUL characters in my aw-qt.ini file and that caused it to crash before start.
Error was displayed as "Failed to execute \_\_main\_\_.py" or something like that

## To Reproduce
1. Have only NULs in aw-qt.ini (in %appdata%\Local\activitywatch\activitywatch\aw-qt directory)
2. Start the program (aw-qt.exe)
3. It throws the error dialog and fails to start

## Documentation
No logs of writing to aw-qt.ini were found. Logs from bash:
```
mewash@DESKTOP-HCTNNQJ MINGW64 ~/AppData/Local/Programs/ActivityWatch
$ ./aw-qt.exe
Traceback (most recent call last):
  File "aw_qt\__main__.py", line 3, in <module>
  File "lib\site-packages\click\core.py", line 829, in __call__
  File "lib\site-packages\click\core.py", line 782, in main
  File "lib\site-packages\click\core.py", line 1066, in invoke
  File "lib\site-packages\click\core.py", line 610, in invoke
  File "aw_qt\main.py", line 24, in main
  File "aw_qt\config.py", line 26, in __init__
  File "lib\site-packages\aw_core\config.py", line 23, in load_config
  File "configparser.py", line 717, in read_file
  File "configparser.py", line 1079, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\mewas\\AppData\\Local\\activitywatch\\activitywatch\\aw-qt\\aw-qt.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

## Additional context
I've just installed this software yesterday, and woken up with this error.
I have launched to see the logs with Git Bash, but initially it happened on startup

**Comment by ErikBjare** [comment]
We've seen this every now and again on Windows. 

Not sure what the cause is (I think @johan-bjareholt speculated in some forum thread though), but we just switched to `toml` configuration in v0.11.0, and hopefully the same won't happen there.
