### ISSUE TITLE
Conflict with qustodio

### ISSUE THREAD

**Issue by weathon** [ActivityWatch/activitywatch#540]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 Home 1909 18363.1256
- **ActivityWatch version**: Latest

## Describe the bug
After install the activity watcher, the Qustodio shows the device is offline.

## To Reproduce
1. Install Qustodio first
2. install aw

**Comment by ErikBjare** [comment]
Sounds like an issue with Qustodio, not with ActivityWatch. Closing.
