### ISSUE TITLE
activitywatch fails to start under supervision

### ISSUE THREAD

**Issue by dbieber** [ActivityWatch/activitywatch#541]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

I'm trying to use supervisor (http://supervisord.org/) to run and monitor activitywatch.
I have tried having supervisor manage aw-qt as well as individual processes e.g. aw-server, aw-client.

Starting these processes manually outside of supervisor works fine, both as my user and as root.
However, starting any of these processes under supervisor fails instantly without logs.
I expect that the issue may be that the parent process is exiting, and then supervisor considers it done and cleans up any child processes. Is that consistent with the way e.g. aw-server starts up? (I haven't verified this theory yet.)

**Comment by johan-bjareholt** [comment]
>  I expect that the issue may be that the parent process is exiting, and then supervisor considers it done and cleans up any child processes. Is that consistent with the way e.g. aw-server starts up? (I haven't verified this theory yet.)

This is not the case.

aw-server and aw-server-rust both support running within systemd and they both work fine that way.
Also, aw-qt is pretty much a process manager in itself, so putting that within yet another process manager seems like a bad fit (especially considering that it also has a GUI).

I'm closing this as it has little to do with activitywatch in itself, but with supervisor.
If you do find some strange unexpected behaviour though that could be an bug/issue, feel free to open a new issue that is more specific.

**Comment by dbieber** [comment]
I had gotten my instance of supervisor into a bad state. I think the reason for this was that I switched my python installation from 3.9 to 3.7 in order to successfully build activitywatch. Restarting supervisor resolved the issue with supervisor. I expect it will be able to manage aw now but haven’t confirmed this yet.

**Comment by dbieber** [comment]
OK, it's up and running, working fine. No problems managing aw-server and my two aw-watchers using supervisor.
