### ISSUE TITLE
WebUI extremely slow after computer idles overnight

### ISSUE THREAD

**Issue by prplecake** [ActivityWatch/activitywatch#550]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 20H2
- **ActivityWatch version**: 0.10.0

## Describe the bug
WebUI is extremely sluggish after computer idles overnight. Taking ~1-2 minutes to load the interface.

To resolve the issue, I have to do a full restart of my machine. Simply quitting AW and restarting it doesn't resolve it.

## To Reproduce
1. Make sure AW is running.
2. Let your computer idle overnight.
3. Refresh WebUI. Not how slow it loads.

## Expected behavior
No difference in load times after idling overnight.

## Documentation
There aren't any errors logged.

**Comment by ErikBjare** [comment]
That's weird, I've never heard anyone have this issue before.

Can you check your process manager and check which process is actually using resources? (is it your browser or aw-server?)

**Comment by prplecake** [comment]
> Can you check your process manager and check which process is actually using resources? (is it your browser or aw-server?)

Can do. I haven't seen this issue reoccur yet, I thought leaving the machine idle over the weekend would get it to reproduce.

I'll keep an eye on it over the next week.

**Comment by ErikBjare** [comment]
Might be related to https://github.com/ActivityWatch/activitywatch/issues/460

**Comment by prplecake** [comment]
> I haven't seen this issue reoccur yet, I thought leaving the machine idle over the weekend would get it to reproduce.
> 
> I'll keep an eye on it over the next week.

Still haven’t seen this issue reappear. There must’ve been something else going on at the time. (Perhaps one of the watchers I was using was sending AW bad data and causing problems loading the WebUI.)

**Comment by prplecake** [comment]
I think I'm seeing this again. It took about a minute for the webpage to load with Firefox showing CPU usage around 5% and aw-server showing about 0.3%.

After the slow load, subsequent loads are quick. I wonder if Firefox isn't building a cache at first page load. What's odd is I already have AW loaded in a tab, so wouldn't Firefox already have a cache?

**Comment by johan-bjareholt** [comment]
> After the slow load, subsequent loads are quick. I wonder if Firefox isn't building a cache at first page load. What's odd is I already have AW loaded in a tab, so wouldn't Firefox already have a cache?

Yes, firefox should have cached most things in the web-ui except for the actual usage data (which comes from aw-server).

When you say "idle overnight", do you mean a desktop just doing nothing and being turned on or an laptop/desktop being suspended or hibernated? If suspended/hibernated, my guess would be that when you open the web-ui it will make a request to aw-server, but that request will take a long time due to having to read a lot of data from the HDD/SSD which is likely under a lot of load right after a suspend/hibernation. 

But that's just a guess.

**Comment by prplecake** [comment]
> When you say "idle overnight", do you mean a desktop just doing nothing and being turned on or an laptop/desktop being suspended or hibernated?

Well, it’s a laptop but it’s docked so in the context of this question let’s call it a desktop. It’s on all the time when docked. 

I’ve been meaning to grab the source and see if I can’t get better insight into what’s going on. It might be helpful to see which requests are taking the longest time, I’ll share that data next time.

I haven’t noticed this on macOS at all, even when it wakes from sleep.

**Comment by prplecake** [comment]
I wanted to close this before @stale-bot did cause 1) it’s hardly reproducible and 2) I fucking hate projects that close issues like this. 

It’s not not an issue necessarily because some time has passed, what gives?
