### ISSUE TITLE
Activity of apps created with Coherence X not shown in the correct category

### ISSUE THREAD

**Issue by wenlzhang** [ActivityWatch/activitywatch#555]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **macOS Big Sur 11.1**: 
- **0.10.0**: 

## Describe the bug

Activity of apps created by using Coherence X, an app that turns websites into apps, would not show in the correct category. For instance, if the app Google Calendar is created by using the Google Chrome browser, then the activity of Google Calendar would show as Google Chrome, instead of Google Calendar. Coherence can be found on the following website:
https://www.bzgapps.com/coherence

## To Reproduce
  1. Create an app by using Coherence X
  2. Observe the activity of the app in ActivityWatch

## Expected behavior

The activity of an app created by using Coherence X would show by the app name, instead of the browser name.

**Comment by ErikBjare** [comment]
Not much we can do about it, it's an issue with Coherence X not setting their appname properly.

If you are writing categorization rules, use the window title instead of the appname in your category rule.

**Comment by wenlzhang** [comment]
I tried both the app name and window title in the categorization rules, and they are counted on as browser activity.

**Comment by ErikBjare** [comment]
How do your rules look? Have you ensured that the more specific rule is deeper than your 'browser activity' rule?

**Comment by wenlzhang** [comment]
> How do your rules look? Have you ensured that the more specific rule is deeper than your 'browser activity' rule? (since both will match, I assume)

I created separate rules for Google Calendar and Google Chrome. By "browser activity", I meant that the activity of Google Calendar was counted on as that of Google Chrome. For illustration purpose, my rules were created like the following:

- Internet
  - Google Chrome: Rule (regex): Google Chrome
- Calendar
  - Google Calendar: Rule (regex): Google Calendar

**Comment by ErikBjare** [comment]
Since the first rule matches both events, you need to place the second one in a deeper category for it to take priority (as briefly mentioned at the top of the categorization rules settings).

As an example, this should work:

- Internet (No rule)
  - Google Chrome (Rule (regex): Google Chrome)
- Planning (No rule)
  - Calendar (No rule)
    - Google Calendar (Rule (regex): Google Calendar)

Or this:

- Internet (Rule (regex): Google Chrome)
- Calendar (No rule)
  - Google Calendar (Rule (regex): Google Calendar)

**Comment by wenlzhang** [comment]
Thanks for the detailed explanations.

I tried the second method and the statistics did not change. The activity of Google Calendar is shown as Google Chrome.

**Comment by ErikBjare** [comment]
But if you followed the second example, then you should no longer have a Google Chrome category? Did you not try the first one? (they should be equivalent)

If you remove the "Internet"/"Google Chrome" category all together, does it correctly classify the calendar events?

Perhaps you misunderstood me: the "Top Applications" won't ever change, but the "Top Categories" should. 

I'm fairly certain it should work if you follow/understand the instructions correctly, as the categorization code has extensive tests.

**Comment by wenlzhang** [comment]
> But if you followed the second example, then you should no longer have a Google Chrome category? Did you not try the first one? (they should be equivalent, but wouldn't hurt to try)

I just tried both methods, and they did not work for me.

> If you remove the "Internet"/"Google Chrome" category all together, does it then correctly classify the calendar events?

When I remove the "Internet"/"Google Chrome" category all together, the event would not be classified as calender events. Instead, it would be classified as "Uncategorized".

> Perhaps you misunderstood me: the "Top Applications" won't ever change, but the "Top Categories" should.

Indeed, I was checking on the "Top Applications" before this post ...

> I'm fairly certain it should work if you follow/understand the instructions correctly, as the categorization code has extensive tests.

I am not sure why this happened for me. Maybe it is related to how Coherence X handled this ...

**Comment by ErikBjare** [comment]
Is the title of the window Coherence X creates actually "Google Calendar" then?

You can check by having the calendar open for a few seconds, then navigating to 'Raw data' -> Click 'open' on the window bucket -> Check that the 'title' property is actually 'Google Calendar'.

**Comment by wenlzhang** [comment]
After checking the raw data, it turns out the value of the key "app" is "Google Chrome" and the value of the key "title" is empty.

**Comment by ErikBjare** [comment]
Oh, that explains it. 

Can you see any other window titles in ActivityWatch? Might be related to a permissions issue on macOS (if you restart ActivityWatch it should ask you to give accessibility permissions). Note that you need to remove it from the list (not just uncheck/recheck the box) and then re-add it if you've updated the `.app`.

**Comment by wenlzhang** [comment]
I was not able to see any window titles in ActivityWatch. After resolving the permission issue, I can see window titles for all apps now.

The title for Google Calendar is now "Google Calendar - Week of 25 January 2021", as I used the Weekly View. I can use this title for setting category rules. However, in the next week, the title would change and the rule would probably not work. This may also happen for other apps created with Coherence X because the window title may change when the address changes. Is there a workaround for this?

**Comment by ErikBjare** [comment]
You don't need the full title in the rule, just "Google Calendar" should
suffice.

**Comment by wenlzhang** [comment]
Great! It works for me now.

**Comment by wenlzhang** [comment]
After further testing, I found that the activity of Dynalist (for dynalist.io) created by using Coherence cannot be recorded by ActivityWatch. The window title of the Dynalist app include the keyword “Dynalist”. However, the activity of Dynalist cannot be recognized by ActivityWatch, and the title field in the ActivityWatch raw data is empty.
