### ISSUE TITLE
AW can't read windows titles when upgrade to macOS Big Sur 

### ISSUE THREAD

**Issue by IIPatternII** [ActivityWatch/activitywatch#557]
**Hi! First of all, thank you for the app! Now, here goes the report:**

 - [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: macOS Big Sur 11.1
- **ActivityWatch version**: 0.10.0

## Describe the bug

**Activity Watch can't read window titles:**

![image](https://user-images.githubusercontent.com/48034748/106396637-01482580-63e8-11eb-8051-119093cd9e26.png)

**aw-watcher-window events:**

![image](https://user-images.githubusercontent.com/48034748/106396831-3739d980-63e9-11eb-9850-c75354240f4c.png)

## To Reproduce

1. Have already installed AW
2. Update to macOS Big Sur 11.1

## Expected behavior

AW reads titles and classifies time following regex rules.

**Comment by ErikBjare** [comment]
Probably a duplicate of https://github.com/ActivityWatch/activitywatch/issues/376

Have you tried the workaround described there? (re-add ActivityWatch to accessibility permissions, not just uncheck/recheck box)

**Comment by IIPatternII** [comment]
It was indeed a duplicate. 
The workaround (remove and re-add ActivityWatch to accessibility permissions) worked!

The underlying problem is addressed on #376, so I will close this issue.

Thank you @ErikBjare !
