### ISSUE TITLE
Timeline visualization (barchart) should start at the day start of day time

### ISSUE THREAD

**Issue by AugustoQueiroz** [ActivityWatch/activitywatch#562]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

The Timeline (barchart) visualization on the web interface always goes from 0:00 to 23:59. Considering the interface has a start of the day setting for when to consider activity as happening in one day or another, this setting should be taken into account when producing the bar plot. As of now, activity done between midnight and whatever time the day is considered to start at will not show up on the plot, as it happened after the axis limit on one day, and is not accounted for in the next day. This doesn't seem to be a bug per se.

**Comment by ErikBjare** [comment]
This is fixed in https://github.com/ActivityWatch/aw-webui/pull/254 and will be in the next release :)

**Comment by AugustoQueiroz** [comment]
Ah, awesome, thanks! Sorry if I overlooked that!
