### ISSUE TITLE
Outdated docs for writing first watcher with heartbeat on v0.10.0

### ISSUE THREAD

**Issue by nickderobertis** [ActivityWatch/activitywatch#564]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 20.04
- **ActivityWatch version**: 0.10.0

## Describe the bug
I tried to run the second example from the documentation page ["Writing your first watcher"](https://docs.activitywatch.net/en/latest/examples/writing-watchers.html) which shows how to implement a heartbeat event. First, the code would not run, because `ActivityWatchClient.hostname` does not seem to exist anymore, I had to update line 17 to use `client.client_hostname` instead of `client.hostname`. Then it was able to run successfully, but the heartbeat events do not seem to work as expected. I get the following output from the script:

```
Sending heartbeat 0
Sending heartbeat 1
Sending heartbeat 2
Sending heartbeat 3
Sending heartbeat 4
[{'id': 1, 'timestamp': datetime.datetime(2021, 2, 11, 15, 39, 12, 347000, tzinfo=datetime.timezone.utc), 'duration': datetime.timedelta(0), 'data': {'label': 'non-heartbeat event'}}]
```

## To Reproduce
Run the second example from the documentation page ["Writing your first watcher"](https://docs.activitywatch.net/en/latest/examples/writing-watchers.html)

## Expected behavior
The comment in the script says that the output should show two events, one for the non-heartbeat event and one for the heartbeat event, with duration of 5 seconds. In the output I am only getting the non-heartbeat event, so I am not sure what needs to be done to get the heartbeats working appropriately. 

## Additional Comments

Thanks for your work on this awesome project! I'm trying to write a watcher which has a small GUI to let me select which project I'm working on, as I want to log time spent on some open-source projects under other projects because I develop the features to support the other projects, and a rules-based approach won't work because I may want to assign time from an open-source project to multiple other projects.

**Comment by nickderobertis** [comment]
I notice that if I remove `queued=True` from the `client.heartbeat` command in line 47, then I do get the expected output. I have also tried adding a sleep at the end before getting the events, and that did not help. So it seems for some reason queued events may not be working properly, or the API has changed around them. Anyway, I should be able to move forward on development for now excluding `queued=True`.

**Comment by johan-bjareholt** [comment]
Thank you for the feedback!

I will push the fix for client.client_hostname to the documentation.

Regarding removing queued=True, we want an example with queueing as it's much more efficient. An alternative solution would be to set commit_interval=4.0 as an argument to heartbeat.
The reason why it did not show up before was because since the default commit_interval is 5 seconds and the difference between the first and last heartbeat is just 4 seconds it will not be commited to aw-server.

**Comment by nickderobertis** [comment]
Thanks for the quick fix! I took the changes from the PR and added them to my application and now it is successfully sending queued events. My app is working well to report the currently active project and switch via the system tray: https://github.com/nickderobertis/aw-watcher-project

Haven't had time to write up good docs yet but it is working well for me for now.

**Comment by johan-bjareholt** [comment]
I'll have to mention though that there is currently no easy way to add visualizations for non-official watchers in the web-ui, so you will either have to modify aw-webui or write your own application which queries aw-server.

I feel particularily sorry for the guy who wrote https://github.com/Alwinator/aw-watcher-table and hoped to be able to easily add his own visualizations to the web-ui, but has not been able to for quite some time now. Just so you know!

**Comment by nickderobertis** [comment]
Yes, thanks for the heads up, I thought about integrating this into the web UI, but thought it would be most convenient as a system tray app. The web UI was useful to determine the correct query to get the data but from there I am generating a PDF report so seems a bit out of scope for the web UI anyway. 

I do think it'd be great if there was some kind of plugin structure for the web UI, and if there was I would implement the reporting feature using it. But of course that would be time-consuming and I know time is always limited in open source :) For now I just have the reporting in a separate project customized to my use case.

My aw-watcher-project app is working well for my use case. Hopefully I'll find some time to write up some docs. Maybe after that you could include it on the watchers page if you think anyone else would find it useful.
