### ISSUE TITLE
Timeline should remember the last setting

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/activitywatch#567]
It would be convenient if the timeline (http://localhost:5600/#/timeline) would remember the last
setting.

I usually look at the 2h timeline. We use a commercial web based time tracker, and i use ActivityWatch to fix my times, if I forgot to press the button in the commercial tool.

I never want to see the 12h view which I see by default.

**Comment by ErikBjare** [comment]
There's an option in the settings to change the default.

![image](https://user-images.githubusercontent.com/1405370/108504600-7061bd00-72b6-11eb-8346-8eb6fa8e7940.png)
