### ISSUE TITLE
Multiple watchers sending to remote server documentation

### ISSUE THREAD

**Issue by kovasap** [ActivityWatch/activitywatch#572]
Based on my read of the documentation and issues like #249, it seems possible to have a single activitywatch server (running on a local network or in the cloud) and multiple watchers on different devices all sending data to that server.  However, I can't find a cohesive documentation page that describes how to do this and affirms that doing this is a supported use of AW.  For instance, I'm not sure if doing this is secure, or if there are other gotchas that would prevent this kind of setup.  

For my case, I'm interested in having two computers and my android phone send to this server.

I'd be interested in helping make this doc page happen, but probably would need to discuss a lot with more experienced users to make sure I'm not missing anything.

- [x ] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by johan-bjareholt** [comment]
This has been discussed a lot of times, both on GitHub and on the forum.

But in short:
- It supported, but not recommended and the feature might be removed in the future
- How to change aw-server to bind to a non-local address is documented in the official documentation
- No authentication or security, so if anything use it within a VPN or local network but preferably don't use it at all
- The idea is that it will be replaced by syncing between devices in the future
- The browser extension does not support it (likely many other 3rd-party watchers too)

**Comment by kovasap** [comment]
Ah got it.  Is there an open issue for the syncing work?  I've been rolling
my own syncing with selfspy before I came across this project, and I'm
curious what the plans are here and if I could help with them.

**Comment by johan-bjareholt** [comment]
The "big" issue is the following:

https://github.com/ActivityWatch/activitywatch/issues/35

But regarding progress, it's been stale for a while now unfortunately and I think this was the latest activity:

https://github.com/ActivityWatch/aw-server-rust/pull/71

The idea is to have one database per device and then each device only have read access to the database it owns itself. Then you can put a folder of each database in a folder of your choice which can be synced with whatever syncing provider you'd want such as Google Drive, Syncthing, Dropbox etc.

**Comment by ErikBjare** [comment]
I've added documentation for this in https://github.com/ActivityWatch/docs/pull/60/files

**Comment by kovasap** [comment]
Ok thanks for the update.  And thanks Erik for adding the doc page!!
