### ISSUE TITLE
Incorrect display of icons in the list of Windows apps

### ISSUE THREAD

**Issue by rakleed** [ActivityWatch/activitywatch#577]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 v. 20H2
- **ActivityWatch version**: 0.10.0

## Describe the bug
In "Settings - Apps - Apps & features" and "Control Panel - Programs - Programs and Features" in Windows 10, the application icon is displayed incorrectly - as if the icon was simply not added.

## To Reproduce
    1. Install ActivityWatch on Windows
    1. Go to "Settings - Apps - Apps & features" or "Control Panel - Programs - Programs and Features"
    3. Scroll down to ActivityWatch
    4. Look at the icon opposite ActivityWatch

## Expected behavior
The application icon is displayed opposite the name of ActivityWatch.

## Documentation

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/19418601/111845980-fe14e480-8916-11eb-8426-2beac07d415c.png)

![image](https://user-images.githubusercontent.com/19418601/111845496-04ef2780-8916-11eb-8a59-96e26525daff.png)

</details>

## Additional context
This information will probably be useful - http://www.jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayicon.
To fix this, you most likely need to add UninstallDisplayIcon in the registry.

**Comment by johan-bjareholt** [comment]
Thanks for reporting!

I did an attempt, but currently have no easy access to a Windows computer.

https://github.com/ActivityWatch/activitywatch/pull/578
