### ISSUE TITLE
Modifying "Media" or "Comms" category causes TypeError: n is undefined

### ISSUE THREAD

**Issue by kaeltis** [ActivityWatch/activitywatch#580]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version. (latest "nightly" from AppVeyor)
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 20H2
- **ActivityWatch version**: v0.10+commit.1fca356121a54f3feb8fcc583702871be5ed0a35

## Describe the bug
When modifying (for example changing the name or assigning a color) one of the default categories `Media` or `Comms`, the changed category is duplicated to the bottom of the list and the original is unchanged. This does not happen for any of the other categories.

## To Reproduce
1. Go to Settings
2. Click the Edit button next to `Media` or `Comms`
3. Change the name or assign a color
4. Click `Ok`
5. Notice modal does not close, duplicate category in list and error at the top of page and in browser's console

## Expected behavior
These two categories should be changeable like the other ones without causing duplicates or errors.

## Documentation
```
TypeError: n is undefined
    updateClass categories.js:79
    T vuex.esm.js:840
    commit vuex.esm.js:462
    commit vuex.esm.js:461
    _withCommit vuex.esm.js:620
    commit vuex.esm.js:460
    commit vuex.esm.js:405
    handleSubmit CategoryEditTree.vue:168
    handleOk CategoryEditTree.vue:153
    VueJS 4
    hide modal.js:565
    onOk modal.js:756
    VueJS 37
    mountTarget transporter.js:128
    beforeMount transporter.js:94
    VueJS 22
    resetModal CategoryEditTree.vue:184
    VueJS 4
    emitEvent modal.js:716
    show modal.js:537
    showEditModal CategoryEditTree.vue:143
    click CategoryEditTree.vue:1
    VueJS 33
vue.runtime.esm.js:1888:12
```

## Additional context
Seems to be related to closed issues #313 and #317 - however the category `Uncategorized` can be changed without problems even though it also has Rule Type `None` , maybe it's caused by `Media` and `Comms` not having a color assigned?

**Comment by ErikBjare** [comment]
Having the same issue, I think I find the culprit and am on it.
