### ISSUE TITLE
Categorize Geary under Comms/Email

### ISSUE THREAD

**Issue by gabrc52** [ActivityWatch/activitywatch#581]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

The Geary (GNOME default email) email client should be categorized under Comms/Email.

**Comment by ErikBjare** [comment]
There is discussion around improving the defaults here: https://github.com/ActivityWatch/aw-webui/issues/174, where Geary is already mentioned.

Closing.
