### ISSUE TITLE
Adding 2 or more categories at once, they got the same name, even if you change it.

### ISSUE THREAD

**Issue by jairofloress** [ActivityWatch/activitywatch#582]
Version: v0.10.0
To reproduce, go to settings and add more than categories at the same time below any category.
When you assign the name for one of the new, the other get the same name.
If you go to the second and try to change the name, the first one gets the second name.
I hope this helps.
Thanks.

[aw-qt_2021-03-26T00-09-49.log](https://github.com/ActivityWatch/activitywatch/files/6217479/aw-qt_2021-03-26T00-09-49.log)
[aw-server_2021-03-26T00-09-52.log](https://github.com/ActivityWatch/activitywatch/files/6217480/aw-server_2021-03-26T00-09-52.log)
[aw-watcher-afk_2021-03-26T00-09-52.log](https://github.com/ActivityWatch/activitywatch/files/6217481/aw-watcher-afk_2021-03-26T00-09-52.log)
[aw-watcher-window_2021-03-26T00-09-51.log](https://github.com/ActivityWatch/activitywatch/files/6217482/aw-watcher-window_2021-03-26T00-09-51.log)

**Comment by johan-bjareholt** [comment]
Thanks, this issue was easy for me to reproduce.
Will take a look at it.

**Comment by ErikBjare** [comment]
I'm pretty sure this has been reported somewhere else before.

I added some changes in https://github.com/ActivityWatch/aw-webui/pull/293 which makes this a lot less likely to occur (the modal opens immediately when you create a new category). But the bug itself isn't fixed.
