### ISSUE TITLE
Track light sensor / proximity sensor / microphone

### ISSUE THREAD

**Issue by franz101** [ActivityWatch/activitywatch#588]
See title. Couldn't find a way / plugin. Would it be possible to record those sensors every day 30 min for 20 seconds?

**Comment by ErikBjare** [comment]
I don't know what you are asking for, but this is probably not the right place to ask.

You'll probably have to write a watcher for that yourself, see the other watchers in the documentation for examples: https://docs.activitywatch.net/en/latest/watchers.html
