### ISSUE TITLE
Less clicks to get to the desired data

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/activitywatch#589]
![image](https://user-images.githubusercontent.com/414336/115011855-65d73480-9eaf-11eb-80a8-3e530e08f5e0.png)

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

My main use case for ActivityWatch is to see when I left my PC before the break. I sometimes forget to switch off the automatic time tracking of the company I work for (they use toggl).

Now I want to know: When did I start my break?

Above screenshots shows that I need a lot of clicks to get to the desired data. I need several clicks to get to the Timeline.

I think it would be great if  I could get there with less effort. Overall goal: reduce cognitive load.

**Comment by johan-bjareholt** [comment]
I'm not sure if it's available in the latest release, but in the development version it's possible to set the default view to "timeline" in settings, so that's one less click at least.

**Comment by ErikBjare** [comment]
You could also just create a bookmark or some other shortcut to the timeline view.

But yeah, as @johan-bjareholt mentioned this should be improved in the next version where you can set the "landing view".
