### ISSUE TITLE
Change in source code failed to compile 

### ISSUE THREAD

**Issue by daynial** [ActivityWatch/activitywatch#595]
![change](https://user-images.githubusercontent.com/16184163/116228659-03175000-a76f-11eb-8ad5-279cf08cb5ac.PNG)

i have just remove a word in home.vue file after which there is error in compiling the aw-server as follows
![bug](https://user-images.githubusercontent.com/16184163/116228683-0ca0b800-a76f-11eb-9b7e-f295438c61ec.PNG)

Please help

**Comment by ErikBjare** [comment]
The error is pretty clear. I assume the file permissions changed when you saved the file, you need to fix them somehow. I don't have a good understanding of how permissions work on Windows/WSL, so you're on your own here, but there's this: https://stackoverflow.com/questions/38323880/error-eacces-permission-denied

And if this is related to #593, I implore you to reconsider and choose another software for employee monitoring. See https://docs.activitywatch.net/en/latest/remote-server.html
