### ISSUE TITLE
WebUI: missing icon (or character?) in front of categorization rules

### ISSUE THREAD

**Issue by pabuisson** [ActivityWatch/activitywatch#596]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version
- [x] I have searched the issues of this repo and believe that this is not a duplicate.

Versions

- **OS name and version**: MacOS 11.2.3
- **ActivityWatch version**: Version: v0.10.0

## Describe the bug

In the web UI, in the settings tab, in the categorization section: each rule line is prefixed with something (I suppose an icon, or a particular character). For me, this appears like this, with every adblocker turned off:

<img width="472" alt="Capture d’écran 2021-04-28 à 14 22 52" src="https://user-images.githubusercontent.com/769918/116403327-b9da0580-a82d-11eb-8184-c95be37a7f21.png">

As you can see on the screenshot, categories don't have this missing character, only rules have this.

## To Reproduce

Steps to reproduce the behavior, for example:

1. Open the web UI
2. Go to the settings tab
3. Scroll down to Categorization

## Expected behavior

I have no idea what should be shown here. Maybe a platform problem, something compatible with windows or linux OS but no MacOS ? 

## Documentation

NTR

## Additional context

NTR

**Comment by ErikBjare** [comment]
This is an issue in some browsers due to the fonts missing the unicode character used.

It has been fixed and will be in the next release.

**Comment by pabuisson** [comment]
I did not find any issue related to this, sorry for the noise then. And thanks for the fix 👍

**Comment by ErikBjare** [comment]
There was never an issue opened for it :)

No worries, thanks for taking the time to report it! (and sorry for being
slow on making a new release)
