### ISSUE TITLE
I have executed this project but it gives only application name and it's title only. I need URL that is not given by it.

### ISSUE THREAD

**Issue by bharat303** [ActivityWatch/activitywatch#597]
- [ ] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by ErikBjare** [comment]
I'm not entirely sure what you are asking, but this is probably not the right place to ask.

You need to use the aw-watcher-web web extension to collect URLs, see: https://github.com/ActivityWatch/aw-watcher-web
