### ISSUE TITLE
TypeError: can't convert undefined to object

### ISSUE THREAD

**Issue by Hocuri** [ActivityWatch/activitywatch#598]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Manjaro, Kernel 5.9.16-1-MANJARO
- **ActivityWatch version**: v0.10.0

## Describe the bug
Every time I hit "OK" on the Edit category dialog, instead of the window closing, this message appears:
"TypeError: can't convert undefined to object. See dev console (F12) and/or server logs for more info."

## To Reproduce
Go to Settings
Hit "Add new category" at the bottom
Click "Edit" on the new category
Optional: Change pattern or name
Hit "OK"

## Expected behavior

The changes should be applied and the window should close.

## Documentation

![Screenshot_2021-05-01_15-31-47](https://user-images.githubusercontent.com/18012815/116784021-33722d80-aa92-11eb-9cd7-967f3d7eea30.png)
![Screenshot_2021-05-01_15-33-00](https://user-images.githubusercontent.com/18012815/116784067-69171680-aa92-11eb-8f54-d6ca96cc4e1c.png)

I can post logs, but which ones do you want? aw-qt/, aw-server/,          aw-watcher-afk/,     aw-watcher-window/?

**Comment by ErikBjare** [comment]
I think the dev console logs should be the most helpful. 

But tbh there's a fair chance it has already been fixed in master (we've been slow with making a new release).

**Comment by Hocuri** [comment]
So, shall I wait for the release or send the console logs?
