### ISSUE TITLE
Error in directions from virtualenv

### ISSUE THREAD

**Issue by theguybieber** [ActivityWatch/activitywatch#60]
README.md has this command to great a virtual environment:

virtualenv venv --python=python3 --clear

This does not work. Here is the python3 recommended way (which works):

python3 -m venv venv

**Comment by johan-bjareholt** [comment]
Thanks a lot for the help!

I think both me and @erikbjare usually don't run activitywatch in virtualenv, but still recommend it due to aw not being complete and doesn't have a 1.0 release yet.

Fixed this in a4b67a0

**Comment by ErikBjare** [comment]
I frequently run ActivityWatch in a virtualenv. Not sure why the plain `virtualenv` command didn't work for you (might be different on platforms) but thanks for pointing it out. The `python3 -m` method sure is better, thanks @theguybieber!

**Comment by johan-bjareholt** [comment]
@ErikBjare We both usually run either linux or windows though, I'm guessing that neither of us have tested virtualenv on mac before? Might have been an incompatability there?

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah, probably something along those lines I assume.

@theguybieber What was the exact error you were getting? How did it "not work"?

**Comment by theguybieber** [comment]
Weird. I just tried it again and it's working. Before it wasn't generating all the files in the venv/bin directory. In particular, none of the activate scripts you need to source to run in the virtual environment.
