### ISSUE TITLE
changing window title using xdotool is not reflected in acitivitywatch

### ISSUE THREAD

**Issue by ahmednofal** [ActivityWatch/activitywatch#601]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 20.04 
- **ActivityWatch version**: Version: v0.10.0 

## Describe the bug
Changing window title using xdotool does not get reflected in actiyivitywatch. It still sees the old title instead.
## To Reproduce

 I have been using the regex engine included to separate work from entertainment and it works like a charm, however I would like to be able to separate with a single key-binding between different parts of work, without having to set a certain window name or application permamenantly to be under a certain category. So I have been using this command instead to change the window title 

`ORIGINAL=$(xdotool getactivewindow getwindowname)`
`xdotool getwindowfocus set_window --name "$1 () $ORIGINAL"`

where $1 is the argument passed to the script containing those last two command. So I can bind different keys on my keyboard to pass in different values for $1 and hence I can control which windows fall under which regex.
But so far activitywatch is not seeing the change

## Expected behavior
I expect that when I use xdotool to change the window title (to include a regex used by a category in activitywatch) to be detected as part of the category and have the window title change, but it stays the same and within the old category

**Comment by johan-bjareholt** [comment]
I answered this question on the forums

https://forum.activitywatch.net/t/how-to-change-the-window-title-so-that-you-can-force-some-windows-to-fall-into-some-regex-space/1252/2?u=johan-bjareholt

**Comment by ahmednofal** [comment]
Works like a charm, thank you for your for the quick reply and effort. I would like to share the script I am using. 

    #!/bin/sh

    CURR_WIN_TITLE=$(xdotool getactivewindow getwindowname)
    NO_SEPARATOR=$(sed 's/ () //g' <<< $CURR_WIN_TITLE)
    NO_SPECIFIC_STRING_MARKER=$(sed 's/specific_string_marker//g' <<< $NO_SEPARATOR)
    ORIGINAL=$(sed 's/specific_string_marker_2//g' <<< $NO_SPECIFIC_STRING_MARKER)
    WINDOWID=$(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2)
    xprop -id "$WINDOWID" -f _NET_WM_NAME 8u -set _NET_WM_NAME "$1 () $ORIGINAL"

if the script name on you machine is `change_wtitle.sh` You can invoke it like this:
1- ` ./change_wtitle.sh <specific_string_marker>` 
or for the second marker
2- ` ./change_wtitle.sh <specific_string_marker_2>` 

I bind a key to do 1 and another key to do 2
