### ISSUE TITLE
Not working in 32 bit OS

### ISSUE THREAD

**Issue by wurstisgood** [ActivityWatch/activitywatch#605]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- **ActivityWatch version**: 

## Additional context

![image](https://user-images.githubusercontent.com/70360301/121718837-5ca9c300-cb00-11eb-9a11-a121612498db.png)

**Comment by ErikBjare** [comment]
As mentioned in other issues, unfortunately we do not and will not support 32bit Windows (too much work).

**Comment by wurstisgood** [comment]
ok i will use procrastitracker
