### ISSUE TITLE
Dark Mode & UI changes

### ISSUE THREAD

**Issue by Albonycal** [ActivityWatch/activitywatch#606]
This project is awesome but it still needs some improvement
The webUI looks dated & lacks dark mode (which would be a great relief for my eyes :D )
(I'm ready to provide additional feedback)
Thank you

**Comment by ErikBjare** [comment]
Issues are not the right place for feature requests or feedback.

If you search, you'll find other comments already dealing with both dark mode and the general design, both in the issues and on the forum. Leave a comment there instead!
