### ISSUE TITLE
Enable button doesnt work

### ISSUE THREAD

**Issue by SuperMonkeyAZ** [ActivityWatch/activitywatch#608]
I noticed that even when I unclicked enable, the timers were still going. I don't know if its intentional but it doesn't work.

**Comment by ErikBjare** [comment]
So many questions.

What button? What timer? What version?

Please use an issue template and include the needed details.

**Comment by ErikBjare** [comment]
Closing due to no reply. Feel free to create a new issue with the necessary details.
