### ISSUE TITLE
Is the Linux version ready to install?

### ISSUE THREAD

**Issue by sojusnik** [ActivityWatch/activitywatch#610]
ATM the [latest Linux version](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.11.0) is linked wrongly:

IS: https://github.com/ActivityWatch/activitywatch/releases/download/v0.11.0/activitywatch-v0.11.0-linux-x86_64.dmg
SHOULD: https://github.com/ActivityWatch/activitywatch/releases/download/v0.11.0/activitywatch-v0.11.0-linux-x86_64.zip

Is this due to a glitch or is the Linux version not ready for installation?

**Comment by ekianjo** [comment]
Indeed should be this link, probably a c&p issue
https://github.com/ActivityWatch/activitywatch/releases/download/v0.11.0/activitywatch-v0.11.0-linux-x86_64.zip

**Comment by ErikBjare** [comment]
Yes, indeed a hasty copy-paste issue. Fixed.
