### ISSUE TITLE
TypeError: t is undefined on activity and timeline view

### ISSUE THREAD

**Issue by TheTimeWalker** [ActivityWatch/activitywatch#612]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Manjaro Linux KDE 5.22.1
- **ActivityWatch version**: 0.11.0
- **Firefox version**: 89.0.1

## Describe the bug

After updating to the latest version, I now always get an error that says `TypeError: t is undefined`. This happens on both the Activity view as wel las timeline view. With this I also only get a grey color for all bars and the starburst graph only on the activity view.

## To Reproduce

1. Update from 0.10.0 to 0.11.0
2. Open the Activity view

## Expected behavior

All the bars are colored accordingly and I don't get an error message

## Documentation

Firefox log:
```
TypeError: t is undefined
    datasets TimelineBarChart.vue:99
    Lodash 10
    value TimelineBarChart.vue:99
    value TimelineBarChart.vue:50
    VueJS 10
    query_category_time_by_period_completed activity.ts:499
    T vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    commit vuex.esm.js:796
    r activity.ts:302
    l runtime.js:63
    k runtime.js:293
    x runtime.js:118
    Babel 2
vue.runtime.esm.js:1888:12
    VueJS 13
    query_category_time_by_period_completed activity.ts:499
    T vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    commit vuex.esm.js:796
    r activity.ts:302
    l runtime.js:63
    k runtime.js:293
    x runtime.js:118
    Babel 2
 ```

**Comment by satcom886** [comment]
I can also reproduce this issue. I also tried deleting `~/.local/share/activitywatch` and the problem persists.

**Comment by ErikBjare** [comment]
@satcom886 Categories (the likely culprit) are not stored in that folder, try resetting them to defaults from the settings (you can export them before you do so).

**Comment by satcom886** [comment]
@ErikBjare Yep, that helped. It's gone now.

**Comment by ErikBjare** [comment]
It would be really helpful if someone could send me their exported categories that cause the error. I think I have a fix, but since I can't reproduce, it's difficult to be sure.

**Comment by satcom886** [comment]
Unfortunately I didn't export them, as I didn't really have a reason to.

**Comment by kulbhushanchand** [comment]
Hi @ErikBjare,

Please find the exported categories that cause the error at  https://gist.github.com/kulbhushanchand/a3f9ff3001df1a22e5e01a93be339dc8

PS.- I'm the author of the comment that you have referenced above at https://github.com/ActivityWatch/activitywatch/issues/612#issuecomment-863933453

**Comment by Bad3r** [comment]
I just installed ActivityWatch for the first time and I am having the same issue.
- OS: Linux `5.12.12-arch1-1`
- Version: `v0.11.0`

### log
```ps
vue.runtime.esm.js:1888:12
TypeError: can't access property "map", t is undefined
    query aw-client.js:168
    r aw-client.js:7
    r aw-client.js:3
    query aw-client.js:165
    r activity.ts:288
    l runtime.js:63
    k runtime.js:293
    x runtime.js:118
    Babel 4
    query_category_time_by_period activity.ts:275
    j vuex.esm.js:851
    dispatch vuex.esm.js:516
    dispatch vuex.esm.js:406
    t Trends.vue:73
    l runtime.js:63
    k runtime.js:293
    x runtime.js:118
    Babel 4
    e Trends.vue:72
    t Trends.vue:68
    l runtime.js:63
    k runtime.js:293
    x runtime.js:118
    Babel 4
    e Trends.vue:66
    VueJS 12
vue.runtime.esm.js:1888:12
```

While attempting to export my categories (Default never changed it) I received the following JSON parse error
```ps
vue.runtime.esm.js:1888
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at a.exportClasses (CategorizationSettings.vue:77)
    at ne (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2175)
    at HTMLButtonElement.Ji.o._wrapper (vue.runtime.esm.js:6917)
ie @ vue.runtime.esm.js:1888
```

**Comment by TheTimeWalker** [comment]
@ErikBjare Here's my exported categories list: [aw-category-export.txt](https://github.com/ActivityWatch/activitywatch/files/6685396/aw-category-export.txt)
Had to change it to TXT as json files can't be uploaded

**Comment by ErikBjare** [comment]
Thanks @kulbhushanchand, very helpful!

I think I've found the culprit: In the new default categories there is an 'Uncategorized' category, which the code assumed to exist, but it doesn't in the old defaults, which causes the error. Working on a fix in https://github.com/ActivityWatch/aw-webui/pull/296

@Bad3r That looks like a separate issue. Can't quite figure out the cause, but looks like somehow the `timeperiods` passed to `AWClient.query` is undefined. 

The category export error is probably because you've never made any changes, and therefore when it tries to load the category rules from `localStorage` it gets 'undefined' which `JSON.parse` tries to parse... (leading to the `Unexpected token u`). I'll fix it right away.
