### ISSUE TITLE
It says version "v0.10.0" even after updating to v0.11.0

### ISSUE THREAD

**Issue by m-GDEV** [ActivityWatch/activitywatch#613]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Peppermint OS based on Ubuntu 18.04 LTS**: 
- **ActivityWatch version v0.11.0**: 

## Describe the bug

After updating my activitywatch to the newest version I was admiring the new UI and I looked at the bottom of the page and saw "Version v0.10.0" instead of "Version v0.11.0".

## To Reproduce

    1. Go to activity page on localhost
    2. Look at bottom of page and see incorrect version number

## Expected behavior

The correct version number should be listed

## Documentation

Picture of what I'm seeing: 

https://imgur.com/a/gfbN3oS
## Additional context

N/A

**Comment by ErikBjare** [comment]
Weird, it looks correct for me: 
![image](https://user-images.githubusercontent.com/1405370/122546359-281d9600-d02f-11eb-9b25-e2d12f6f1d3f.png)

**Comment by m-GDEV** [comment]
> Weird, it looks correct for me:
> ![image](https://user-images.githubusercontent.com/1405370/122546359-281d9600-d02f-11eb-9b25-e2d12f6f1d3f.png)

It seems to be working for now as well. I probably didn't quit the older version properly first. Thanks!
