### ISSUE TITLE
Avast detects malware

### ISSUE THREAD

**Issue by RasheedAZ** [ActivityWatch/activitywatch#617]
Hi. Avast claims this is infected:

![Screenshot 2021-06-20 213828](https://user-images.githubusercontent.com/16827461/122685452-92b51880-d25f-11eb-81ed-99bafca17349.png)

False positive?

**Comment by ErikBjare** [comment]
Yup, see #181. Please click the 'Report as false positive' button, thanks!

Duplicate, so closing.

**Comment by RasheedAZ** [comment]
OK done. Thanks. VirusTotal no longer gives a positive detection results.
