### ISSUE TITLE
Windows 10 - reported as trojan virus

### ISSUE THREAD

**Issue by Muchaszewski** [ActivityWatch/activitywatch#621]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 Pro 20H2
- **ActivityWatch version**: 0.11

## Describe the bug

Windows considers 2 files from 0.11 version as trojans (Google Chrome as well)
![image](https://user-images.githubusercontent.com/5092066/123137154-f869f600-d453-11eb-9650-58cb66cc2d95.png)

## To Reproduce
    1. Go to 'https://github.com/ActivityWatch/activitywatch/releases/tag/v0.11.0'
    2. Click on 'Windows'
    3. See Chrome considering setup as dangerous
    4. Confirm anyway
    5. See Windows considering file(s) as dangerous trojans

## Expected behavior

ActivityWatch should not be considered a virus
## Documentation

Virus total: https://www.virustotal.com/gui/file/00a6f5cf0bb7d75924387f4cc0c9cf5be563275d7f23df2af04a86d162aca327/detection
Windows:
![image](https://user-images.githubusercontent.com/5092066/123138214-0ff5ae80-d455-11eb-91d0-1ca424632e30.png)
Chrome (PL):
![image](https://user-images.githubusercontent.com/5092066/123138277-1f74f780-d455-11eb-8ea0-091577f82a77.png)

**Comment by ErikBjare** [comment]
We appreciate the report, but tend to close all issues like this in favor of #181. 

Thanks for reporting.
