### ISSUE TITLE
Simple full-text search

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/activitywatch#623]
It would be nice to have a simple full-text search.

Use-case: As a user would like to quickly find the event, when there were events with "12345" in the a title of a window.

Background: I worked on ticket 12345, and I get paid for working on it. But I forgot to start the commercial time tracking app.

Now I want to know: When did I start to work on it?

**Comment by ErikBjare** [comment]
There's something basic like that at http://localhost:5600/#/search

Does it do what you wanted?

**Comment by guettli** [comment]
Great! That's exactly what I was looking for.

The search is a bit hidden behind "tools". But maybe this conversation will lead people googling for it to the right place.

Thank you!
