### ISSUE TITLE
Error while building on VoidLinux

### ISSUE THREAD

**Issue by salastro** [ActivityWatch/activitywatch#624]
- [ ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: VoidLinux x86_64-musl
- **ActivityWatch version**: commit 9ac2e2fab448cd83edf76bed2fd371089250f338

## Describe the bug

When I try `make build` I get this as an error:
```
  WARNING: Discarding file:///home/salahdin/.cache/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz. Command errored out with exit status 1: /home/salahdin/.srcpkgs/activitywatch/venv/bin/python3 /home/salahdin/.srcpkgs/activitywatch/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptlp0q5wg Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /home/salahdin/.srcpkgs/activitywatch/venv/bin/python3 /home/salahdin/.srcpkgs/activitywatch/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmptlp0q5wg Check the logs for full command output.
  WARNING: Ignoring invalid distribution -w-core (/home/salahdin/.srcpkgs/activitywatch/venv/lib/python3.9/site-packages)
  WARNING: Ignoring invalid distribution -w-core (/home/salahdin/.srcpkgs/activitywatch/venv/lib/python3.9/site-packages)


  at ~/.local/lib/python3.9/site-packages/poetry/utils/env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│
      1077│         return decode(output)
      1078│
      1079│     def execute(self, bin, *args, **kwargs):

  • Updating types-click (7.1.2 -> 7.1.1)
make[1]: *** [Makefile:4: build] Error 1
make[1]: Leaving directory '/home/salahdin/.srcpkgs/activitywatch/aw-qt'
make: *** [Makefile:36: build] Error 2
```

## To Reproduce

1. Use latest update of VoidLinux x86_64-musl (2021-06-25)
2. Use the following versions of the required software:
	- `git` version 2.32.0 
	- `Python` 3.9.5
	- `Poetry` version 1.1.6
	- `node` v14.16.0 / `npm` 6.14.11
	- `rustc` 1.55.0-nightly (a85f584ae 2021-06-16) / `cargo` 1.54.0-nightly (44456677b 2021-06-12)
3. Clone the latest git version of activity watch (9ac2e2fab448cd83edf76bed2fd371089250f338)
4. execute `python3 -m venv venv` in the source code directory
5. execute `source ./venv/bin/activate` in the source code directory
6. execute `make build`  in the source code directory
## Expected behavior

The program builds perfectly fine without any kind of errors whatsoever.

## Additional context

When I tried to open the file `/tmp/tmptlp0q5wg` it did not exist (the file was simply not there).

**Comment by johan-bjareholt** [comment]
The first two lines of this log indicates that it's the dependency PyQt5 failing to build rather than aw-qt itself.
I think we need to be able to look at the `/tmp/tmptlp0q5wg` file to be able to understand what's going on here. Maybe install it seperately with something like `pip install PyQt5==5.15.2`?
Otherwise your build environment seems to be OK.
