### ISSUE TITLE
Here is a aw-stop script that will stop the aw processes

### ISSUE THREAD

**Issue by theguybieber** [ActivityWatch/activitywatch#63]
Might be nice to have a stop script.

```sh
ps -ef | grep aw-server | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep aw-watcher-afk | grep -v grep | awk '{print $2}' | xargs kill -9
ps -ef | grep aw-watcher-window | grep -v grep | awk '{print $2}' | xargs kill -9
```

[aw-stop.txt](https://github.com/ActivityWatch/activitywatch/files/1048598/aw-stop.txt)

**Comment by ErikBjare** [comment]
Killing with `-9` can lead to all sorts of trouble since it won't allow processes to exit cleanly. If you are going to use this, expect trouble sooner or later.

I usually just do `killall aw-server aw-watcher-afk aw-watcher-window`.

**Comment by theguybieber** [comment]
Yeah killall didn't seem to work for me. I took the -9 off to avoid problems.

**Comment by ErikBjare** [comment]
Not sure if macOS has `pkill`, but if it does `pkill aw-server` or (`pkill aw-(watcher|server)` to match all of them) might work better.

**Comment by johan-bjareholt** [comment]
pkill should be available

https://unix.stackexchange.com/a/5722
