### ISSUE TITLE
App doesn't open after installing it and opening it (Mac OS Big Sur)

### ISSUE THREAD

**Issue by glassnor** [ActivityWatch/activitywatch#630]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Mac OS Big Sur 11.4 (20F71) 
- **ActivityWatch version**:  0.11.0, downloaded from: https://activitywatch.net/

## Describe the bug

I'm unable to open the app
## To Reproduce

1. I installed the app from the DMG
2. copied app to apps folder
3. Clicked to allow it to open from security preferences
4. Clicked in security and privacy to give accessibility access to the app
<img width="649" alt="Screen Shot 2021-07-04 at 9 26 50 AM" src="https://user-images.githubusercontent.com/10133086/124386802-1d5b3600-dcaa-11eb-9d5f-924d7c3f411d.png">

5. And tried opening the app
## Expected behavior

I expect the app to open

Unexpected result:
The app doesn't open, nothing happens at all... Very confused about why since its a clean install on a relatively new OS install without a lot of software installed... I'm happy to provide more info and a zoom to do a screenshare, If I end up using the software I'm also happy to donate $100+ to the project to thank you for the product and the help.... hell if you just help me get it set up and working I'll probably donating $100 to thank someone for the help.

**Comment by ofou** [comment]
Hey Glassnor, if you're looking for a workaround on a M1 Macbook Air (BigSur 11.4) or any M1, the older version it's still working. I'm using it myself, you just need to downgrade to [v0.10.0](https://github.com/ActivityWatch/activitywatch/tree/v0.10.0). 
There are two options, one it's installing the older `.dmg` directly from the previous link or if you installed it using `brew`, do the following:

Open a Terminal and edit the file using this command:
```bash
open -e /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/activitywatch.rb
```
then comment the `sha256` line and change it to version `"0.10.0"`:

```
cask "activitywatch" do
  version "0.10.0"
  # sha256 "91deabd5844968467b5b6b3423e12654d4e339ba309f333c25d991a2e689fd96"

  url "https://github.com/ActivityWatch/activitywatch/releases/download/v#{vers$
      verified: "github.com/ActivityWatch/activitywatch/"
  name "ActivityWatch"
  desc "Time tracker"
  homepage "https://activitywatch.net/"

  app "ActivityWatch.app"

  zap trash: "~/Library/Application Support/activitywatch"
end
```
Finally, reinstall the older version:

```
brew reinstall activitywatch
```

I'm still researching why it's not working, it appears to be the same problem on various M1 devices (#622).
I'm a user too, hope this helps you.

**Comment by glassnor** [comment]
I'm actually on a macbook pro with the old processors, not the M1... Apologies @ofou that I didn't say that, and thanks for your suggestion, I may still try it if I don't hear other suggestions

**Comment by ErikBjare** [comment]
Hey everyone, sorry for the macOS issues, it has been a recurring issue throughout the years.

I've made some attempts at making it work reliably, but it has proven difficult (esp as I have limited knowledge of macOS internals). 

If anyone wants to help out with a fix for this, I'd be more than happy to offer a generous bounty. Good starting points are https://github.com/ActivityWatch/activitywatch/pull/620 and https://github.com/ActivityWatch/activitywatch/pull/344, as well as generally searching through past issues mentioning similar issues.

**Comment by faisalmukhtarch** [comment]
> Hey Glassnor, if you're looking for a workaround on a M1 Macbook Air (BigSur 11.4) or any M1, the older version it's still working. I'm using it myself, you just need to downgrade to [v0.10.0](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.10.0).
> There are two options, one it's installing the older `.dmg` directly from the previous link or if you installed it using `brew`, do the following:
> 
> Open a Terminal and edit the file using this command:
> 
> ```shell
> open -e /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/activitywatch.rb
> ```
> 
> then comment the `sha256` line and change it to version `"0.10.0"`:
> 
> ```
> cask "activitywatch" do
>   version "0.10.0"
>   # sha256 "91deabd5844968467b5b6b3423e12654d4e339ba309f333c25d991a2e689fd96"
> 
>   url "https://github.com/ActivityWatch/activitywatch/releases/download/v#{vers$
>       verified: "github.com/ActivityWatch/activitywatch/"
>   name "ActivityWatch"
>   desc "Time tracker"
>   homepage "https://activitywatch.net/"
> 
>   app "ActivityWatch.app"
> 
>   zap trash: "~/Library/Application Support/activitywatch"
> end
> ```
> 
> Finally, reinstall the older version:
> 
> ```
> brew reinstall activitywatch
> ```
> 
> I'm still researching why it's not working, it appears to be the same problem on various M1 devices (#622).
> I'm a user too, hope this helps you.

Thanks a lot. I was trying to install on my M1 Mac but it was failing. I can finally install it but the menu is very much blurred. Are you experiencing the same?

**Comment by ofou** [comment]
Yep @faisalmukhtarch, I'm experiencing the same, not a big deal at the moment to me tough. 🤥

But hey @ErikBjare thanks for pointing out the security vulnerability, that's kind of worrisome about running `v0.10.0` on macOS. I'll get deeper into it, just getting on board setting up dev env is kind of difficult on M1, for some reason `aw_webui` build keep failing `(Failed at the deasync@0.1.21 install script)`. I'll check the dependencies again [from the docs](https://docs.activitywatch.net/en/latest/installing-from-source.html#checking-dependencies), just in case.

By the way, thanks for doing this project. I'm migrating from Rescuetime and Wakatime. We're not yet there... but I'm loving ActivityWatch so far, plus it's open source! ♡

**Comment by arnaujc91** [comment]
Same here. Just installed the App via Homebrew and also simply running the .dmg file. Both ways the app is unable to start.

**Comment by spodlipnik** [comment]
Same problem here. Any updates on this issue?

**Comment by ErikBjare** [comment]
Sorry guys, but I don't have the bandwidth to deal with this right now. It has proven to be more difficult than I previously expected.

You can try some of the old workarounds as described in https://github.com/ActivityWatch/activitywatch/issues/323 to get it running from the `.zip` macOS release.

I should add that there's a **sizeable bounty** (>$1,000) for anyone who manages to fix the macOS releases. A good starting point is: https://github.com/ActivityWatch/activitywatch/pull/620

Related issues:
 - https://github.com/ActivityWatch/activitywatch/issues/334
 - https://github.com/ActivityWatch/activitywatch/issues/622 (might be a duplicate)

**Comment by aaayushsingh** [comment]
Hey @ErikBjare, 
Came here from the Upwork post. Is anyone working on this? Do I have to lock this or something before I get started or try to fix this? 

Question: 
Can this be reproduced if I follow the `make build` method from the documentation? if no, how do I package it as .dmg to test the process descried in the issue?

**Comment by ErikBjare** [comment]
Hey @aaayushsingh! 

Thanks for the initiative, but please keep Upwork-related inquiries to the Upwork-platform until you've gotten the green light to get started. Thanks :)

In case you're eager, or just curious, there's documentation on how to build from source and package as a `.dmg` here: https://docs.activitywatch.net/en/latest/installing-from-source.html

**Comment by cyann** [comment]
FYI, I got it working by doing this:
* Right-click on ActivityWatch, select View Package Content (or something similar, I'm not running the English version)
* Open the `Content` folder
* Open `info.plist` in TextEdit
* Change the string `<string>MacOS/aw-qt</string>` to `<string>aw-qt</string>`
* Save and try

**Comment by meain** [comment]
@cyann Wow, that actually seems to work.

**Comment by cyann** [comment]
However it looks like it doesn't stay running...

**Comment by meain** [comment]
![Screenshot 2021-09-28 at 10 24 30 PM](https://user-images.githubusercontent.com/14259816/135131574-543992ef-4849-45e1-bc69-41906796af20.png)

I do get this error in the UI, but at least it seems to be working so far. Let me see if it stays up.

**Comment by cyann** [comment]
Weird: opening it with double-click did not work, but it works with the terminal:
```
open /Applications/ActivityWatch.app
```

**Comment by meain** [comment]
Same for me actually. Had to open through shell. I just thought it was blocked due to some security thing, but least it been working fine for me for some time now.

**Comment by arnaujc** [comment]
It didnt work for me, not even using the terminal

**Comment by rakleed** [comment]
> Weird: opening it with double-click did not work, but it works with the terminal:
> 
> ```
> open /Applications/ActivityWatch.app
> ```

@cyann But in this case, when you open the Dashboard, the “Query”, “Raw Data” and “Settings” tabs in the upper right corner do not open.

**Comment by cyann** [comment]
@rakleed Sorry, I've stopped using ActivityWatch.
