### ISSUE TITLE
Version 0.11 aw-qt does not start on Linux

### ISSUE THREAD

**Issue by ribtoks** [ActivityWatch/activitywatch#636]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 20.04
- **ActivityWatch version**: 0.11

## Describe the bug

I started previous AW service by going to unzipped ActivityWatch binaries archive (from GitHub) and double-clicked the `aw-qt` binary. After upgrading to 0.11, when double-clicking it, I see the message `there's no application installed for shared library files`. Starting `aw-qt` from the terminal works, but it's unusable to every time go to the terminal to start it.

## To Reproduce

(provided in "describe the bug")

## Expected behavior

After double-clicking `aq-qt`, it actually starts.

**Comment by TarryDan** [comment]
I may be experiencing a similar issue (Ubuntu 20.04).

I have unzipped the folder, but double-clicking aw-qt pops up an "Choose an application" popup. Running the binary aw-qt in the terminal will work,

**Comment by JunjieLeiCoe** [comment]
Same issue here -- with the (Same) OS Ubuntu 20.04
the binary executable file aw-qt is not runnable.
