### ISSUE TITLE
Version is duplicated in name of app in list of installed apps

### ISSUE THREAD

**Issue by rakleed** [ActivityWatch/activitywatch#637]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 v. 20H1
- **ActivityWatch version**: 0.11.0

## Describe the bug
The version of the app is duplicated in the name of the app in the list of installed apps in "Settings - Apps - Apps & features" and "Control Panel - Programs - Programs and Features" in the version for Windows. Please remove the version number from the app name, as the version number is displayed next to the name in a separate field.

## To Reproduce
1. Install ActivityWatch
2. Go to "Settings - Apps - Apps & features" or "Control Panel - Programs - Programs and Features"

## Expected behavior
The app title will display only the title without the version number.

## Documentation

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/19418601/125517768-f2cb83b7-2538-4a0b-aa8b-136205227ffd.png)

![image](https://user-images.githubusercontent.com/19418601/125517916-76dae9f1-95f5-4056-8b6b-e79ff37bfd01.png)

</details>

**Comment by ErikBjare** [comment]
Not sure how to fix this. For anyone willing to look into this, the installer is generated using this file: https://github.com/ActivityWatch/activitywatch/blob/master/scripts/package/activitywatch-setup.iss

I don't see any obvious way to change the title, as from the looks of it, it should just be 'ActivityWatch'.
