### ISSUE TITLE
TypeError: t.target is undefined Error

### ISSUE THREAD

**Issue by thepuppet33r** [ActivityWatch/activitywatch#648]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Pop Os! 21.04
- **ActivityWatch version**: v0.11.0

## Describe the bug
Editing any settings in the Settings pane gives the following error: 
TypeError: t.target is undefined. 

## To Reproduce
1. Go to Settings. 
2. Edit any setting (like start time). 
[Logs.zip](https://github.com/ActivityWatch/activitywatch/files/6926897/Logs.zip)

## Expected behavior
1. Should allow me to edit and save settings. 

## Documentation

![Peek 2021-08-03 16-34](https://user-images.githubusercontent.com/16672129/128082434-39604401-d68d-4e4b-9f9f-e974d3e38647.gif)

**Comment by Obspogon** [comment]
I can confirm, I am having the same issue

**Comment by ErikBjare** [comment]
Fixed in master (https://github.com/ActivityWatch/aw-webui/commit/8d348e2e008bdf15ccd2b02d4ceb9f8b43941d87), should be in the next release.
