### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined. See dev console (F12) and/or server logs for more info.

### ISSUE THREAD

**Issue by RapGabs** [ActivityWatch/activitywatch#650]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 + 21H1 
- **ActivityWatch version**: v0.11.0 

## Describe the bug
Although activity watcher is running perfectly and I can track all the activities really well. But, as soon as I want to change something, eg: the 'start of the day' time or 'landing page', etc. on the settings page, I get this error popping up at the top.
What steps can I take to fix it?

## To Reproduce

1. Go to Settings.
2. Edit any setting (like start time).
3. Save.

## Expected behavior
Should allow me to edit and save settings.

## Documentation
[Logs.zip](https://github.com/ActivityWatch/activitywatch/files/6927389/Logs.zip)

## Additional context
![image](https://user-images.githubusercontent.com/70739853/128094867-864c535f-3b7f-4abd-9b3f-b39e3144f4a3.png)

**Comment by ErikBjare** [comment]
Duplicate of #650 (and probably others)
