### ISSUE TITLE
Poetry Install gives error on make build

### ISSUE THREAD

**Issue by valensway** [ActivityWatch/activitywatch#651]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**:  Windows 10 x86
- **ActivityWatch version**: 0.11.0

## Describe the bug
I am using Python 3.7.9 and when i try run the command 'make build', it gives me this make error on poetry install. When i run only poetry install it works, okay, but with the make build command it gives the error.
The response 
poetry install
make: *** [Makefile:4: build] Error 1

**Comment by ErikBjare** [comment]
Unfortunately, there's nothing to go on in that log.

I don't know why poetry returns error code 1 without output, that seems very strange.
