### ISSUE TITLE
Unable to download .exe vía browser dangerous file

### ISSUE THREAD

**Issue by Noya-santiago** [ActivityWatch/activitywatch#653]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Windows 10 PRO N + 21H1 **: 

## Describe the bug

When downloading the installer vía a web browser, it is marked as potentially dangerous and it is impossible to download. 
It happens in Chrome, Brave and firefox. Does not happen on edge. It also happen with the zip version

## Documentation

![image](https://user-images.githubusercontent.com/62810706/129424908-8bd0cde2-6dff-4ab1-bc51-5c55967e8717.png)
 (Translation: Chrome blocked activitywatch-v0.1....exe because it is a dangerous file)

**Comment by ErikBjare** [comment]
See #181. Closing.
