### ISSUE TITLE
Hıgh CPU usage (%5-10) on WMI Provider Host when aw-watcher-window is active. 

### ISSUE THREAD

**Issue by JFMugen** [ActivityWatch/activitywatch#654]
To be honest I am not sure if this is a bug or intended. Please tell me if it is normal. 

- [X] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue
I realized WMI Provider Host always using >%5 CPU and spikes to %10 when I open a new window etc. It drops to %0 when I disable aw-watcher-window. Is that normal/intended?

**Comment by ErikBjare** [comment]
I don't know if there's anything we can do about this, or if the CPU usage is considered normal (as I don't really use Windows).

**Comment by JFMugen** [comment]
> I don't know if there's anything we can do about this, or if the CPU usage is considered normal (as I don't really use Windows).

Is it normal the app constantly uses WMI Provider Host? From what I read, the high usage is result of bad behavior of a program etc. So I thought there is a hidden bug or something like that.

**Comment by ErikBjare** [comment]
The app uses WMI to get the active window title, so some use is to be expected.

I can't say if the high usage can be reduced, but here's the code used: https://github.com/ActivityWatch/aw-watcher-window/blob/master/aw_watcher_window/windows.py

**Comment by JFMugen** [comment]
> The app uses WMI to get the active window title, so some use is to be expected.
> 
> I can't say if the "high" usage can be reduced, but here's the code used: https://github.com/ActivityWatch/aw-watcher-window/blob/master/aw_watcher_window/windows.py

Hmm, I don't know much about the coding, but it looks pretty basic. I am not sure if there is more resource-friendly way to do it, so I will suggest 2 basic workarounds. 

- Better one -> Option to put a time interval setting so instead of requesting information from WMI every second, you can change it to once in a min etc. It would give less accurate results but uses less resources.

- Worse one -> Option to disable aw_watcher_window. I like the feature but I prefer less CPU usage over it. Disabling it manually every time kinda annoying. 

Btw, just asking, is " get_app_path " even needed in the code? Looks like it can be removed alltogether.

**Comment by ErikBjare** [comment]
>Option to put a time interval setting so instead of requesting information from WMI every second, you can change it to once in a min etc. It would give less accurate results but uses less resources.

You already can, see the docs for aw-watcher-window's `poll_time`: https://docs.activitywatch.net/en/latest/configuration.html

>Option to disable aw_watcher_window.

You can do this too, through the aw-qt config. I now notice it isn't documented, but you can set `aw-qt.toml` to something like:

```toml
[aw-qt]
autostart_modules = ["aw-server", "aw-watcher-afk"]  # "aw-watcher-window"
```

> Btw, just asking, is " get_app_path " even needed in the code? Looks like it can be removed alltogether.

Yeah, looks like dead code. Could be removed.

**Comment by JFMugen** [comment]
> > Option to put a time interval setting so instead of requesting information from WMI every second, you can change it to once in a min etc. It would give less accurate results but uses less resources.
> 
> You already can, see the docs for aw-watcher-window's `poll_time`: https://docs.activitywatch.net/en/latest/configuration.html
>
> > Option to disable aw_watcher_window.
> 
> You can do this too, through the aw-qt config. I now notice it isn't documented, but you can set `aw-qt.toml` to something like:
> 
> ```toml
> [aw-qt]
> autostart_modules = ["aw-server", "aw-watcher-afk"]  # "aw-watcher-window"
> ```

Sorry, I thought there is no such setting when I couldn't see it in settings. And just to be sure, editing .toml files are enough right? (I changed both .ini and .toml to try anyway) 

Firstly, aw-watcher-window still launches at start (I just copy-paste your code). 

Secondly, poll_time kinda works? I am not sure. The CPU usage is always below <%1 but somehow when I check dashboard, it updates just like before. I changed it to 60 seconds, so it shouldn't update below 1 minute, right? But it does update every second correctly. 

So in the end, CPU usage is lower but nothing changed? I think there is something wrong here. (by the way, I had to restart PC to see changes)

**Comment by ErikBjare** [comment]
> And just to be sure, editing .toml files are enough right?

Yes, that should be enough. I just tested editing my aw-qt config to start aw-server-rust instead of aw-server, and it works as expected.

> Secondly, poll_time kinda works? I am not sure. The CPU usage is always below <%1 but somehow when I check dashboard, it updates just like before. I changed it to 60 seconds, so it shouldn't update below 1 minute, right? But it does update every second correctly.

Not sure why this is, when I set `poll_time` it works as expected:

![image](https://user-images.githubusercontent.com/1405370/129906373-1fd11b6c-4916-4c9a-9239-6bbfe27ef6ab.png)

~1min later:

![image](https://user-images.githubusercontent.com/1405370/129906496-133c2f53-ebf5-4e76-9b4a-8110c2f6ae0d.png)

> (by the way, I had to restart PC to see changes)

Restarting aw-qt should be enough.

**Comment by ErikBjare** [comment]
Should also note that setting `poll_time` to a high value is likely to break things in the analysis, I'd recommend keeping it below 5s.

**Comment by JFMugen** [comment]
Please tell me if I am doing something wrong. 

![image](https://user-images.githubusercontent.com/61559703/129913313-a601ed4e-1f33-4d3e-9f5b-87497b04f04e.png)

After restarting ActivityWatch, it is enabled.

![image](https://user-images.githubusercontent.com/61559703/129913562-9086fd46-ef85-4fc3-afef-0a39eaf146af.png)

And about poll_time, tried with 5 second. 

![image](https://user-images.githubusercontent.com/61559703/129913706-a0734be2-dcc9-4113-8fc8-78b9ee8b2bb9.png)

This is the result. I alt-tab rapidly to see if it can see it or not. 

![image](https://user-images.githubusercontent.com/61559703/129913917-e925a635-006f-4d40-8416-f6a5e7836ba9.png)

If I didn't misunderstand something, it doesn't work. Maybe a Windows issue? I am not sure. 

(by the way CPU usage still <%1 when I change it to 5 second, but didn't restart my pc this time)

**Comment by ErikBjare** [comment]
You have to remove the '#' used to comment out the config. With it there,
the lines are not read. Write it exactly as I pasted.

**Comment by JFMugen** [comment]
> You have to remove the '#' used to comment out the config. With it there, the lines are not read. Write it exactly as I pasted.

Well, that's embarrassing :) 

I thought I shouldn't remove them since they were like that when I open the file. Looks like it works right now. 

But, that makes it interesting as well. 

Since I didn't remove # before, how CPU usage dropped from %5-10 to <%1? Everything should've been the same, am I wrong? I feel like some weird thing happens, but I have no idea what or how :/

It is possible it is on my side as well, but I am not sure. It is up to you to close this issue or keep it open for future testing maybe,

Thank you very much for the help. I will write if I can find something interesting that can cause this problem.

**Comment by ErikBjare** [comment]
> Everything should've been the same, am I wrong?

Everything is rarely the same :)

Could just have been something else random. I'll close this issue, but will keep it in mind and investigate WMI when I have access to a Windows machine.
