### ISSUE TITLE
POST methods never work again once I open dashboard

### ISSUE THREAD

**Issue by idevlp** [ActivityWatch/activitywatch#664]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- Windows 10 Pro 21H1
- Activity Watch v0.11.0

## Describe the bug
Post methods never work once I open the dashboard

EDIT: this also affects get methods

## To Reproduce
1. Test post methods with curl/postman (works)
2. Open web dashboard
3. Test the same post methods and server fails to respond
4. quit ActivityWatch from tray and reopen it
5. Test post methods with curl/postman (works)

EDIT: if I refresh the dashboard or open a new dashboard while the post method is still waiting for response, it suddenly works...

## Expected behavior
Post methods should always work without issues

## Additional context
Proof:
![output](https://user-images.githubusercontent.com/90207354/132607697-71b39a67-6f07-4300-9162-4bd09756eca7.gif)

**Comment by johan-bjareholt** [comment]
The web-ui is probably freezing on some request, could you go into the Chrome/Firefox debug network tab while opening the web-ui? I think you can open it by pressing F12.

**Comment by idevlp** [comment]
Here it is
![capture4](https://user-images.githubusercontent.com/90207354/132675478-10f5b77a-e9e6-40f5-8e8b-398b1fd2b94f.PNG)

I am also trying to investigate the problem with Wireshark and postman. I am very new to those tools and it seems to good challenge to investigate while learning how to use them

**Comment by idevlp** [comment]
Very weird! After investigating with wireshark, it seems heartbeat post requests from ActivityWatch itself doesn't get a response once I open the dashboard. Is this only happening to me? I am using clean windows 10 installation and the only localhost server I use is ActivityWatch.

**Comment by idevlp** [comment]
This is out my knowledge scope:

Post requests are back to working once I close the browser that I opened the dashboard with. If I just close the dashboard tab, I have to wait for some minutes before it goes back to working. I opened windows resource monitor and it the data flow between chrome and aw-server was around 100k-200k B/sec even though the tab was closed. 

maybe the issue is that the server keeps connecting with the browser even if the page is fully loaded? Maybe because the dashboard is live and keeps syncing data with chrome? idk

**Comment by idevlp** [comment]
Here is the proof that closing the browser brings back post requests to working.

https://user-images.githubusercontent.com/90207354/132688083-4d407e83-1576-4fb7-b654-220dabff5fd4.mp4

**Comment by idevlp** [comment]
Switching to aw-server-rust fixed the issue @johan-bjareholt 🎉

**Comment by ErikBjare** [comment]
Huh, peculiar that the user disappeared and deleted their account without resolution. I wonder what request it got stuck on?
