### ISSUE TITLE
dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by rrjanbiah** [ActivityWatch/activitywatch#670]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 16.04.7 LTS
- **ActivityWatch version**: activitywatch-v0.11.0-linux-x86_64.zip

## Describe the bug

Similar to #378, can't start it in Ubuntu, but different errors

## To Reproduce

```
./aw-qt 
[5869] Error loading Python lib '/home/me/applications/activitywatch/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/me/applications/activitywatch/libpython3.8.so.1.0)
```

## Documentation

Can't find log file at `/home/me/.cache/activitywatch/log`

**Comment by mr-asa** [comment]
I have the same problem
```sh
Error loading Python lib '/home/username/soft/activitywatch/libpython3.8.so.1.0': 
dlopen: /lib64/libc.so.6: 
version `GLIBC_2.27' not found (required by /home/username/soft/activitywatch/libpython3.8.so.1.0)
```

**version**: activitywatch-v0.11.0-linux-x86_64
**OS**: openSUSE Leap 15.2 (x86-64), Cinnamon 4.4.8

**Comment by dumprop** [comment]
> I have the same problem
> 
> ```shell
> Error loading Python lib '/home/username/soft/activitywatch/libpython3.8.so.1.0': 
> dlopen: /lib64/libc.so.6: 
> version `GLIBC_2.27' not found (required by /home/username/soft/activitywatch/libpython3.8.so.1.0)
> ```
> 
> **version**: activitywatch-v0.11.0-linux-x86_64 **OS**: openSUSE Leap 15.2 (x86-64), Cinnamon 4.4.8

openSUSE Leap 15.2 no longer supported, try to upgrade to Leap 15.3 (I'm almost sure it will work on 15.4)

**Comment by ErikBjare** [comment]
> Ubuntu 16.04.7 LTS

Sorry, but we will not support >5 year old distributions. You could still run AW from source if you can't upgrade for some reason.

> openSUSE Leap 15.2

As @dumprop said, this is not only unsupported by AW, but also EOL. Upgrade your system.
