### ISSUE TITLE
"Start of Day" setting time picker gives an error on change of values and does not save the time.

### ISSUE THREAD

**Issue by CowboyBebop** [ActivityWatch/activitywatch#681]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 Home 21H1 19043.1288
- **ActivityWatch version**: 0.11.0

## Describe the bug
Whenever I try to change the start of day setting I get:
`TypeError: Cannot read properties of undefined (reading 'value'). See dev console (F12) and/or server logs for more info.`
By the looks of it, it may be a name wrong variable name or type on the `onChange` function?

## To Reproduce

    1. Go to `http://localhost:5600/#/settings` (Settings in the browser host)
    2. Change the "Start of Day" setting either by arrow keys or selecting time with the picker
    3. See error the error appear at the top

## Expected behavior
Change the "Start of Day" time which would be saved when I close the window

## Documentation

Console log:
```
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'value')
    at change (DaystartSettings.vue?e987:1)
    at ne (vue.runtime.esm.js:1854)
    at a.n (vue.runtime.esm.js:2179)
    at ne (vue.runtime.esm.js:1854)
    at a.Cn.t.$emit (vue.runtime.esm.js:3888)
    at a.onChange (form-text.js:228)
    at ne (vue.runtime.esm.js:1854)
    at HTMLInputElement.n (vue.runtime.esm.js:2179)
    at HTMLInputElement.Ji.o._wrapper (vue.runtime.esm.js:6917)
```

**Comment by CowboyBebop** [comment]
yep

**Comment by ErikBjare** [comment]
This has been reported before (but maybe on the forum, there was a initial barrage of reports around the release).

Anyway, it's fixed in master and will work in the next release. You can try a nightly build (see https://github.com/ActivityWatch/activitywatch/issues/507) if you want it fixed straight away :)
