### ISSUE TITLE
ActivityWatch not starting on Windows 10

### ISSUE THREAD

**Issue by Dominiquini** [ActivityWatch/activitywatch#682]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 x64 Version 21H1 (OS Build 19043.1320)
- **ActivityWatch version**: 0.11.0

## Describe the bug
When I try to start the graphical interface from the start menu "ActivityWatch" or running the executable "aw-qt.exe", nothing happens! No error is showed, but the application don't start... I checked on the Task Manager and verify that the folder is not been used!
But I was able to use the application when I run manually the executables "aw-server.exe", "aw-watcher-afk.exe" and "aw-watcher-window.exe" and accessing the URL "localhost:5600"!

## To Reproduce
  Steps to reproduce the behavior, for example:
    1. Go to Start Menu
    2. Click on 'ActivityWatch'
    4. Nothing happens...

## Expected behavior
In a older version, a system tray icon appears and I can open the GUI to view my tracker...

**Comment by arturdaraujo** [comment]
Same issue here. the ActivityWatch version: 0.11.0 is not working on my Windows 10 although the version 0.10.0 is opening just fine.
