### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'label').

### ISSUE THREAD

**Issue by oliver11111** [ActivityWatch/activitywatch#685]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 21H1 Build 19043.1288
- **ActivityWatch version**: v0.11.0

## Describe the bug
After upgrading from 0.10 to 0.11 and adding another category, I consistently get 
"TypeError: Cannot read properties of undefined (reading 'label')."

The console shows:
Cannot call query_editor as we do not have any editor buckets 
activity.ts:158

Also my output is grey scale rather than color

## To Reproduce
Refresh activity page

## Expected behavior
No error being displayed and Activity information displayed in color.

## Documentation
[aw-server_2021-11-08T18-12-17.log](https://github.com/ActivityWatch/activitywatch/files/7501571/aw-server_2021-11-08T18-12-17.log)

**Comment by ErikBjare** [comment]
This should have been reported elsewhere, but can't find it right now.

In any case, it should be fixable by either (1) manually adding a 'Uncategorized' category and setting category colors, or (2) resetting categories to defaults. I think nightly builds (see #507) should also have the bug fixed.
