### ISSUE TITLE
Ubuntu 21.10: No tray icon

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/activitywatch#688]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

I installed the izip according to the docs:

> If you’ve installed by extracting a zip archive, simply run the ./aw-qt binary in the installation directory (either from your terminal or on Windows by double-clicking). You now should see an icon appear in your system tray.

But the tray icon is not visible.

The icon was visible on my old laptop running Ubuntu 20.04. 

But on Ubuntu 21.10 it runs, and the server at localhost is reachable, but the tray icon is missing.

No big deal. I can bookmark http://localhost:5600/#/timeline, but a tray icon would be nice.

```
uname -a
Linux p15 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ActivityWatch Version 0.11
```

Please let me know if I can support you to solve this issue. Thank you.

**Comment by ErikBjare** [comment]
Probably same issue as in https://github.com/ActivityWatch/activitywatch/issues/660#issuecomment-959889230

A workaround is to remove the libharfbuzz.so.0 file in the installation directory.

The next release will not have the libharfbuzz.so.0 file, and will therefore not have this issue.

Closing the issue since I'm 99% certain that will fix it for you.

**Comment by 1gmar** [comment]
After upgrading to the latest version (v0.13.1), the tray icon is not showing again.
Host 
```
Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
```
Did anybody else experience this?

**Comment by 1gmar** [comment]
This solved the issue
https://github.com/ActivityWatch/activitywatch/issues/960#issuecomment-2242612399
