### ISSUE TITLE
Beta testing for 0.7 release

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#69]
Finally, we're here. v0.7 is closing in, and all that's left to do before we make a stable release is more testing.

#### How to test:

 1. Download the [latest beta release](https://github.com/ActivityWatch/activitywatch/releases)
 2. Start aw-qt (tip: set it up for start on boot using whatever way to do this that your platform offers)
 3. Ensure everything works smoothly (basic usage + grep the logs for `WARN` and `ERROR`)

#### Targets left to test:

 - [x] Linux
 - [x] Windows
 - [x] macOS

**Note:** I'm attempting to write a proper changelog (with all major changes since `v0.6`). So much has changed (and it's been so long!) that I'm having a hard time writing it, so if there is anything significant you notice I've forgotten, please let me know! (you can see the current state of the changelog in the latest GitHub release description)

**Comment by johan-bjareholt** [comment]
These are the issues i found when testing on Linux. All were related to aw-qt sadly

- [ ] https://github.com/ActivityWatch/aw-qt/issues/18
- [ ] https://github.com/ActivityWatch/aw-qt/issues/19
- [ ] https://github.com/ActivityWatch/aw-qt/issues/20

**Comment by ErikBjare** [comment]
I've stumbled a minor bug while testing on Windows:

 - [ ] This line was reached when trying to read open the activity view for a certain date: https://github.com/ActivityWatch/aw-core/blob/8921b264c4e46bf3022e63480bf064dcc1091b1b/aw_core/transforms.py#L97

**Comment by ErikBjare** [comment]
Found a bug in aw-watcher-window (on Linux): 

 - [ ] https://github.com/ActivityWatch/aw-watcher-window/issues/19

**Comment by johan-bjareholt** [comment]
https://github.com/ActivityWatch/aw-qt/issues/22

**Comment by ErikBjare** [comment]
Alright, looks like all remaining bugs are related to aw-qt.

I'll make a point of fixing them before beta 3.

**Comment by ErikBjare** [comment]
Most things have been fixed for a while now. 

I'm not considering that aw-qt bug you found critical so closing this.

I think we're ready for a real release whenever we feel like it now.

**Comment by ErikBjare** [comment]
Reopening due to: https://github.com/ActivityWatch/activitywatch/issues/113

**Comment by ErikBjare** [comment]
#113 done. I think we're ready to release a stable version now.
