### ISSUE TITLE
Normalize Icon-size on Linux / ZorinOS

### ISSUE THREAD

**Issue by KiritoStorm** [ActivityWatch/activitywatch#690]
I don't know how the icon looks on other operating systems, but I just want to report that the icon on Zorin is really big compared to other programs, as you can see on the screenshot the icon of MS Teams and Steam is much smaller.

![image](https://user-images.githubusercontent.com/46503102/143586347-052e3b3f-5208-415a-a7db-4703eb38e734.png)

**Comment by ErikBjare** [comment]
I have no idea why the icons render at different sizes (we're not doing anything special afaik). 

Have you noticed another application rendering at the same (larger) size? The Steam and MS Teams icons look awfully small, are you sure those are not the icons that should be sized differently?

**Comment by KiritoStorm** [comment]
It's normal that the other icons are so little, it's the same size like all other icons in this area like WIFI, Sound and more.
I'm not using Zorin for a long time but, I haven't seen any application that has such an big icon.

Have you tried it on Zorin too? Maybe this is a Zorin issue, I don't know.

**Comment by KiritoStorm** [comment]
It's fixed now. :heavy_check_mark:

**Comment by KiritoStorm** [comment]
It's fixed now. heavy_check_mark
