### ISSUE TITLE
ActivityWatch doesn't display data from aw-watcher-web-chrome bucket

### ISSUE THREAD

**Issue by herosnowman** [ActivityWatch/activitywatch#698]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 20H2 (OS Build 19042.1415)
- **ActivityWatch version**: Version: v0.11.0

## Describe the bug
ActivityWatch web interface doesn't display data from aw-watcher-web-chrome bucket.

## To Reproduce
1. Install Brave browser
2. Setup ActivityWatch on windows and install extension on Brave browser
3. Go to http://localhost:5600/#/activity/PC-NAME/view/browser
4. See nothing displayed

## Expected behavior
http://localhost:5600/#/activity/PC-NAME/view/browser should display data such as 'Top Browser Domains' and 'Top Browser URLs'.

## Additional context
The bucket exists and is getting updated:
![image](https://user-images.githubusercontent.com/28194972/147878701-06a8a97e-9b00-480f-8fee-cdf67ed493d5.png)
The problem:
![image](https://user-images.githubusercontent.com/28194972/147878719-9697e9f2-0d78-42d5-b733-dbe97a9bbc64.png)

I've also exported the  aw-watcher-web-chrome bucket as json and checked that its content is valid.

## What I have already tried
Full reinstall of ActivityWatch (including deletion of AppData\Local\activitywatch folder) and Brave browser.

**Comment by johan-bjareholt** [comment]
This has been thoroughly discussed before, see following issue:

https://github.com/ActivityWatch/activitywatch/issues/461#issuecomment-666639858
