### ISSUE TITLE
Virus thread detected - Cisco Secure Endpoint

### ISSUE THREAD

**Issue by chuckthenerd** [ActivityWatch/activitywatch#708]
FYI - aw-qt.exe is being detected by Cisco Secure Endpoint as a threat.  Install is unsuccessful.

> aw-qt.exe has been detected as
> W32.Auto:7a9a1510f1.in03. Talos. Quarantine was
> successful.

I'm downloading threat dictionary updates in the background and will update if newer threat dictionary clears this up.

**Comment by ErikBjare** [comment]
Thanks for the report. I'll close this since we gather similar reports (and their status) in #181.
