### ISSUE TITLE
ActivityWatch on Android 11 crashes a lot

### ISSUE THREAD

**Issue by JVT038** [ActivityWatch/activitywatch#719]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Android 11
- **ActivityWatch version**:  0.10.0

## Describe the bug
The app crashes randomly, quite frequently.
Sometimes, 1 second after opening the app, it crashes, and sometimes it takes 10 seconds for the app to crash.
Either way, it crashes a lot.

## To Reproduce
1. Install version 0.10.0 on Android 11
2. Open the app
3. Watch it crash

## Expected behavior
I expected the app to behave normally, and not crash

## Documentation
Where can I find android logs? I'll add them here, once I find them.

## Additional context
I don't use the regular Google Android. I use a fork of LineageOS, called [/e/ OS](https://e.foundation/), so this means Google Play Services doesn't exist for example. (It's been replaced with MicroG). So this means that all the Google apps / services have been removed and replaced with an alternative.
Perhaps my lack of Google services is causing this issue?

**Comment by DutchEclipse** [comment]
For me, it also often crashes, let's say every 5 seconds or right away when launching the application.

I use an OnePlus phone with Oxygen OS 11 (Android 11).

**Comment by JVT038** [comment]
So for some reason, it just stopped crashing? Idk why, but it doesn't crash anymore. It's still the same version, `v0.10.0 (rust)`
