### ISSUE TITLE
Create AppImage - script attached

### ISSUE THREAD

**Issue by guysoft** [ActivityWatch/activitywatch#725]
Hey,
I have managed to create an appimage. I can provide a script here for you to build one.
However, I tried adding it to CI. But I can't test here because mac fails to build because of no devkeys set.

```bash
#!/bin/bash
wget https://github.com/ActivityWatch/activitywatch/releases/download/v0.11.0/activitywatch-v0.11.0-linux-x86_64.zip
unzip activitywatch-v0.11.0-linux-x86_64.zip

pushd activitywatch
  wget https://raw.githubusercontent.com/guysoft/activitywatch/appimage/AppRun
  chmod 755 AppRun
  cp ./aw-server/aw_server/static/static/logo.png ./activitywatch.png
popd

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod 755 appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage activitywatch

ls -l *.AppImage

echo "output should be at: appimagetool-x86_64.AppImage"
```
Relaed #10 

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

**Comment by pktiuk** [comment]
I think AppImage would be very useful for this app.
