### ISSUE TITLE
I tried to use the stopwatch function, but this message came up

### ISSUE THREAD

**Issue by dkxoekrlapgiwoe** [ActivityWatch/activitywatch#732]
- [ ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- **ActivityWatch version**: 

## Additional context

I tried to use the stopwatch function, but this message came up

TypeError: Cannot read properties of null (reading 'timestamp'). See dev console (F12) and/or server logs for more info.

**Comment by ErikBjare** [comment]
Most certainly a duplicate. Should have been fixed a long time ago in master.

**Comment by dkxoekrlapgiwoe** [comment]
I downloaded the 0.11.0 version, does it mean that there is a next version?

**Comment by ErikBjare** [comment]
There will be, but not quite yet (only a beta, so far).
