### ISSUE TITLE
ActivityWatch in Docker: "host header is invalid"

### ISSUE THREAD

**Issue by stevenkur** [ActivityWatch/activitywatch#735]
I am trying to create a docker container for the latest version of activitywatch. While creating the container, I get into some problems that I cannot find how to solve it. I already checked everywhere, but I couldn't find similar issues like mine. 

Currently I already succeeded in running it in the docker container on Server PC. But when I opened the site, It shows "host header is invalid" error like this picture. 
<img width="1820" alt="error" src="https://user-images.githubusercontent.com/15223337/164345877-29f37ec5-908c-4903-a54b-82598663540c.png">

In the Dockerfile, I already set to run the host at 0.0.0.0. I've also changed the aw-server.toml file host configuration to 0.0.0.0. Here's the screenshot of the Dockerfile and aw-server.toml configuration.
<img width="604" alt="Screen Shot 2022-04-21 at 9 33 38 AM" src="https://user-images.githubusercontent.com/15223337/164347043-e3a8e8f3-d133-4e02-bfda-c36a5ba732f1.png">
<img width="347" alt="Screen Shot 2022-04-21 at 9 34 01 AM" src="https://user-images.githubusercontent.com/15223337/164347167-be4dcd60-c950-4b75-953a-d40f530b0250.png">

But when I check the container log, it's not assigned to 0.0.0.0, but to docker IP like this picture.
<img width="935" alt="log" src="https://user-images.githubusercontent.com/15223337/164346024-3696ead9-f159-4041-9df2-087608137688.png">

I tried this on the older version of activitywatch (until version 0.8.2) and it works, but it doesn't work for the latest version. In the older version, the IP is assigned to 0.0.0.0:5600 in the docker container log, so I can access it and sending bucket to the docker. But in the current version, I can only access the site and cannot sending any bucket to the server.

It would great if you could help me in this matter. Thank you.

**Comment by ErikBjare** [comment]
Alright, so you're bumping into the Host-header check (`host header is invalid`) which was added in https://github.com/ActivityWatch/aw-server/commit/3e8731fd70fbf05d842ec73b86533fd04f17c606 to protect against DNS rebinding attacks.

The equivalent for aw-server-rust is here: https://github.com/ActivityWatch/aw-server-rust/pull/250

Looking at the aw-server commit, it looks like the header check isn't being disabled despite the host being set to 0.0.0.0 ([this comment](https://github.com/ActivityWatch/aw-server/blob/d335d9067c4d48172ac81ec1bdaed1a00807c846/aw_server/rest.py#L29) saw this issue coming). 

However, aw-server-rust seems to correctly handle that case (and even has [a test](https://github.com/ActivityWatch/aw-server-rust/pull/250/files#diff-1b1f3a9b98b628b1b3793fdfd86695db05fad56052c9fab38f98319f0cce43f0R127-R138)).

So, a short-term fix is to use aw-server-rust instead, long-term (and probably trivial) fix is to disable the Host-header check entirely when host is set to `0.0.0.0` (and maybe log a warning).

**Comment by ErikBjare** [comment]
Fixed the `0.0.0.0` case for aw-server in https://github.com/ActivityWatch/aw-server/commit/c9bbc48c06be0e4f65ed763f316fbdb2e79a1e94
