### ISSUE TITLE
Not able to install in MacOs dist built app

### ISSUE THREAD

**Issue by ajaydoyenhub** [ActivityWatch/activitywatch#738]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

I have cloned ActivityWatch in MacOS and installed the required packages.
Also, perform the below command
> make build
> make package
> make dist/ActivityWatch.dmg

After performing the above operation, I'm trying to install it by double clicking on the ActivityWatch.dmg file but It's not working.

Anyone please help me out from this if I'm missing something or any help.

**Comment by ErikBjare** [comment]
"it's not working" is not enough info. *How* is it not working?

Have you read the other issues about macOS? If so and your issue is
different, then how is it different?

**Comment by ErikBjare** [comment]
No response. Closing.
