### ISSUE TITLE
[Bug] Query API not returning events until about half hour after the 'start time'

### ISSUE THREAD

**Issue by nirurin** [ActivityWatch/activitywatch#747]
- [X ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X ] I have searched the issues of this repo and believe that this is not a duplicate.

- **Windows 11**: 
- **0.11.0**: 

## Describe the bug
I seem to have come across a bug in the query system... The images below show the problem, as you can see the 'start time' and 'end time' in the url query, and the time of events in the log. First image shows a 15 minute window, with no events returned. But then I make the time-window longer, and run the report... and events appear, INCLUDING events that should have been in the original (empty) report. 

[Image](https://cdn.discordapp.com/attachments/755334543891759194/985082138338668554/Screenshot_2022-06-11_082427.png)
[Image](https://cdn.discordapp.com/attachments/755334543891759194/985082138594533376/Screenshot_2022-06-11_082307.png)

If I set a short time frame (eg. the last 20 minutes) it comes back with an empty result. But if I go back a longer time (like an hour) it shows events, and the latest event is 7:14  (which is only 1 minute ago). So does the query engine break if you query a short period of time?
As you can see, even on the longer time frame, the start time is 6:25 but the first log event is 6:42. If I keep going back it seems whatever the start time is, the first shown entry will be about half hour later (even if there are logged events in that time)

[Image](https://cdn.discordapp.com/attachments/755334543891759194/985083298336370708/Screenshot_2022-06-11_082609.png)

## Expected behavior
Accurate event reporting relative to the start-time and end-time of the query. Seems to start half hour (approx) after the start-time. 

## Documentation
see above

**Comment by ErikBjare** [comment]
As I replied in the Discord:

> This is a bug in versions including v0.11.0 and older (but not for aw-server-rust). If you update to v0.12.0b2, the bug should be gone.

Closing.
