### ISSUE TITLE
Can't start application on Linux

### ISSUE THREAD

**Issue by Gochkin** [ActivityWatch/activitywatch#748]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Distro: Manjaro Linux, base: Arch Linux, Kernel: 5.19.0-1-MANJARO, arch: x86_64
- **ActivityWatch version**: 0.11.0

## Describe the bug
Application can't be launched. The output from cli:
```
 $~ aw-qt
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 3, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 760, in main
  File "click/_unicodefun.py", line 126, in _verify_python3_env
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
[14458] Failed to execute script __main__
```

## To Reproduce
Try to launch `aw-qt` from terminal

## Expected behavior

The application should be launched as expected

## Documentation
Provided in **Describe the bug** section

**Comment by ErikBjare** [comment]
As the error suggests, this stems from a misconfigured environment, and is not a bug in ActivityWatch.

Read this for more info and what to do about it: https://click.palletsprojects.com/en/8.1.x/unicode-support/#surrogate-handling
