### ISSUE TITLE
Publish to Windows Package Manager

### ISSUE THREAD

**Issue by vedantmgoyal2009** [ActivityWatch/activitywatch#752]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

With every new release of ActivityWatch, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if the maintainers would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

**Comment by ErikBjare** [comment]
>I can create a pull request if the maintainers would like. It would help in keeping manifests up-to-date at WinGet with every new release automatically.

That would be nice. I wont have the time to maintain such an workflow, but if it works and is low-maintenance I'd be happy to have it!

One question though: Is the best place for the workflow the main activitywatch repo (on release tags), or can it just as easily be done in a seperate repo to submit the PRs to winget-pkgs? (cron-job that checks for new releases)

**Comment by vedantmgoyal2009** [comment]
@ErikBjare I've created https://github.com/ActivityWatch/activitywatch/pull/754
