### ISSUE TITLE
Appname to a list in the web-ui - Microsoft Edge Archlinux

### ISSUE THREAD

**Issue by darylhowes** [ActivityWatch/activitywatch#753]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: - XeroLinux Plasma
- **ActivityWatch version**: - Version: v0.11.0) 

## Describe the bug

Hello I’m having similar issues to an issue that war raised a while back were the aw-watcher-web-edge RawData is being collected but now displayed on the Activity - Browser page. From the following two posts the appname needs to be follow a specific format which.

I wonder if this is required for Archlinux and the edge appname Microsoft-Edge-Stable?

## Documentation

https://github.com/ActivityWatch/aw-watcher-web/issues/61
https://github.com/ActivityWatch/aw-webui/commit/6acb378995c4241b0f2a7a149ff9b35e2b60f7e6

**Comment by ErikBjare** [comment]
@darylhowes I just double-checked by installing Edge stable, beta, and dev versions from the AUR. The appnames I got are:

 - Microsoft-edge
 - Microsoft-edge-beta
 - Microsoft-edge-dev

Can you confirm?

**Comment by darylhowes** [comment]
Hello Erik,

The edge I'm using was microsoft-edge-stable.  I will confirm if it was AUR
this evening when I get home.
Thanks.

**Comment by darylhowes** [comment]
Yes, all lower case.
Thank you.
