### ISSUE TITLE
TypeError: can't convert undefined to object

### ISSUE THREAD

**Issue by ivangretsky** [ActivityWatch/activitywatch#762]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10, Firefox (latest stable)
- **ActivityWatch version**: v0.11.0

## Describe the bug
I cannot save changes to newly added categories. And make other changes in settings and elsewhere. Seems to be the same as #598.

**Comment by BelKed** [comment]
I can't reproduce this issue on the latest beta (`v0.12.0b2`) on macOS High Sierra 10.13.6.
If I remember correctly, I think I had the same problem with the older version, but upgrading solved it...

**Comment by ivangretsky** [comment]
Thanks, @BelKed !
Upgrading to latest beta fixed it indeed!

**Comment by ivangretsky** [comment]
This should be published as a new stable ASAP))
