### ISSUE TITLE
KDE Apps reported as unknown

### ISSUE THREAD

**Issue by garageman2335** [ActivityWatch/activitywatch#770]
- [x ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x ] I have searched the issues of this repo and believe that this is not a duplicate.

-  KDE Neon 5.25 
- v0.11.0 

## Describe the bug
When using okular activity watch is unable to report data. Window title and application reported as "unknown", looking in raw data gives the same results. I have tried with multiple .pdf files to see if it is a specific pdf that I am reading. I have also found the same problem when trying to use other KDE programs such as discover, so it must be a specific KDE issue

## Expected behavior
I expected it to show the window title of the app

**Comment by garageman2335** [comment]
I am using wayland

**Comment by BelKed** [comment]
Hey @garageman2335 👋

Your issue is a possible duplicate of these:
- https://github.com/ActivityWatch/activitywatch/issues/92
- https://github.com/ActivityWatch/aw-watcher-window/issues/18

Please, check them out...

**Comment by garageman2335** [comment]
Sorry about that, I did try and have a look for duplicates however it didn't occur to me until I after I posted it that this was just a symptom of Wayland issues
