### ISSUE TITLE
Unable to edit stopwatch

### ISSUE THREAD

**Issue by HertogArjan** [ActivityWatch/activitywatch#771]
- [ ] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 Pro 10.0.19044 Build 19044
- **ActivityWatch version**: v0.12.0b3

## Describe the bug
At the Stopwatch screen I am unable to edit completed stopwatches. No new window is displayed after pressing the 'Edit' button.

## To Reproduce

1. Start a new stopwatch
2. Stop the stopwatch
3. Try to edit/delete the stopwatch

## Expected behavior
I expect a new window to open where I can edit/delete the stopwatch.

## Documentation
No new entries appear in the log files when I click the 'Edit' button, no errors are produced. Nothing in the browser console (F12) either.

**Comment by BelKed** [comment]
I can confirm this bug on the same version (`v0.12.0b3`)...

---

By the way, it's just an *early experiment*:
![Screen Shot 2022-08-03 at 21 45 24](https://user-images.githubusercontent.com/66956532/182695911-bfc4489a-9ab9-49e8-a68a-ca5ca3b7e119.png)

**Comment by HertogArjan** [comment]
This bug appears to be fixed in v0.12.0, so I will close this issue.
