### ISSUE TITLE
aw-watcher-window can't get active window title on some apps on MacOs

### ISSUE THREAD

**Issue by Programmierus** [ActivityWatch/activitywatch#785]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

**MacOs Monterrey 12.5.1**
**ActivityWatch 0.12.0**

I spent quite some time today trying to solve problems of my ActivityWatch, mostly succeeded (#784), but not completely. As I am tailing the `aw-watcher-window_XXXX.log` I permanently see following error messages popping up:

```
2022-09-07 18:58:12 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:77)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 74, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 55, in get_current_window
  File "aw_watcher_window/lib.py", line 27, in get_current_window_macos
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.
```

It is very important to mention though that this now (after I fixed permission issues with #784) happens **not on every window**. Further research showed that window watcher can't get Brave window titles on my machine nor it can detect e.g. WhatsApp Desktop (as soon as I switch to them those messages popup). But it tracks most other windows without any issue:

![image](https://user-images.githubusercontent.com/49633745/188873438-0d54b1a5-f058-4031-8169-c3bbdbbc2362.png)

As you see on screenshot (I marked red) there is other strange behaviour to see: Brave browser's Title was recorded as app: iTerm2 which can't be correct.

**Comment by Programmierus** [comment]
Relates to #742 (same error text), but different situation...

**Comment by ErikBjare** [comment]
I've replicated the issue and this should have been resolved in the just-released v0.12.0, let me know if that fixes the issue for you.

**Comment by jamieastley** [comment]
Came here looking for solutions to the same issue and have just downloaded `0.12.1` which seems to have fixed the problem for me, thanks very much!

(M1 Pro, MacOS 12.5 Beta)

**Comment by Programmierus** [comment]
Worked like a charm for me! Thanks :)
