### ISSUE TITLE
v0.12.0 Mac .dmg download gives "Resource Busy" error

### ISSUE THREAD

**Issue by jameswilson** [ActivityWatch/activitywatch#786]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: macOS Catalina 10.15.7
- **ActivityWatch version**: v0.12.0

## Describe the bug
Extracting the Mac .dmg file presents a dialog window that says "Warning The following disk images couldn't be opened", and "Resource busy".

<img width="372" alt="Screen Shot 2022-09-07 at 10 21 49 AM" src="https://user-images.githubusercontent.com/243532/188916650-f6bc586c-3c00-4d59-88dd-11a9dffcea09.png">

## To Reproduce

1. I download the .dmg file from latest releases on github.
2. I double click the .dmg to extract it.
3. I see a dialog window that says "Warning The following disk images couldn't be opened", and "Resource busy".

## Expected behavior
I expected to see the same behavior as version [v0.12.0b3](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.0b3)

Where a new Finder window appears with the ActivityWatch.app and a shortcut to Applications folder.
<img width="638" alt="Screen Shot 2022-09-07 at 10 25 14 AM" src="https://user-images.githubusercontent.com/243532/188917297-4866d29f-f803-4b52-9407-ae90da955968.png">

**Comment by ErikBjare** [comment]
Uh, are you sure it'd done downloading or something? Pretty sure there's no difference from v0.12.0b3

**Comment by ErikBjare** [comment]
Closing due to no response. If this wasn't spurious, let me know.
