### ISSUE TITLE
MacOS Status Bar Icon Size

### ISSUE THREAD

**Issue by rtpHarry** [ActivityWatch/activitywatch#788]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: macOS Monterey 
- **ActivityWatch version**:  0.12.0 

## Describe the bug
Not really a bug just some feedback. 

I'm liking the new high res icon in the latest version but I think that perhaps it needs a bit of padding around the edges as it seems oversized compared to other icons:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/1038062/189339972-d986a5ac-1590-4997-8bbf-e0c573570f38.png">

Sort of related to #690

**Comment by ErikBjare** [comment]
In v0.12.1 we have updated to Qt6 which seems to have given the icon slightly more padding. Let me know if that's satisfactory.

**Comment by ErikBjare** [comment]
Pretty sure v0.12.1 fixed it, closing.
