### ISSUE TITLE
aw-qt being flagged by Norton Antivirus

### ISSUE THREAD

**Issue by danmaxis** [ActivityWatch/activitywatch#791]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
- **ActivityWatch version**: 

## Describe the bug

Since I updated to activity watch version v0.12.0, my antivirus is raising blocked suspicious activity warnings.
It says aw-qt is trying to delete files in protected folders.

## To Reproduce

1.  Update activity watch version to v0.12.0.

## Expected behavior

Previous version was running fine.

## Documentation

![image](https://user-images.githubusercontent.com/486996/189768622-1c97bdb4-c4f9-40af-951f-045dec3d298c.png)

Obs.: Brazillian portuguese window screenshot showing Data protector displaying a warning concerning aw-qt process trying to reach protected files.

**Comment by ErikBjare** [comment]
See #181, closing.
