### ISSUE TITLE
Just dont even get any resource from api.github

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [ActivityWatch/activitywatch#796]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

why get something from https://api.github.com/repos/ActivityWatch/activitywatch/releases/latest
i dont think its crucial to the operation of the app,i can view stats and everything,should the released app be fully local?
What is the reason for doing that api call?@@

**Comment by Aziks0** [comment]
The call is made to check if an update is available (see [here](https://github.com/ActivityWatch/aw-webui/blob/1980a403dfc2a9f54c0700c202d20e17ccf8bba6/src/components/NewReleaseNotification.vue#L84)). You can deactivate this by unchecking `New release notification` on your settings page.

**Comment by ErikBjare** [comment]
It is as @Aziks0 said.

Closing.

**Comment by RESDXChgfore9hing** [comment]
![didntseemtoworkwhattechdoesitusecookie](https://user-images.githubusercontent.com/75789716/190919305-66ffc9c0-5601-4f02-aae5-ac9d6c1c1fd2.PNG)

sadly it didnt seems to be that simple.does it use cookie to save the setting?or some cache?
My default* browser clears everything.Can I disable it by directly editing the source code?
I assume I can just do a find an replace on the js,is that possible?

**Comment by johan-bjareholt** [comment]
@RESDXChgfore9hing Yes, it uses the browsers localstorage API, and lots of other features in the web-ui does that too (pretty much everything in the settings page, as well as some more stuff like where visualizations are placed in the Activity view).

It would be pretty easy to remove the code yourself in the web-ui, but it would make more sense to just give an exception for aw-webui to not clear it's localstorage.

Once you turn off that setting, everything in ActivityWatch is fully local.

**Comment by RESDXChgfore9hing** [comment]
noted.
