### ISSUE TITLE
The counter does not work when playing Steam games

### ISSUE THREAD

**Issue by David7ce** [ActivityWatch/activitywatch#806]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Arch Linux  (5.19.12-arch1-1) 
- **ActivityWatch version**: v0.12.1 

## Describe the bug
This only happens when opening a game and you are with full screen.

## To Reproduce
Open a game in Steam an the counter stops.

**Comment by ErikBjare** [comment]
This works just fine for me, with exception for the occasional game that is controller-only, which the AFK watcher sometimes doesn't pick up (but window watcher still logs fine).

Needs more details to reproduce.
