### ISSUE TITLE
Increasing engagement from exposure

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#81]
Before announcing, we'd do good to have clearer paths to action for those who visit our website and GitHub. This will help in retaining interest.

 - [x] Have a mailing list for announcements
 - [x] Make improvements to website
   - [x] Add link to installation instructions in docs
   - [ ] Add link to sign up for email announcements
 - [x] Link to downloads/getting started guide on the website
 - [x] Display GitHub star button on website
 - [x] "Share on Twitter" button? (perhaps best done in the web UI, happy users are the most likely to share)

Related closed issue: 
 - https://github.com/ActivityWatch/activitywatch/issues/29 - Add badges and ways for new users to follow/find ActivityWatch on the web

**Comment by WouterGordts** [comment]
For what it's worth; I found this project and the navigation was quite confusing in the beginning. I think the website itself should definitely have a link to the documentation page, and a link to the zipped downloads. I only found these by going to the readthedocs and then from the installation section. The actual documentation seems to be scattered a bit as well. I found the readthedocs site to be very well written and structured. Building on top of that would be the best I think.

**Comment by ErikBjare** [comment]
Thanks for your feedback @WouterGordts. 

We should definitely link to the docs from the website, especially the installation guide. Added it as a task.

**Comment by ErikBjare** [comment]
Made some progress in https://github.com/ActivityWatch/activitywatch.github.io/commit/4af027737263e364b02f35ccd22ece36d5da32e0

**Comment by ErikBjare** [comment]
We need better screenshots, see: https://github.com/ActivityWatch/activitywatch/issues/122

**Comment by ErikBjare** [comment]
This is basically done. I'm sure there's more that we can do, but that'll forever be the case. Closing.
