### ISSUE TITLE
Steam Deck Immutable Filesystem

### ISSUE THREAD

**Issue by PeterKW** [ActivityWatch/activitywatch#811]
Is there anything else I can try to install on Arch with immutable system directories? Is there a flatpak / appimage that I could try? 
Thank you very much, Peter

```

(deck@steamdeck ~)$ yay -S activitywatch-bin
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  activitywatch-bin-0.12.1-1

:: Downloaded PKGBUILD (1/1): activitywatch-bin
  1 activitywatch-bin                (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: activitywatch-bin
==> Making package: activitywatch-bin 0.12.1-1 (Tue Oct 18 16:10:41 2022)
==> Retrieving sources...
  -> Downloading activitywatch-v0.12.1-linux-x86_64.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  133M  100  133M    0     0  2108k      0  0:01:05  0:01:05 --:--:-- 5394k
==> Validating source files with md5sums...
    activitywatch-v0.12.1-linux-x86_64.zip ... Skipped
==> Making package: activitywatch-bin 0.12.1-1 (Tue Oct 18 16:11:47 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found activitywatch-v0.12.1-linux-x86_64.zip
==> Validating source files with md5sums...
    activitywatch-v0.12.1-linux-x86_64.zip ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting activitywatch-v0.12.1-linux-x86_64.zip with bsdtar
bsdtar: Failed to set default locale
==> Sources are ready.
==> ERROR: Cannot find the fakeroot binary.
error making: activitywatch-bin
(1)(deck@steamdeck ~)$ 

```

**Comment by johan-bjareholt** [comment]
Even if it worked, Steam Deck runs Wayland as far as I know which is not yet properly supported by ActivityWatch due to the lack of an API for us to introspect windows (At least that's the case for the Gamescope compositor, not sure when running KDE in desktop mode or whatever it's called).

I have plans to fix this, but it's a lot of work and unfortunately don't have much spare time right now.

**Comment by johan-bjareholt** [comment]
There are issues here both for Wayland support and for flatpak support, but I am too lazy to find them for you right now.

**Comment by ErikBjare** [comment]
>Steam Deck runs Wayland as far as I know

This is not true. In "Desktop mode" it runs X11. 

I've been running it just fine for weeks (apart from the occasional game not using mouse/keyboard emulation so inaccurate AFK detection).

I just downloaded the zip and added aw-qt to autostart applications (in some convoluted way).

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ActivityWatch/activitywatch/issues/811#issuecomment-1286024320

Issue | URI
-|-
Flatpak | https://github.com/ActivityWatch/activitywatch/issues/476#issue-697146800
Wayland | https://github.com/ActivityWatch/activitywatch/issues/92#issue-247417607
