### ISSUE TITLE
Takes a lot of time to load the data

### ISSUE THREAD

**Issue by sahil-html** [ActivityWatch/activitywatch#812]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11 Chrome Browser
- **ActivityWatch version**: Seems latest, I have installed it a week ago.

## Describe the bug
1. It takes a lot of time to load the data. I have to try multiple times to get it completely.

**Comment by ShootingKing-AM** [comment]
Seems like the same issue as #773

**Comment by ErikBjare** [comment]
Indeed, closing in favor of #773
