### ISSUE TITLE
After update and switching to Rust server, ActivityWatch starts two instances on the system startup. 

### ISSUE THREAD

**Issue by AgainPsychoX** [ActivityWatch/activitywatch#813]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 (10.0.19043.2130)
- **ActivityWatch version**: v0.12.1 (rust)

## Describe the bug
After update and switching to Rust server, ActivityWatch starts two instances on the system startup. Two icons are visible on the taskbar too. 

## Expected behavior
Only single instance on start-up.

## Documentation
Even it's listed twice on autostart list in Windows Settings:
![image](https://user-images.githubusercontent.com/23557839/197352985-09e1accd-6aa2-4507-b3f4-eb282c7c25ad.png)

## Workaround
Removal of autostart entry using some other software, like Autoruns from SysInternals (https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns)

**Comment by bastienperez** [comment]
You can remove with `shell:startup` without any third party tool.
To help with this issue, the old one is called _(#MyAppName)_ in my computer.

**Comment by ErikBjare** [comment]
I hopefully just fixed this in https://github.com/ActivityWatch/activitywatch/issues/886#issuecomment-1879605724.

Thanks for reporting!

**Comment by ErikBjare** [comment]
Didn't fix it, but issue is tracked in #886
