### ISSUE TITLE
Forum Signup

### ISSUE THREAD

**Issue by happycoffeebean** [ActivityWatch/activitywatch#821]
I tried to sign up to participate in forums, but upon submitting my information, I get a message: "New registrations are not allowed from your IP address."  My IP address is 65.32.150.108

- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Pretty much everything I stated at the top.  I'm a brand new user as of tonight.  I used to use RescueTime until it got expensive, and I could not fine-tune it to my needs.

**Comment by borisjoffe** [comment]
I have the same issue when I try logging in. I get:
"You can't log in as <username> from that IP address." where <username> is my username

**Comment by happycoffeebean** [comment]
@borisjoffe I tried it again today, and it worked.  Give it another shot!

**Comment by borisjoffe** [comment]
I can now log in as well

**Comment by brimwats** [comment]
> @borisjoffe I tried it again today, and it worked. Give it another shot!

you should close the issue then :)
