### ISSUE TITLE
Firefox extension not available in extension store

### ISSUE THREAD

**Issue by rsmyst** [ActivityWatch/activitywatch#826]
For some reason, the extension has been removed from the store. i would love to use activity watch but i need it to track my browser behaviuor as well. any help?

**Comment by BelKed** [comment]
Duplicate of:
- https://github.com/ActivityWatch/activitywatch/discussions/818
- https://github.com/ActivityWatch/aw-watcher-web/issues/94

---

For now, you can install the extension manually as mentioned there: https://github.com/ActivityWatch/aw-watcher-web/issues/94#issuecomment-1315773537

**Comment by ErikBjare** [comment]
I've now updated the [README](https://github.com/ActivityWatch/aw-watcher-web/blob/master/README.md) with workarounds. 

Since this is a duplicate, I'll close this issue. Thanks for reporting!
