### ISSUE TITLE
In China, you cannot access the network normally, so you need to use VPN.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [ActivityWatch/activitywatch#832]
- **OS name and version**: Windows 11
- **ActivityWatch version**: 0.12.1
## Describe the bug
In China, you cannot access the network normally, so you need to use VPN.
I remember that the previous version can be accessed normally.

## Documentation
[aw-qt.zip](https://github.com/ActivityWatch/activitywatch/files/10277706/aw-qt.zip)

**Comment by dingwen07** [comment]
Can you be more specific about the issue? Neither GitHub nor activitywatch.net is blocked in China.

**Comment by Benjamin-Watson0** [comment]
The current situation is that the official website can be opened, but the specific time cannot be checked. I think it is a network problem. Everything is normal after using VPN. In addition, github is also in a difficult state of access in China. Although it is not blocked, we often cannot access it and need VPN.
Activitywatch.net can be accessed normally. 
http://localhost:5600/#/home It can be accessed normally.
http://localhost:5600/#/timeline Cannot accesshttps://user-images.
I didn't test other related items.
![image](https://user-images.githubusercontent.com/112467275/211191851-0a6fe9ce-eca7-4fcf-b1d0-372a3ba214fb.png)

githubusercontent.com/112467275/211191779-c499568d-0e7a-4b86-8ccc-1da12bbcb1f3.mp4

**Comment by dingwen07** [comment]
I believe your issue is related to #773.

For me, switching to the rust server resolves the issue.

**Comment by dingwen07** [comment]
Your issue might be related to #773.

For me, switching to the rust server resolves the issue.

**Comment by Benjamin-Watson0** [comment]
![image](https://user-images.githubusercontent.com/112467275/211194253-54c00ab8-f72c-4cee-aa97-bfafcf7c337a.png)
Is that what you're talking about? After I switched to it, the problem remained unsolved.

**Comment by BelKed** [comment]
@Benjamin-Watson0, as @dingwen07 correctly [mentioned](https://github.com/ActivityWatch/activitywatch/issues/832#issuecomment-1374799640), the problem with not loading the *Timeline* tab of ActivityWatch web interface, is the same problem as discussed in https://github.com/ActivityWatch/activitywatch/issues/773.

Although, if you are in a rush, you can download the nightly build, as I mentioned in https://github.com/ActivityWatch/activitywatch/issues/773#issuecomment-1370838605.

---

ActivityWatch runs on your computer, and the URL you are visiting – [`http://localhost:5600`](http://localhost:5600) – is local, so your country **cannot** block it. If you want to know more about what is the `localhost`, feel free to read this article – https://whatismyipaddress.com/localhost.

**Comment by Benjamin-Watson0** [comment]
Thank you for understanding. I look forward to the release of the new version.
