### ISSUE TITLE
Add unstable/wip notice to Web UI and other user-centered places

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#84]
I want us to be clear about which things in the Web UI are stable.
This could give us some empathy for missing features and less-than-good characteristics.

While we want to encourage feedback in general, we don't need it on things that are preliminary. 
This would also increase awareness among developers about what's in progress and what isn't.

Places to add the notice:

 - "Activity"-view in the Web UI

The notices should also reference any related issues in the tracker.

**Comment by nikanar** [comment]
The "export as JSON" button in dashboard/Buckets view says "not implemented", while seemingly working. What it its status ?

**Comment by ErikBjare** [comment]
@nikanar It's working, that should be removed.

**Comment by johan-bjareholt** [comment]
It is removed in the latest master commit as far as I can see.

**Comment by nikanar** [comment]
Tentative attempt : 
![aw-wip-notice](https://user-images.githubusercontent.com/11622029/28502840-31df5022-6fc9-11e7-88bf-037c67d82309.png)

**Comment by ErikBjare** [comment]
Closing this, needs a little styling but I doubt I'll forget.
