### ISSUE TITLE
Apple Silicon build?

### ISSUE THREAD

**Issue by cyugao** [ActivityWatch/activitywatch#842]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Hi, I've seen this issue was raised before but somehow it disappeared.
I know the lack of m1 images on GitHub. Is it possible to do a native build through something like [MacStadium](https://www.macstadium.com/opensource)?

**Comment by BelKed** [comment]
I believe this is the issue you mentioned: https://github.com/ActivityWatch/activitywatch/issues/641
