### ISSUE TITLE
I am getting an "Internal Server Error" error when launching ActivityWatch

### ISSUE THREAD

**Issue by welovfree** [ActivityWatch/activitywatch#844]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Microsoft Windows Version 21H2 (OS Buld 19044.2486) 
- **ActivityWatch version**: Version:  v0.12.1

## Describe the bug
I am getting an "Internal Server Error" error when launching ActivityWatch, or whenever I click on any option on the dashboard.

## To Reproduce
  Steps to reproduce the behavior, for example:
    1. Double click the ActivityWatch icon to launch the app
    2. The "Internal Server Error" error highlighted in a red rectangle shows up at the top.

## Expected behavior
The data is expected to show up.

## Additional context
An image illustrating the error produced:
![Image showing the error](https://i.imgur.com/YRuXZ9G.jpeg)

**Comment by ErikBjare** [comment]
Can't help without logs. Possibly a category issue.

**Comment by welovfree** [comment]
@ErikBjare Oh! you are right! It is indeed a category issue as I forgot to escape the "+" sign for this pattern "Learn C++" in:

 **Edit Category > Rule > Pattern**

The problem is now fixed!

**Comment by ErikBjare** [comment]
Nice! 

I might have to improve error messages here in the future, although the regex validation in v0.12.2b1 should help too.

Closing.
