### ISSUE TITLE
two activitywatches and localhost:5600 not accessible

### ISSUE THREAD

**Issue by wirescarryingme** [ActivityWatch/activitywatch#849]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10
- **ActivityWatch version**: The latest version

## Describe the bug
I uninstalled Activitywatch to install a beta version linked in   #847  as I was having the same issue as mentioned in the bug report. Now theres two of them and I cannot access Activitywatch at all. I went through the uninstallation process via windows "Apps & Features" area in the settings. Nothing was off about the uninstallation process. 

## To Reproduce
    1. Uninstall Activitywatch
    2. Reinstall the latest beta version
    3. Try to access localhost:5600 (Activitywatch)

## Expected behavior
I only have one installed, and only one should show up in the tray. I should also be able to access the program.

## Documentation 
Two Activitywatches in the tray:
![image](https://user-images.githubusercontent.com/104281294/220178358-7995210e-8083-4772-b721-61ddf9110ef3.png)

When I open either one of those activitywatches: 
![image](https://user-images.githubusercontent.com/104281294/220178455-b8bc4e58-ee77-432e-828b-fbb101860aca.png)

## Additional context 
Before this I had the Axios error bug and I was trying to find a way to fix it.

**Comment by ErikBjare** [comment]
Did you resolve the issue?

**Comment by Chealer** [comment]
I reported a different issue which involves a duplicated ActivityWatch icon - but no real breakage - in ticket #886.
