### ISSUE TITLE
Server log tab is weirdly empty and logs don't exist

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/activitywatch#86]
![aw-server-log](https://user-images.githubusercontent.com/11622029/28197799-4c310e60-6827-11e7-9af1-c903a55ca811.png)

This tab is empty, and shows `undefined:undefined` values with empty Name/Time/Origin fields, as pictured. Is this meant to be this way or is something wrong in my setup ?

Perhaps relatedly, the "How to contribute" page states that log files on linux should be at  `~/.local/cache/activitywatch/logs` but on my machine, `~/.local/cache` doesn't exist. Where are the logs ?

**Comment by johan-bjareholt** [comment]
Yeah, the WebUI log view has been broken for a few weeks when we did some refactoring and we are aware of it. We are considering to remove it for the time being.

My logs are in .cache/log/aw-{server,watcher-window,watcher-afk}, so the "How to contribute" page should probably be updated

**Comment by nikanar** [comment]
Less broken windows will make the project nicer, sure do remove it for the time being imho.

I found my logs (on arch linux), in `~/.cache/activitywatch/log/aw-{same+qt}`, almost the same as you but not exactly.

**Comment by ErikBjare** [comment]
@johan-bjareholt Could you comment out the link to the log view for now?

I fixed the log path here: https://github.com/ActivityWatch/activitywatch/commit/a0b1f3487f59013cc0859951e3b8624ac6fc9e4e

**Comment by johan-bjareholt** [comment]
@ErikBjare Disabled the log view here https://github.com/ActivityWatch/aw-webui/commit/a746516d164f8d51fae4abfe1896a1a4ed5085ed

I'll close this for now then.
