### ISSUE TITLE
Firefox extension doesn't start automatically when opening the browser

### ISSUE THREAD

**Issue by isle9** [ActivityWatch/activitywatch#869]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 22.10
- **ActivityWatch version**: v0.12.2

## Describe the bug
Seems like the background script doesn't start automatically when the browser is opened and only does so when I manually reneable it from the extension menu.

## To Reproduce
    1. Open the Firefox browser.
    2. Open the AW website.
    3. Check if the bucket is syncing.
    4. If not, disable and enable it again from the extension menu.
    5. Check again and it should work.

## Expected behavior
I expected it to automatically work without me needing to enable it every time.

## Documentation
Before manually re-enabling it:
![image](https://user-images.githubusercontent.com/74906541/230320916-82627a6a-f149-4a2b-9cb6-cb49efd247eb.png)
After:
![image](https://user-images.githubusercontent.com/74906541/230321084-fd59c8fc-cada-4a60-b5c8-246c3bc714ec.png)

**Comment by isle9** [comment]
[Probably connected to this.](https://github.com/ActivityWatch/aw-watcher-web/issues/105)

**Comment by ErikBjare** [comment]
Thanks for reporting this, thanks to your pinpointing of the problem a fix was trivial.

Just sent it off to Mozilla Addons, should be out soon: https://github.com/ActivityWatch/aw-watcher-web/issues/105#issuecomment-1499283469
