### ISSUE TITLE
Cannot detect Genshin Impact

### ISSUE THREAD

**Issue by GitPinkRabbit** [ActivityWatch/activitywatch#873]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 21H2 19044.2846
- **ActivityWatch version**: v0.12.2 (rust)

## Describe the bug
Today I played Genshin Impact for around 2 hours and found that it's not detect by ActivityWatch.

The thing is, it can be detected before 2023/03/31 and after that I didn't see it anymore in ActivityWatch.

![image](https://user-images.githubusercontent.com/46786295/233795326-9c3bc30b-0d2d-40f0-ac8b-0665ac0a129e.png)

As you can see, ActivityWatch knows that I'm not AFK, but it didn't know what I was doing then.

## To Reproduce
Maybe just play it for two minutes and see whether if ActivityWatch detects it.

I'm using CN version's launcher though, so it may not reproduce on global version's launcher.

**Update:** A friend of mine told me it's related to the new version v0.12.2, he is using v0.12.1 and it works fine. Also I updated to the new version at 2023/04/01, which matches the evidence. I don't know which part of logs may help.

The main process name for the CN version is `YuanShen.exe`.

## Expected behavior
It detects it, just as if should.

![image](https://user-images.githubusercontent.com/46786295/233795543-08c673df-84eb-470e-ae60-8cc6524a0415.png)

The image comes from 2023/03/31. The word "原神" is the Chinese name for Genshin Impact.

**Comment by BelKed** [comment]
If it detects only minute or two of the played/opened game, it's possibly related to: https://github.com/ActivityWatch/activitywatch/issues/124

**Comment by GitPinkRabbit** [comment]
A friend of mine told me it's related to the new version v0.12.2, he is using v0.12.1 and it works fine. Also I updated to the new version at 2023/04/01, which matches the evidence.

I don't know which part of logs may help.

**Comment by GitPinkRabbit** [comment]
> If it detects only minute or two of the played/opened game, it's possibly related to: #124

It's not detecting at all.

**Comment by BelKed** [comment]
So then, would you mind downgrading to the [`v0.12.1`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.1) to confirm it works there? :)

**Comment by GitPinkRabbit** [comment]
> So then, would you mind downgrading to the [`v0.12.1`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.1) to confirm it works there? :)

I downgraded to v0.12.1 today and it works fine.

![image](https://user-images.githubusercontent.com/46786295/234519471-478ffca7-a9b2-4f77-9d53-641175e85855.png)

**Comment by BelKed** [comment]
Thanks for confirming :)

**Comment by dingwen07** [comment]
Apparently new version is not able to detect any windows with elevated rights, like Genshin.

**Comment by GitPinkRabbit** [comment]
> Apparently new version is not able to detect any windows with elevated rights, like Genshin.

Is that intended? I‘m still using the old version, will it be fixed?

**Comment by dingwen07** [comment]
> > Apparently new version is not able to detect any windows with elevated rights, like Genshin.
> 
> 
> 
> Is that intended? I‘m still using the old version, will it be fixed?

By reading the change log, the new version switched from WMI to Win32 API (#83) to obtain window in focus, I guess it fixed the issue of high CPU usage of WMI Provider Host. That should be the cause of the behavior change.

It is expected for a program without elevated rights being unable to access programs with elevated rights.

**Comment by panblue** [comment]
Had the same issue with a non-Steam game: since updating, the playtime was not being tracked. Removing the Administrator rights to the game or elevating ActivityWatch rights to Administrator, both approaches solved the issue.

**Comment by GitPinkRabbit** [comment]
> Had the same issue with a non-Steam game: since updating, the playtime was not being tracked. Removing the Administrator rights to the game or elevating ActivityWatch rights to Administrator, both approaches solved the issue.

May I ask what should I do to elevating ActivityWatch rights to Administrator?

**Comment by panblue** [comment]
> > Had the same issue with a non-Steam game: since updating, the playtime was not being tracked. Removing the Administrator rights to the game or elevating ActivityWatch rights to Administrator, both approaches solved the issue.
> 
> May I ask what should I do to elevating ActivityWatch rights to Administrator?

Sure!

Locate the ActivityWatch EXE file. For me, it was at this location: C:\Users*your username*\AppData\Local\Programs\ActivityWatch\aw-qt.exe

Right-click on the ActivityWatch EXE file > select 'Properties.' > In the 'Properties' window, go to the 'Compatibility' tab. > Tick the box that says 'Run this program as an administrator' > Apply and OK to save changes.

Hope that helps!

**Comment by GitPinkRabbit** [comment]
> > > Had the same issue with a non-Steam game: since updating, the playtime was not being tracked. Removing the Administrator rights to the game or elevating ActivityWatch rights to Administrator, both approaches solved the issue.
> > 
> > 
> > May I ask what should I do to elevating ActivityWatch rights to Administrator?
> 
> Sure!
> 
> Locate the ActivityWatch EXE file. For me, it was at this location: C:\Users_your username_\AppData\Local\Programs\ActivityWatch\aw-qt.exe
> 
> Right-click on the ActivityWatch EXE file > select 'Properties.' > In the 'Properties' window, go to the 'Compatibility' tab. > Tick the box that says 'Run this program as an administrator' > Apply and OK to save changes.
> 
> Hope that helps!

Really appreciate that!

**Comment by ErikBjare** [comment]
Running it as administrator is not something I'm comfortable recommending as a fix, but glad if it's working for you!

This was a regression when we updated the method of getting window titles to a faster one. We might re-add the old method of getting window titles (slower) as a fallback if the primary one fails.

**Comment by ErikBjare** [comment]
@BelKed Are you interested in working on the fix I suggested? To fallback to the old method if the new one fails. Should be pretty easy if you just have a look at https://github.com/ActivityWatch/aw-watcher-window/pull/83

I think it's an important fix, it not really acceptable imo that administrator rights means it doesn't get tracked. The only reason I can think of why I'm holding back on cutting a stable release right now.

I'd do it myself, but I don't have access to a Windows system. Would really appreciate it if you, or someone else, could find the time :)

**Comment by BelKed** [comment]
Unfortunately, I'm pretty busy with school and work at the moment, so I probably won't be able to find the time to do this. I also don't use Windows, so I probably couldn't test it properly...

**Comment by ErikBjare** [comment]
@BelKed I understand, just wanted to check :)

**Comment by ishanfdo18098** [comment]
> Had the same issue with a non-Steam game: since updating, the playtime was not being tracked. Removing the Administrator rights to the game or elevating ActivityWatch rights to Administrator, both approaches solved the issue.

ActivityWatch didnt detect Factorio (also elevated rights) too. This solved the problem (ran acitivitywatch with as admininstrator). 
Thank you 🙂

**Comment by ErikBjare** [comment]
We have a WIP fix here: https://github.com/ActivityWatch/aw-watcher-window/pull/96

Anyone with a little dev experience and access to a Windows machine is encouraged to test it :)

**Comment by suiahae** [comment]
> We have a WIP fix here: [ActivityWatch/aw-watcher-window#96](https://github.com/ActivityWatch/aw-watcher-window/pull/96)
> 
> Anyone with a little dev experience and access to a Windows machine is encouraged to test it :)

Thank you for your effort! This fix works for https://github.com/ActivityWatch/activitywatch/issues/1004#issuecomment-1878185792.

But since I don't have Factorio and Genshin installed, I can't confirm if it works.
