### ISSUE TITLE
0.12.2, 0.12.3b1 don't install Python, Qt deps correctly on Windows 8.1

### ISSUE THREAD

**Issue by TuggyNE** [ActivityWatch/activitywatch#883]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 8.1 Pro x64
- **ActivityWatch version**: v0.12.2, but similar issues with 0.12.3b1, which I tried first.

## Describe the bug
After upgrade or fresh installation, using the Start Menu shortcut or opening aw-qt.exe directly fails with a Python stacktrace about ImportErrors. The versions differ slightly:
0.12.3b1 upgrade from 0.12.0: says something about Python38.dll incompatibility (the installation directory had both Python38.dll and Python39.dll, with dates corresponding to release dates of the respective ActivityWatch versions).
0.12.2 fresh install: "ImportError: DLL load failed while importing QtWidgets: The specified procedure could not be found."

## To Reproduce
0. Install
1. Run aw-qt.exe e.g. from Start Menu

## Expected behavior
The tray icon process to load and bootstrap everything else.

## Additional context
If Windows 8.1 is unsupported, the README or release notes or installation documentation should indicate this. They don't.

Somehow, the installer for 0.12.2 was able to get the two watchers and the configured (Rust) server running although the tray icon that would normally coordinate them fails to load, and aw-watcher-window logs many exceptions. 0.12.3b1 was unable to get anything to run at all.

Typical aw-watcher-window exception:
2023-05-12 21:26:15 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 42, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "aw_watcher_window\windows.py", line 18, in get_app_path
pywintypes.error: (5, 'GetModuleFileNameEx', 'Access is denied.')

Downgrading in place to 0.12.0 worked without problems.

**Comment by ErikBjare** [comment]
We generally stop supporting old operating systems at the same pace as the rest of the ecosystem (that we depend on).

In the case of Windows 8.1, it looks like it [reached End of Life in January](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93). As such, some of our dependencies likely stopped supporting it (like Qt in this case), and us in turn when we update them.

We don't have the resources to support old operating systems, so I'm closing this. Thanks for reporting though!
