### ISSUE TITLE
make clean doesn't cd to the right place

### ISSUE THREAD

**Issue by nikanar** [ActivityWatch/activitywatch#89]
```
.../activitywatch$ make clean
rm -r build dist
rm: cannot remove 'build': No such file or directory
rm: cannot remove 'dist': No such file or directory
make: *** [Makefile:64: clean] Error 1
.../activitywatch$ 
```

There are `build` and `dist` directories in all `aw-*` subdirectories, so I'm not sure if this should apply to `aw-core`, `aw-qt`, or all, but... right now, make clean at the top level doesn't seem to do the right thing.

**Comment by johan-bjareholt** [comment]
Seems like we are missing -f on rm so it gives a non-zero exit code when quitting and therefore causing make to fail.

Fixed it here https://github.com/ActivityWatch/activitywatch/commit/c4dbf06c8e59891fb5653c47406fafdea18f5e98

Regarding recursive clean on all projects, that would be nifty. We could add a clean_all target or similar to that so you can still choose to just clean the bundle. Doesn't like most of the subprojects have a clean target yet though.

**Comment by johan-bjareholt** [comment]
Fixed clean_all aswell, closing

https://github.com/ActivityWatch/activitywatch/commit/d7f9b190f2c448697602a489785a8b96ca29d3fc
