### ISSUE TITLE
Install Documentation lacks list of dependancies

### ISSUE THREAD

**Issue by mryellow** [ActivityWatch/activitywatch#899]
Debian complains with: 

```
[6581] Error loading Python lib '..../activitywatch/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ..../activitywatch/libpython3.9.so.1.0)
```

No doubt other distros complain about other things but there is no list of required dependencies which must be installed before using the software. Which is a blocker to non-technical users.

Perhaps an actual installer as suggested by #888 is something which should be looked at sooner rather than later.

**Comment by johan-bjareholt** [comment]
Update your debian version (you are probably running Debian Buster?). The latest version is Debian Bullseye and has been released for almost 2 years. The next version Debian Bookworm will be released in a couple of months, so you could wait for that as well.

buster: glibc 2.28-10
bullseye: glibc 2.31-13
