### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#9]
We need something basic, something possibly clean and uncoloured that can be styled later if needed.

Possible designs will likely be brainstormed at next meetup.

**Comment by johan-bjareholt** [comment]
All glory to my ms paint skills

http://i.imgur.com/a8J17iS.png

**Comment by ErikBjare** [comment]
Haha, nice.
I think I had a logo along those lines that I mocked in Blender. Made
another design as well that's in the Slack.

**Comment by ErikBjare** [comment]
We completed the first version of the logo a while back. Closing.
