### ISSUE TITLE
Module aw-server quit unexpectedly

### ISSUE THREAD

**Issue by Bartek200219** [ActivityWatch/activitywatch#901]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 21H2 19044.2965
- **ActivityWatch version**: latest

## Describe the bug
Module aw-server quit unexpectedly, ![aw-qt_2023-06-06_17-04-08](https://github.com/ActivityWatch/activitywatch/assets/37016424/be7d35c2-e815-4d8e-9724-b8211ed574f8)
Restart doesn't change anything

## To Reproduce
1. Install activitywatch and chrome extention
2. use for 2 weeks

## Expected behavior
aw-server shouldn't quit unexpectedly

## Documentation
```
2023-06-06 17:04:10 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2023-06-06 17:04:10 [INFO ]: Starting up...  (aw_server.main:41)
2023-06-06 17:04:10 [INFO ]: Using database file: C:\Users\Bartek\AppData\Local\activitywatch\activitywatch\aw-server\peewee-sqlite.v2.db  (aw_datastore.storages.peewee:126)
```

## Additional context
Nothing more to see in logs, sometimes error don't occur.

**Comment by BelKed** [comment]
Could you please try to start ActivityWatch from the command line? It should tell us why it won't start...
```
C:\\path\to\aw-watcher-window --verbose
```

**Comment by Bartek200219** [comment]
I had a problem with RAM and that was the issue
