### ISSUE TITLE
Category Builder doesn't work "TypeError: c[f].events is undefined"

### ISSUE THREAD

**Issue by douglasg14b** [ActivityWatch/activitywatch#905]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10
- **ActivityWatch version**: v0.12.2

## Describe the bug

Just installed and setup ActivityWatch and after a day of work went to setup categories. Category builder doesn't work, just shows `loading` perpetually. When it loads, the following error shows in console:

![image](https://github.com/ActivityWatch/activitywatch/assets/1400380/da8a4e69-2440-4607-b120-c45bdc9ecbd4)

Which is thrown from here: https://github.com/ActivityWatch/aw-webui/blob/1f194ff6886d82ac5928e8cb944888d378c54157/src/views/settings/CategoryBuilder.vue#L227

## To Reproduce

Unknown, happens every time

## Expected behavior

It doesn't fail, and loads categories

## Documentation

The date range selection appears to be borked? Inconsistent date offsets/not using UTS everywhere?

1. Select 18th -> 20th (Today is the 19th) the network request responds with 810 items
2. Select 18th -> 21st (2 days in the future) the network request returns 999 items
   - It also doesn't fail, and loads a bunch of categories 

## Additional context

Watchers:
- `[aw-watcher-web](https://github.com/ActivityWatch/aw-watcher-web)
- [aw-watcher-vscode](https://github.com/ActivityWatch/aw-watcher-vscode)
- [OlivierMary/aw-watcher-jetbrains](https://github.com/OlivierMary/aw-watcher-jetbrains)

**Comment by BelKed** [comment]
Would you mind installing the latest beta version [`v0.12.3b3`](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b3) to confirm that the bug still occurs in there?

**Comment by ErikBjare** [comment]
Maybe there is a strange `word` in `words_in_event`?

The `word.length <= 2` will return false for any non-strings, for example. But `split` would never do that...

I played a bit with the code just to try and figure it out, but it all looks right to me... I ended up improving the common string algorithm to also include common bigrams: https://github.com/ActivityWatch/aw-webui/pull/455

**Comment by douglasg14b** [comment]
I was only able to repro this with a fresh setup, now that there is more than a day of data it doesn't seem to crop up 🤔 

@ErikBjare I would recommend some offensive programming around this, and validating that the `events` property of each value actually exists wherever it is they are pulled or created from. And then logging contextual errors if it's missing. This can greatly assist with finding the bug source in the future.

**Comment by gleycerparra** [comment]
Any solution? I installed it yesterday as a new user, and this bug is also happening to me.

**Comment by JaydonZhao** [comment]
Hi, marvelous developer,
I installed AcitvityWatch earlier today, and I have the same issue: **Category builder doesn't work, just shows loading perpetually.**
Is there any solution for it as of now?

**Comment by Qemuel8** [comment]
So the way i fixed this could also solve it for other.
-Go to category builder.
-Press Show Options.
-Select a different host name.

as i understand my issue was related to having an old watcher that i wasnt using and was deleted but was still showing in the list of hosts. Picking the new host solved the problem for me.

**Comment by ErikBjare** [comment]
@Qemuel8 Good observation!

The categorization helper currently assumes which hostname is the target, but it can be changed by clicking "Show options" and choosing the correct host in the dropdown.

**Comment by ErikBjare** [comment]
Fixed now, see https://github.com/ActivityWatch/activitywatch/issues/965#issuecomment-1817986172

Thanks for reporting!
