### ISSUE TITLE
Builds don't work on Windows 7

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#91]
Message: "Error loading Python DLL python35.dll (error code 1114)"

See original issue here: https://github.com/ActivityWatch/aw-qt/issues/23

**Comment by idevwebs** [comment]
2 years later, any update on this? Running aw-qt is instant crash in win764. Should we assume AW is not going to work on this version of windows?

**Comment by ErikBjare** [comment]
Unless someone takes it upon themselves to fix the issue and make a PR,
unfortunately yes.

**Comment by ErikBjare** [comment]
This is unlikely to ever get resolved since there isn't anyone willing to pick it up. Closing.
