### ISSUE TITLE
Module aw-server quit unexpectedly - No log file found

### ISSUE THREAD

**Issue by ItsTHEAvro** [ActivityWatch/activitywatch#916]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Microsoft Windows 10 Pro, 10.0.19044 Build 19044

- **ActivityWatch version**: v0.12.3b4

## Describe the bug
aw-server quits every time ActivityWatch is opened.

## To Reproduce
    1. Install ActivityWatch
    2. Open ActivityWatch

## Expected behavior
aw-server starts. No error message to be shown.

## Documentation
Screenshot: 
![image](https://github.com/ActivityWatch/activitywatch/assets/42869374/d3543420-39d3-4089-9db7-e4a3757e48b8)

Logs:
aw-qt, aw-watcher-afk, aw-watcher-window, all of there contains logs except aw-server folder. The aw-server folder is empty.
[aw-qt_2023-07-08T08-53-14.log](https://github.com/ActivityWatch/activitywatch/files/11987360/aw-qt_2023-07-08T08-53-14.log)
[aw-watcher-afk_2023-07-08T08-53-15.log](https://github.com/ActivityWatch/activitywatch/files/11987361/aw-watcher-afk_2023-07-08T08-53-15.log)
[aw-watcher-window_2023-07-08T08-53-15.log](https://github.com/ActivityWatch/activitywatch/files/11987365/aw-watcher-window_2023-07-08T08-53-15.log)

## Additional context
Tried uninstalling, restarting PC, then reinstalling ActivityWatch. Same result.

**Comment by ItsTHEAvro** [comment]
Installing ActivityWatch v0.12.3b3 seems to have fixed this issue.

**Comment by AuroraTea** [comment]
> Installing ActivityWatch v0.12.3b3 seems to have fixed this issue.

Here is ActivityWatch v0.12.3b4, windows x86_64, also

**Comment by ErikBjare** [comment]
What's the output if you run `aw-server.exe` from the terminal?

**Comment by AuroraTea** [comment]
@ErikBjare 
![image](https://github.com/ActivityWatch/activitywatch/assets/43649460/0af10ae4-b80a-4038-a92b-fe4bdf46b8ad)

**Comment by ErikBjare** [comment]
Looks like this is handled upstream here: https://github.com/pyinstaller/pyinstaller-hooks-contrib/commit/0f40dc6e74086e5472aee75070b9077b4c17ab18

Just need to wait for a new version of pyinstaller-hooks-contrib, then update to that, and it should work again.
