### ISSUE TITLE
XDG_CONFIG_HOME support on MacOS

### ISSUE THREAD

**Issue by jag-k** [ActivityWatch/activitywatch#921]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Please add support `$XDG_CONFIG_HOME` env var for config on MacOS

**Comment by ErikBjare** [comment]
We are using https://github.com/platformdirs/platformdirs and https://github.com/djc/appdirs-rs to get platform directories. We do not want to implement custom logic on top of it, if we can help it.

If you want an alternative storage location for the config folder on macOS, I suggest you use symlinks.
