### ISSUE TITLE
Cities Skylines (v. 1.16.0-f3) Time Tracking Error

### ISSUE THREAD

**Issue by FakeTuxedo** [ActivityWatch/activitywatch#930]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: <Windows 10>
- **ActivityWatch version**: <v0.12.2>

## Describe the bug
Every program and window title on my computer, except Cities Skylines (v. 1.16.0-f3), shows up in the ActivityWatch dashboard.
## To Reproduce
Simply open Cities Skylines (v. 1.16.0-f3), close it, and open the dashboard for ActivityWatch.

**Comment by BelKed** [comment]
It’s probably the same issue as here:
- https://github.com/ActivityWatch/activitywatch/issues/873

**Comment by FakeTuxedo** [comment]
Thank you, that worked
