### ISSUE TITLE
Top Browser Domains/URLs - No data

### ISSUE THREAD

**Issue by cyugao** [ActivityWatch/activitywatch#968]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 14.0
- **ActivityWatch version**: v0.12/v0.12.3b10

## Describe the bug
I am using Microsoft Edge browser. In the timeline panel, the `aw-watcher-web-edge` clearly shows the data received (urls).
However, there is nothing to be shown: Top Browser Domains/URLs - No data.

I have been experience this issue for quite some time. Also see for example https://forum.activitywatch.net/t/top-browser-domains-urls-no-data-microsoft-edge-extension-installed/2201

**Comment by cyugao** [comment]
Any updates? This issue is still present with the latest version 0.13.

**Comment by BelKed** [comment]
What is the name of the Microsoft Edge application that appears in the **Top Applications** on your operating system?
It's probably different from the following, as the error occurs:
```
msedge.exe
Microsoft Edge
Microsoft-Edge-Stable
Microsoft-edge
microsoft-edge
microsoft-edge-beta
microsoft-edge-dev
```

**Comment by cyugao** [comment]
@BelKed 
Hi it is `Microsoft Edge Beta`.

**Comment by BelKed** [comment]
Thanks, this should be an easy fix :)
Just a quick question — what OS are you using?

**Comment by cyugao** [comment]
Thanks. I'm on Mac Sonoma.

**Comment by BelKed** [comment]
Great, my guess was right :D

If you like, you can try the fixed version:
1. Navigate to the "nightly" build of `aw-webui` from the PR I've made a few minutes ago ([link](https://github.com/ActivityWatch/aw-webui/actions/runs/9573094435?pr=595#artifacts)).
2. Download the artifact called `build-webpack` ([direct download link](https://github.com/ActivityWatch/aw-webui/actions/runs/9573094435/artifacts/1614856308)).
3. Move the contents of the extracted `build-webpack` into the `static` directory of the ActivityWatch. The path to the `static` directory is `/Applications/ActivityWatch.app/Contents/Resources/aw_server/static`.
4. You should see that the **Top Browser Domains/URLs** are filled correctly on the Python server (`aw-server`, not `aw-server-rust`).

**Comment by cyugao** [comment]
Thanks for the fix!

**Comment by tshrjn** [comment]
I'm facing similar issue on Arc Browser on MacOS. 

The timeline shows activity from `aw-watcher-web-chrome`, but Top Domains & URLs.
