### ISSUE TITLE
Using namespaces for event/bucket types

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#97]
Our current event/bucket types carry significant meaning yet lack any form of consistent naming scheme.

I propose a simple solution, partly [inspired by the activity types used by Google Fit](https://developers.google.com/fit/android/data-types).

Examples:

 - org.activitywatch.window.active
 - org.activitywatch.input.afk
 - org.activitywatch.tab.active
 - org.activitywatch.spotify.playing

We should probably construct a function that maps the old ones to the new ones for compatibility purposes. Would also be useful if we want to move some community-created watcher into the activitywatch namespace later on.

Another related thing I'd like to see in the future: Optional use of JSON Schemas for buckets.

**Comment by johan-bjareholt** [comment]
If we implement this, i think we should remove the "org." and "com." prefix, doesn't really add any value in our case.

**Comment by ErikBjare** [comment]
This has practically been completed. Closing.
