### ISSUE TITLE
Web UI inaccessible after updating to 0.12.3b11

### ISSUE THREAD

**Issue by martin-t** [ActivityWatch/activitywatch#974]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Kubuntu 22.04
- **ActivityWatch version**: 0.12.3b11

## Describe the bug
After updating to 0.12.3b11, the web UI at `http://localhost:5600/` returns 404. The previous version, 0.12.3b10, worked fine.

Full error page:
```text

404: Not Found

The requested resource could not be found.
Rocket 
```

I am using the Rust server.

## To Reproduce
Open the URL directly or click Open web UI in the firefox addon.

## Expected behavior
It should work as it used to ;)

## Documentation
This is in logs:
```
[2023-10-25 04:03:45][[33mWARN[0m][rocket::response::responder::_]: Response was `None`.
[2023-10-25 04:03:45][[33mWARN[0m][rocket::server::_]: No [1;34m404[0m catcher registered. Using Rocket default.
```

**Comment by ErikBjare** [comment]
Thanks for reporting!

Looks like this was a mess up in the CI where the web UI was built after the aw-server-rust binary, and thus not included: https://github.com/ActivityWatch/activitywatch/actions/runs/6575708468/job/17863486842#step:13:627

I'll fix this ASAP and make a new release!

**Comment by ErikBjare** [comment]
Give the new release a try, and let me know if there are any issues: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b12

**Comment by martin-t** [comment]
Everything works now, thanks.
