### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#98]
`aw-server` is taking too much CPU for my taste while running aw-watcher-afk and aw-watcher-window (~10% in htop isn't unusual, I've seen worse sometimes) and I think its time we did a little optimization.

The heartbeat API is the primary target for most optimizations since it's the most called endpoint.

Alternatives:

 - [x] Cache last heartbeat in aw-server to prevent DB fetch (improves heartbeat performance between 30-40%: https://github.com/ActivityWatch/aw-server/pull/32)
   - Done in https://github.com/ActivityWatch/aw-server/pull/46
 - [x] Don't send heartbeats immediately to server, instead send pre-merged heartbeats every x seconds. This has been discussed by me and @johan-bjareholt. I think we could live with a 30-60 second delay between "heartbeat batches".
   - Done in https://github.com/ActivityWatch/aw-client/pull/33

**Comment by ErikBjare** [comment]
Should probably mention that heartbeats with non-zero duration are supported since https://github.com/ActivityWatch/aw-core/pull/47 (not tested, however)

**Comment by ErikBjare** [comment]
@johan-bjareholt has started working on client-side merging of events in https://github.com/ActivityWatch/aw-client/pull/25

**Comment by ErikBjare** [comment]
I think we've gotten enough performance improvements for now with https://github.com/ActivityWatch/aw-server/pull/32 and https://github.com/ActivityWatch/aw-client/pull/33. Closing.

**Comment by Albonycal** [comment]
aw-watcher-window (& other components) are use a lot of CPU resources..
I've seen 80+ % by window watcher...
I'm running arch linux (fully updated) 
`dwm` as my window manager
` i3 2310m @ 2.1ghz` CPU

**Comment by johan-bjareholt** [comment]
@Albonycal For me aw-watcher-window-wayland uses 0.0% CPU and aw-server is mostly at 0.0% CPU but occasionally goes to 4-5% CPU (also archlinux but with a i5-5300U and sway).
That any activitywatch component uses 80%+ CPU is certainly not supposed to happen (unless you are using the web-ui, then aw-server can have a lot of CPU usage).

Unfortunately since we can't reproduce your case of 80%+ CPU usage you need to by yourself profile the application while it runs.

**Comment by Albonycal** [comment]
I mean only a web browser and terminal window was open..
Yea I know the WebUI can use CPU while it's in use.. But I was just casually using my laptop..
