### ISSUE TITLE
Cannot add categories: You have unsaved changes!

### ISSUE THREAD

**Issue by justyn** [ActivityWatch/activitywatch#987]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- Ubuntu 20.04 with kernel 5.15.0-88-generic: 
- v0.12.3b12: 
- Web UI commit hash: 1131f9b

## Describe the bug

When clicking "add category" it doesn't let me, it just says "You have unsaved changes".

I have tried restarting the backend, and opening a new private browsing window, but it makes no difference.

If I click "discard" the message goes away, but it comes back if I try again to add a category.

## To Reproduce

1. Go to Settings
2. Click: "Add category"

## Expected behavior

Not see a message: "You have unsaved changes"

## Documentation
![image](https://github.com/ActivityWatch/activitywatch/assets/203419/5b2e75d5-bb14-4271-bd4c-ee2d6877e944)

I can't see anything strange in the logs for aw-server or aw-qt.

## Additional context

I have no custom categories, only the defaults.

**Comment by ErikBjare** [comment]
You are misunderstanding the message.

It means you added a category, and now you'd need to save if you want to keep that category/changes, or discard if you don't.

**Comment by justyn** [comment]
Yep, oops! 🤦

I didn't notice the little blank category that had been added to the list, I guess I was expecting a popup.

Thanks!

Nothing to see here....

**Comment by ErikBjare** [comment]
I know, we really should add that popup... :)

**Comment by justyn** [comment]
I think it's just that the "you have unsaved changes" message appears immediately with emphasis/colouring, which draws the eye and you miss the subtle new blank category added to the list.

If you're me, anyway!
